import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
import { Webhook } from 'npm:svix';
const json=(data:unknown,status=200)=>new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8'}});const clean=(v:unknown)=>String(v??'').trim();
const deliveryState=(type:string)=>type==='email.delivered'?'delivered':(['email.bounced','email.failed'].includes(type)?'failed':type==='email.complained'?'complained':type==='email.sent'?'sent':'unknown');
Deno.serve(async(req)=>{try{
 if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);
 const supabaseUrl=Deno.env.get('SUPABASE_URL'),serviceRoleKey=Deno.env.get('SUPABASE_SERVICE_ROLE_KEY'),resendApiKey=Deno.env.get('RESEND_API_KEY'),webhookSecret=Deno.env.get('RESEND_WEBHOOK_SECRET');if(!supabaseUrl||!serviceRoleKey)return json({error:'SUPABASE_ADMIN_ENV_MISSING'},500);if(!resendApiKey)return json({error:'RESEND_API_KEY_MISSING'},500);if(!webhookSecret)return json({error:'RESEND_WEBHOOK_SECRET_MISSING'},500);
 const rawBody=await req.text(),svixId=req.headers.get('svix-id'),svixTimestamp=req.headers.get('svix-timestamp'),svixSignature=req.headers.get('svix-signature');if(!svixId||!svixTimestamp||!svixSignature)return json({error:'WEBHOOK_SIGNATURE_HEADERS_MISSING'},400);
 let event:any;try{event=new Webhook(webhookSecret).verify(rawBody,{'svix-id':svixId,'svix-timestamp':svixTimestamp,'svix-signature':svixSignature});}catch{return json({error:'WEBHOOK_SIGNATURE_INVALID'},400);}
 const admin=createClient(supabaseUrl,serviceRoleKey,{auth:{persistSession:false,autoRefreshToken:false}});const type=clean(event?.type);const eventEmailId=clean(event?.data?.email_id||event?.data?.id);
 if(type!=='email.received'){
  if(!eventEmailId)return json({ok:true,ignored:true,type});
  const {data,error}=await admin.rpc('luvia_booking_email_mark_delivery',{p_provider_message_id:eventEmailId,p_provider_event_id:svixId,p_event_type:type,p_delivery_state:deliveryState(type),p_evidence:{webhook:event},p_occurred_at:event?.created_at||event?.data?.created_at||null});if(error)return json({error:'DELIVERY_EVENT_STORE_FAILED',details:error.message},500);return json({ok:true,type,delivery:data});
 }
 const emailId=eventEmailId;if(!emailId)return json({error:'RECEIVED_EMAIL_ID_MISSING'},400);
 const {data:dup}=await admin.from('booking_messages').select('id,booking_id').eq('webhook_event_id',svixId).maybeSingle();if(dup)return json({ok:true,duplicate:true,bookingId:dup.booking_id,messageId:dup.id});
 const receivedResponse=await fetch(`https://api.resend.com/emails/receiving/${encodeURIComponent(emailId)}`,{headers:{Authorization:`Bearer ${resendApiKey}`,Accept:'application/json'}});const receivedEmail=await receivedResponse.json().catch(()=>({}));if(!receivedResponse.ok)return json({error:'RECEIVED_EMAIL_FETCH_FAILED',details:receivedEmail},502);
 const recipients:string[]=[...(Array.isArray(receivedEmail.to)?receivedEmail.to:[]),...(Array.isArray(receivedEmail.received_for)?receivedEmail.received_for:[]),...(Array.isArray(event?.data?.to)?event.data.to:[])].map(clean).filter(Boolean);const headers=receivedEmail.headers&&typeof receivedEmail.headers==='object'?receivedEmail.headers:{};const inReplyTo=clean(headers['in-reply-to']||headers['In-Reply-To']);const references=clean(headers['references']||headers['References']);
 const {data:match,error:matchError}=await admin.rpc('luvia_booking_match_inbound_v2',{p_to:recipients,p_in_reply_to:inReplyTo||null,p_references:references||null,p_provider_message_id:null});if(matchError)return json({error:'INBOUND_MATCH_FAILED',details:matchError.message},500);const bookingId=clean(match?.bookingId),threadId=clean(match?.threadId),method=clean(match?.method);if(!bookingId)return json({error:'BOOKING_EMAIL_THREAD_NOT_FOUND',recipients},422);
 const {data:booking,error:bookingError}=await admin.from('bookings').select('id,status,trip_id').eq('id',bookingId).maybeSingle();if(bookingError||!booking)return json({error:'BOOKING_NOT_FOUND'},404);
 const alias=recipients.find(a=>/booking-[0-9a-f-]{36}@/i.test(a))||recipients[0]||null;
 const {data:stored,error:storeError}=await admin.from('booking_messages').insert({booking_id:bookingId,direction:'inbound',channel:'email',transport_provider:'resend',sender:clean(receivedEmail.from||event?.data?.from)||null,recipient:alias,intended_recipient:alias,actual_recipient:alias,subject:clean(receivedEmail.subject||event?.data?.subject)||null,body_text:clean(receivedEmail.text)||null,provider_message_id:emailId,provider_thread_id:threadId||null,email_thread_id:threadId||null,correlation_method:method||'unknown',delivery_status:'received',idempotency_key:`resend:inbound:${emailId}`,received_at:receivedEmail.created_at||event?.data?.created_at||event?.created_at||new Date().toISOString(),message_id_header:clean(receivedEmail.message_id||event?.data?.message_id||headers['message-id'])||null,in_reply_to:inReplyTo||null,references_header:references||null,webhook_event_id:svixId,metadata:{webhook_type:type,resend_email_id:emailId,matched_by:method,email_thread_id:threadId},raw_payload:{webhook:event,received_email:receivedEmail}}).select('*').single();if(storeError)return json({error:'INBOUND_STORE_FAILED',details:storeError.message},500);
 if(threadId)await admin.from('booking_email_threads').update({state:'replied',last_inbound_message_id:stored.id,last_activity_at:new Date().toISOString(),updated_at:new Date().toISOString()}).eq('id',threadId);
 await admin.from('booking_events').insert({booking_id:bookingId,trip_id:booking.trip_id,event_type:'booking.message.received',payload:{message_id:stored.id,transport_provider:'resend',provider_message_id:emailId,sender:stored.sender,subject:stored.subject,correlation_method:method,email_thread_id:threadId}});
 const {data:intel,error:intelError}=await admin.rpc('luvia_booking_process_inbound_intelligence_v2',{p_message_id:stored.id});if(intelError)console.warn('BOOKING_INTELLIGENCE_V2_WARNING',intelError);
 return json({ok:true,version:'2.0.0',core:'4.68.1',bookingId,messageId:stored.id,threadId,correlationMethod:method,provider:'resend',direction:'inbound',intelligence:intel||null});
}catch(error){return json({error:'BOOKING_EMAIL_INBOUND_UNHANDLED',details:error instanceof Error?error.message:String(error)},500);}});
