(()=>{'use strict';
const VERSION='4.16.1';
const TILES=Object.freeze({
 flights:{title:'Flüge',icon:'✈️',description:'Flughäfen und Terminals für eure An- oder Abreise.',tags:['Flughäfen','Terminals','Anreise'],preset:'flights'},
 rail:{title:'Bahn',icon:'🚆',description:'Fern-, Regional- und wichtige Umsteigebahnhöfe.',tags:['Fernverkehr','Regionalbahn','Bahnhöfe'],preset:'rail'},
 coaches:{title:'Bus & Fernbus',icon:'🚌',description:'Fernbusbahnhöfe und zentrale Busstationen.',tags:['Fernbus','Busbahnhöfe','Haltestellen'],preset:'coaches'},
 ferries:{title:'Fähren',icon:'⛴️',description:'Fährterminals und relevante Hafenverbindungen.',tags:['Fähren','Terminals','Häfen'],preset:'ferries'},
 local:{title:'Nahverkehr',icon:'🚇',description:'Metro, U-Bahn, S-Bahn, Straßenbahn und Bus vor Ort.',tags:['Metro','Tram','Bus'],preset:'local'},
 taxi:{title:'Taxi & Fahrdienste',icon:'🚕',description:'Taxistände und lokale Fahrdienste für flexible Wege.',tags:['Taxi','Transfer','Tür zu Tür'],preset:'taxi'},
 rental:{title:'Vermietung',icon:'🚗',description:'Mietwagen, Leihfahrzeuge und Sharing-Angebote.',tags:['Mietwagen','Sharing','Abholung'],preset:'rental'},
 parking:{title:'Parken & Laden',icon:'🅿️',description:'Parkhäuser, Park-and-Ride und Ladepunkte.',tags:['Parken','P+R','Laden'],preset:'parking'}
});
const SECTIONS=Object.freeze([{eyebrow:'An- & Abreise',title:'Wie kommt ihr hin und wieder zurück?',description:'Die großen Etappen eurer Reise – klar nach Verkehrsmittel getrennt.',tiles:['flights','rail','coaches','ferries']},{eyebrow:'Vor Ort',title:'Wie bewegt ihr euch am Reiseziel?',description:'Nahverkehr, flexible Fahrten, Vermietung sowie Parken und Laden.',tiles:['local','taxi','rental','parking']}]);
let state={root:null,trip:null,active:null,mounted:false,view:'guided',contract:null};
const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const enabled=()=>window.LuviaModuleRegistry?.isEnabled?.(state.trip,'mobility')===true;
const profile=()=>window.LuviaProfileService?.snapshot?.().profile||{};
function tile(id,index){const item=TILES[id];return `<button class="places-hub-tile move-hub-tile" data-move-module="${esc(id)}" aria-label="${esc(item.title)} öffnen"><span class="places-hub-tile-top"><span class="places-hub-icon" aria-hidden="true">${item.icon}</span><span class="places-hub-number">Move ${String(index+1).padStart(2,'0')}</span></span><span class="places-hub-copy"><strong>${esc(item.title)}</strong><small>${esc(item.description)}</small></span><span class="places-hub-tags" aria-hidden="true">${item.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</span><span class="places-hub-open">Direkt öffnen</span></button>`;}
function renderGuided(){state.active=null;state.contract=null;state.view='guided';if(!state.root)return;state.root.innerHTML='<div class="move-guided-host" data-move-guided></div>';window.LuviaGuidedDiscovery?.mount?.(state.root.querySelector('[data-move-guided]'),{domain:'move',trip:state.trip,initialPreferences:window.LuviaUserPreferences?.get?.()||profile(),onBrowse:renderBrowseHub,onComplete:result=>open(result.contract?.moveTile,null,result.contract)});}
function renderBrowseHub(){state.active=null;state.contract=null;state.view='browse';let counter=0;const sections=SECTIONS.map(section=>`<section class="move-hub-group"><header class="move-hub-group-head"><span class="rv2-kicker">${esc(section.eyebrow)}</span><h2>${esc(section.title)}</h2><p>${esc(section.description)}</p></header><div class="places-hub-grid move-hub-grid">${section.tiles.map(id=>tile(id,counter++)).join('')}</div></section>`).join('');state.root.innerHTML=`<section class="places-hub move-hub move-hub-direct"><header><span class="rv2-kicker">Luvia Move · Direkt stöbern</span><h1>Mobilität auf einen Blick.</h1><p>Öffne ein Verkehrsmittel direkt oder lass Move euch in einer kurzen Sequenz zur passenden Richtung führen.</p><button type="button" class="places-guided-return" data-move-guided-return>✦ Von Move führen lassen</button></header>${enabled()?sections:'<div class="places-hub-empty">Move ist für diese Reise nicht aktiviert.</div>'}</section>`;bind();}
async function open(id,payload,contract=null){const item=TILES[id];if(!item||!enabled())return renderGuided();if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state.active=id;state.mounted=true;state.view='module';state.contract=contract||null;window.LuviaMobility?.configureView?.(item.preset);const banner=contract?window.LuviaDiscoveryContracts?.banner?.(contract,{title:'Diese Move-Ergebnisse passen zu eurer Auswahl'})||'':'';state.root.innerHTML=`<section class="places-experience move-experience is-switching"><div class="places-experience-nav"><button class="places-back" data-move-back>← Neu von Move führen lassen</button><button class="places-direct-link" data-move-browse>Alle Bereiche</button></div>${banner}<div id="mobility-module"></div></section>`;requestAnimationFrame(()=>state.root.querySelector('.move-experience')?.classList.remove('is-switching'));if(contract)window.LuviaDiscoveryContracts?.setPending?.(contract);await window.LuviaModules?.mountModule?.('mobility',state.trip);if(contract){try{await window.LuviaMobility?.search?.(contract.query,{discoveryContract:contract,sortBy:'distance'})}finally{window.LuviaDiscoveryContracts?.clearPending?.(contract)}}if(payload){await window.LuviaMobility?.load?.();await window.LuviaMobility?.openPlace?.({...payload,type:'mobility'});}bind();}
async function showHub(){if(!state.root)return false;if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state.mounted=false;renderGuided();return true;}
async function showBrowse(){if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state.mounted=false;renderBrowseHub();}
function bind(){state.root?.querySelectorAll('[data-move-module]').forEach(button=>button.onclick=()=>open(button.dataset.moveModule));state.root?.querySelector('[data-move-back]')?.addEventListener('click',showHub);state.root?.querySelectorAll('[data-move-browse],[data-move-guided-return]').forEach(button=>button.addEventListener('click',button.hasAttribute('data-move-browse')?showBrowse:showHub));state.root?.querySelector('[data-guided-refine]')?.addEventListener('click',showHub);}
async function mount(root,trip,options={}){state.root=root;state.trip=trip;const requested=options.tileId||options.preset||(options.payload?inferTile(options.payload):null);if(requested&&TILES[requested])await open(requested,options.payload,options.contract||null);else renderGuided();}
async function unmount(){if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state={root:null,trip:null,active:null,mounted:false,view:'guided',contract:null};}
function inferTile(payload={}){const explicit=payload.moveTile||payload.mobilityTile||payload.preset;if(explicit&&TILES[explicit])return explicit;const place=payload.seedPlace||payload.place||{};const mode=window.LuviaTransportIntelligence?.mode?.(place)?.value||'';if(/Flughafen/.test(mode))return'flights';if(/Bahn/.test(mode))return'rail';if(/Bus/.test(mode))return'coaches';if(/Fähre/.test(mode))return'ferries';if(/Metro|Stadtbahn|Straßenbahn|ÖPNV/.test(mode))return'local';if(/Taxi/.test(mode))return'taxi';if(/Mietwagen|Sharing/.test(mode))return'rental';if(/Park|Ladestation/.test(mode))return'parking';return'local';}
function openPlace(payload={}){return open(inferTile(payload),payload);}
window.LuviaMoveShell=Object.freeze({version:VERSION,mount,unmount,open,openPlace,showHub,showBrowse,active:()=>state.active,tiles:()=>Object.keys(TILES)});
})();
