(() => {
  'use strict';
  const VERSION='4.24.0';
  const TILES={flights:{title:'Flüge',preset:'airport'},rail:{title:'Bahn',preset:'rail'},coaches:{title:'Fernbus',preset:'coach'},ferries:{title:'Fähren',preset:'ferry'},local:{title:'ÖPNV',preset:'transit'},taxi:{title:'Taxi',preset:'taxi'},rental:{title:'Mietwagen & Sharing',preset:'rental'},parking:{title:'Parken & Laden',preset:'parking'}};
  let state={root:null,trip:null,mounted:false,view:'planning',active:null};
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  async function open(id,payload){const item=TILES[id];if(!item)return showBrowse();if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state.active=id;state.mounted=true;state.view='catalog';window.LuviaMobility?.configureView?.(item.preset);state.root.innerHTML='<section class="places-experience move-experience is-catalog-mode"><div class="places-experience-nav"><button class="places-back" data-back-planning>← Zur Planung</button><button class="places-direct-link" data-all-catalog>Alle Bereiche</button></div><div id="mobility-module"></div></section>';await window.LuviaModules?.mountModule?.('mobility',state.trip);if(payload){await window.LuviaMobility?.load?.();await window.LuviaMobility?.openPlace?.({...payload,type:'mobility'})}bind()}
  async function showBrowse(){if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state.mounted=false;state.view='catalog-hub';state.root.innerHTML=`<section class="places-hub move-hub move-hub-direct"><header><span class="rv2-kicker">Bewusster Katalogmodus</span><h1>Mobilitätspunkte frei durchsuchen.</h1><p>Move bleibt als kanonischer Tool- und Katalog-Core erhalten. Die neue Planning Session löst jedoch keine Verbindung automatisch aus.</p><button type="button" class="places-guided-return" data-back-planning>← Zur neuen Planung</button></header><div class="places-hub-grid move-hub-grid">${Object.entries(TILES).map(([id,item])=>`<button class="places-hub-tile" data-move-module="${esc(id)}"><span class="places-hub-copy"><strong>${esc(item.title)}</strong><small>Mobilitätskatalog öffnen</small></span><span class="places-hub-open">Bereich öffnen</span></button>`).join('')}</div></section>`;bind()}
  async function showHub(){if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state.mounted=false;state.active=null;state.view='planning';state.root.innerHTML='<div data-planning-foundation-host></div>';window.LuviaPlanningFoundation?.mount?.(state.root.querySelector('[data-planning-foundation-host]'),{surface:'move',trip:state.trip,onCatalog:showBrowse});return true}
  function bind(){state.root?.querySelectorAll('[data-move-module]').forEach(button=>button.onclick=()=>open(button.dataset.moveModule));state.root?.querySelectorAll('[data-back-planning]').forEach(button=>button.onclick=showHub);state.root?.querySelector('[data-all-catalog]')?.addEventListener('click',showBrowse)}
  async function mount(root,trip,options={}){state.root=root;state.trip=trip;if(options.tileId&&TILES[options.tileId])await open(options.tileId,options.payload);else if(options.catalog)await showBrowse();else await showHub()}
  async function unmount(){if(state.mounted)await window.LuviaModules?.unmountModule?.('mobility');state={root:null,trip:null,mounted:false,view:'planning',active:null}}
  function inferTile(payload={}){const explicit=payload.moveTile||payload.mobilityTile||payload.preset;if(explicit&&TILES[explicit])return explicit;return'local'}
  function openPlace(payload={}){return open(inferTile(payload),payload)}
  window.LuviaMoveShell=Object.freeze({version:VERSION,mount,unmount,open,openPlace,showHub,showBrowse,active:()=>state.active,view:()=>state.view,tiles:()=>Object.keys(TILES)});
})();
