(() => {
  'use strict';
  const VERSION='4.27.0';
  const MODULES={photo_spots:{title:'Fotospots',host:'photo-spots-module'},attractions:{title:'Sehenswürdigkeiten & Aktivitäten',host:'attractions-module'},restaurants:{title:'Restaurants',host:'restaurants-module'},accommodations:{title:'Unterkünfte',host:'accommodations-module'},nature:{title:'Natur & Ausflüge',host:'nature-module'},shopping:{title:'Shopping',host:'shopping-module'}};
  let state={root:null,trip:null,mounted:null,view:'final'};
  const enabled=()=> (window.LuviaModuleRegistry?.enabledForTrip?.(state.trip)||[]).filter(id=>MODULES[id]);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function unmountExperience(){window.LuviaPlacesSpatialExperience?.unmount?.();window.LuviaPlacesFinal?.unmount?.()}
  async function open(id,payload){if(!MODULES[id]||!enabled().includes(id))return showBrowse();if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);unmountExperience();state.mounted=id;state.view='catalog';state.root.innerHTML=`<section class="places-experience is-catalog-mode"><div class="places-experience-nav"><button class="places-back" data-back-final>← Zur räumlichen Suche</button><button class="places-direct-link" data-all-catalog>Alle Bereiche</button></div><div id="${MODULES[id].host}"></div></section>`;await window.LuviaModules?.mountModule?.(id,state.trip);if(payload)requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('luvia:open-place',{detail:payload})));bind()}
  async function showBrowse(){if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);unmountExperience();state.mounted=null;state.view='catalog-hub';state.root.innerHTML=`<section class="places-hub places-hub-direct"><header><span class="rv2-kicker">Klassischer Katalog</span><h1>Alle Places durchsuchen.</h1><p>Dieser Modus bleibt als bewusste Alternative erhalten. Die räumliche Luvia-Suche öffnet ihn niemals automatisch.</p><button type="button" class="places-guided-return" data-back-final>← Zur räumlichen Suche</button></header><div class="places-hub-grid">${enabled().map(id=>`<button class="places-hub-tile" data-place-module="${esc(id)}"><span class="places-hub-copy"><strong>${esc(MODULES[id].title)}</strong><small>Kanonischen Cloud-Katalog öffnen</small></span><span class="places-hub-open">Bereich öffnen</span></button>`).join('')}</div></section>`;bind()}
  async function showHub(){if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);unmountExperience();state.mounted=null;state.view='spatial';await window.LuviaPlacesSpatialExperience.mount(state.root,state.trip);return true}
  function bind(){state.root?.querySelectorAll('[data-place-module]').forEach(button=>button.onclick=()=>open(button.dataset.placeModule));state.root?.querySelectorAll('[data-back-final]').forEach(button=>button.onclick=showHub);state.root?.querySelector('[data-all-catalog]')?.addEventListener('click',showBrowse)}
  async function mount(root,trip,options={}){state.root=root;state.trip=trip;if(options.tileId&&MODULES[options.tileId])await open(options.tileId,options.payload);else if(options.catalog)await showBrowse();else await showHub()}
  async function unmount(){unmountExperience();if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);state={root:null,trip:null,mounted:null,view:'spatial'}}
  function openPlace(payload={}){const type=payload.type||payload.placeType||'';const map={restaurant:'restaurants',accommodation:'accommodations',attraction:'attractions',photo_spot:'photo_spots',nature:'nature',shopping:'shopping'};return open(map[type]||'attractions',payload)}
  window.LuviaPlacesShell=Object.freeze({version:VERSION,mount,unmount,open,openPlace,showHub,showBrowse,active:()=>state.mounted,view:()=>state.view,modules:()=>Object.keys(MODULES)});
})();
