(()=>{'use strict';
const VERSION='4.16.1';
const PLACE_MODULES={
  photo_spots:{type:'photo_spot',title:'Fotospots',icon:'📸',description:'Aussichten, Lichtstimmungen und besondere Fotomomente entdecken.',tags:['Golden Hour','Aussicht','Erinnerungen'],host:'photo-spots-module'},
  attractions:{type:'attraction',title:'Sehenswürdigkeiten & Aktivitäten',icon:'✨',description:'Museen, Parks, Aussichtspunkte und Erlebnisse entdecken.',tags:['Kultur','Aktivitäten','Highlights'],host:'attractions-module'},
  restaurants:{type:'restaurant',title:'Restaurants',icon:'🍽️',description:'Genuss, Cafés und besondere Restaurantmomente entdecken.',tags:['Restaurants','Cafés','Genuss'],host:'restaurants-module'},
  accommodations:{type:'accommodation',title:'Unterkünfte',icon:'🏨',description:'Hotels, Apartments und besondere Unterkünfte finden.',tags:['Hotels','Apartments','Reisebasis'],host:'accommodations-module'},
  nature:{type:'nature',title:'Natur & Ausflüge',icon:'🌿',description:'Parks, Landschaften und besondere Ausflugsziele entdecken.',tags:['Natur','Ruhe','Ausflüge'],host:'nature-module'},
  shopping:{type:'shopping',title:'Shopping',icon:'🛍️',description:'Märkte, Boutiquen, Souvenirs und besondere Einkaufsorte entdecken.',tags:['Märkte','Boutiquen','Souvenirs'],host:'shopping-module'}
};
let state={root:null,trip:null,active:null,mounted:null,view:'guided',contract:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function enabled(){const ids=window.LuviaModuleRegistry?.enabledForTrip?.(state.trip)||[];return ids.filter(id=>PLACE_MODULES[id]);}
function tile(id,index){const m=PLACE_MODULES[id];return `<button class="places-hub-tile" data-place-module="${esc(id)}" aria-label="${esc(m.title)} öffnen"><span class="places-hub-tile-top"><span class="places-hub-icon" aria-hidden="true">${m.icon}</span><span class="places-hub-number">Place ${String(index+1).padStart(2,'0')}</span></span><span class="places-hub-copy"><strong>${esc(m.title)}</strong><small>${esc(m.description)}</small></span><span class="places-hub-tags" aria-hidden="true">${m.tags.map(tag=>`<span>${esc(tag)}</span>`).join('')}</span><span class="places-hub-open">Direkt öffnen</span></button>`;}
function profile(){return window.LuviaProfileService?.snapshot?.().profile||{};}
function renderGuided(){state.active=null;state.contract=null;state.view='guided';if(!state.root)return;state.root.innerHTML='<div class="places-guided-host" data-places-guided></div>';window.LuviaGuidedDiscovery?.mount?.(state.root.querySelector('[data-places-guided]'),{domain:'places',trip:state.trip,initialPreferences:window.LuviaUserPreferences?.get?.()||profile(),onBrowse:renderBrowseHub,onComplete:result=>open(result.contract?.moduleId,null,result.contract)});}
function renderBrowseHub(){state.active=null;state.contract=null;state.view='browse';const modules=enabled();state.root.innerHTML=`<section class="places-hub places-hub-direct"><header><span class="rv2-kicker">Luvia Places · Direkt stöbern</span><h1>Alle Places auf einen Blick.</h1><p>Du weißt schon, wonach du suchst? Öffne einen Bereich direkt – oder lass dich wieder von Luvia führen.</p><button type="button" class="places-guided-return" data-places-guided-return>✦ Von Luvia inspirieren lassen</button></header><div class="places-hub-grid">${modules.map(tile).join('')||'<div class="places-hub-empty">Für diese Reise ist noch kein Places-Bereich aktiviert.</div>'}</div></section>`;bind();}
async function applyContract(contract){if(!contract)return;const api={restaurants:window.LuviaRestaurantsV2,accommodations:window.LuviaAccommodations,attractions:window.LuviaAttractions,photo_spots:window.LuviaPhotoSpots,shopping:window.LuviaShopping,nature:window.LuviaNature}[contract.moduleId];await api?.search?.(contract.moduleId==='restaurants'?contract:contract.query,{discoveryContract:contract});}
async function open(id,payload,contract=null){if(!PLACE_MODULES[id]||!enabled().includes(id))return renderGuided();if(state.mounted&&state.mounted!==id)await window.LuviaModules?.unmountModule?.(state.mounted);state.active=id;state.mounted=id;state.view='module';state.contract=contract||null;const m=PLACE_MODULES[id];const banner=contract?window.LuviaDiscoveryContracts?.banner?.(contract,{title:'Diese Places passen zu eurer geführten Auswahl'})||'':'';state.root.innerHTML=`<section class="places-experience is-switching"><div class="places-experience-nav"><button class="places-back" data-places-back>← Neu inspirieren lassen</button><button class="places-direct-link" data-places-browse>Alle Bereiche</button></div>${banner}<div id="${m.host}"></div></section>`;requestAnimationFrame(()=>state.root.querySelector('.places-experience')?.classList.remove('is-switching'));if(contract)window.LuviaDiscoveryContracts?.setPending?.(contract);await window.LuviaModules.mountModule(id,state.trip);if(contract){try{await applyContract(contract)}finally{window.LuviaDiscoveryContracts?.clearPending?.(contract)}}if(payload)requestAnimationFrame(()=>window.dispatchEvent(new CustomEvent('luvia:open-place',{detail:payload})));bind();}
async function showHub(){if(!state.root)return false;if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);state.mounted=null;renderGuided();return true;}
async function showBrowse(){if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);state.mounted=null;renderBrowseHub();}
function bind(){state.root?.querySelectorAll('[data-place-module]').forEach(button=>button.onclick=()=>open(button.dataset.placeModule));state.root?.querySelector('[data-places-back]')?.addEventListener('click',showHub);state.root?.querySelectorAll('[data-places-browse],[data-places-guided-return]').forEach(button=>button.addEventListener('click',button.hasAttribute('data-places-browse')?showBrowse:showHub));state.root?.querySelector('[data-guided-refine]')?.addEventListener('click',showHub);}
async function mount(root,trip,options={}){state.root=root;state.trip=trip;const requested=options.moduleId||null;if(requested&&enabled().includes(requested))await open(requested,options.payload,options.contract||null);else renderGuided();}
async function unmount(){if(state.mounted)await window.LuviaModules?.unmountModule?.(state.mounted);state={root:null,trip:null,active:null,mounted:null,view:'guided',contract:null};}
function openPlace(payload={}){const id=payload.type==='restaurant'?'restaurants':payload.type==='accommodation'?'accommodations':payload.type==='attraction'?'attractions':payload.type==='photo_spot'?'photo_spots':payload.type==='shopping'?'shopping':payload.type==='nature'?'nature':null;return id?open(id,payload):false;}
window.LuviaPlacesShell=Object.freeze({version:VERSION,mount,unmount,open,openPlace,showHub,showBrowse,active:()=>state.active});
})();
