(() => {
  'use strict';
  const JOIN_PARAMS=['luvia_join','paris_join'];
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function ensureStyles(){if(document.getElementById('luviaEntryStyles'))return;const s=document.createElement('style');s.id='luviaEntryStyles';s.textContent=`.luvia-entry-layer{position:fixed;inset:0;z-index:1000050;display:grid;place-items:center;padding:18px;background:linear-gradient(145deg,rgba(255,248,246,.98),rgba(239,249,247,.98));font-family:Inter,system-ui,sans-serif;overflow:auto}.luvia-entry-card{width:min(760px,100%);padding:28px;border:1px solid rgba(238,111,131,.16);border-radius:30px;background:rgba(255,255,255,.96);box-shadow:0 28px 80px rgba(44,63,78,.18)}.luvia-entry-head{display:flex;gap:14px;align-items:center;margin-bottom:22px}.luvia-entry-logo{width:48px;height:48px;background:url('luvia-logo.svg') center/contain no-repeat}.luvia-entry-head h2{margin:0;color:#263b54;font:800 34px/1.05 'Playfair Display',Georgia,serif}.luvia-entry-head p{margin:6px 0 0;color:#748391}.luvia-entry-list{display:grid;gap:12px}.luvia-entry-trip{display:grid;grid-template-columns:1fr auto;gap:16px;align-items:center;padding:18px;border:1px solid #e5eaec;border-radius:20px;background:#fff}.luvia-entry-trip strong{display:block;color:#304b61;font-size:18px}.luvia-entry-trip small{display:block;margin-top:5px;color:#788793}.luvia-entry-btn{border:0;border-radius:14px;padding:12px 17px;background:linear-gradient(100deg,#ee6f83,#f2a66f);color:#fff;font-weight:900;cursor:pointer}.luvia-entry-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.luvia-entry-secondary{border:1px solid #dde5e8;border-radius:14px;padding:11px 15px;background:#fff;color:#405a6e;font-weight:800;cursor:pointer}.luvia-entry-empty{padding:28px;text-align:center;border:1px dashed #dbe3e6;border-radius:20px;color:#71818e}.luvia-entry-empty strong{display:block;margin-bottom:8px;color:#304b61;font-size:20px}@media(max-width:640px){.luvia-entry-layer{padding:0;place-items:stretch}.luvia-entry-card{min-height:100dvh;border:0;border-radius:0;padding:24px 18px}.luvia-entry-trip{grid-template-columns:1fr}.luvia-entry-btn{width:100%}}`;document.head.appendChild(s)}
  const close=()=>document.getElementById('luviaEntryLayer')?.remove();
  function openManager(){close();window.ParisProfileCenter?.open?.('trips')}
  function render(trips){ensureStyles();close();return new Promise(resolve=>{const layer=document.createElement('div');layer.id='luviaEntryLayer';layer.className='luvia-entry-layer';const content=trips.length?`<div class="luvia-entry-list">${trips.map((t,i)=>`<article class="luvia-entry-trip"><div><strong>${esc(t.symbol)} ${esc(t.title)}</strong><small>${t.destination?.name?'📍 '+esc(t.destination.name)+' · ':''}${t.isOwner?'Reisebesitzer':'Mitreisend'}</small></div><button class="luvia-entry-btn" data-trip="${i}">Öffnen</button></article>`).join('')}</div>`:`<div class="luvia-entry-empty"><strong>Noch keine Reise</strong>Erstelle deine erste Reise oder tritt über einen Einladungscode bei.</div>`;layer.innerHTML=`<section class="luvia-entry-card" role="dialog" aria-modal="true"><div class="luvia-entry-head"><span class="luvia-entry-logo"></span><div><h2>${trips.length?'Reise auswählen':'Willkommen bei Luvia'}</h2><p>${trips.length?'Welche Reise möchtest du öffnen?':'Dein Reisetagebuch beginnt mit einer Reise.'}</p></div></div>${content}<div class="luvia-entry-actions"><button class="luvia-entry-secondary" data-manage>${trips.length?'Reisen verwalten':'Erste Reise erstellen'}</button></div></section>`;layer.querySelectorAll('[data-trip]').forEach(b=>b.onclick=()=>{const trip=trips[Number(b.dataset.trip)];window.LuviaTripStore.setActive(trip.id);close();resolve(trip)});layer.querySelector('[data-manage]').onclick=()=>{openManager();resolve(null)};document.body.appendChild(layer)})}
  function incoming(){const p=new URLSearchParams(location.search);for(const k of JOIN_PARAMS){const v=p.get(k)?.trim().toUpperCase();if(v)return v}return''}
  async function joinIncoming(client,code){const memberName=prompt('Wie heißt du?');if(!memberName?.trim())throw new Error('Für den Beitritt wird dein Name benötigt.');const id=await window.LuviaLegacyParisCloud.joinTrip(client,{code,memberName});const trip=window.LuviaTripStore.normalize({tripId:id,memberName,role:'member',joinCode:code,cloud:true});window.LuviaTripStore.upsert(trip,{activate:true});const url=new URL(location.href);JOIN_PARAMS.forEach(k=>url.searchParams.delete(k));history.replaceState({},'',url.pathname+url.search+url.hash);return trip}
  async function chooseTrip(client=window.ParisCloud?.client){await window.LuviaTripStore.loadRemote(client);const s=window.LuviaTripStore.snapshot();if(s.trips.length===1){window.LuviaTripStore.setActive(s.trips[0].id);return s.trips[0]}return render(s.trips)}
  async function ensure(client=window.ParisCloud?.client){const code=incoming();if(code)return joinIncoming(client,code);await window.LuviaTripStore.loadRemote(client);const s=window.LuviaTripStore.snapshot();if(s.activeTrip)return s.activeTrip;if(s.trips.length===1){window.LuviaTripStore.setActive(s.trips[0].id);return s.trips[0]}return render(s.trips)}
  function showInvite(profile=null){const trip=profile?.id?profile:window.LuviaTripStore.snapshot().activeTrip;if(!trip?.joinCode)return alert('Für diese Reise ist aktuell kein Einladungscode verfügbar.');const url=new URL(location.href);url.search='';url.hash='';url.searchParams.set('luvia_join',trip.joinCode);navigator.clipboard?.writeText(url.toString()).then(()=>alert(`Einladungslink kopiert.\n\nCode: ${trip.joinCode}`),()=>prompt('Diesen Einladungslink kopieren:',url.toString()))}
  window.LuviaEntry=Object.freeze({get profile(){return window.LuviaTripStore?.snapshot?.().activeTrip||null},ensure,chooseTrip,showInvite,reset(){window.LuviaTripStore.clearActive();location.reload()}});
})();
