(()=>{'use strict';
const MODULE_ID='accommodations',VERSION='5.0.0-bright-stay-offer-identity';
const PLACE_CONFORMANCE_MARKERS=Object.freeze(['LuviaPlaceExperience.plannedPanel','LuviaPlaceExperience.discovery','LuviaPlaceCollections.favoritePanel','LuviaPlaceUI.card']);
const QUICK=[['🏨','Entdecken','Unterkünfte'],['🏨','Hotel','Hotel'],['🏢','Apartment','Apartment'],['🏡','Ferienhaus','Ferienhaus'],['🛏️','Hostel','Hostel'],['⛺','Camping','Campingplatz'],['🌴','Resort','Resort']];
const state={root:null,trip:null,query:'Unterkünfte',filter:'Unterkünfte',options:{},results:[],entities:[],searchMap:new Map(),routeCache:new Map(),loading:false,error:null,visibleCount:6,stayDecision:null,stayLoading:false,stayError:null,stayInput:null};
const esc=v=>window.LuviaPlaceExperience?.esc?.(v)||String(v??'');
const tripContract=()=>window.LuviaTripContractV1||window.LuviaTripContract||null;
const tripId=()=>state.trip?.tripId||state.trip?.id||tripContract()?.getActiveTrip?.()?.tripId||tripContract()?.getActiveTrip?.()?.id||tripContract()?.getContext?.()?.tripId||null;
const destination=()=>state.trip?.destination?.name||state.trip?.destinationName||window.LuviaDestination?.getActive?.()?.canonicalCity?.name||'eurem Reiseziel';
const place=e=>e?.place||e||{},link=e=>e?.tripPlace||e?.trip_place||{};
const ext=e=>{const legacy=e?.extension||e?.accommodation||{},id=link(e)?.id||e?.tripPlaceId;const cloud=id?window.LuviaTripPlaceData?.recordForTripPlace?.(id)?.fields||{}:{};return {...legacy,...cloud}};
const providerId=p=>String(p?.providerPlaceId||p?.provider_place_id||p?.sourceId||p?.source_id||p?.id||'').replace(/^places\//,'');
const fmtDistance=m=>{m=Number(m);if(!Number.isFinite(m))return null;return m<1000?`${Math.round(m/50)*50} m`:`${(m/1000).toFixed(m<10000?1:0).replace('.',',')} km`};
const clean=value=>String(value??'').trim();
const isoDate=value=>/^\d{4}-\d{2}-\d{2}$/.test(clean(value))?clean(value):null;
function formatDate(value){const iso=isoDate(value);if(!iso)return'';const [year,month,day]=iso.split('-');return`${day}.${month}.${year}`}
function parseDate(value){const input=clean(value);if(isoDate(input))return input;const match=input.match(/^(\d{1,2})\.(\d{1,2})\.(\d{4})$/);if(!match)return null;const iso=`${match[3]}-${match[2].padStart(2,'0')}-${match[1].padStart(2,'0')}`,date=new Date(`${iso}T00:00:00Z`);return Number.isNaN(date.getTime())||date.toISOString().slice(0,10)!==iso?null:iso}
function tripStayInput(){const trip=state.trip||tripContract()?.getActiveTrip?.()||{},people=Array.isArray(trip.participants)?trip.participants:[],children=people.filter(person=>Number(person?.age)>=0&&Number(person.age)<18),adults=Math.max(1,people.length-children.length||1),target=trip.destination||{};return{tripId:tripId(),destination:destination(),cityCode:clean(target.cityCode||trip.cityCode).toUpperCase()||null,latitude:Number.isFinite(Number(target.latitude))?Number(target.latitude):null,longitude:Number.isFinite(Number(target.longitude))?Number(target.longitude):null,providerDestinationIds:target.providerDestinationIds||trip.providerDestinationIds||{},checkIn:isoDate(trip.startDate||trip.start_date),checkOut:isoDate(trip.endDate||trip.end_date),adults,children:children.length,childAges:children.map(person=>Number(person.age)),rooms:Math.max(1,Math.ceil(adults/2)),currency:'EUR',providers:['amadeus_hotels','hotelbeds']}}
function stayInput(){return state.stayInput||tripStayInput()}
function stayNights(input=stayInput()){if(!input?.checkIn||!input?.checkOut)return null;const nights=Math.round((new Date(`${input.checkOut}T00:00:00Z`)-new Date(`${input.checkIn}T00:00:00Z`))/86400000);return nights>0?nights:null}
function money(total,currency='EUR'){return Number.isFinite(Number(total))?new Intl.NumberFormat('de-DE',{style:'currency',currency:clean(currency)||'EUR',maximumFractionDigits:2}).format(Number(total)):'Preis offen'}
function providerName(id){return({amadeus_hotels:'Amadeus',hotelbeds:'Hotelbeds','booking.com':'Booking.com',expedia:'Expedia'})[clean(id).toLowerCase()]||clean(id)||'Hotelanbieter'}
function offerCanOpen(offer,input){return window.LuviaBookingStayDecisionCore?.createOfferHandoff?.(offer,input)?.valid===true}
function normalized(p,l={}){return {...p,id:p.id||p.placeId||providerId(p),placeId:p.id||p.placeId,primaryType:'accommodation',symbol:'🏨',lifecycle:l.status||p.lifecycleStatus||'discovered',address:p.shortAddress||p.formattedAddress||p.formatted_address||p.address||'',description:p.editorialSummary||p.description||'',matchScore:p.matchScore||p.match_score||Math.max(50,Math.min(96,Math.round((Number(p.rating)||3.8)*17))),metadata:{...(p.metadata||{}),tripPlaceId:l.id}}}
async function photoUris(photos,max=6){const out=[];for(const photo of (photos||[]).slice(0,max)){try{if(photo.uri||photo.url){out.push({uri:photo.uri||photo.url});continue}const r=await window.LuviaPlaces.photo(photo.name,{maxWidthPx:1200,maxHeightPx:900});if(r?.data?.photoUri)out.push({uri:r.data.photoUri})}catch{}}return out}
async function hydrate(places){await Promise.all((places||[]).slice(0,20).map(async p=>{if(!p._cardPhotoUri&&p.photos?.length){const x=await photoUris(p.photos,1);if(x[0])p._cardPhotoUri=x[0].uri}const origin=window.LuviaTravelContext?.snapshot?.()?.location;if(!origin||!p.location||!window.LuviaPlaces?.route)return;const key=providerId(p);try{let route=state.routeCache.get(key);if(!route){route=(await window.LuviaPlaces.route(origin,p.location))?.data||null;if(route)state.routeCache.set(key,route)}if(route?.drive?.distanceMeters){p.route=route;p.gpsDistanceMeters=route.drive.distanceMeters;p._gpsDistanceMeters=route.drive.distanceMeters;p.distanceMeters=route.drive.distanceMeters}}catch{}}))}
function intelligence(p,e=null){const base=window.LuviaPlaceIntelligence?.analyze?.('accommodation',p,{trip:state.trip,destination:destination(),extension:ext(e)})||{};return{...base,score:base.score||p.matchScore||75,distanceLabel:base.distanceLabel||fmtDistance(p.distanceMeters),warnings:base.warnings||[]}}
function resultCard(p,favoriteEntity=null){const added=Boolean(favoriteEntity);p=normalized(p);const intel=intelligence(p),rating=p.rating?`${Number(p.rating).toFixed(1).replace('.',',')} ★ · ${p.userRatingCount||0} Bewertungen`:'';p.description=[rating,p.description].filter(Boolean).join(' · ');return window.LuviaPlaceUI.card(p,{className:'rv2-search-card rv2-search-card-intelligent',openAttribute:`data-place-card-open="result:${esc(providerId(p))}"`,media:p._cardPhotoUri?`<div class="rv2-card-media"><img src="${esc(p._cardPhotoUri)}" alt="${esc(p.name)}" loading="eager" fetchpriority="high" decoding="sync"></div>`:`<div class="rv2-card-media is-placeholder"><span>🏨</span></div>`,intelligence:intel,actions:`<button type="button" class="rv2-detail-button primary" data-place-card-open="result:${esc(providerId(p))}">Warum passt das?</button>${window.LuviaPlaceCollections.favoriteButton({placeType:'accommodation',providerPlaceId:providerId(p),tripPlaceId:favoriteEntity?link(favoriteEntity).id:'',isFavorite:added})}`})}
function savedCard(e){const p=normalized(place(e),link(e)),l=link(e),intel=intelligence(p,e);const rating=p.rating?`${Number(p.rating).toFixed(1).replace('.',',')} ★ · ${p.userRatingCount||0} Bewertungen`:'';p.description=[rating,p.description].filter(Boolean).join(' · ');return window.LuviaPlaceUI.card(p,{className:'rv2-search-card rv2-search-card-intelligent',openAttribute:`data-place-card-open=\"saved:${esc(l.id)}\"`,media:p._cardPhotoUri?`<div class=\"rv2-card-media\"><img src=\"${esc(p._cardPhotoUri)}\" alt=\"${esc(p.name)}\" loading=\"eager\" fetchpriority=\"high\"></div>`:`<div class=\"rv2-card-media is-placeholder\"><span>🏨</span></div>`,intelligence:intel,actions:`<button type=\"button\" class=\"rv2-detail-button primary\" data-place-card-open=\"saved:${esc(l.id)}\">Warum passt das?</button>${window.LuviaPlaceCollections.favoriteButton({placeType:'accommodation',providerPlaceId:providerId(p),tripPlaceId:l.id,isFavorite:Boolean(l.is_favorite)})}`})}
async function hydrateFavoriteMedia(){const favorites=state.entities.filter(e=>link(e).is_favorite===true).filter(e=>providerId(place(e))&&!place(e)._cardPhotoUri).slice(0,6);if(!favorites.length)return;let changed=false;for(const entity of favorites){const p=place(entity),id=providerId(p);try{const prepared=await window.LuviaPlaceDetails?.prepare?.(id,{regionCode:'DE',photoLimit:1});const detail=prepared?.place||prepared?.response?.data?.place||{};Object.assign(p,detail,{providerPlaceId:id,primaryType:'accommodation'});const photos=prepared?.photos?.length?prepared.photos:await photoUris((detail.photos||[]).slice(0,1),1);if(photos[0]?.uri){p._cardPhotoUri=photos[0].uri;changed=true}state.searchMap.set(id,p)}catch(_){}}if(changed&&state.root?.isConnected)render()}
function scheduledItems(){return (window.LuviaTripPlaceData?.dateEntries?.('accommodation')||[]).map(e=>({id:e.id,tripPlaceId:e.tripPlaceId,dataKey:e.dataKey,title:e.title,time:`${new Date(e.startAt).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})} · ${new Date(e.startAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr`,entry:e}))}
function staySearchPanel(){const input=stayInput();return `<section class="hotel-search-panel" aria-labelledby="hotel-search-title"><div class="hotel-section-heading"><div><span>Aufenthalt</span><h3 id="hotel-search-title">Wann und für wen?</h3></div><small>Alle Daten bleiben änderbar.</small></div><form class="hotel-search-form" data-stay-search><label><span>Check-in</span><input name="checkIn" inputmode="numeric" autocomplete="off" placeholder="TT.MM.JJJJ" value="${esc(formatDate(input.checkIn))}" aria-label="Check-in im Format TT.MM.JJJJ"></label><label><span>Check-out</span><input name="checkOut" inputmode="numeric" autocomplete="off" placeholder="TT.MM.JJJJ" value="${esc(formatDate(input.checkOut))}" aria-label="Check-out im Format TT.MM.JJJJ"></label><label><span>Erwachsene</span><input name="adults" type="number" min="1" max="100" value="${esc(input.adults||1)}"></label><label><span>Zimmer</span><input name="rooms" type="number" min="1" max="30" value="${esc(input.rooms||1)}"></label><button type="submit" ${state.stayLoading?'disabled':''}>${state.stayLoading?'Preise werden geprüft …':'Preise vergleichen'}</button></form><p class="hotel-format-note">Datumsformat: TT.MM.JJJJ</p></section>`}
function stayTruth(){const decision=state.stayDecision;if(state.stayLoading)return`<div class="hotel-truth is-loading"><span></span><p><strong>Livepreise werden abgefragt.</strong> Luvia vergleicht nur identische Reisedaten.</p></div>`;if(state.stayError)return`<div class="hotel-truth is-warning"><b>Livepreise gerade nicht verfügbar</b><p>${esc(state.stayError)} Passende Unterkünfte könnt ihr trotzdem ansehen und merken.</p></div>`;if(!decision)return`<div class="hotel-truth"><b>Noch kein Preisvergleich</b><p>Reisedaten prüfen und die Suche starten.</p></div>`;const count=Number(decision.claims?.liveProviderCount||0);if(!decision.claims?.priceRankingAvailable)return`<div class="hotel-truth is-warning"><b>Keine Livepreis-Quelle verbunden</b><p>Luvia erfindet keine Preise. Affiliate-Links zählen nicht als Preisquelle.</p></div>`;return`<div class="hotel-truth is-success"><b>${count} Live-${count===1?'Quelle':'Quellen'} geprüft</b><p>Günstigster vollständiger Gesamtpreis dieser aktuell verbundenen Quellen – kein Marktbestpreis.</p></div>`}
function liveHotelCard(hotel,index){const offer=hotel.bestAvailableTotal,query=state.stayDecision?.query||stayInput(),nights=stayNights(query),canOpen=offerCanOpen(offer,query),refundable=offer?.cancellation?.refundable===true;return `<article class="hotel-offer-card${index===0?' is-leading':''}"><div class="hotel-card-top"><div><span class="hotel-result-index">${index+1}</span><span class="hotel-card-kicker">${index===0?'Günstigster belegter Gesamtpreis':'Weiteres vergleichbares Angebot'}</span><h3>${esc(hotel.propertyName||'Unterkunft')}</h3></div><div class="hotel-price"><strong>${esc(money(offer?.price?.total,offer?.price?.currency))}</strong><span>gesamt${nights?` · ${nights} ${nights===1?'Nacht':'Nächte'}`:''}</span></div></div><div class="hotel-facts"><span>${esc(providerName(offer?.providerId))}</span>${offer?.roomName?`<span>${esc(offer.roomName)}</span>`:''}${offer?.board?`<span>${esc(offer.board)}</span>`:''}<span>${refundable?'Stornierbar':'Stornierung prüfen'}</span></div><p class="hotel-source-note">${hotel.offerCount||1} belegte${hotel.offerCount===1?'r Tarif':' Tarife'} · Provisionen beeinflussen die Reihenfolge nicht.</p>${canOpen?`<button type="button" class="hotel-offer-open" data-stay-offer="${esc(offer.offerId)}" data-property-key="${esc(hotel.propertyKey)}">Dieses Angebot öffnen</button>`:`<p class="hotel-no-handoff">Kein eindeutig verifizierter Buchungslink für dieses Angebot.</p>`}</article>`}
function discoveryCard(p){const id=providerId(p),entity=state.entities.find(item=>providerId(place(item))===id),favorite=Boolean(link(entity).is_favorite),rating=Number(p.rating);return `<article class="hotel-discovery-card"><div class="hotel-discovery-media">${p._cardPhotoUri?`<img src="${esc(p._cardPhotoUri)}" alt="${esc(p.name||'Unterkunft')}" loading="lazy">`:'<span aria-hidden="true">⌂</span>'}</div><div class="hotel-discovery-copy"><span>Unterkunft · noch ohne Livepreis</span><h3>${esc(p.name||'Unterkunft')}</h3>${p.formattedAddress||p.shortAddress||p.address?`<p>${esc(p.formattedAddress||p.shortAddress||p.address)}</p>`:''}<div class="hotel-facts">${Number.isFinite(rating)?`<span>${rating.toFixed(1).replace('.',',')} ★</span>`:''}${p.userRatingCount?`<span>${esc(p.userRatingCount)} Bewertungen</span>`:''}</div><div class="hotel-card-actions"><button type="button" data-place-card-open="result:${esc(id)}">Details</button>${favorite?`<button type="button" data-favorite="${esc(link(entity).id)}">Gemerkt ✓</button>`:`<button type="button" data-import="${esc(id)}">Merken</button>`}</div></div></article>`}
function hotelResults(){const decision=state.stayDecision,hotels=decision?.hotels||[];if(hotels.length)return`<section class="hotel-results"><div class="hotel-section-heading"><div><span>Livepreise</span><h3>${hotels.length} ${hotels.length===1?'Unterkunft':'Unterkünfte'} vergleichbar</h3></div><small>${esc(formatDate(decision.query?.checkIn))}–${esc(formatDate(decision.query?.checkOut))}</small></div><div class="hotel-offer-list">${hotels.map(liveHotelCard).join('')}</div></section>`;const visible=state.results.slice(0,state.visibleCount);return`<section class="hotel-results"><div class="hotel-section-heading"><div><span>Passende Unterkünfte</span><h3>${state.loading?'Orte werden gesucht …':`${state.results.length} Vorschläge für ${esc(destination())}`}</h3></div><small>ohne erfundene Preise</small></div>${state.loading?'<div class="hotel-loading" aria-label="Unterkünfte werden geladen"><span></span><span></span><span></span></div>':`<div class="hotel-discovery-list">${visible.map(discoveryCard).join('')||'<div class="hotel-empty">Noch keine passende Unterkunft gefunden. Ändert Ziel oder Kategorie.</div>'}</div>`}${state.results.length>visible.length?`<button type="button" class="hotel-more" data-place-more>Weitere ${Math.min(6,state.results.length-visible.length)} anzeigen</button>`:''}</section>`}
function compactPlan(){const items=scheduledItems(),favorites=state.entities.filter(e=>link(e).is_favorite===true);return `<section class="hotel-compact-sections"><details${items.length?' open':''}><summary><span><b>Geplante Aufenthalte</b><small>${items.length?`${items.length} ${items.length===1?'Eintrag':'Einträge'}`:'Noch kein Eintrag'}</small></span></summary><div class="hotel-compact-list">${items.slice(0,4).map(item=>`<button type="button" data-place-schedule="${esc(item.id)}"><strong>${esc(item.title)}</strong><span>${esc(item.time)}</span></button>`).join('')||'<p>Eine Unterkunft könnt ihr über „Details“ zur Timeline hinzufügen.</p>'}</div></details><details><summary><span><b>Gemerkt</b><small>${favorites.length?`${favorites.length} ${favorites.length===1?'Unterkunft':'Unterkünfte'}`:'Noch nichts gemerkt'}</small></span></summary><div class="hotel-compact-list">${favorites.slice(0,6).map(item=>`<button type="button" data-place-card-open="saved:${esc(link(item).id)}"><strong>${esc(place(item).name||'Unterkunft')}</strong><span>Details und Planung öffnen</span></button>`).join('')||'<p>Merkt interessante Unterkünfte, um sie später zu vergleichen.</p>'}</div></details></section>`}
function render(){if(!state.root)return;window.LuviaPlaceCollections?.remember?.('accommodation',state.entities,tripId());const accent=state.trip?.accent||'#4fa3a6';state.root.className='luvia-accommodations-v2';for(const key of ['--trip-accent','--module-accent','--hotel-accent'])state.root.style.setProperty(key,accent);state.root.innerHTML=`<div class="hotel-shell"><header class="hotel-hero"><span>Luvia · Hotels</span><h2>Unterkünfte, die zu eurer Reise passen</h2><p>Livepreise vergleichen, sinnvoll einordnen und genau das ausgewählte Angebot öffnen.</p></header>${staySearchPanel()}<nav class="hotel-kind-filter" aria-label="Unterkunftsart">${QUICK.slice(1).map(([icon,label,query])=>`<button type="button" data-place-query="${esc(query)}" class="${state.filter===query?'active':''}"><span aria-hidden="true">${icon}</span>${esc(label)}</button>`).join('')}</nav>${stayTruth()}${hotelResults()}${compactPlan()}<p class="hotel-legal-note">Luvia zeigt nur Preise verbundener, aktuell erreichbarer Quellen. Die endgültige Verfügbarkeit und Buchung bestätigt immer der Anbieter.</p></div>`;bind()}
async function load(){try{await window.LuviaTripPlaceData?.hydrate?.(tripId());const r=await window.LuviaPlaceEntities.list({tripId:tripId(),type:'accommodation'});state.entities=(r?.data?.entities||[]).filter(e=>link(e).status!=='archived');await hydrate(state.entities.map(place));state.error=null}catch(e){state.error=e.message||String(e)}render();hydrateFavoriteMedia().catch(()=>{})}
async function search(query=state.query,options={}){state.visibleCount=6;state.query=String(query||'Unterkünfte').trim()||'Unterkünfte';state.options=options;state.loading=true;state.error=null;render();try{const r=options.discoveryContract?await window.LuviaDiscoveryContracts.search({tripId:tripId(),type:'accommodation',contract:options.discoveryContract,maxResultCount:16}):await window.LuviaPlaceEntities.searchPlaces({tripId:tripId(),type:'accommodation',query:`${state.query} ${destination()}`,maxResultCount:16,strictDestination:true,minRating:options.minRating,sortBy:options.sortBy||'relevance',openNow:options.openNow||false});state.results=r?.data?.places||[];await hydrate(state.results);state.searchMap=new Map(state.results.map(p=>[providerId(p),p]))}catch(e){state.error=e.message||String(e)}state.loading=false;render()}
async function searchStayOffers(input=stayInput()){const contract=window.LuviaBookingContractV1,normalized={...tripStayInput(),...input,checkIn:parseDate(input.checkIn),checkOut:parseDate(input.checkOut),adults:Math.max(1,Number(input.adults)||1),rooms:Math.max(1,Number(input.rooms)||1)};state.stayInput=normalized;state.stayDecision=null;state.stayError=null;if(!normalized.checkIn||!normalized.checkOut){state.stayError='Bitte Check-in und Check-out im Format TT.MM.JJJJ eintragen.';render();return null}if(normalized.checkOut<=normalized.checkIn){state.stayError='Der Check-out muss nach dem Check-in liegen.';render();return null}if(typeof contract?.reads?.searchStayOffers!=='function'){state.stayError='Der Hotelpreisvergleich ist noch nicht erreichbar.';render();return null}state.stayLoading=true;render();try{state.stayDecision=await contract.reads.searchStayOffers(normalized);state.stayError=null;return state.stayDecision}catch(error){const expected=['BOOKING_STAY_SEARCH_TRANSPORT_UNAVAILABLE','BOOKING_STAY_SEARCH_GATEWAY_FAILED','BOOKING_CONTRACT_PROVIDER_UNAVAILABLE'].includes(error?.code);state.stayError=expected?'Die verbundenen Preisquellen antworten gerade nicht.':(error?.message||'Der Hotelpreisvergleich konnte nicht geladen werden.');return null}finally{state.stayLoading=false;render()}}
async function importOne(id,{silent=false}={}){try{const response=await window.LuviaPlaceEntities.importPlace(id,{tripId:tripId(),type:'accommodation',tripPlace:{status:'idea',isFavorite:true},extension:{accommodationType:state.filter.toLowerCase()}});if(!silent)window.LuviaUIKit?.toast?.('Unterkunft als Favorit gespeichert.',{type:'success'});await load();return state.entities.find(e=>providerId(place(e))===String(id))||response?.data?.entity||null}catch(e){state.error=e.message||String(e);render();throw e}}
function stayForm(e){const x=ext(e);return `<section class="rv2-workspace-section rv2-stay-section"><span class="rv2-workspace-kicker">Aufenthalt & Buchung</span><div class="stay-form"><label>Check-in<input type="datetime-local" data-in value="${x.check_in_at?new Date(x.check_in_at).toISOString().slice(0,16):''}"></label><label>Check-out<input type="datetime-local" data-out value="${x.check_out_at?new Date(x.check_out_at).toISOString().slice(0,16):''}"></label><label>Gäste<input type="number" min="1" data-guests value="${x.guest_count||1}"></label><label>Zimmer<input type="number" min="1" data-rooms value="${x.room_count||1}"></label><label>Buchungsnummer<input data-booking value="${esc(x.booking_number||'')}"></label><label>Buchungsanbieter<input data-provider value="${esc(x.booking_provider||'')}"></label><label class="wide check"><input type="checkbox" data-base ${x.is_trip_base?'checked':''}> Fester Ausgangspunkt</label><label class="wide">Notizen<textarea data-notes>${esc(x.notes||'')}</textarea></label></div><button class="rv2-action primary" data-save-stay>Aufenthalt speichern</button></section>`}
function accommodationActions(l){return window.LuviaPlaceUIActions.actionButtons({favorite:Boolean(l?.is_favorite),planned:Boolean(ext({tripPlace:l||{}}).check_in_at),favoriteAttr:l?.id?'data-fav':'data-import-detail',planAttr:'data-plan-accommodation'})}
function openStayPlanning(p,l,e){return window.LuviaPlaceUIActions.openTimelineDialog({type:'accommodation',tripId:tripId(),place:p,entity:e,tripPlace:l,importEntity:async()=>importOne(providerId(p),{silent:true}),onSaved:async()=>{await load()}})}
async function detail(raw,l=null,e=null){
  let p=normalized(raw,l||{});
  const overlay=window.LuviaPlaceDetail.openLoading({typeLabel:'Unterkunft'});
  const renderDetail=(photos=[],alternativesContent='<p class="rv2-muted">Weitere Details werden geladen …</p>')=>window.LuviaPlaceDetail.update(overlay,{place:p,photos,intelligence:intelligence(p,e),destination:destination(),typeLabel:'Unterkunft',primaryActions:accommodationActions(l),lifecycle:{title:'Unterkunfts-Lebenszyklus',status:l?.status||'discovered',order:['discovered','favorite','selected','booked','checked_in','checked_out','visited','rated']},alternativesContent,capabilityContent:'',footerActions:''});
  const bindActions=()=>{const root=overlay.node;root.querySelector('[data-plan-accommodation]')?.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();openStayPlanning(p,l,e)});root.querySelector('[data-import-detail]')?.addEventListener('click',async ev=>{ev.preventDefault();ev.stopPropagation();const imported=await importOne(providerId(p),{silent:true});if(imported){l=link(imported);e=imported;renderDetail(p._cardPhotoUri?[{uri:p._cardPhotoUri}]:[]);bindActions()}});root.querySelector('[data-fav]')?.addEventListener('click',async ev=>{ev.preventDefault();ev.stopPropagation();await window.LuviaPlaceCommands.toggleFavorite({tripId:tripId(),placeType:'accommodation',tripPlaceId:l.id,entity:e,isFavorite:!l.is_favorite,status:l.status||'idea'});l={...l,is_favorite:!l.is_favorite};renderDetail();bindActions()});root.querySelectorAll('[data-place-alternative]').forEach(button=>button.addEventListener('click',event=>{event.preventDefault();event.stopPropagation();const alternative=state.searchMap.get(button.dataset.placeAlternative)||(state.results||[]).find(item=>providerId(item)===button.dataset.placeAlternative);if(alternative)detail(alternative)}))};
  renderDetail(p._cardPhotoUri?[{uri:p._cardPhotoUri}]:[]);bindActions();
  try{
    const prepared=await window.LuviaPlaceDetails.prepare(providerId(p),{regionCode:'DE',photoLimit:6,seedPlace:p});
    p=normalized({...p,...(prepared?.place||{})},l||{});
    const photos=prepared?.photos?.length?prepared.photos:await photoUris(p.photos);
    const alternatives=(state.results||[]).filter(a=>providerId(a)!==providerId(p)).slice(0,3);
    const alternativeContent=alternatives.length?`<div class="rv2-alternatives">${alternatives.map(a=>{const ai=intelligence(a,null),id=providerId(a);return `<button type="button" class="luv-place-alternative" data-place-alternative="${esc(id)}"><span><strong>${esc(a.name||'Alternative')}</strong><small>${esc(ai.distanceLabel?'GPS-Entfernung verfügbar':'Alternative aus der aktuellen Suche')}</small></span><b>${esc(ai.score)} %</b></button>`}).join('')}</div>`:'<p class="rv2-muted">Noch keine belastbaren Alternativen aus der aktuellen Suche verfügbar.</p>';
    renderDetail(photos,alternativeContent);bindActions();
  }catch(error){console.warn('[Luvia Accommodations] Details konnten nicht vollständig geladen werden.',error)}
}
async function saveStay(root,e,close){const l=link(e),p=place(e),a={check_in_at:root.querySelector('[data-in]').value?new Date(root.querySelector('[data-in]').value).toISOString():null,check_out_at:root.querySelector('[data-out]').value?new Date(root.querySelector('[data-out]').value).toISOString():null,guest_count:Number(root.querySelector('[data-guests]').value||1),room_count:Number(root.querySelector('[data-rooms]').value||1),booking_number:root.querySelector('[data-booking]').value.trim()||null,booking_provider:root.querySelector('[data-provider]').value.trim()||null,is_trip_base:root.querySelector('[data-base]').checked,notes:root.querySelector('[data-notes]').value.trim(),place_name:p.name};await window.LuviaTripPlaceData.upsert({tripId:tripId(),tripPlaceId:l.id,placeId:p.id,placeType:'accommodation',fields:a});close?.();await Promise.all([window.LuviaJourneyContractV1?.commands?.hydrate?.(tripId()),load()]);window.dispatchEvent(new CustomEvent('luvia:place-plan-changed',{detail:{tripId:tripId(),type:'accommodation',tripPlaceId:l.id}}));window.dispatchEvent(new CustomEvent('luvia:in-window-data-changed',{detail:{tripId:tripId(),placeType:'accommodation',tripPlaceId:l.id}}))}
function bind(){
  const root=state.root;
  root.onsubmit=async event=>{
    event.preventDefault();
    const submitted=event.target,form=new FormData(submitted);
    if(submitted.matches('[data-stay-search]'))await searchStayOffers({...stayInput(),checkIn:form.get('checkIn'),checkOut:form.get('checkOut'),adults:Number(form.get('adults')),rooms:Number(form.get('rooms'))});
  };
  root.onclick=async event=>{
    const offerButton=event.target.closest('[data-stay-offer]');
    if(offerButton){
      event.preventDefault();
      const hotel=(state.stayDecision?.hotels||[]).find(item=>item.propertyKey===offerButton.dataset.propertyKey);
      const offer=hotel?.bestAvailableTotal?.offerId===offerButton.dataset.stayOffer?hotel.bestAvailableTotal:null;
      if(!offer)return;
      offerButton.disabled=true;offerButton.textContent='Angebot wird geöffnet …';
      try{await window.LuviaBookingContractV1.commands.openStayOffer({offer,query:state.stayDecision.query,tripId:tripId()},{userGesture:true})}
      catch(error){window.LuviaUIKit?.toast?.(error?.message||'Dieses konkrete Hotelangebot konnte nicht geöffnet werden.',{type:'error'});offerButton.disabled=false;offerButton.textContent='Dieses Angebot öffnen'}
      return;
    }
    const more=event.target.closest('[data-place-more]');
    if(more){state.visibleCount=Math.min(state.results.length,state.visibleCount+6);render();return}
    const quick=event.target.closest('[data-place-query]');
    if(quick){state.filter=quick.dataset.placeQuery;state.stayDecision=null;await search(state.filter,state.options);return}
    const imported=event.target.closest('[data-import]');
    if(imported){event.preventDefault();event.stopPropagation();await importOne(imported.dataset.import);return}
    const favorite=event.target.closest('[data-favorite]');
    if(favorite){event.preventDefault();event.stopPropagation();const entity=state.entities.find(item=>String(link(item).id)===String(favorite.dataset.favorite));if(entity){await window.LuviaPlaceCommands.toggleFavorite({tripId:tripId(),placeType:'accommodation',tripPlaceId:link(entity).id,entity,isFavorite:!link(entity).is_favorite,status:link(entity).status||'idea'});await load()}return}
    const open=event.target.closest('[data-place-card-open]');
    if(open&&!event.target.closest('[data-import],[data-favorite]')){event.preventDefault();event.stopPropagation();const [kind,id]=String(open.dataset.placeCardOpen||'').split(':');if(kind==='result'){const selected=state.searchMap.get(id);if(selected)detail(selected)}else{const entity=state.entities.find(item=>String(link(item).id)===id);if(entity)detail(place(entity),link(entity),entity)}return}
    const scheduled=event.target.closest('[data-place-schedule]');
    if(scheduled){const item=scheduledItems().find(entry=>String(entry.id)===String(scheduled.dataset.placeSchedule));if(item)openPlace({tripPlaceId:item.tripPlaceId,placeId:item.entry?.placeId})}
  };
  root.onpointerover=event=>{const card=event.target.closest('[data-place-card-open^="result:"]');if(card){const id=String(card.dataset.placeCardOpen||'').split(':')[1];if(id)window.LuviaPlaceDetails?.prefetch?.([id],{regionCode:'DE'})}};
  root.onfocusin=root.onpointerover;
}
async function mount(instance,context={}){state.root=instance?.roots?.[0]||document.querySelector('#accommodations-module');state.trip=context.trip||instance?.trip||tripContract()?.getActiveTrip?.()||null;state.stayInput=tripStayInput();state.stayDecision=null;state.stayError=null;render();await load();const tasks=[];if(!state.results.length&&!window.LuviaDiscoveryContracts?.pendingFor?.('accommodations'))tasks.push(search('Unterkünfte',{sortBy:'relevance'}));if(state.stayInput.checkIn&&state.stayInput.checkOut)tasks.push(searchStayOffers(state.stayInput));await Promise.allSettled(tasks);return instance}
function unmount(){state.root=null;state.trip=null}
async function openPlace(payload={}){const e=state.entities.find(x=>String(link(x).id)===String(payload.tripPlaceId)||String(place(x).id)===String(payload.placeId));if(e){detail(place(e),link(e),e);return true}return false}
window.addEventListener('luvia:open-place',e=>{if(e.detail?.type==='accommodation')openPlace(e.detail)});window.addEventListener('luvia:schedule-intelligence-changed',()=>state.root&&render());window.addEventListener('luvia:trip-place-data-changed',()=>state.root&&render());window.addEventListener('luvia:place-collection-changed',e=>{if(state.root&&e.detail?.placeType==='accommodation')load()});
window.LuviaAccommodations=Object.freeze({version:VERSION,load,search,searchStayOffers,openPlace,mount,unmount});window.LuviaModules?.register({id:MODULE_ID,order:60,group:'Places',icon:'🏨',title:'Hotels',description:'Unterkünfte mit belegten Livepreisen und exakter Angebotsidentität.',selectors:['#accommodations-module'],version:VERSION,mount,unmount});
})();
