(() => {
  'use strict';
  const KEY='luviaUserProfileCacheV1';
  const listeners=new Set();
  let state={profile:null,loaded:false,syncing:false,error:null,lastSyncedAt:null};
  const defaults=user=>({userId:user?.id||null,email:user?.email||'',displayName:user?.user_metadata?.display_name||user?.user_metadata?.full_name||user?.email?.split('@')[0]||'Luvia Reisende:r',firstName:user?.user_metadata?.first_name||'',lastName:user?.user_metadata?.last_name||'',avatarUrl:'',avatarColor:'#ee6f83',language:'de',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'Europe/Berlin',homeLocation:'',dietaryPreferences:[],travelPreferences:{pace:'balanced',budget:'medium',interests:[]},themeMode:'system',density:'comfortable',reducedMotion:false,useTripAccent:true,defaultView:'dashboard',showArchivedTrips:false,personalizedRecommendations:true,activityData:true,locationSharing:false,notifications:false,activeTripId:null,archivedTripIds:[],coverPreferences:{mode:'accent'},dashboardWidgets:[],createdAt:null,updatedAt:null});
  const read=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'null')}catch{return null}};
  const write=value=>{try{localStorage.setItem(KEY,JSON.stringify(value))}catch{}};
  const snap=()=>Object.freeze({...state,profile:state.profile?structuredClone(state.profile):null});
  function emit(reason){const s=snap();listeners.forEach(fn=>{try{fn(s)}catch(e){console.warn('[LuviaProfile]',e)}});window.dispatchEvent(new CustomEvent('luvia:profile-changed',{detail:{...s,reason}}));return s;}
  function mapRow(row,user){const base=defaults(user),settings=row?.settings||{},prefs=row?.travel_preferences||{};return {...base,userId:row?.user_id||base.userId,email:user?.email||base.email,displayName:row?.display_name||base.displayName,firstName:row?.first_name||'',lastName:row?.last_name||'',avatarUrl:row?.avatar_url||'',avatarColor:row?.avatar_color||base.avatarColor,language:row?.language||base.language,timezone:row?.timezone||base.timezone,homeLocation:row?.home_location||'',dietaryPreferences:row?.dietary_preferences||[],travelPreferences:{...base.travelPreferences,...prefs},themeMode:row?.theme_mode||settings.themeMode||base.themeMode,density:settings.density||base.density,reducedMotion:Boolean(settings.reducedMotion),useTripAccent:settings.useTripAccent!==false,defaultView:settings.defaultView||base.defaultView,showArchivedTrips:Boolean(settings.showArchivedTrips),personalizedRecommendations:settings.personalizedRecommendations!==false,activityData:settings.activityData!==false,locationSharing:Boolean(settings.locationSharing),notifications:Boolean(settings.notifications),activeTripId:row?.active_trip_id||null,archivedTripIds:settings.archivedTripIds||[],coverPreferences:settings.coverPreferences||base.coverPreferences,dashboardWidgets:Array.isArray(settings.dashboardWidgets)?settings.dashboardWidgets:base.dashboardWidgets,createdAt:row?.created_at||null,updatedAt:row?.updated_at||null};}
  function rowPayload(p){return {p_display_name:p.displayName,p_first_name:p.firstName||null,p_last_name:p.lastName||null,p_avatar_url:p.avatarUrl||null,p_avatar_color:p.avatarColor||'#ee6f83',p_language:p.language||'de',p_timezone:p.timezone||'Europe/Berlin',p_home_location:p.homeLocation||null,p_dietary_preferences:p.dietaryPreferences||[],p_travel_preferences:p.travelPreferences||{},p_theme_mode:p.themeMode||'system',p_active_trip_id:p.activeTripId||null,p_settings:{density:p.density,reducedMotion:Boolean(p.reducedMotion),useTripAccent:p.useTripAccent!==false,defaultView:p.defaultView||'dashboard',showArchivedTrips:Boolean(p.showArchivedTrips),personalizedRecommendations:p.personalizedRecommendations!==false,activityData:p.activityData!==false,locationSharing:Boolean(p.locationSharing),notifications:Boolean(p.notifications),archivedTripIds:p.archivedTripIds||[],coverPreferences:p.coverPreferences||{mode:'accent'},dashboardWidgets:Array.isArray(p.dashboardWidgets)?p.dashboardWidgets:[]}};}
  async function load(client){const auth=window.ParisAuth.getState(),user=auth.user;if(!auth.authenticated||!user){state={profile:null,loaded:true,syncing:false,error:null,lastSyncedAt:null};return emit('signed-out');}const cached=read();state={...state,profile:{...defaults(user),...(cached?.userId===user.id?cached:{})},syncing:true,error:null};emit('cache-loaded');try{const r=await client.rpc('luvia_get_my_profile');if(r.error)throw r.error;const row=Array.isArray(r.data)?r.data[0]:r.data;state.profile=mapRow(row,user);state.loaded=true;state.syncing=false;state.lastSyncedAt=new Date().toISOString();write(state.profile);return emit('cloud-loaded');}catch(error){console.warn('[LuviaProfile] Cloud-Profil nicht verfügbar.',error);state.loaded=true;state.syncing=false;state.error=error;return emit('offline-cache');}}
  async function save(patch){const client=await window.LuviaSupabaseService.start(),auth=window.ParisAuth.getState();if(!auth.authenticated)throw new Error('Bitte zuerst anmelden.');const next={...(state.profile||defaults(auth.user)),...patch,updatedAt:new Date().toISOString()};state.profile=next;state.syncing=true;state.error=null;write(next);emit('saving');try{const r=await client.rpc('luvia_upsert_my_profile',rowPayload(next));if(r.error)throw r.error;const row=Array.isArray(r.data)?r.data[0]:r.data;state.profile=mapRow(row,auth.user);state.syncing=false;state.lastSyncedAt=new Date().toISOString();write(state.profile);emit('saved');return state.profile;}catch(error){state.syncing=false;state.error=error;emit('save-failed');throw error;}}
  async function setActiveTrip(id){const p=await save({activeTripId:id||null});return p.activeTripId;}
  async function archiveTrip(id,archived=true){const set=new Set(state.profile?.archivedTripIds||[]);archived?set.add(id):set.delete(id);return save({archivedTripIds:[...set]});}
  function completion(){const p=state.profile||{};const fields=[p.displayName,p.avatarUrl,p.homeLocation,p.timezone,(p.dietaryPreferences||[]).length,(p.travelPreferences?.interests||[]).length];return Math.round(fields.filter(Boolean).length/fields.length*100);}
  window.LuviaProfileService=Object.freeze({version:'1.1.0',load,save,setActiveTrip,archiveTrip,completion,snapshot:snap,subscribe(fn){listeners.add(fn);fn(snap());return()=>listeners.delete(fn)}});
})();
