'use strict';
const assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),path=require('node:path'),fs=require('node:fs');
globalThis.Deno={env:{get:()=>''}};
(async()=>{
  const apple=await import(pathToFileURL(path.resolve(__dirname,'../supabase/functions/luvia-gateway/_shared/apple-maps.ts')));
  assert.equal(apple.appleMapsConfiguration().configured,false);
  assert.throws(()=>apple.assertAppleMapsDisplayContract({mapRenderer:'maplibre',storageContract:'transient'}),error=>error.code==='APPLE_MAP_DISPLAY_REQUIRED');
  assert.throws(()=>apple.assertAppleMapsDisplayContract({mapRenderer:'apple-mapkit',storageContract:'durable'}),error=>error.code==='APPLE_MAP_TRANSIENT_STORAGE_REQUIRED');
  assert.deepEqual(apple.assertAppleMapsDisplayContract({mapRenderer:'apple-mapkit',storageContract:'transient'}),{renderer:'apple-mapkit',storage:'transient'});
  assert.equal(apple.appleCategoriesFor({category:'food',includedTypes:['vegetarian_restaurant'],strictTypeFiltering:true}).supported,false,'Apple must not invent dietary or national-cuisine evidence');
  assert(apple.appleCategoriesFor({category:'nightlife'}).categories.includes('Nightlife'));
  const place=apple.normalizeApplePlace({id:'I123',name:'Strand Café',poiCategory:'Cafe',coordinate:{latitude:54.02,longitude:10.75},formattedAddressLines:['Strandallee 1','23683 Scharbeutz'],urls:['https://example.test'],telephone:'+494500000'});
  assert.equal(place.providerPlaceId,'apple:I123');assert.equal(place.primaryType,'cafe');assert.equal(place.persistenceAllowed,false);assert.equal(place.displayContract,'apple-mapkit-only');assert.equal(place.photos.length,0);
  const routes=apple.normalizeAppleDirections({routes:[{distanceMeters:800,durationSeconds:600,stepIndexes:[0,1]}],steps:[{stepPathIndex:0},{stepPathIndex:1}],stepPaths:[[{latitude:54,longitude:10.7},{latitude:54.01,longitude:10.71}],[{latitude:54.01,longitude:10.71},{latitude:54.02,longitude:10.72}]]},'WALK');
  assert.deepEqual(routes[0].geometry.coordinates,[[10.7,54],[10.71,54.01],[10.72,54.02]]);assert.equal(routes[0].persistenceAllowed,false);
  const migration=fs.readFileSync(path.resolve(__dirname,'../supabase/migrations/20260905193000_apple_maps_compliance_provider.sql'),'utf8');
  assert.match(migration,/apple-maps-services/);
  assert.match(migration,/operations,enabled,daily_limit,monthly_limit/);
  assert.match(migration,/\],false,0,0,10/);
  assert.match(migration,/must not enter MapLibre/);
  const rendererConfig=JSON.parse(fs.readFileSync(path.resolve(__dirname,'../config/luvia-map-renderers.v1.json'),'utf8'));
  assert.equal(rendererConfig.visibleSurfacePolicy.maximumConcurrentRenderers,1);
  assert.equal(rendererConfig.releasePolicy.currentPrimary,'maplibre');
  assert.equal(rendererConfig.releasePolicy.plannedPrimary,'maplibre');
  assert.equal(rendererConfig.releasePolicy.optionalPaidCandidate,'apple-mapkit');
  assert.equal(rendererConfig.releasePolicy.optionalCandidateFallback,'maplibre');
  assert.equal(rendererConfig.releasePolicy.appleEnrollmentPolicy,'defer_until_ios_distribution_or_explicit_paid_decision');
  assert(rendererConfig.releasePolicy.optionalCandidateActivationRequires.includes('paid_apple_developer_program_membership_or_team_access'));
  assert(rendererConfig.renderers.maplibre.forbiddenProviderData.includes('apple'));
  assert.equal(rendererConfig.fallbackTransition.removeAppleMapDataBeforeMapLibre,true);
  console.log('Apple Maps provider contract: Apple-MapKit-only display, transient storage, truthful taxonomy and disabled budget: PASS');
})().catch(error=>{console.error(error);process.exitCode=1});
