'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={console,Date,Promise,Map,Set,Object,Array,Math,Number,String,Boolean,RegExp,JSON};
ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);
const load=file=>vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
load('core/places/places-domain-contract-core.js');load('core/places/global-place-contracts.js');
const api=ctx.LuviaGlobalPlaceContracts,domain=ctx.LuviaPlacesDomainContractCoreV1;
const place=(id,name,features={})=>({id,providerPlaceId:id,name,types:['restaurant'],features,location:{latitude:54.0225,longitude:10.7544}});
for(const [query,city]of [['Zeige mir Restaurants in Scharbeutz.','Scharbeutz'],['Restaurants in Scharbeutz anzeigen · Restaurants suchen','Scharbeutz'],['Restaurants in Bremen auflisten','Bremen'],['Restaurants in Bremen entdecken','Bremen'],['Show restaurants in Copenhagen','Copenhagen']]){
 const contract=api.evidenceContract(query,'food',{},city);
 assert.equal(contract.strict,false,query+' must remain category discovery');
 assert.equal(api.accepts(place('generic','Essbar'),'food',query,{}, {evidenceContract:contract}),true);
}
assert.equal(api.accepts(place('generic','Essbar'),'food','Kletterpark finden',{}, {evidenceContract:api.evidenceContract('Kletterpark finden','food')}),false);
assert.equal(api.accepts(place('steak','Kleines Steakhouse',{servesVegetarianFood:true}),'food','Vegetarisch geeignetes Restaurant',{}),false);
assert.equal(api.accepts({...place('steak','Kleines Steakhouse',{servesVegetarianFood:true}),types:['restaurant','vegetarian']},'food','Vegetarisch geeignetes Restaurant',{}),false);
assert.equal(api.accepts(place('veg','Gartenküche',{servesVegetarianFood:true}),'food','Veganes Restaurant',{}),false);
assert.equal(api.accepts(place('vegan','Gartenküche',{servesVegetarianFood:true,servesVeganFood:true}),'food','Veganes Restaurant',{}),true);
assert.equal(api.accepts(place('vegan','Gartenküche',{servesVeganFood:true}),'food','Veganes Restaurant',{}),true);
assert.equal(api.accepts(place('vegan','Vegan Döner'),'food','Veganes Restaurant',{}),true);
assert.equal(api.accepts(place('vegan','Vegan Döner',{servesVeganFood:false}),'food','Veganes Restaurant',{}),false);
assert.equal(api.spatialIntent('Restaurant am Wasser').prefer.includes('waterfront'),true);
assert.equal(api.queryCascade({text:'Restaurant in Bremen',category:'food'},'Bremen')[0],'Restaurant in Bremen');
assert.equal(domain.localSearchRadius({searchRadiusMeters:20000}),3000);
assert.equal(domain.localSearchRadius({searchRadiusMeters:20000},5000),5000);
assert.equal(domain.localSearchRadius({},NaN),3000);
const raw=Array.from({length:20},(_,i)=>place('thin-'+i,'Restaurant '+i));
raw.push(place('grand','Grande Beach Café',{servesVegetarianFood:true}),place('coast','COAST',{servesVegetarianFood:true}),place('roof','ROOF',{servesVegetarianFood:true}));
const calls=[];
ctx.LuviaPlaceEntities={searchPlaces:async options=>{calls.push(options);return{data:{places:raw.slice(0,options.maxResultCount),providers:{requested:['geoapify'],used:['geoapify']}}}}};
ctx.LuviaAI=null;ctx.LuviaIntelligenceContractV1=null;
load('app/adapters/places-discovery-adapter.js');
(async()=>{
 const request={text:'Vegetarisch geeignetes Restaurant am Wasser in Scharbeutz finden',category:'food',destination:'Scharbeutz',destinationContext:{name:'Scharbeutz',location:{latitude:54.0225,longitude:10.7544},searchRadiusMeters:20000},limit:3,queryVariantLimit:3,diversity:{minimumQueryVariants:1,targetCandidates:3},strictPlaceType:'restaurant'};
 const thin=await ctx.LuviaPlacesDiscoveryService.recommend({...request,candidateLimit:20});
 assert.equal(thin.places.length,0,'first twenty contain no dietary proof');
 calls.length=0;
 const full=await ctx.LuviaPlacesDiscoveryService.recommend({...request,candidateLimit:50});
 assert.equal(full.places.length,3,'eligible restaurants beyond twenty must be considered');
 assert.equal(calls.length,1,'three visible eligible results stop the cascade');
 assert.equal(calls[0].maxResultCount,50,'cached smaller windows must not poison broader reads');
 assert.equal(calls[0].destination.searchRadiusMeters,3000,'same local radius as map');
 assert.equal(full.selectionMeta.rawCandidateCount,23);
 assert.equal(full.selectionMeta.eligibleCandidateCount,3);
 calls.length=0;
 await ctx.LuviaPlacesDiscoveryService.recommend({...request,candidateLimit:50});
 assert.equal(calls.length,0,'equivalent repeat uses bounded cache');
 const profile=await ctx.LuviaPlacesDiscoveryService.recommend({...request,text:'Zeige mir Restaurants in Scharbeutz.',candidateLimit:50,requirePreferenceEvidence:true,preferences:{dietaryPreferences:['vegetarian']}});
 assert.equal(profile.places.length,3);
 assert.ok(profile.places.every(p=>p.features.servesVegetarianFood===true),'confirmed profile must exclude unknown diet from chat recommendations');
 const runtime=fs.readFileSync('core/ai/ai-action-runtime.js','utf8'),dashboard=fs.readFileSync('core/ai/ai-dashboard-service.js','utf8'),adapter=fs.readFileSync('core/platform/places-contract-adapter.js','utf8');
 assert.match(runtime,/resultStatus:cards.length\?'ready':'empty'/);
 assert.doesNotMatch(dashboard,/Die passenden Informationen sind da/);
 assert.match(adapter,/selectionMeta:response/);assert.match(adapter,/evidenceContract:response/);
 const sheet=fs.readFileSync('app/journey/journey-suggestion-sheet.js','utf8');
 const planning={clean:v=>String(v||'').trim(),dateValue:v=>String(v||'').slice(0,10)};
 vm.createContext(planning);vm.runInContext(sheet.slice(sheet.indexOf('function planningDay('),sheet.indexOf('function currentInput(')),planning);
 const trip={startDate:'2027-06-12',endDate:'2027-06-19'};
 assert.equal(planning.planningDay({},trip,{targetDate:'2026-08-31'},{}),'2027-06-12','stale timeline guidance cannot choose the previous year');
 assert.equal(planning.planningDay({},trip,{targetDate:'2027-06-14'},{}),'2027-06-14');
 assert.equal(planning.planningDay({targetDate:'2027-06-13'},trip,{targetDate:'2027-06-14'},{}),'2027-06-13');
 assert.equal(planning.planningDay({targetDate:'2026-08-31'},trip,{},{}),'2027-06-12','legacy surface target date must also stay inside the current trip');
 assert.match(sheet,/name="date" type="date" required/);assert.match(sheet,/name="time" type="time" required/);
 let writes=0;const plan={},subject={id:'roof'},form={querySelector:()=>({}),reportValidity:()=>false,scrollIntoView:()=>{}};
 const review={result:{choices:[subject],input:{}},providerId:p=>p.id,schedulerFor:()=>form,scheduleFor:()=>[{place:subject,fits:true}],selectedPlaces:()=>[subject],plans:new Map(),ensurePlan:()=>plan,sync:()=>{},commitOrPropose:()=>{writes++;}};
 vm.createContext(review);vm.runInContext(sheet.slice(sheet.indexOf('  const commitPlan=async'),sheet.indexOf("  root.addEventListener('click',event=>{const footerPlan"))+';globalThis.commitPlan=commitPlan;',review);
 await review.commitPlan('roof',{});assert.equal(plan.reviewing,true);assert.equal(writes,0,'opening the planning form must not persist a default time');
 await review.commitPlan('roof',{});assert.equal(writes,0,'invalid visible inputs must not persist');
 const timeline=fs.readFileSync('core/places/timeline-core.js','utf8'),durationContext={enrichOwnerPlace:x=>x,typeIcon:()=>''};vm.createContext(durationContext);
 vm.runInContext(timeline.slice(timeline.indexOf('function dataEntry('),timeline.indexOf('function eventEntry(')),durationContext);
 assert.equal(durationContext.dataEntry({fields:{metadata:{durationMinutes:90}}}).durationMinutes,90,'owner-declared duration must reach Journey');
 assert.equal(durationContext.dataEntry({fields:{metadata:{durationMinutes:-1}}}).durationMinutes,null,'invalid duration is not a declared plan');
 let handoff,attempts=0,routeMode='external',optionsSeen;
 const nearby={hidden:true,innerHTML:'',reveals:0,scrollIntoView(){this.reveals++},querySelector(){return{append:action=>{handoff=action}}}};
 const distant={hidden:true},button={textContent:'Reservierung prüfen'},viewState={completed:[]};
 const bookingContext={clean:v=>String(v||'').trim(),esc:v=>String(v||''),providerId:p=>p.id,FormData:class{get(){return''}},dateValue:v=>v,timeValue:()=>'',document:{createElement:()=>({dataset:{},addEventListener(type,fn){this.click=fn},focus(){},scrollIntoView(){}})},contracts:()=>({booking:{commands:{openPlaceBooking:async(p,options)=>{optionsSeen=options;if(routeMode==='external'){options.onExternalReady({route:{provider:'official_website'},open:async()=>{attempts++;if(attempts===1)throw Error('Fenster blockiert');options.onExternal({route:{provider:'official_website'}})}});return{channel:'external_ready'}}options.onUnavailable({route:{reason:routeMode==='technical'?'ROUTE_PREVIEW_UNAVAILABLE':'NO_VERIFIED_ROUTE'}});return{channel:'unavailable'}}}}})};
 vm.createContext(bookingContext);vm.runInContext(sheet.slice(sheet.indexOf('async function openBooking('),sheet.indexOf('function durationFor(')),bookingContext);
 const handle={overlay:{querySelector:selector=>selector==='[data-lvjs-status]'?distant:{}}};
 await bookingContext.openBooking({id:'roof',name:'ROOF'},button,{},handle,{input:{}},viewState,nearby);
 assert.match(nearby.innerHTML,/Reservierungsseite von ROOF gefunden/);assert.equal(distant.hidden,true,'result must be beside the initiating action, not offscreen above it');
 assert.doesNotMatch(nearby.innerHTML,/official_website|Booking Core prüft/);assert.ok(nearby.reveals>0);assert.equal(button.disabled,false);assert.equal(attempts,0,'route preview must not open a provider window');
 await handoff.click();assert.equal(handoff.disabled,false,'blocked handoff remains retryable');await handoff.click();assert.equal(attempts,2);assert.match(nearby.innerHTML,/Reservierungsseite geöffnet/);
 routeMode='manual';await bookingContext.openBooking({id:'roof',name:'ROOF',address:'Strandallee 130a'},button,{},handle,{input:{}},viewState,nearby);assert.match(nearby.innerHTML,/Bitte direkt beim Ort anfragen/);assert.match(nearby.innerHTML,/Strandallee 130a/);
 routeMode='technical';await bookingContext.openBooking({id:'roof',name:'ROOF'},button,{},handle,{input:{}},viewState,nearby);assert.match(nearby.innerHTML,/gerade nicht prüfbar/);assert.doesNotMatch(nearby.innerHTML,/weder ein nutzbarer/,'outage is not evidence of absent contact');
 let recoveryNow=Date.now(),recoveryMode='success',recoveryProvider='geoapify';
 ctx.Date=class extends Date{static now(){return recoveryNow}};
 ctx.LuviaPlaceEntities.searchPlaces=async()=>{if(recoveryMode==='fail')throw Object.assign(new Error('timeout'),{code:'TIMEOUT'});return{data:{places:recoveryMode==='empty'?[]:[place(recoveryProvider+':retained','Küstenküche')],providers:{requested:[recoveryProvider],used:[recoveryProvider]}}}};
 load('app/adapters/places-discovery-adapter.js');
 const recoveryRequest={tripId:'recovery',text:'Restaurants',category:'food',destinationContext:{name:'Scharbeutz'},fastPath:true,fastQueryLimit:1,candidateLimit:20,limit:20};
 const discover=opts=>ctx.LuviaPlacesDiscoveryService.recommend({...recoveryRequest,...opts});
 const verified=await discover();assert.equal(verified.places.length,1);
 recoveryNow+=4*60*1000;recoveryMode='fail';
 const recovered=await discover();assert.equal(recovered.places[0].providerPlaceId,verified.places[0].providerPlaceId);assert.equal(recovered.plan.attempts[0].stale,true);assert.equal(recovered.places[0].ownerObservedAt,verified.places[0].ownerObservedAt,'recovery does not pretend to be a fresh observation');
 await assert.rejects(discover({destinationContext:{name:'Bremen'}}),/timeout/,'another destination cannot reuse the cohort');
 await assert.rejects(discover({includedTypes:['cafe']}),/timeout/,'another filter cannot reuse the cohort');
 await assert.rejects(discover({openNow:true}),/timeout/,'current opening status cannot use stale data');
 recoveryNow+=12*60*1000;await assert.rejects(discover(),/timeout/,'recovery expires without sliding the original observation time');
 recoveryMode='success';await discover();recoveryNow+=4*60*1000;recoveryMode='empty';assert.equal((await discover()).places.length,0);
 recoveryMode='fail';await assert.rejects(discover(),/timeout/,'a successful empty result invalidates earlier cached places');
 recoveryMode='success';recoveryProvider='google';await discover();recoveryNow+=4*60*1000;recoveryMode='fail';await assert.rejects(discover(),/timeout/,'other provider content is excluded from this recovery policy');
 console.log('B1 discovery, bounded recovery, dietary proof, trip day and explicit plan review: PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
