'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const ctx={console,Date,Promise,Map,Set,Object,Array,Math,Number,String,Boolean,RegExp,JSON};
ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);
const load=file=>vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
load('core/places/places-domain-contract-core.js');load('core/places/global-place-contracts.js');
const api=ctx.LuviaGlobalPlaceContracts,domain=ctx.LuviaPlacesDomainContractCoreV1;
const place=(id,name,features={})=>({id,providerPlaceId:id,name,types:['restaurant'],features,location:{latitude:54.0225,longitude:10.7544}});
for(const [query,city]of [['Zeige mir Restaurants in Scharbeutz.','Scharbeutz'],['Restaurants in Scharbeutz anzeigen · Restaurants suchen','Scharbeutz'],['Restaurants in Bremen auflisten','Bremen'],['Restaurants in Bremen entdecken','Bremen'],['Show restaurants in Copenhagen','Copenhagen']]){
 const contract=api.evidenceContract(query,'food',{},city);
 assert.equal(contract.strict,false,query+' must remain category discovery');
 assert.equal(api.accepts(place('generic','Essbar'),'food',query,{}, {evidenceContract:contract}),true);
}
assert.equal(api.accepts(place('generic','Essbar'),'food','Kletterpark finden',{}, {evidenceContract:api.evidenceContract('Kletterpark finden','food')}),false);
assert.equal(api.accepts(place('steak','Kleines Steakhouse',{servesVegetarianFood:true}),'food','Vegetarisch geeignetes Restaurant',{}),false);
assert.equal(api.accepts({...place('steak','Kleines Steakhouse',{servesVegetarianFood:true}),types:['restaurant','vegetarian']},'food','Vegetarisch geeignetes Restaurant',{}),false);
assert.equal(api.accepts(place('veg','Gartenküche',{servesVegetarianFood:true}),'food','Veganes Restaurant',{}),false);
assert.equal(api.accepts(place('vegan','Gartenküche',{servesVegetarianFood:true,servesVeganFood:true}),'food','Veganes Restaurant',{}),true);
assert.equal(api.accepts(place('vegan','Gartenküche',{servesVeganFood:true}),'food','Veganes Restaurant',{}),true);
assert.equal(api.accepts(place('vegan','Vegan Döner'),'food','Veganes Restaurant',{}),true);
assert.equal(api.accepts(place('vegan','Vegan Döner',{servesVeganFood:false}),'food','Veganes Restaurant',{}),false);
assert.equal(api.spatialIntent('Restaurant am Wasser').prefer.includes('waterfront'),true);
assert.equal(api.queryCascade({text:'Restaurant in Bremen',category:'food'},'Bremen')[0],'Restaurant in Bremen');
assert.equal(domain.localSearchRadius({searchRadiusMeters:20000}),3000);
assert.equal(domain.localSearchRadius({searchRadiusMeters:20000},5000),5000);
assert.equal(domain.localSearchRadius({},NaN),3000);
const raw=Array.from({length:20},(_,i)=>place('thin-'+i,'Restaurant '+i));
raw.push(place('grand','Grande Beach Café',{servesVegetarianFood:true}),place('coast','COAST',{servesVegetarianFood:true}),place('roof','ROOF',{servesVegetarianFood:true}));
const calls=[];
ctx.LuviaPlaceEntities={searchPlaces:async options=>{calls.push(options);return{data:{places:raw.slice(0,options.maxResultCount),providers:{requested:['geoapify'],used:['geoapify']}}}}};
ctx.LuviaAI=null;ctx.LuviaIntelligenceContractV1=null;
load('app/adapters/places-discovery-adapter.js');
(async()=>{
 const request={text:'Vegetarisch geeignetes Restaurant am Wasser in Scharbeutz finden',category:'food',destination:'Scharbeutz',destinationContext:{name:'Scharbeutz',location:{latitude:54.0225,longitude:10.7544},searchRadiusMeters:20000},limit:3,queryVariantLimit:3,diversity:{minimumQueryVariants:1,targetCandidates:3},strictPlaceType:'restaurant'};
 const thin=await ctx.LuviaPlacesDiscoveryService.recommend({...request,candidateLimit:20});
 assert.equal(thin.places.length,0,'first twenty contain no dietary proof');
 calls.length=0;
 const full=await ctx.LuviaPlacesDiscoveryService.recommend({...request,candidateLimit:50});
 assert.equal(full.places.length,3,'eligible restaurants beyond twenty must be considered');
 assert.equal(calls.length,1,'three visible eligible results stop the cascade');
 assert.equal(calls[0].maxResultCount,50,'cached smaller windows must not poison broader reads');
 assert.equal(calls[0].destination.searchRadiusMeters,3000,'same local radius as map');
 assert.equal(full.selectionMeta.rawCandidateCount,23);
 assert.equal(full.selectionMeta.eligibleCandidateCount,3);
 calls.length=0;
 await ctx.LuviaPlacesDiscoveryService.recommend({...request,candidateLimit:50});
 assert.equal(calls.length,0,'equivalent repeat uses bounded cache');
 const profile=await ctx.LuviaPlacesDiscoveryService.recommend({...request,text:'Zeige mir Restaurants in Scharbeutz.',candidateLimit:50,requirePreferenceEvidence:true,preferences:{dietaryPreferences:['vegetarian']}});
 assert.equal(profile.places.length,3);
 assert.ok(profile.places.every(p=>p.features.servesVegetarianFood===true),'confirmed profile must exclude unknown diet from chat recommendations');
 const runtime=fs.readFileSync('core/ai/ai-action-runtime.js','utf8'),dashboard=fs.readFileSync('core/ai/ai-dashboard-service.js','utf8'),adapter=fs.readFileSync('core/platform/places-contract-adapter.js','utf8');
 assert.match(runtime,/resultStatus:cards.length\?'ready':'empty'/);
 assert.doesNotMatch(dashboard,/Die passenden Informationen sind da/);
 assert.match(adapter,/selectionMeta:response/);assert.match(adapter,/evidenceContract:response/);
 const sheet=fs.readFileSync('app/journey/journey-suggestion-sheet.js','utf8');
 const planning={clean:v=>String(v||'').trim(),dateValue:v=>String(v||'').slice(0,10)};
 vm.createContext(planning);vm.runInContext(sheet.slice(sheet.indexOf('function planningDay('),sheet.indexOf('function currentInput(')),planning);
 const trip={startDate:'2027-06-12',endDate:'2027-06-19'};
 assert.equal(planning.planningDay({},trip,{targetDate:'2026-08-31'},{}),'2027-06-12','stale timeline guidance cannot choose the previous year');
 assert.equal(planning.planningDay({},trip,{targetDate:'2027-06-14'},{}),'2027-06-14');
 assert.equal(planning.planningDay({targetDate:'2027-06-13'},trip,{targetDate:'2027-06-14'},{}),'2027-06-13');
 assert.equal(planning.planningDay({targetDate:'2026-08-31'},trip,{},{}),'2027-06-12','legacy surface target date must also stay inside the current trip');
 assert.match(sheet,/name="date" type="date" required/);assert.match(sheet,/name="time" type="time" required/);
 let writes=0;const plan={},subject={id:'roof'},form={querySelector:()=>({}),reportValidity:()=>false,scrollIntoView:()=>{}};
 const review={result:{choices:[subject],input:{}},providerId:p=>p.id,schedulerFor:()=>form,scheduleFor:()=>[{place:subject,fits:true}],selectedPlaces:()=>[subject],plans:new Map(),ensurePlan:()=>plan,sync:()=>{},commitOrPropose:()=>{writes++;}};
 vm.createContext(review);vm.runInContext(sheet.slice(sheet.indexOf('  const commitPlan=async'),sheet.indexOf("  root.addEventListener('click',event=>{const footerPlan"))+';globalThis.commitPlan=commitPlan;',review);
 await review.commitPlan('roof',{});assert.equal(plan.reviewing,true);assert.equal(writes,0,'opening the planning form must not persist a default time');
 await review.commitPlan('roof',{});assert.equal(writes,0,'invalid visible inputs must not persist');
 console.log('B1 discovery, bounded coverage, dietary proof, trip day and explicit plan review: PASS');
})().catch(e=>{console.error(e);process.exitCode=1});
