const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..');
const ui=fs.readFileSync(path.join(root,'core/booking/booking-ui.js'),'utf8');
const css=fs.readFileSync(path.join(root,'core/places/places-final-foundation.css'),'utf8');
const ver=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
const handoff=fs.readFileSync(path.join(root,'booking-handoff.html'),'utf8');
assert(ver.includes("core:'4.39.4'"));assert(ver.includes("build:'13.39.4'"));assert(html.includes('v=13.39.4'));
assert(ui.includes('const routeCache=new Map()'));
assert(ui.includes("document.addEventListener('pointerover'"));
assert(ui.includes("window.open('/booking-handoff.html','_blank')"));
assert(!ui.includes("window.open('about:blank','_blank')"));
assert(!ui.includes("button.textContent='Buchungsweg wird geprüft …'"));
assert(ui.includes("window.open(target.toString(),'_blank','noopener,noreferrer')"));
assert(css.includes('.places-final-result{height:auto;min-height:372px;max-height:none'));
assert(css.includes('.places-final-result-body{min-height:372px;overflow:visible'));
assert(!css.includes('height:350px;min-height:350px;max-height:350px'));
assert(handoff.includes('Luvia öffnet eure Reservierung'));
console.log('LUVIA_V13_39_4_BOOKING_HANDOFF_SPEED_OK');