const fs=require('fs'),path=require('path'),vm=require('vm'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const context={window:{LuviaBookingProviderCapabilities:{get:id=>({id,luviaAccessState:'partner_required',platform:{availability:false,createReservation:false,statusWebhook:null,statusPolling:true},attribution:'none'})}},console};context.globalThis=context;vm.createContext(context);
vm.runInContext(fs.readFileSync(path.join(root,'core/booking/providers/tock-adapter.js'),'utf8'),context);
const a=context.window.LuviaTockProviderAdapter;assert(a);
assert.equal(a.normalizeVenueReference('12345'),'12345');
assert.equal(a.normalizeVenueReference('venue_paris-1'),'venue_paris-1');
assert.equal(a.normalizeVenueReference('bad value with spaces'),null);
assert.equal(a.normalizeReservationReference('987654321'),'987654321');
assert.equal(a.mapProviderStatus('EXPECTED'),'confirmed');
assert.equal(a.mapProviderStatus('CANCELLED'),'cancelled');
assert.equal(a.mapProviderStatus('NO_SHOW'),'action_required');
assert.equal(a.mapProviderStatus('UNVERIFIED_NEW_STATE'),null,'unknown Tock status must not be guessed');
assert.equal(a.canApplyProviderStatus('EXPECTED'),true);
const cap=context.window.LuviaBookingProviderCapabilities.get('tock');
assert.equal(cap.luviaAccessState,'partner_required');
assert.equal(cap.platform.availability,false);
assert.equal(cap.platform.createReservation,false);
assert.equal(cap.platform.statusPolling,true);
console.log('LUVIA_V13_47_0_TOCK_ADAPTER_FOUNDATION_OK');
