const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'..');
const ui=fs.readFileSync(path.join(root,'core/booking/booking-ui.js'),'utf8');
const edge=fs.readFileSync(path.join(root,'supabase/functions/booking-route-resolve/index.ts'),'utf8');
const css=fs.readFileSync(path.join(root,'core/places/places-final-foundation.css'),'utf8');
const ver=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');
const html=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(ver.includes("core:'4.39.3'"));assert(ver.includes("build:'13.39.3'"));assert(html.includes('v=13.39.3'));
assert(ui.includes("window.open('about:blank','_blank')"));
assert(ui.includes('handoffWindow.location.replace'));
assert(!ui.includes("window.location.assign(target.toString())"));
assert(!ui.includes("button.textContent='Buchungsweg wird geprüft …'"));
assert(ui.includes('handoffWindow.close()'));
assert(edge.includes("const VERSION='1.3.0'"));
assert(edge.includes('BROKEN_HANDOFF_HINT'));
assert(edge.includes('validateHandoff'));
assert(edge.includes("reason:'BROKEN_WIDGET_OR_PAGE'"));
assert(edge.includes("reason:'VENUE_MISMATCH'"));
assert(edge.includes("'NO_HEALTHY_BOOKING_ROUTE'"));
assert(css.includes('.places-final-result{height:350px;min-height:350px;max-height:350px}'));
assert(css.includes('-webkit-line-clamp:2'));
console.log('LUVIA_V13_39_3_BOOKING_HANDOFF_RELIABILITY_OK');
