const fs=require('fs'),assert=require('assert');
const moduleCode=fs.readFileSync('modules/cycling-routes/cycling-route-module.js','utf8');
const moduleCss=fs.readFileSync('modules/cycling-routes/cycling-route-module.css','utf8');
const service=fs.readFileSync('intelligence/cycling-route-service.js','utf8');
const gateway=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling.ts','utf8');
const shell=fs.readFileSync('core/places/place-experience-shell.js','utf8');
const contract=fs.readFileSync('core/places/place-ui-contract.js','utf8');
for(const token of ['LuviaPlaceExperience.moduleShell','loadingSources:new Set()','Promise.allSettled','resultCache:new Map()','radiusMeters:100000','200000','mergeResults','progressMarkup'])assert(moduleCode.includes(token),`Cycling progressive discovery token missing: ${token}`);
assert(!moduleCode.includes('await search(\'Mountainbike Trails Gravel Fahrradrouten\''),'Module mount must not block on the initial route search');
assert(!moduleCode.includes('luv-cycling-head'),'Cycling must not render a local header class');
assert(!moduleCss.includes('.luv-cycling-head'),'Cycling CSS must not override the canonical Place header');
for(const token of ['function moduleShell','canonical-module-shell'])assert(shell.includes(token),`Global module shell token missing: ${token}`);
assert(contract.includes("renderer:'LuviaPlaceExperience.moduleShell'"),'UI contract does not name the global module shell renderer');
for(const token of ['searchTimeoutMs:9500','defaultRadiusMeters:100000','maxRadiusMeters:200000','CACHE_TTL'])assert(service.includes(token),`Cycling client performance token missing: ${token}`);
for(const token of ['Promise.any','7200','parallelEndpoints:true','significantWords','qualityScore','distanceFromDestinationMeters','100000','200000'])assert(gateway.includes(token),`Cycling gateway performance/quality token missing: ${token}`);
assert(gateway.includes('warning=error instanceof Error'),'Search must fail soft instead of causing repeated transient backend retries');
assert(moduleCode.includes('new FormData(event.target)'),'Cycling search must read the actual global search form');
assert(moduleCode.includes('pull.?&.?bear'),'Google fallback must reject clearly irrelevant shopping results');
console.log('Cycling search performance and global UI conformance: OK');
