const fs=require('fs'),vm=require('vm'),assert=require('assert');
const code=fs.readFileSync('core/places/cycling-route-intelligence-service.js','utf8');
const sandbox={window:{}};vm.createContext(sandbox);vm.runInContext(code,sandbox);
const C=sandbox.window.LuviaCyclingRouteIntelligence;assert(C,'Cycling Route Intelligence missing');
let r=C.analyze({name:'Emsland MTB Singletrail',routeData:{profile:'mtb',distanceMeters:27400,estimatedDurationMinutes:137,difficulty:'S2',surface:'ground, gravel',roundTrip:true,network:'lcn',reference:'MTB 4',geometryPointCount:180}});
assert.strictEqual(r.routeProfile.value,'Mountainbike-Trail');
assert.strictEqual(r.difficulty.value,'S2');
assert(/27/.test(r.distance.value),'distance missing');
assert(/Mountainbike/.test(r.bikeRecommendation.value),'MTB bike recommendation missing');
assert(/Rundtour/.test(r.routeShape.value),'round trip classification missing');
r=C.analyze({name:'Gravel Runde',routeData:{profile:'gravel',distanceMeters:64000,surface:'fine_gravel',roundTrip:true}});
assert.strictEqual(r.routeProfile.value,'Gravel-Tour');
assert(/Gravelbike/.test(r.bikeRecommendation.value),'gravel recommendation missing');
r=C.analyze({name:'City Route',routeData:{profile:'city'}});
assert(/City-Radtour/.test(r.routeProfile.value),'city route classification missing');
assert(/Noch kein belastbares Höhenprofil/.test(r.elevation.value),'truthful elevation fallback missing');
const ext=C.extension({routeData:{profile:'mtb',osmType:'relation',osmId:'123',geometrySegments:[[{lat:1,lon:2},{lat:2,lon:3}]],roundTrip:true}},C.analyze({routeData:{profile:'mtb'}}));
assert.strictEqual(ext.osm_id,'123');assert(Array.isArray(ext.route_geometry));assert.strictEqual(ext.round_trip,true);
console.log('Cycling route intelligence: OK');
