const fs=require('fs'),assert=require('assert');
const gateway=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling.ts','utf8');
const google=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling-google.ts','utf8');
const index=fs.readFileSync('supabase/functions/luvia-gateway/index.ts','utf8');
const service=fs.readFileSync('intelligence/cycling-route-service.js','utf8');
const moduleCode=fs.readFileSync('modules/cycling-routes/cycling-route-module.js','utf8');
const intelligence=fs.readFileSync('core/places/cycling-route-intelligence-service.js','utf8');
for(const token of ['cycling.search.google','googleCyclingSearch','guaranteedPrimaryResults','cycling.search.routes','cycling.search.trails','cycling.search.generated'])assert(gateway.includes(token),`Gateway discovery token missing: ${token}`);
for(const token of ['places.googleapis.com/v1','routes.googleapis.com/directions/v2:computeRoutes',"travelMode: 'BICYCLE'",'syntheticAnchors','Promise.race','routesDoNotWaitForSlowPlaces','routeRetryWithReducedWaypoints'])assert(google.includes(token),`Google cycling token missing: ${token}`);
for(const token of ["'cycling.search.google'","'cycling.search.generated'","'cycling.search.routes'","'cycling.search.trails'"])assert(index.includes(token),`Gateway action missing: ${token}`);
for(const token of ['searchGoogle','searchGenerated','searchRoutes','searchTrails','googlePrimary:true',"'cycling.search.google'"])assert(service.includes(token),`Client discovery token missing: ${token}`);
for(const token of ["loadingSources=new Set(['google'])","loadingSources=new Set(['ors','trailforks','routes','trails'])",'LuviaPlaceExperience.moduleShell','LuviaPlaceExperience.discovery','searchGoogle','Google-Routen und Tourziele','Places API (New) und Routes API'])assert(moduleCode.includes(token),`Module discovery token missing: ${token}`);
assert(moduleCode.includes("search('Fahrradrouten und Trails',{profile:'touring',radiusMeters:120000})"),'Initial search must start with a useful broad touring profile');
for(const token of ['Google Routes','cycling_anchor','generated_round_trip','route_warnings','anchor_place_ids'])assert(intelligence.includes(token),`Cycling intelligence token missing: ${token}`);
console.log('Cycling discovery rebuild and Google-first architecture: OK');
