const fs=require('fs');
const vm=require('vm');
const assert=require('assert');
const gateway=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling.ts','utf8');
const googleGateway=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling-google.ts','utf8');
const gatewayIndex=fs.readFileSync('supabase/functions/luvia-gateway/index.ts','utf8');
const serviceCode=fs.readFileSync('intelligence/cycling-route-service.js','utf8');
const moduleCode=fs.readFileSync('modules/cycling-routes/cycling-route-module.js','utf8');
const intelligence=fs.readFileSync('core/places/cycling-route-intelligence-service.js','utf8');
const entityGateway=fs.readFileSync('supabase/functions/luvia-gateway/_shared/place-entities.ts','utf8');
for(const token of ['googleCyclingSearch','cycling.search.google','OPENROUTESERVICE_API_KEY','cycling.search.generated','cycling-mountain','round_trip'])assert(gateway.includes(token),`Hybrid gateway token missing: ${token}`);
for(const token of ['google-routes','generated_round_trip','cycling_anchor','anchorPlaceIds','viaPoints'])assert(googleGateway.includes(token),`Google hybrid token missing: ${token}`);
assert(gatewayIndex.includes("'cycling.search.google'"),'Google cycling action is not routed through the gateway');
for(const token of ['searchGoogle','searchTrailforks','searchGenerated',"'cycling.search.google'"])assert(serviceCode.includes(token),`Client hybrid token missing: ${token}`);
for(const token of ["loadingSources=new Set(['google'])",'Für euch erstellt','isGenerated','isGoogleAnchor','maxGeneratedResultCount:4'])assert(moduleCode.includes(token),`Cycling module hybrid token missing: ${token}`);
for(const token of ['generated_round_trip','generated_route','generation_profile','Google Routes'])assert(intelligence.includes(token),`Cycling intelligence hybrid token missing: ${token}`);
assert(entityGateway.includes("provider==='google-routes'?'google_routes'"),'Universal import must preserve Google Routes as canonical source');
const googleRoute={id:'google-cycle-mtb-test',providerPlaceId:'google-cycle-mtb-test',provider:'google-routes',source:'google_routes',name:'MTB-Erkundungsrunde · 18 km',primaryType:'cycling_route',location:{latitude:48.85,longitude:2.35},routeData:{generated:true,resultKind:'generated_round_trip',profile:'mtb',qualityScore:92,distanceMeters:18000,roundTrip:true,warnings:['Beta-Hinweis']}};
const anchor={id:'google-anchor-park',providerPlaceId:'google-anchor-park',provider:'google-places',source:'google_places',name:'Bois de Vincennes',primaryType:'cycling_route',location:{latitude:48.82,longitude:2.43},routeData:{resultKind:'cycling_anchor',qualityScore:76}};
const calls=[];
const context={console,setTimeout,clearTimeout,window:{LuviaBackend:{request:async(action,payload)=>{calls.push({action,payload});if(action==='cycling.search.google')return{data:{routes:[googleRoute],anchors:[anchor],summary:{selectedCount:1,anchorCount:1}}};return{data:{routes:[],summary:{selectedCount:0}}};}},LuviaDestination:{getActive:()=>({name:'Paris',countryCode:'FR',location:{latitude:48.85,longitude:2.35}})}}};
vm.createContext(context);vm.runInContext(serviceCode,context,{filename:'cycling-route-service.js'});
(async()=>{
  const api=context.window.LuviaCyclingRoutes;
  assert(api&&typeof api.searchGoogle==='function','searchGoogle API missing at runtime');
  const direct=await api.searchGoogle('MTB-Trails',{profile:'mtb'});
  assert.equal(direct.data.routes[0].provider,'google-routes');
  const combined=await api.search('MTB-Trails',{profile:'mtb'});
  assert.equal(combined.data.routes.length,2,'Google routes and anchors must survive the combined client merge');
  assert(calls.some(call=>call.action==='cycling.search.google'),'Google primary action was not requested');
  console.log('Cycling Google-first hybrid engine: OK');
})().catch(error=>{console.error(error);process.exit(1)});
