const fs=require('fs'),assert=require('assert');
const moduleCode=fs.readFileSync('modules/cycling-routes/cycling-route-module.js','utf8');
const moduleCss=fs.readFileSync('modules/cycling-routes/cycling-route-module.css','utf8');
const service=fs.readFileSync('intelligence/cycling-route-service.js','utf8');
const gateway=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling.ts','utf8');
const google=fs.readFileSync('supabase/functions/luvia-gateway/_shared/cycling-google.ts','utf8');
const shell=fs.readFileSync('core/places/place-experience-shell.js','utf8');
const contract=fs.readFileSync('core/places/place-ui-contract.js','utf8');
for(const token of ['LuviaPlaceExperience.moduleShell',"loadingSources=new Set(['google'])","loadingSources=new Set(['ors','trailforks','routes','trails'])",'Promise.allSettled','resultCache:new Map()','mergeResults','progressMarkup'])assert(moduleCode.includes(token),`Cycling progressive discovery token missing: ${token}`);
assert(moduleCode.indexOf('searchGoogle')<moduleCode.indexOf("loadingSources=new Set(['ors','trailforks','routes','trails'])"),'Google primary discovery must finish before optional supplements begin');
assert(!moduleCode.includes('luv-cycling-head'),'Cycling must not render a local header class');
assert(!moduleCss.includes('.luv-cycling-head'),'Cycling CSS must not override the canonical Place header');
for(const token of ['function moduleShell','canonical-module-shell'])assert(shell.includes(token),`Global module shell token missing: ${token}`);
assert(contract.includes("renderer:'LuviaPlaceExperience.moduleShell'"),'UI contract does not name the global module shell renderer');
for(const token of ['searchGoogle','googlePrimary:true','defaultRadiusMeters:150000','maxRadiusMeters:300000','CACHE_TTL'])assert(service.includes(token),`Cycling client performance token missing: ${token}`);
for(const token of ['googleCyclingSearch','Promise.allSettled','cycling.search.google','parallelEndpoints: true'])assert(gateway.includes(token),`Cycling gateway performance token missing: ${token}`);
for(const token of ['PROVIDER_TIMEOUT_MS = 8500','CACHE_TTL_MS = 30 * 60_000','Promise.race','1800','routesDoNotWaitForSlowPlaces','routeRetryWithReducedWaypoints','cfg.queries.slice(0, 3)'])assert(google.includes(token),`Google cycling performance token missing: ${token}`);
assert(moduleCode.includes('new FormData(event.target)'),'Cycling search must read the actual global search form');
console.log('Cycling search performance and global UI conformance: OK');
