const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const collab=read('core/collaboration/collaboration-service.js');
const gateway=read('supabase/functions/luvia-gateway/index.ts');
const config=read('supabase/config.toml');
const index=read('index.html');
const version=read('intelligence/kernel/version.js');
assert(collab.includes('heartbeatInFlight'));
assert(collab.includes('heartbeatReadyAfter'));
assert(collab.includes('sessionEpoch'));
assert(collab.includes('setTimeout(()=>{if(token===watchToken&&tripId===id)heartbeat()},1600)'));
assert(!collab.includes('await heartbeat();if(token!==watchToken'));
assert(gateway.indexOf("if(req.method==='OPTIONS')") < gateway.indexOf("if(!origin)return errorResponse(403"));
assert(gateway.includes("access-control-request-headers"));
assert(gateway.includes("version:'4.45.1',build:'13.45.1',core:'4.45.1'"));
assert(config.includes('[functions.luvia-gateway]\nverify_jwt = false'));
assert(index.includes('?v=13.45.1'));
assert(version.includes("core:'4.45.1'"));
assert(version.includes("build:'13.45.1'"));
console.log('LUVIA_V13_45_1_FINAL_CONSOLE_RELIABILITY_OK');
