const fs=require('fs');
const assert=require('assert');
const timeline=fs.readFileSync('core/places/timeline-core.js','utf8');
const actions=fs.readFileSync('core/places/place-ui-actions.js','utf8');
const experience=fs.readFileSync('core/places/place-experience-shell.js','utf8');
const tripData=fs.readFileSync('core/places/trip-place-data-service.js','utf8');
const uiContract=fs.readFileSync('core/places/place-ui-contract.js','utf8');
const typeContract=fs.readFileSync('core/places/place-type-contract.js','utf8');
const definitions=fs.readFileSync('core/places/place-type-definitions.js','utf8');
const css=fs.readFileSync('core/places/place-ui.css','utf8');
const restaurant=fs.readFileSync('modules/restaurants-v2/restaurant-module.js','utf8');

assert(timeline.includes("function isPlaceDataEntry"),'Place-data detector missing');
assert(timeline.includes("e.source==='place-data'||Boolean"),'Raw trip_place_data date entries are not detected');
assert(timeline.includes("function editEntry(e,onDone){return isPlaceDataEntry(e)?editPlaceDates(e,onDone):editLegacySchedule(e,onDone)}"),'Global editor still routes raw Place entries into legacy schedule writes');
assert(timeline.includes("const rowId=uuid(e?.rowId)"),'Legacy schedule writes are not UUID guarded');
assert(timeline.includes("form?.addEventListener('submit'"),'Planning editor is not a real form with Enter submit');
assert(timeline.includes("LuviaPlaceCollections?.saveDateFields"),'Planning editor does not use the global Place writer');
assert(timeline.includes("openPlanningEditor,editEntry"),'Global planning editor is not public');
assert(actions.includes("LuviaTimelineCore?.openPlanningEditor"),'Initial planning does not reuse the global editor');
assert(actions.includes("LuviaPlaceCollections.saveDateFields"),'Initial planning bypasses the global single writer');
assert(restaurant.includes("LuviaTimelineCore?.openPlanningEditor"),'Restaurant planning does not use the same global editor');
assert(experience.includes('function planningEditor'),'Shared planning form renderer missing');
assert(experience.includes('data-luvia-place-plan-form'),'Shared planning renderer is not a form');
assert(tripData.includes("canonicalTripPlaceId=canonicalUuid(tripPlaceId)"),'tripPlace UUID guard missing');
assert(tripData.includes("canonicalTripId=canonicalUuid(id)"),'trip UUID guard missing');
assert(uiContract.includes("planningDialog:'LuviaPlaceExperience.planningEditor'"),'UI contract does not declare the canonical planning editor');
assert(uiContract.includes("submitOnEnter:true"),'Enter submit is not contractually defined');
assert(typeContract.includes("'insightCards'"),'Insight Card capability missing from Place Type Contract');
assert(definitions.includes("insightCards:true"),'Productive insight types are not contractually marked');
assert(definitions.includes("insightSection:{key:'photoGuidance',layout:'cards'"),'Photo insight layout missing from contract');
assert(definitions.includes("insightSection:{key:'shoppingGuidance',layout:'cards'"),'Shopping insight layout missing from contract');
assert(css.includes('canonical contract-driven Place planning editor'),'Planning dialog styles are not owned by the global Place UI');
console.log('Global Place planning dialog and insight contract: OK');
