'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const fixture=fs.readFileSync('tests/fixtures/m16.5-block0-human-ai-consumer-browser.html','utf8');
const dashboard=fs.readFileSync('core/ai/ai-dashboard-service.js','utf8');
const projection=JSON.parse(fs.readFileSync('config/luvia-human-ai-consumer-projections.v1.json','utf8'));
assert.match(fixture,/B0\.08/);
assert.match(fixture,/human-ai-consumer-projection-core\.js/);
for(const text of ['Orte finden','Timeline','Angabe fehlt','Ohne Internet','Zwei Wünsche'])assert.ok(fixture.includes(text),text);
assert.match(fixture,/rückgängig/i);
assert.match(fixture,/14\.06\.2027/);
assert.match(fixture,/data-consumer-view/);
assert.equal(projection.projections.length,333);
assert.match(dashboard,/data-ai-consumer-projection/);
assert.match(dashboard,/projectIntentSummary/);
assert.match(dashboard,/projectPreview/);
assert.match(dashboard,/projectReceipt/);
assert.match(dashboard,/projectReadFailure/);
assert.match(dashboard,/readFailureProjection\(failure\)\.message/);
assert.match(dashboard,/projectResult/);
assert.match(dashboard,/data-ai-consumer-view/);
assert.doesNotMatch(dashboard,/Places bleibt Owner der Ortsdaten/);
assert.doesNotMatch(dashboard,/Verbindlich bestätigen/);
assert.doesNotMatch(dashboard,/alle erkannten Wünsche mit dir Schritt für Schritt/);
console.log('M16.5 Block 0 visible bright Human-AI consumer chat: PASS');
