'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');

const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const dashboard=read('core/ai/ai-dashboard-service.js');
const runtimeSource=read('core/ai/ai-action-runtime.js');
const actionCoreSource=read('core/intelligence/intelligence-action-contract-core.js');
const css=read('core/ai/ai-brain.css');
const experienceCss=read('core/experience/experience-foundation.css');
const fixture=read('tests/fixtures/m16.5ab-living-compass-ai-browser.html');

assert.match(dashboard,/kind:'sheet'/,'Luvia Compass must use the universal Living Sheet host');
assert.match(dashboard,/Was möchtest du erleben\?/);
assert.match(dashboard,/lvx-command-eyebrow">Luvia/);
assert.match(dashboard,/Ein Satz darf mehrere Wünsche enthalten/);
assert.match(dashboard,/actionResponse\.results\.forEach\(appendRichResult\)/,'every routed owner result must be rendered');
assert.match(dashboard,/LuviaJourneySuggestions\.openResults/,'AI Places must enter the shared Journey/Places result sheet');
assert.match(dashboard,/!offer\.payload\?\.fields\?\.planned_at/,'only an incomplete planning request may open the Journey planning sheet');
assert.match(dashboard,/selectedId:subject\.providerPlaceId/,'the directly selected AI Place remains selected');
assert.match(dashboard,/reads\?\.getActiveTrip/,'modern trip.v1 reads binding must work');
assert.match(dashboard,/askOverlay\?\.isConnected/,'the global chat mount must be idempotent');
assert.equal((fixture.match(/LuviaAIDashboard\.openChat\(/g)||[]).length,0,'the fixture must not register a second chat-open owner');
assert.equal(fixture.includes('window.LuviaAIActionRuntime={'),false,'the visible fixture must exercise the real production action runtime, not a no-op substitute');
assert.match(fixture,/window\.__ownerCalls=/,'visible owner-command evidence must remain inspectable in the fixture');
assert.match(fixture,/core\/ai\/ai-action-runtime\.js/,'the visible fixture must load the same action runtime as the app');
assert.match(runtimeSource,/multiIntent:requests\.length>1/);
assert.match(runtimeSource,/Zur Timeline hinzufügen/);
assert.match(runtimeSource,/commands\.importPlace/,'a confirmed concrete timeline request must enter Places through its public import command');
assert.match(runtimeSource,/commands\.updateLifecycle/,'a confirmed plan/unplan command must keep the Places lifecycle projection coherent');
assert.match(runtimeSource,/preferenceOwner:'identity\.v1'/,'Places discovery must record the confirmed Identity preference owner');
assert.match(dashboard,/data-ai-place-open/,'each inline Place result must expose the shared typed detail sheet');
assert.match(dashboard,/data-ai-place-map/,'each Places response must expose a shared MapLibre projection');
assert.match(dashboard,/data-map-renderer="maplibre"/,'the inline map must retain an inspectable renderer contract without technical consumer copy');
assert.match(dashboard,/Luvia Karte · Deine Suche/,'the inline map must preserve the original discovery request');
assert.match(dashboard,/readPlaceViewport\(result,descriptor\)/,'map gestures must reuse the original query and evidence gates');
assert.match(dashboard,/result\.kind==='place_collection'\?placeMapMarkup\(result\):/,'the inline AI Places result must not duplicate pins in a separate result grid');
assert.match(dashboard,/\.slice\(0,3\)/,'each wish must render no more than three Places cards');
assert.match(dashboard,/data-ai-place-detail-layer/,'AI Place selection must preserve the chat and open a second Living Sheet');
assert.match(dashboard,/LuviaPlaceDetails\.prepare/,'AI Place details must keep consuming the Places-owned detail read');
assert.doesNotMatch(dashboard,/LuviaApp\?\.openPlace/,'AI Place selection must not fall back into the legacy typed rv2 detail surface');
assert.doesNotMatch(dashboard,/rv2-/,'the AI-native Place detail consumer must not emit legacy rv2 markup');
assert.match(dashboard,/closeOnEscape:false/,'the chat host must defer Escape while its nested Place detail is active');
assert.match(dashboard,/if\(activePlaceDetail\)closePlaceSubject\(\);else LuviaUI\?\.closeTop\?\.\('escape'\)/,'Escape must close exactly one visible layer: detail first, chat second');
assert.match(experienceCss,/\.lvx-ai-place-detail-sheet/,'the nested Place detail Living Sheet must have its own accepted light consumer styling');
assert.match(dashboard,/Mit deinen freigegebenen Reiseinformationen/,'live output must be explained in consumer language');
assert.match(dashboard,/Ohne Live-Antwort – bitte wichtige Angaben prüfen/,'fallback output must remain visibly distinguishable without implementation jargon');
assert.match(dashboard,/actionResponse\.clarificationRequired/,'safe owner reads must survive a partial multi-intent that still needs mutation inputs');
assert.match(dashboard,/planning\.dialogue/,'the global chat must reuse the existing OpenAI planning capability for multilingual semantic decomposition');
assert.match(dashboard,/compileDialogue/,'model output must be recompiled through the browserless owner-safe validator');
assert.match(dashboard,/sliceIntentGraph/,'multi-wish conversations must execute one owner-safe sequence at a time');
assert.match(dashboard,/data-ai-sequence-continue/,'read-only results must require a visible explicit control before continuing to the next wish');
assert.match(dashboard,/successfulReceipt\(receipt\)\)await advanceConversation\('owner-receipt',entry\)/,'a successful confirmed result must continue the next wish through the guarded sequence');
assert.match(dashboard,/projectSequenceTransition\(\{nextLabel:next\.label\}\)/,'the next wish must be announced through concise consumer copy');
assert.match(dashboard,/data-ai-planning-trace/,'S16.01 must expose a visible planning trace');
assert.match(dashboard,/data-ai-read-retry/,'failed owner reads need an explicit read-only retry');
assert.match(dashboard,/data-ai-read-refine/,'failed owner reads need a manual refinement path');
assert.match(dashboard,/consumer\(\)\.projectReadFailure\(\{result,area:areaLabel\(result\.owner\)\}\)/,'provider failure must use the fail-closed consumer error projection instead of invented evidence');
assert.match(dashboard,/renderJourneyResilience/,'Journey day results must consume the S16.03 and S16.04 read projections');
assert.match(runtimeSource,/readRecovery:\{kind:'owner-read'/,'read failure recovery must be distinct from mutation retry');
assert.match(runtimeSource,/traceOnly:true,slice:'S16\.01'/,'S16.01 must be emitted as its own flaggable product result');
assert.match(runtimeSource,/prepare\('identity\.preferences\.update'/,'a complete explicit preference intent must prepare a real Identity owner confirmation');
assert.match(css,/\.luv-ai-proposal-overlay\.luvia-living-sheet-overlay/);
assert.match(css,/@media\(prefers-reduced-motion:reduce\)/);
assert.match(css,/scrollbar-width:none/);

const sandbox={window:{},globalThis:null,Object,Array,String,Number,Boolean,Date,Math,RegExp,JSON,Set,Map,console};
sandbox.globalThis=sandbox.window;
vm.runInNewContext(actionCoreSource,sandbox,{filename:'intelligence-action-contract-core.js'});
const core=sandbox.LuviaIntelligenceActionContractCoreV1;
assert.ok(core,'intelligence action contract missing');
const mappedPlace=core.normalizePlace({id:'places/map-place',name:'Map Place',coordinates:{latitude:54.02691,longitude:10.75756}});
assert.equal(mappedPlace.coordinates.latitude,54.02691,'valid Places owner coordinates must survive the Intelligence read projection');
assert.equal(core.normalizePlace({id:'places/invalid-map-place',coordinates:{latitude:154,longitude:10}}).coordinates,null,'invalid coordinates must be omitted instead of clamped or invented');
const routes=core.routeIntents('Am Dienstag gegen 13 Uhr vegetarisch essen, danach ins Museum und später unsere Buchungen prüfen.');
assert.equal(routes.length,3,'one natural-language sentence must route to Places, Journey and Booking');
assert.deepEqual(Array.from(routes,r=>r.actionId),['booking.trip.read','places.discovery.recommend','journey.day.read']);
assert.deepEqual(Array.from(routes.find(r=>r.actionId==='places.discovery.recommend').input.categories),['food','culture']);

console.log('M16.5AB Living Compass AI owner orchestration OK');
