'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const moduleSource=fs.readFileSync('modules/accommodations/accommodation-module.js','utf8');
const css=fs.readFileSync('modules/accommodations/accommodation-module.css','utf8');
const fixture=fs.readFileSync('tests/fixtures/m16.5-block1-hotel-consumer-owner-browser.html','utf8');

for(const token of ["VERSION='5.3.0-contextual-filters-history'",'luvia-hotels-bright-v3','data-hotel-search-status','Unterkünfte konnten nicht geladen werden','data-place-retry','reads.searchStayOffers','commands.openStayOffer','commands.openPlaceBooking','data-hotel-booking','openHotelSheet','data-hotel-map','mountProjection','cardReference','userGesture:true','Dieses Angebot öffnen','Datumsformat: TT.MM.JJJJ','Duffel Stays beantragt · Freigabe ausstehend','kein Marktbestpreis',"placeType:'accommodation'",'LuviaPlaceExperience.plannedPanel','LuviaPlaceExperience.discovery','LuviaPlaceCollections.favoritePanel','LuviaPlaceUI.card'])assert.ok(moduleSource.includes(token),`Hotel consumer owner token missing: ${token}`);
for(const forbidden of ['Tickets prüfen','Eintritt noch ungeklärt','data-book-accommodation'])assert.ok(!moduleSource.includes(forbidden),`Hotel module must not contain generic ticket semantics: ${forbidden}`);
assert.match(moduleSource,/function openHotelSheet\(selected,[\s\S]*?places:\[selected\],selectedId:providerId\(selected\)/,'one Hotel pin must open exactly one Hotel in the shared sheet');
assert.doesNotMatch(moduleSource,/function openHotelSheet\(selected,choices=/,'the Hotel pin contract must not carry the complete search result list into the sheet');
assert.doesNotMatch(moduleSource,/LuviaPlaceDetail(?!s)|data-hotel-detail-booking/,'the retired Hotel detail card must not remain in the consumer bundle');
assert.match(moduleSource,/onViewportSearch:descriptor=>spatial\.viewportSearch/,'Hotel map panning and zooming must use the shared live viewport contract');
assert.match(moduleSource,/onSelect:id=>focusHotel\(id,\{move:false\}\)/,'selecting a Hotel pin must not programmatically move the map and trigger another provider viewport read');
assert.match(moduleSource,/maxResultCount:80/,'the initial Hotel map must request the complete bounded provider result set');
assert.match(moduleSource,/maxResultCount:80[\s\S]*strictDestination:true/,'Hotel discovery must request a bounded complete provider page without claiming mathematical completeness');
assert.match(moduleSource,/onViewportResults:rows=>\{state\.results=filteredHotelRows\(spatial\?\.decoratePreferences\?\.\(rows,state\.trip\)\|\|rows\);state\.searchMap=new Map/,'live Hotel pins must replace and preference-decorate the selectable map projection atomically after exact local filters');
for(const token of ['bindMapPreviewGesture','data-hotel-fit-mode','data-hotel-map-navigate','data-hotel-map-tool="search"','data-hotel-map-tool="categories"','data-hotel-map-tool="filter"','data-hotel-map-preview','interactiveOrigin'])assert.ok(moduleSource.includes(token),`shared Hotel map interaction token missing: ${token}`);
assert.match(moduleSource,/onSelect:id=>focusHotel\(id,\{move:false\}\)/,'one Hotel pin must stage only its compact preview while keeping the map viewport locked before any sheet opens');
assert.match(moduleSource,/openHotelMapSheet\(places,id,options=\{\}\)/,'Hotel preview taps and drags must use the same exact-snapshot adapter as Places');
for(const token of ['data-hotel-filter-toggle','data-hotel-filter="accessible"','data-hotel-pin-history','Preisfilter folgt mit Livepreisen'])assert.ok(moduleSource.includes(token),`Hotel contextual filter/history token missing: ${token}`);
assert.match(css,/\.luvia-accommodations-v2/);
assert.match(css,/\.hotel-offer-card/);
assert.doesNotMatch(css,/consume the restaurant design contract/i);
for(const token of ['Kontrollierte Browser-Abnahme','2027-06-12','2027-06-14','HBX-9','HBX-RATE-9','openStayOffer','accommodation-module.css','accommodation-module.js'])assert.ok(fixture.includes(token),`Visible Hotel owner fixture missing: ${token}`);
assert.ok(!fixture.includes('Tickets prüfen'));
console.log('M16.5 Block 1 bright Hotel consumer + exact owner handoff: PASS');
console.log('TT.MM.JJJJ, honest live-price copy, shared map, exact Place booking route and no ticket semantics: PASS');
