'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');

const read=file=>fs.readFileSync(file,'utf8');
const exists=file=>fs.existsSync(file);
const places=read('app/places/places-spatial-experience.js');
const placesCss=read('app/places/places-spatial-experience.css');
const sheet=read('app/journey/journey-suggestion-sheet.js');
const composer=read('app/journey/journey-day-composer.js');
const composerCss=read('app/journey/journey-day-composer.css');
const photoAttributions=read('assets/place-evidence/ATTRIBUTIONS.md');
const proposals=read('app/collaboration/journey-place-proposals.js');
const management=read('app/booking/booking-management-sheet.js');
const tripPlaceData=read('core/places/trip-place-data-service.js');
const timelineCore=read('core/places/timeline-core.js');
const shell=read('app/app-shell.js');
const ui=read('core/ui/ui-manager.js');
const index=read('index.html');
const worker=read('sw.js');
const kernel=read('intelligence/kernel/version.js');
const journeyFixture=read('tests/fixtures/m12-journey-day-composer-browser.html');
const activeBuild=kernel.match(/build:'([^']+)'/)?.[1];
assert.ok(activeBuild,'kernel build version must be declared');

for(const asset of [
  'app/booking/booking-management-sheet.js',
  'app/booking/booking-management-sheet.css',
  'app/journey/journey-offline-pack.js',
  'app/collaboration/journey-place-proposals.js'
]){
  assert.ok(exists(asset),`missing unified owner-flow asset: ${asset}`);
  assert.ok(index.includes(`${asset}?v=${activeBuild}`),`index misses ${asset}`);
  assert.ok(worker.includes(`'${asset}'`),`service worker misses ${asset}`);
}

assert.match(ui,/overlay\.classList\.add\('luvia-living-sheet-overlay'\)/);
assert.match(ui,/content\.classList\.add\('luvia-living-sheet'\)/);
assert.match(ui,/animation:luvia-living-sheet-enter \.62s cubic-bezier\(\.16,1,\.3,1\)/);
assert.match(ui,/html\.luvia-ui-open,body\.luvia-ui-open\{overflow:hidden/);
assert.match(ui,/@media\(prefers-reduced-motion:reduce\)/);

assert.doesNotMatch(places,/if\(focus\)openResultSheet\(\)/,'a Places search must keep the map visible until the user selects a pin');
assert.match(places,/fastPath:true,parallelFastQueries:false,fastQueryLimit:1,queryVariantLimit:1,providerTimeoutMs:6500/,'the visible Places search must make one bounded Geoapify-first provider request');
assert.doesNotMatch(places,/const shouldDeepen=raw\.length<INITIAL_VISIBLE_RESULTS/,'the map must not start a second deep discovery pass after the first Geoapify page');
assert.doesNotMatch(places,/shouldDeepen\?contract\.reads\.recommend\(\{\.\.\.request,fastPath:false/,'an insufficient fast result must not fan out extra Places queries');
assert.doesNotMatch(places,/enrichCards\(raw\.slice\(0,INITIAL_VISIBLE_RESULTS\)\),\s*contract\.reads\.recommend\(\{\.\.\.request,fastPath:false/,'a full fast page must not start an unconditional deep provider search');
assert.doesNotMatch(places,/saveCached\(\);\s*await loadSaved\(\);\s*render\(\)/,'the first provider result paint must never wait for saved-Place hydration');
assert.ok(places.indexOf('render();')<places.indexOf('loadSaved(lifecycleToken).then'),'cached Places must paint before lifecycle hydration during mount');
assert.match(places,/if\(selected\)hydrateMapPreview\(selected\)/,'the first Geoapify page hydrates the selected pin instead of a second discovery pass');
assert.match(places,/async function hydrateMapPreview\(place\)/,'selected pin media stays on-demand after the first result paint');
assert.match(places,/const place=findPlace\(marker\.providerPlaceId\);select\(marker\.providerPlaceId,false,false\);rememberViewed\(place\);\s*\}\)/,'the exact map pin must only select and preview its own Place');
assert.match(places,/return\{places:\[selected\],selectedId:providerId\(selected\)/,'one selected Place must never expand the complete result collection inside the sheet');
assert.match(places,/openSheet\(placesFromSnapshot\(place\),providerId\(place\),\{interactive:true,origin\}\)\?\.settle\?\.\(true\)/,'the compact selected-pin preview must morph into the shared result sheet only after an explicit second action using the exact Place snapshot presented at touch time');
assert.match(sheet,/function openResultsInteractive\(rawInput=\{\}\)/,'the shared sheet must expose a direct-manipulation presentation for map preview swipes');
assert.match(sheet,/interactiveOrigin/,'the interactive sheet must accept the exact compact-preview and map geometry');
assert.match(sheet,/--lvjs-sheet-left[\s\S]*--lvjs-sheet-bottom[\s\S]*--lvjs-sheet-width[\s\S]*--lvjs-sheet-height/,'the sheet must interpolate all four map-bound dimensions under the finger');
assert.match(places,/onViewportSearch:descriptor=>\{const active=activeSearchDefinition\(\);return viewportSearch/,'the primary Places map must discover the visible viewport after pan or zoom');
assert.match(places,/decoratePreferences/,'personal preference evaluation must decorate the complete viewport instead of selecting its contents');
assert.match(places,/place\?\.distanceReference==='device'/,'Places may only label or sort a distance as nearby when the current device is the explicit reference');
assert.match(places,/vom aktuellen Standort/,'device GPS distances must name their reference in the visible card');
assert.match(places,/const api=globalThis\.LuviaJourneySuggestions,opener=interactive\?api\?\.openResultsInteractive:api\?\.openResults/);
assert.match(places,/onSelectionChange:id=>select\(id,false,false\)/,'sheet swipes and selections must keep the selected marker synchronized without changing the locked map viewport');
assert.match(places,/data-places-plan=/);
assert.match(places,/await openResultSheet\(\[findPlace\(id\)\]\.filter\(Boolean\),id\)/,'a direct Place action must enter the same single-Place sheet as its map pin');
assert.match(places,/event\.preventDefault\(\);event\.stopPropagation\(\)/,'the direct Timeline action must not be swallowed by its surrounding result-card interaction');
assert.match(places,/Zur Timeline hinzufügen/);
assert.match(places,/Beste Bewertung/);
assert.match(places,/Kürzeste Entfernung/);
assert.match(places,/Persönliche Passung/);
assert.match(sheet,/Wischt seitlich/,'the unified result sheet must disclose its touch gesture');
assert.match(places,/function admissionFor\(place\)/,'every Place category must ask the Booking owner for its admission decision');
assert.match(places,/bookingContract\(\)\?\.reads\?\.resolveAdmission/,'Places must consume the public universal Booking owner contract');
assert.match(places,/return'Unterkunft'/,'Places cards must present provider-classified lodging as accommodation instead of inheriting a misleading active-category label');
assert.match(places,/state\.category==='nightlife'/,'nightlife bars must retain their current discovery context instead of being relabeled as ordinary dining');
assert.match(placesCss,/scrollbar-width: none !important/);
assert.match(read('app/journey/journey-day-composer.css'),/\.lvjs-choice-scheduler/,'each card must own its scheduling and primary-action surface');
assert.match(read('app/journey/journey-day-composer.css'),/\.lvjs-choice-schedule-fields label:first-child\{grid-column:1\/-1\}/,'the complete date must own a full card row on desktop and mobile');
assert.match(read('app/journey/journey-day-composer.css'),/overflow-y:hidden!important/,'the horizontal result rail may not create a detached vertical card scrollbar');
assert.match(read('app/journey/journey-day-composer.css'),/grid-template-rows:auto auto minmax\(0,1fr\) auto/,'mobile sheet tracks must no longer reserve a global white confirmation bar');

assert.match(sheet,/function openResults\(/,'the result sheet must mount synchronously so direct manipulation can start before its asynchronous enrichment');
assert.match(sheet,/sharedPreferenceContext\(input,\{fast:true\}\)/,'Places search results must paint from provider facts and the bounded local preference projection');
assert.match(sheet,/const photoReady=await Promise\.all\(rawInput\.places\.map\(place=>within\(enrich\(place\),350,place\)\)\)/,'the exact selected Place must receive a bounded provider-photo attempt before first paint');
assert.match(sheet,/rankForTravelers\(photoReady,input\.groupContext,input,\{useAI:false\}\)/,'AI explanation must not delay the first photo-ready Places result sheet');
assert.match(sheet,/LuviaPlacesResultEnrichment/,'full traveler and AI enrichment must repaint the already visible Places sheet in the background');
assert.match(sheet,/Ein Tipp wählt/);
assert.match(sheet,/data-lvjs-heading/,'the visible result count must be patched from the actual loaded choices');
assert.match(sheet,/actualCount=result\.choices\.length/,'the sheet may not claim a desired count that the provider did not return');
assert.match(sheet,/Alle Richtungen entdecken/,'a time-window shortlist must retain a path into the complete Places spectrum');
assert.match(sheet,/luvia:places-discovery-requested/,'the spectrum bridge must expose its complete category intent to the Places owner');
assert.match(sheet,/const selectedIds=new Set/);
assert.match(sheet,/scheduleFor\(chosen,plans,result\.input\)/);
assert.match(sheet,/transferBetween\(previous,place,input,'selection'\)/);
assert.match(sheet,/previousTimelineEntry\(start,input\)/,'the first selected Place must inherit its route trace from the previous confirmed Timeline entry');
assert.match(sheet,/previous-selected-place/,'distances between selected Places must explicitly name the previous selected Place as their reference');
assert.match(sheet,/previous-timeline-place/,'the first selected Place may explicitly reference the previous confirmed Timeline Place');
assert.match(sheet,/Von „\$\{origin\}“/,'every visible inter-Place distance must name the exact origin instead of an ambiguous distance');
assert.match(sheet,/distanceReference:place\.distanceReference==='device'\?'current-device-location':null/,'a device distance must remain explicitly distinguishable from the inter-Place route trace');
assert.match(sheet,/transferLabel:clean\(override\.transferLabel\)/,'the evidenced route trace must survive the Places-to-Timeline owner handoff');
assert.match(sheet,/function exactTimelineConflict\(/,'existing Timeline moments and route buffers must be checked before a new Place is confirmed');
assert.match(sheet,/openingStale/,'stale or contradictory provider opening facts must stay explicitly uncertain');
assert.match(sheet,/nearestAlternative\(place,choices=\[\],excluded=\[\]\)/);
assert.match(sheet,/alternativeHistory=new Map/,'nearby alternatives must retain a per-source history across background enrichment');
assert.match(sheet,/Alternative · \$\{esc\(alternativeCause\(place,alternative\)\)\}/,'an alternative action must state its evidenced reason instead of using a generic label');
assert.match(sheet,/history\.add\(id\)/,'repeated alternative actions must advance instead of returning the same Place forever');
assert.match(sheet,/function openingAt\(place,start,end\)/,'provider opening periods must be checked against each card-local plan');
assert.match(sheet,/openingConflict=opening\.known&&opening\.open===false/,'a provider-proven closed window must block Timeline confirmation');
assert.match(sheet,/Wetterreaktion:/,'real same-day weather must be able to warn an outdoor proposal');
assert.match(sheet,/travelerInsights/);
assert.match(sheet,/Für \$\{strongest\.isCurrent\?'dich':strongest\.name\}/,'the concise explanation must name the actual traveler without the old generic fit phrase');
assert.match(sheet,/function genericEvidenceReason\(value=''/,'generic provider/category boilerplate must be detected before it reaches a visible personal explanation');
assert.match(sheet,/Für \$\{current\.isCurrent\?'dich':current\.name\} noch nicht belegt/,'insufficient personal evidence must name the affected traveler instead of implying a positive fit');
assert.match(sheet,/group\?\.reliable===true/,'a group percentage must be suppressed until every traveler has a sufficiently evidenced personal basis');
assert.match(sheet,/minimumCoverage:45|coverage>=45/,'thin evidence may not produce a visible personal percentage');
assert.match(sheet,/KI formuliert nur die Kurzbegründung und verändert weder Fakten noch Prozentwerte/);
assert.match(sheet,/const foodPlace=\['food','cafe'\]\.includes\(visualCategory\(place\)\)/,'dietary evidence must only be requested from food and cafe candidates');
assert.match(sheet,/applicable&&preference\.test\(signals\)/,'non-food Places must not receive irrelevant vegetarian or vegan warnings');
assert.match(sheet,/admission\.action\.label/,'the Booking owner must provide the category-appropriate ticket or reservation action label');
assert.match(sheet,/hotel\|lodging\|hostel\|motel\|resort\|accommodation/,'the shared result sheet must recognize accommodation from provider types');
assert.match(sheet,/if\(visual==='accommodation'\)return'accommodation'/,'an accommodation must never fall through to the attraction owner type');
assert.match(sheet,/accommodation:'Unterkunft'/,'a hotel must be presented as an accommodation instead of a generic Place');
assert.match(sheet,/if\(\['nightlife','activities','wellness'\]\.includes\(visual\)\)return'activity'/,'nightlife and activities must keep an activity owner identity instead of being persisted as restaurants');
assert.match(sheet,/providerNativeTypes/,'visual category projection must use the complete provider taxonomy when a primary type is generic');
assert.match(sheet,/data-lvjs-booking="\$\{esc\(id\)\}"/,'only a selected card with an evidenced Booking route may expose its action');
assert.match(sheet,/await openBooking\(place,bookingButton,form/,'Booking must act on the exact card-local Place without creating a Timeline identity before submit');
assert.match(sheet,/data-lvjs-plan="\$\{esc\(id\)\}"/,'each card must bind its own explicit Timeline action for real pointer and touch input');
assert.match(sheet,/function imageAttribution\(place\)/,'verified fixture or provider photo attribution must be carried as structured evidence');
assert.match(sheet,/lvjs-photo-credit/,'the visible suggestion card must disclose photographer and license');
assert.match(sheet,/imageAttribution:imageAttribution\(place\)/,'photo attribution must survive the Places-to-Timeline owner handoff');
assert.match(composer,/lvjt-photo/,'the Timeline must render its Place photo and source as one semantic unit');
assert.match(composer,/photoCredit/,'the Timeline must disclose the persisted photo author and license');
assert.match(photoAttributions,/Café de Flore, Paris[\s\S]*Public domain/,'the Café de Flore evidence asset must name its place, author, license and source');
assert.match(photoAttributions,/Jardin du Luxembourg, Paris[\s\S]*CC BY-SA 3\.0/,'the Jardin photo must have a reproducible license record');
assert.match(photoAttributions,/Musée de la Vie romantique, Paris[\s\S]*CC BY-SA 4\.0/,'the museum photo must have a reproducible license record');
assert.equal(exists('assets/place-evidence/cafe-de-flore-arnaud25.jpg'),true,'the exact Café de Flore photograph must be local and immutable');
assert.equal(exists('assets/place-evidence/jardin-du-luxembourg-aconcagua.jpg'),true,'the exact Jardin du Luxembourg photograph must be local and immutable');
assert.equal(exists('assets/place-evidence/musee-vie-romantique-discoa340.jpg'),true,'the exact museum photograph must be local and immutable');
assert.match(sheet,/<form class="lvjs-choice-scheduler"/,'the card-local Booking adapter must pass a real HTMLFormElement to the unchanged Booking Core');
assert.match(sheet,/const handleState=new WeakMap\(\)/,'ephemeral sheet state must not be written onto the frozen Overlay Host handle');
assert.match(sheet,/const handleControllers=new WeakMap\(\)/,'repaint-safe event controllers must live outside the frozen Overlay Host handle');
assert.match(sheet,/results\.addEventListener\('click'/,'real pointer and touch selection must use an attached delegated click listener');
assert.doesNotMatch(sheet,/handle\._lvjs/,'the frozen Overlay Host handle must never receive ad-hoc mutable properties');
assert.match(sheet,/commands\.importPlace/);
assert.match(sheet,/commands\.plan/);
assert.match(tripPlaceData,/_local_projection:'pending'/,'the canonical Place owner must stage an immediate local projection before cloud reconciliation');
assert.match(timelineCore,/function projectPlaceData\(source=/,'the Timeline owner must consume the staged canonical Place projection');
assert.match(timelineCore,/function ownerCoordinates\(place=/,'the Timeline boundary must recover canonical coordinates from the owning Places row');
assert.match(timelineCore,/enrichOwnerPlace\(scheduleEntry\(row\),state\.places\[row\.place_id\]/,'legacy Schedule and Booking projections must retain their linked Place coordinates');
assert.match(timelineCore,/providerFacts:\{\.\.\.providerFacts,coordinates:/,'provider-coordinate evidence must remain available to Journey consumers');
assert.match(shell,/addEventListener\('luvia:timeline-changed',refreshTimelineProjection\)/,'the visible App Shell must repaint the active Timeline from the owner projection');
assert.match(shell,/surface\.replaceWith\(nextSurface\)/,'owner updates must project inside the active Timeline surface instead of reloading the complete App Shell route');
assert.match(shell,/if\(nextHtml===timelineLastHtml\)return/,'duplicate owner events must not repaint an unchanged Timeline');
assert.doesNotMatch(sheet,/await journey\?\.commands\?\.hydrate\?\.\(tid\)/,'the card-local plan must not block visible feedback on a full Journey rehydrate');

assert.match(proposals,/LuviaCollaboration/,'group decisions must reuse the existing collaboration owner');
assert.match(proposals,/groupFit:clone\(place\?\.groupFit\|\|null\)/,'the evidenced deterministic group fit must survive the vote handoff');
assert.match(proposals,/aiScoreUsed:false/);
assert.doesNotMatch(proposals,/aiMatchScore:Number\.isFinite/,'AI ranking percentages must never become collaboration truth');
assert.match(proposals,/trip_activity_events/,'proposal truth must remain event-sourced in the existing trip activity stream');
assert.match(proposals,/hours:24/);
assert.match(proposals,/hours:12/);
assert.match(proposals,/hours:1/);
assert.match(proposals,/mode:'owner_decides'/);
assert.match(proposals,/luvia_list_trip_members/,'the collaboration coordinator may read the existing member projection');
assert.doesNotMatch(proposals,/\.from\(/,'the proposal coordinator must not create a private table or direct persistence boundary');
assert.equal(exists('supabase/migrations/20260829090000_journey_place_proposals.sql'),false,'Integration may not mutate the shared Production schema for this UI flow');

assert.match(composer,/LuviaBookingManagementSheet\.open/);
assert.match(composer,/lvjt-proposal-entry/,'group decisions must live at their proposed time inside the Timeline flow');
assert.match(composer,/data-proposal-vote="yes"/);
assert.match(sheet,/source:'journey-proposal-local-projection'/,'a newly created group decision must repaint the active Timeline immediately instead of waiting for realtime hydration');
assert.match(composer,/data-visit-confirm/,'GPS moments remain pending until explicit confirmation');
assert.match(composer,/lvjt-transfer-trace/,'the Timeline must expose the thin, explicitly referenced route trace between confirmed Places');
assert.match(composer,/function derivedTransfer\(previous,current\)/,'older owner entries with two real coordinates must gain an explicit A-to-B trace without inventing GPS evidence');
assert.match(composer,/Weg noch nicht berechenbar · verlässliche Ortskoordinaten fehlen/,'a location-bound pair with missing owner coordinates must expose the missing evidence instead of silently dropping the route');
assert.match(composer,/function isLocationBound\(entry=/,'pure notes and memories must remain distinct from location-bound route entries');
assert.match(composer,/Places-Koordinaten beider Orte/,'a derived transfer must disclose its actual coordinate source');
assert.match(composer,/function transferMarkup\(/,'A-to-B evidence must expose its distance as a dedicated visible value');
assert.match(composerCss,/\.lvjt-entry-card\{grid-column:3/,'the transfer evidence must never displace the following Timeline card into the time column');
assert.match(composerCss,/\.lvjt-transfer-trace\{grid-column:3/,'the route trace and the Place card must share the actual content column');
assert.match(composer,/lvjt-plan-trust/,'confirmed, waiting, voting, suggested and offline states must remain visible per Timeline entry');
assert.match(composer,/function planningTraceMarkup\(entry=/,'the persisted explainable Planning Trace must have a compact user-visible projection');
assert.match(composer,/Wie kam dieser Eintrag zustande\?/,'the Planning Trace must be expressed in human language instead of hidden metadata');
assert.match(composer,/Rohkontext und exakte Geräteposition werden nicht gespeichert/,'the visible trace must disclose its privacy boundary');
assert.match(composerCss,/\.lvjt-place-trace/,'the Planning Trace must stay inside the canonical light Journey sheet');
assert.match(composer,/function showUndo\(/,'add, move and delete flows must retain a short recoverable undo window');
assert.match(journeyFixture,/fixtureEntryStoreKey/,'visible Journey E2E must use a reload-capable fake owner instead of losing mutations on navigation');
assert.ok(
  journeyFixture.indexOf('../../core/intelligence/travel-orchestration-core.js')>-1
  && journeyFixture.indexOf('../../core/intelligence/travel-orchestration-core.js')<journeyFixture.indexOf('../../app/journey/journey-suggestion-sheet.js'),
  'visible Journey E2E must load the explainable orchestration owner before a suggestion can persist its Planning Trace'
);
assert.match(journeyFixture,/persistFixtureEntries\(\);return\{ok:true,action:'plan'/,'visible Journey E2E must persist a planned Place before it reports success');
assert.match(journeyFixture,/target\.startAt=next\.toISOString\(\);persistFixtureEntries\(\)/,'visible Journey E2E must persist a moved Timeline entry before repaint');
assert.match(journeyFixture,/source\.entries\.splice\(index,1\);persistFixtureEntries\(\)/,'visible Journey E2E must persist deletion and the subsequent undo restoration through the owner');
assert.match(journeyFixture,/title:'Jardin du Luxembourg besucht'.*persistFixtureEntries\(\)/,'a confirmed GPS moment must survive reload in the visible fake owner');
assert.match(journeyFixture,/fixtureWeatherMode==='rain'/,'the visible Journey fixture must expose a reproducible dated rain-evidence state');
assert.match(journeyFixture,/fixtureOpeningMode==='stale'/,'the visible Journey fixture must expose stale provider-opening evidence without asserting safety');
assert.match(journeyFixture,/mode==='closed'.*hour:12/s,'the visible Journey fixture must expose a provider-proven closed planning window');
assert.match(journeyFixture,/balance\)===?'food'|get\('balance'\)==='food'/,'the visible Journey fixture must expose exactly one reproducible day-balance correction state');
assert.match(journeyFixture,/routeBufferMinutes:fixtureTravelSpeed==='calm'\?15/,'the visible Journey fixture must prove that travel pace changes the real arrival buffer');
assert.match(management,/commands\.modifyBooking/);
assert.match(management,/commands\.cancelBooking/);
assert.match(management,/contract\.reads\.get/);
assert.match(management,/Änderung wurde beim Anbieter angefragt/);
assert.match(journeyFixture,/bookingManaged/);
assert.match(journeyFixture,/modifyBooking:async/);
assert.match(journeyFixture,/cancelBooking:async/);
assert.match(journeyFixture,/reply:async/);
assert.match(management,/commands\.reply/);
assert.match(management,/kind:'sheet'/);

console.log('M16.5AB Unified Places → Journey Living Sheet: PASS');
