'use strict';

const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');

const ROOT=path.resolve(__dirname,'..');
const read=relative=>fs.readFileSync(path.join(ROOT,relative),'utf8').replace(/\r\n?/g,'\n');
const index=read('index.html');
const version=read('intelligence/kernel/version.js');
const worker=read('sw.js');
const pwa=read('intelligence/pwa-service.js');
const shell=read('app/app-shell.js');
const hubs=read('app/module-hubs.js');
const hubCss=read('app/module-hubs.css');
const places=read('app/places/places-spatial-experience.js');
const placesCss=read('app/places/places-spatial-experience.css');
const runner=read('tests/run-m4.3-safe-regression.cjs');
const ownership=read('docs/modularization/FILE-OWNERSHIP.csv');
const pcr=read('docs/modularization/PCR-M16.5Q-LIVING-COMPASS-INTEGRATION-RECOVERY.md');

assert.match(version,/core:'4\.82\.129'/);
assert.match(version,/build:'13\.82\.129'/);
assert.match(version,/name:'M16\.5 Block 1 Consumer Truth Repair'/);
assert.match(version,/channel:'integration-preview'/);
assert.match(worker,/const CACHE='luvia-shell-v13\.82\.129'/);
assert.match(worker,/const BUILD='13\.82\.129'/);
assert.equal(index.includes('?v=13.82.61'),false,'active entry retains the handset-revoked cache key');
assert.equal(index.includes('?v=13.82.62'),false,'active entry retains the superseded moment-routing/needle cache key');
assert.equal(index.includes('?v=13.82.63'),false,'active entry retains the publicly superseded route-host click-replay cache key');
for(const asset of ['intelligence/kernel/version.js','intelligence/pwa-service.js','app/app-shell.js','app/module-hubs.js','app/module-hubs.css','app/places/places-spatial-experience.js','app/places/places-spatial-experience.css'])assert.ok(index.includes(`${asset}?v=13.82.129`),`M16.5Q cache key missing for ${asset}`);
const earlyPwaScript='intelligence/pwa-service.js?v=13.82.129';
assert.equal(index.split(earlyPwaScript).length-1,1,'the PWA recovery runtime must be loaded exactly once');
assert.ok(index.indexOf(earlyPwaScript)<index.indexOf('<link rel="stylesheet"'),'stale-controller recovery must begin before any blocking stylesheet');

assert.match(pwa,/const BUILD=SCRIPT_URL\.searchParams\.get\('v'\)[^\n]*globalThis\.LuviaKernelVersion/,'PWA cache identity must derive from the active release script and kernel fallback');
assert.match(pwa,/const SW_SCRIPT_URL=new URL\('sw\.js',APP_ROOT_URL\);[\s\S]*SW_SCRIPT_URL\.searchParams\.set\('v',BUILD\)/,'the expected worker script URL must carry the exact document build');
assert.match(pwa,/const EXPECTED_CACHE=BUILD\?[^;]+:null/,'PWA cache identity must match the active release');
assert.match(pwa,/const expectedWorker=worker=>Boolean\(BUILD&&worker&&workerBuild\(worker\)===BUILD\)/,'waiting-worker activation must be pinned to the exact expected build');
assert.doesNotMatch(pwa,/luvia-shell-v13\.17\.0/,'stale fixed cache identity must be removed');
const registerScope=pwa.slice(pwa.indexOf('async function register'),pwa.indexOf('function activateWaiting'));
assert.doesNotMatch(registerScope,/activateWaiting|clearOldCaches/,'registration must not activate a waiting worker or delete the controlling worker cache');
assert.match(pwa,/beforeinstallprompt',event=>\{event\.preventDefault\(\);deferredPrompt=event/,'install prompt must be retained');
assert.match(pwa,/controlledAtLoad&&!controllerReloadGuard[\s\S]*location\.reload\(\)/,'new active workers must reload an already controlled page exactly once');
assert.match(pwa,/async function recoverControlledUpgrade\(\)[\s\S]*workerContainer\?\.controller[\s\S]*expectedWorker\(workerContainer\.controller\)[\s\S]*await register\(\)[\s\S]*activateExpectedWaitingSoon\(registration,\{preserveDocument:false\}\)/,'a stale controlling worker must be recoverable into one coherent runtime before page load completes');
assert.match(pwa,/async function activateExpectedWaitingSoon\(reg,[\s\S]*timeoutMs=12000[\s\S]*setTimeout\(resolve,80\)[\s\S]*Date\.now\(\)<deadline/,'waiting-worker publication races must be polled within a strict bound');
assert.match(pwa,/await activateExpectedWaitingSoon\(registration,\{preserveDocument:false\}\)/,'controlled recovery must activate the exact worker and reload instead of preserving a mixed-build document');
assert.match(pwa,/const watch=worker=>[\s\S]*worker\.addEventListener\('statechange'[\s\S]*watch\(reg\.installing\)/,'recovery must observe an update that was already installing before the PWA runtime bound its listeners');
assert.match(pwa,/worker\.state==='installed'\)\{inspect\(\);setTimeout\(inspect,0\)\}/,'waiting-worker inspection must run after the browser publishes the installed worker on the registration');
assert.match(pwa,/workerContainer\?\.controller&&!expectedWorker\(workerContainer\.controller\)\)queueMicrotask\(\(\)=>recoverControlledUpgrade\(\)\)/,'controlled stale clients must start bounded recovery from the early PWA runtime');
assert.match(pwa,/if\(preserveCurrentBuildDocument\)\{preserveCurrentBuildDocument=false;[\s\S]*emit\(\);return\}/,'the already current build document must survive its automatic controller handoff without a second full reload');
assert.match(pwa,/function scheduleRecoveredCacheCleanup\(\)[\s\S]*setTimeout\(clear,800\);setTimeout\(clear,3200\)/,'post-handoff cleanup must remove a stale cache recreated by late old-worker writes');
assert.match(pwa,/preserveCurrentBuildDocument=false;scheduleRecoveredCacheCleanup\(\);emit\(\);return/,'the preserved document handoff must schedule its post-load cache cleanup');
assert.match(pwa,/const readReloadGuard=\(\)=>\{try\{return sessionStorage\.getItem[\s\S]*catch\{return false\}\}/,'blocked session storage must not abort early stale-controller recovery');
assert.doesNotMatch(pwa,/if\(registration\.waiting\)activateWaiting\(registration\)/,'update checks must never activate an unqualified stale waiting worker');
assert.match(pwa,/async function warmShell\(\)[\s\S]*postMessage\(\{type:'WARM_APP_SHELL'\}\)/,'the document must explicitly request full-shell warming after the visible load');
assert.match(shell,/function schedulePwaRegistration\(\)/,'Service Worker registration must have an explicit post-load scheduler');
assert.match(shell,/if\(document\.readyState==='complete'\)afterLoad\(\)[\s\S]*window\.addEventListener\('load',afterLoad,\{once:true\}\)/,'Service Worker registration must not compete with the initial document load');
assert.match(shell,/requestIdleCallback\(start,\{timeout:1600\}\)/,'post-load registration must yield to the first visible render');
assert.match(shell,/register\?\.\(\)\)\.then\(\(\)=>window\.LuviaPWA\?\.warmShell\?\.\(\)\)/,'the full shell must warm only after deferred registration has settled');
assert.doesNotMatch(shell,/window\.LuviaPWA\?\.register\?\.\(\)\.catch\(e=>/,'bootstrap must not directly start a worker update');
const installScope=worker.slice(worker.indexOf("self.addEventListener('install'"),worker.indexOf("self.addEventListener('activate'"));
assert.doesNotMatch(installScope,/skipWaiting/,'a deployed worker must wait instead of taking over a live tab');
assert.match(worker,/const PRECACHE_CONCURRENCY=4/,'upgrade precaching must have a strict concurrency ceiling');
assert.match(worker,/const shellCache=\(\)=>shellCachePromise\|\|\(shellCachePromise=caches\.open\(CACHE\)\)/,'parallel fetch handlers must reuse one opened shell cache');
assert.match(worker,/const CRITICAL_SHELL=APP_SHELL\.filter\(url=>url===SCOPE\|\|CRITICAL_SHELL_PATTERN\.test\(new URL\(url\)\.pathname\)\)/,'upgrade installation must derive a deliberately small critical subset without duplicating shell assets');
const criticalPatternScope=worker.slice(worker.indexOf('const CRITICAL_SHELL_PATTERN'),worker.indexOf('const CRITICAL_SHELL=',worker.indexOf('const CRITICAL_SHELL_PATTERN')));
assert.match(criticalPatternScope,/pwa-service\|kernel\\\/version/,'the tiny install set must retain the recovery and build-identity runtimes');
assert.doesNotMatch(criticalPatternScope,/app-shell|public-landing|luvia-compass/,'large visible surfaces must warm after load instead of blocking worker activation');
assert.match(worker,/Promise\.all\(Array\.from\(\{length:Math\.min\(PRECACHE_CONCURRENCY,urls\.length\)\},fetchNext\)\)/,'upgrade precaching must use the bounded worker pool for the requested asset set');
assert.match(installScope,/precacheShell\(cache,CRITICAL_SHELL\)/,'worker installation must wait only for the critical visible shell');
assert.doesNotMatch(installScope,/precacheShell\(cache,APP_SHELL\)/,'worker installation must never wait for the entire application shell');
assert.match(worker,/event\.data\?\.type==='WARM_APP_SHELL'\)event\.waitUntil\(warmAppShell\(\)\)/,'the complete app shell must warm only on an explicit post-load request');
assert.doesNotMatch(worker,/Promise\.allSettled\(APP_SHELL\.map/,'a service-worker upgrade must not flood the network with the entire shell at once');
assert.match(worker,/event\.data\?\.type==='SKIP_WAITING'/,'explicit controlled activation must remain available');
assert.match(worker,/\(\?:m\?js\|css\|json\|webmanifest\|svg\|png\|webp\|ico\|html\)/,'module loaders, static, brand and photographic assets must remain inside the recovery policy');
assert.match(worker,/activeCache\.match\(request,\{ignoreSearch:true\}\)/,'runtime fetches must read only the current shell cache');
assert.match(worker,/const currentBuildAsset=url=>\{[\s\S]*token===BUILD\|\|token\.startsWith\(`\$\{BUILD\}-`\)[\s\S]*\}/,'only assets explicitly pinned to the active build or its split revision may use immutable cache-first delivery');
assert.match(worker,/if\(cached&&currentBuildAsset\(url\)\)return cached/,'repeat loads must not redownload hundreds of exact-build assets');

for(const context of ['today','plan','trip','memories','profile'])assert.match(hubs,new RegExp(`${context}:Object\\.freeze`),`Compass context missing: ${context}`);
assert.match(shell,/openLivingCompassContext\(context\)/,'top-level navigation must switch embedded Compass context');
assert.match(shell,/flightHost=root\?\.querySelector\('\.lv-living-shell'\)\|\|root[\s\S]*flightHost\.appendChild\(flight\)/,'shared-element flight must survive stage replacement inside the persistent shell');
assert.doesNotMatch(shell,/document\.body\.appendChild\(flight\)/,'shared-element flight must not create a private body overlay');
assert.match(shell,/pendingCompassContext/,'rapid context input must be queued');
assert.match(shell,/pendingCompassExit/,'rapid close or selection input must be queued');
assert.match(shell,/compassIntentSequence=0/,'Compass and route commands must share a monotonic user-intent sequence');
assert.match(shell,/if\(planCompassTransition\)\{pendingCompassExit=\{destination:action,selected:button,intentSequence\}/,'touch selection during a context transition must be replayed instead of dropped');
assert.match(shell,/activeView=view;const sequence=\+\+showSequence;commitScreenIntent\(intent,options\);await unmountCurrent/,'the requested browser-history route must be committed before asynchronous module deactivation');
assert.match(shell,/data-view="\$\{item\.id\}" data-compass-context="\$\{item\.id\}"/,'desktop and mobile primary navigation must expose direct Compass context intent');
assert.match(shell,/const compassNavigation=e\.target\.closest\('button\[data-compass-context\]'\)[\s\S]*openLivingCompassContext\(compassNavigation\.dataset\.compassContext\|\|'plan'\)/,'direct context navigation must enter the accepted Compass without a prior Plan detour');
assert.match(shell,/closest\('button\[data-view\],a\[data-view\],\[role="button"\]\[data-view\]'\)/,'delegated route navigation must be owned by an interactive data-view control');
assert.doesNotMatch(shell,/closest\('\[data-view\]'\)/,'a click inside a route host must never be reinterpreted as navigation back to that host route');
assert.match(shell,/currentPlanCompassStage=\(\)=>root\?\.querySelector\('\[data-stage\] > \.lv-view-host:not\(\.lv-route-previous\) \[data-plan-compass-stage\]'\)/,'Compass commands must never bind to a stale outgoing stage');
assert.match(shell,/queuedContext&&queuedContext\.intentSequence===compassIntentSequence/,'only the latest queued context may replay after destination routing');
assert.match(shell,/superseded=intentSequence!==compassIntentSequence/,'an older delayed Compass action must stop before executing over a newer intent');
assert.match(shell,/compassSelectionDuration=\(\)=>compassMotionReduced\(\)\?0:760/,'the selected needle must retain a bounded mobile-visible motion duration');
assert.match(shell,/renderedCompassNeedleAngle\(needle\)/,'selection must inherit the currently rendered idle needle angle before idle motion is disabled');
assert.match(shell,/needle\.animate\(\[\{transform:`rotate\(\$\{from\}deg\)`\},\{transform:`rotate\(\$\{end\}deg\)`\}\],\{duration,easing:'cubic-bezier\(\.16,\.84,\.18,1\)'/,'selection must interpolate directly and smoothly from the visible angle to the shortest target');
assert.match(shell,/playCompassSelectionNeedle\(stage,directAngle\)/,'direction routing must run the owned selection-needle motion');
assert.doesNotMatch(shell,/compassWait\(compassMotionReduced\(\)\?0:720\)/,'direction routing must not restore the superseded decorative selection delay');
assert.match(shell,/function cancelCompassFlights\(\)[\s\S]*animation\.cancel\(\)/,'in-flight Compass animations must be cancellable');
assert.match(shell,/Promise\.race\(\[animation\.finished\.catch\(\(\)=>null\),compassWait\(duration\+180\)\]\)/,'decorative Compass flights must have a bounded lifetime');
assert.doesNotMatch(shell,/await returnPlanCompassHome\(stage\)/,'decorative return flight must never gate destination routing');
assert.match(shell,/normalizeCompassAngle=angle=>\(\(Number\(angle\|\|0\)\+180\)%360\+360\)%360-180/,'the needle angle normalizer must retain the direct signed range');
assert.match(shell,/directAngle=normalizeCompassAngle\(angle\)/,'the needle must take the direct signed angle to the selected direction');
assert.match(shell,/inheritedSelectionAngle=getComputedStyle\(source\)\.getPropertyValue\('--lv-plan-selection-angle'\)/,'the return flight must preserve the directly selected needle angle');
assert.doesNotMatch(shell,/1080\+angle/,'direction selection must not force three decorative needle rotations');
assert.match(shell,/function rememberCompassPointer\(event\)[\s\S]*setPointerCapture/,'a visible direction must own the physical pointer gesture from press through release');
assert.match(shell,/function releaseCompassPointer\(event\)[\s\S]*choosePlanCompassDirection\(direction\)/,'the latched physical gesture must execute its exact direction even if the animated target moves');
assert.match(shell,/tolerance=gesture\?\.pointerType==='touch'\?32:20/,'real touch input must retain a bounded finger-drift tolerance distinct from the mouse threshold');
assert.match(shell,/suppressedCompassClick=\{pointerType:gesture\.pointerType,until:performance\.now\(\)\+900\}/,'the delayed touch compatibility click must be suppressed across the route handoff');
assert.match(shell,/function rememberCompassPointer\(event\)\{\s*suppressedCompassClick=null/,'a new real pointer gesture must release the prior compatibility-click guard');
assert.match(shell,/navigationTask=Promise\.resolve\(handleHubAction\(destination,meta\)\)[\s\S]*planCompassTransition=false/,'the visual exit lock must be released before an asynchronous destination mount settles');
assert.match(shell,/function excludeRouteHost\(host,excluded=true\)[\s\S]*document\.activeElement\?\.blur\?\.\(\)[\s\S]*host\.inert=excluded/,'an outgoing route must release focus before it becomes inert and aria-hidden');
assert.match(shell,/excludeRouteHost\(previousHost,false\)/,'a superseded route transition must restore the previous host accessibility state');
assert.match(shell,/function settleRouteTransition\(stage\)[\s\S]*hosts\.forEach\(host=>host\.remove\(\)\)/,'rapid Back or route input must remove stale transition hosts');
assert.match(shell,/if\(e\.key==='Escape'\)/,'Escape must close to Today');
assert.match(shell,/ArrowLeft.*ArrowRight.*ArrowUp.*ArrowDown/,'Compass must expose arrow-key navigation');
assert.match(shell,/openCompass:\(context='plan'\)=>openLivingCompassContext\(context\)/,'Places and other destinations must be able to restore the embedded Compass');
assert.match(shell,/lv-living-top-profile[^`]*data-compass-context="profile"/,'the header profile avatar must open the Profile Compass');
assert.match(shell,/lv-living-profile[^`]*data-compass-context="profile"/,'the lower profile card must open the Profile Compass');
const contextScope=shell.slice(shell.indexOf('async function openLivingCompassContext'),shell.indexOf('async function leavePlanCompass'));
assert.match(contextScope,/playCompassContextNeedle/,'context switches must use the bounded playful needle motion');
assert.match(contextScope,/compassContextExitDuration[\s\S]*compassContextEntryDuration/,'old points must leave before the new constellation enters');
assert.doesNotMatch(contextScope,/classList\.remove\('is-plan-compass-detached'\)/,'the top-left source Compass must remain hidden during an open context switch');
assert.doesNotMatch(hubCss,/lv-plan-direction-float/,'Compass direction hit geometry must not float or collapse');
assert.doesNotMatch(hubCss,/--lv-plan-direction-scale|\.lv-plan-direction:hover\{[^}]*scale|\.lv-plan-direction\{[^}]*transition:[^}]*transform/,'hover and selection must never resize or translate a direction hit target');
assert.match(hubCss,/not\(\.is-ready\) \.lv-plan-compass-core\{opacity:0/,'the target Compass carrier must remain invisible before the shared element arrives');
assert.match(hubCss,/is-compass-arriving:not\(\.is-ready\) \.lv-plan-compass-core\{opacity:1[\s\S]*is-compass-arriving:not\(\.is-ready\) \.lv-plan-compass-mark\{transform:none/,'carrier and target Compass must materialize through one coupled parent in the same final handoff phase');
assert.match(hubCss,/@keyframes lv-plan-direction-pop-in[\s\S]*@keyframes lv-plan-direction-pop-out/,'direction constellations require the playful upward entry and matching reverse exit');
assert.match(hubCss,/@keyframes lv-plan-direction-idle-drift[\s\S]*@keyframes lv-plan-needle-idle/,'settled points and the unselected needle require subtle independent idle motion');
assert.match(hubCss,/\.is-context-seeking[^\n]*\.lv-plan-direction-idle\{animation-play-state:paused\}/,'idle drift must pause while a context or destination transition owns the motion');
assert.match(hubCss,/\.lv-plan-direction:hover \.lv-plan-direction-surface[^\n]*\{transform:/,'hover motion must stay inside the immutable physical hit target');
assert.match(hubCss,/\.lv-plan-direction\{[^}]*touch-action:none/,'the non-scrolling Compass stage must retain the real touch pointer instead of ceding it to viewport panning');
assert.match(hubCss,/\.is-returning \.lv-plan-compass-core\{opacity:0/,'the white carrier must leave with the returning Compass');
assert.match(hubCss,/\.lv-plan-compass-flight \.lv-living-compass__needle,[^}]*animation:none/,'the flight needle must never inherit a searching or looping animation');
assert.doesNotMatch(hubCss,/@keyframes lv-plan-context-seek/,'context changes must not spin the needle through decorative revolutions');
assert.match(hubs,/feature\('Live-Momente','Foto, Ton oder Notiz','camera','capture','foundation'\)/,'Trip Live-Momente must retain the accepted Media to Memory capture intent');
assert.match(hubs,/feature\('Moment bewahren','Foto, Ton, Video, Notiz','spark','capture','foundation'\)/,'Memories Moment bewahren must retain the accepted Media to Memory capture intent');
assert.match(hubs,/feature\('Mediathek','Fotos, Videos, Upload Queue','camera','gallery'\)/,'only Mediathek may open the existing gallery destination');
assert.match(shell,/capture:\['Diesen Moment bewusst bewahren\.'/,'capture intent must render its own accepted focus instead of substituting the gallery');
assert.match(shell,/data-compass-focus="\$\{esc\(action\)\}" data-compass-focus-context="\$\{esc\(context\)\}"/,'the capture focus must preserve both semantic action and originating Compass context');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/stalled decorative Compass flight must never gate destination routing/,'real browser coverage must include a deliberately stalled flight');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/outgoing route host must never retain focused descendants while aria-hidden/,'real browser coverage must lock the focus/aria-hidden transition contract');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/direct Today\/Plan\/Trip\/Memories\/Profile context entry/,'real browser coverage must enter every context directly from primary navigation');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/1920x1020 physical pointer routing through all eight Plan directions/,'real browser coverage must reproduce full-size physical pointer routing');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/slow Places mount \/ newer navigation intent ordering/,'real browser coverage must prove that a delayed Places activation cannot overwrite a newer route');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/slow Places mount \/ first Browser Back ordering/,'real browser coverage must prove that the first Back gesture wins during a delayed Places activation');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/productive Places Compass control must restore a fully interactive Plan constellation/,'real browser coverage must click the productive Places-owned Compass return control');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/visible pre-ready press \/ moving target pointer ownership/,'real browser coverage must press a direction before settlement and move it before release');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/reference-timed carrier\/mark handoff, radial pop, coral selection, direct selection needle and coupled reverse exit/,'real browser coverage must lock the accepted reference motion and selection feedback');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/Input\.dispatchTouchEvent/,'real browser coverage must use the browser touch-input path instead of only perfect synthetic taps');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/physical mobile touch drift through Places \/ Booking \/ Live-Momente/,'real browser coverage must retain all three user-reported destinations under finger drift');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/Moment bewahren \/ Mediathek/,'real browser coverage must distinguish capture actions from the gallery on touch');
assert.match(read('tests/m16.5q-living-compass-recovery-e2e.cjs'),/mobile selection needle continuity \/ direct path \/ smooth frame progression/,'real browser coverage must measure the mobile needle path rather than only its final angle');

assert.match(places,/renderToken===state\.renderToken&&container\.isConnected&&state\.map===map/,'late map callbacks must not mutate a replacement surface');
assert.match(places,/state\.map\.easeTo\(\{center:coordinates\.lngLat/,'result selection must move the map using the public coordinate tuple');
assert.match(places,/select\(marker\.providerPlaceId,true,false\)/,'marker selection must move the result list without redundant map motion');
assert.match(places,/LuviaApp\?\.openCompass\?\.\('plan'\)/,'Places back action must restore Plan Compass');
assert.match(places,/data-places-map-fallback/,'honest map fallback markup is required');
assert.match(placesCss,/\.lv-places-spatial__map-fallback/,'honest bright map fallback styling is required');

for(const file of ['tests/fixtures/m16.5q-living-compass-recovery-browser.html','tests/m16.5q-living-compass-recovery-e2e.cjs','tests/m16.5q-pwa-cache-recovery-e2e.cjs','tests/m16.5q-living-compass-recovery-release.test.cjs','docs/modularization/PCR-M16.5Q-LIVING-COMPASS-INTEGRATION-RECOVERY.md'])assert.ok(ownership.includes(file),`ownership registry missing ${file}`);
assert.match(runner,/tests\/m16\.5q-living-compass-recovery-release\.test\.cjs/);
assert.match(pcr,/earlier claim that the public M16\.5P Integration build had received\s+functional acceptance is revoked/i);
assert.match(pcr,/18 CSS pixels[\s\S]*pointercancel/i,'the physical-handset root cause and measured reproduction must remain explicit');
assert.match(pcr,/Automation is not presented as handset acceptance[\s\S]*real user-run[\s\S]*closes that gate for App 13\.82\.64/i,'physical-handset acceptance must be attributed to the explicit user-run retest, never to automation');
assert.match(pcr,/The physical-handset gate for App 13\.82\.64 is closed[\s\S]*user independently[\s\S]*confirmed the previously failing flow works/i,'the user-confirmed stable-origin handset closeout must remain explicit');
assert.match(pcr,/Main remained exactly at\s+`c4b6d1740ad04c291d5e27d8d18b3a32e5ed87ba`/);
assert.match(pcr,/Production remained exactly on deployment\s+`578f13fc-8193-4988-88cf-93c94362fcc3`/);

console.log('M16.5Q Living Compass Integration Recovery Release: PASS');
console.log('App / Core / shell cache: 13.82.129 / 4.82.129 / luvia-shell-v13.82.129');
console.log('Compass contexts, physical touch routing, cleanup, Places map and PWA cache recovery: LOCKED');
console.log('Main / Production release lock: ACTIVE');
