'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const read=file=>fs.readFileSync(file,'utf8');
const registry=JSON.parse(read('config/luvia-human-ai-action-registry.v1.json'));
const context={console,globalThis:null};context.globalThis=context;
context.LuviaIntelligenceDomainContractCoreV1={immutable:value=>value,listCapabilities:()=>[],getCapability:()=>null,listDomains:()=>[],listTools:()=>[],listModelTiers:()=>[],policySnapshot:()=>({}),sanitize:value=>value};
context.LuviaAI={diagnostics:()=>({version:'test'}),run:async()=>({}),ask:async()=>({}),rank:async()=>({}),recommend:async()=>({}),explain:async()=>({}),summarize:async()=>({})};
vm.createContext(context);
for(const file of ['core/intelligence/human-ai-language-compiler-core.js','core/intelligence/human-ai-safety-policy-core.js','core/intelligence/human-ai-action-lifecycle-core.js','core/intelligence/human-ai-capability-discovery-core.js','core/intelligence/human-ai-consumer-projection-core.js','core/platform/intelligence-contract-adapter.js'])vm.runInContext(read(file),context,{filename:file});
const api=context.LuviaIntelligenceContractV1;
assert.equal(api.runtimeVersion,'1.11.0');
for(const method of ['projectHumanActionConsumer','projectHumanActionConversation','projectHumanActionPreview','projectHumanActionReceipt','getHumanActionConsumerCoverage'])assert.equal(typeof api.reads[method],'function',method);
const action=registry.actions.find(item=>item.id==='places.plan'),projection=api.reads.projectHumanActionConsumer({action,capability:{state:'AVAILABLE_AFTER_CONFIRMATION'}});
assert.equal(projection.view,'PREVIEW');
assert.equal(api.reads.projectHumanActionConversation({status:'compiled',intents:[{clause:'Restaurant finden',mode:'read'}],missingInputs:[],conflicts:[],blockedCommands:[]}).visible,false);
assert.equal(api.reads.getHumanActionConsumerCoverage(registry.actions).projectedActions,333);
assert.equal(api.diagnostics().providers.humanActionConsumerProjection,true);
console.log('M16.5 Block 0 Human-AI consumer public Intelligence adapter: PASS');
