const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const version=read('intelligence/kernel/version.js');
const index=read('index.html');
const sw=read('sw.js');
const force=read('force-update.html');
const contract=JSON.parse(read('docs/modularization/contracts/trip.v1.json'));
const adapter='core/platform/trip-contract-adapter.js?v=13.81.5';
assert(version.includes("core:'4.81.5'"));
assert(version.includes("build:'13.81.5'"));
assert(index.includes(adapter),'index must load M3.1 Trip adapter');
assert(index.indexOf('core/trips/join-flow.js?v=13.81.5')<index.indexOf(adapter),'adapter must load after Trip-owned use-case providers');
assert(index.indexOf(adapter)<index.indexOf('app/app-shell.js?v=13.81.5'),'adapter must be ready before AppShell');
assert(sw.includes("const CACHE='luvia-shell-v13.81.5'"));
assert(sw.includes("'core/platform/trip-contract-adapter.js'"),'service worker must cache adapter');
assert(force.includes('appv=13.81.5'),'force-update must target current build');
assert.strictEqual(contract.contractId,'trip.v1');
assert.strictEqual(contract.version,'1');
assert.strictEqual(contract.status,'implemented-m3.1');
assert(contract.runtimeGlobals.includes('LuviaTripContractV1'));
console.log('M3.1 Trip Contract Release Integration: OK');
