const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const version=read('intelligence/kernel/version.js');
const index=read('index.html');
const sw=read('sw.js');
const force=read('force-update.html');
const contract=JSON.parse(read('docs/modularization/contracts/places.v1.json'));
const adapter='core/platform/places-contract-adapter.js?v=13.81.6';

assert(version.includes("core:'4.81.6'"));
assert(version.includes("build:'13.81.6'"));
assert(index.includes(adapter),'index must load M3.2 Places adapter');
assert(index.indexOf('core/places/place-command-service.js?v=13.81.6')<index.indexOf(adapter),'adapter must load after Places-owned command provider');
assert(index.indexOf('intelligence/places-service.js?v=13.81.6')<index.indexOf(adapter),'adapter must load after Places gateway');
assert(index.indexOf(adapter)<index.indexOf('app/app-shell.js?v=13.81.6'),'adapter must be ready before AppShell');
assert(sw.includes("const CACHE='luvia-shell-v13.81.6'"));
assert(sw.includes("'core/platform/places-contract-adapter.js'"),'service worker must cache Places adapter');
assert(force.includes('appv=13.81.6'),'force-update must target current build');
assert.strictEqual(contract.contractId,'places.v1');
assert.strictEqual(contract.version,'1');
assert.strictEqual(contract.runtimeImplementationStage,'M3.2');
assert.strictEqual(contract.status,'implemented-m3.2');
assert(contract.currentImplementation.includes('LuviaPlaceCore'));
assert(contract.currentImplementation.includes('LuviaPlaces'));
assert(contract.currentImplementation.includes('LuviaPlaceCommands'));
assert(contract.currentImplementation.includes('LuviaPlacesContractV1'));
assert(contract.runtimeGlobals.includes('LuviaPlacesContractV1'));
assert(contract.runtimeGlobals.includes('LuviaPlacesContract'));
assert.strictEqual(contract.eventTransport,'DOM CustomEvent via luvia:<event-name>; existing compatibility events retained');
console.log('M3.2 Places Contract Release Integration: OK');
