const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.join(__dirname,'..');
const read=f=>fs.readFileSync(path.join(root,f),'utf8');
const version=read('intelligence/kernel/version.js');
const build=(version.match(/build:'([^']+)'/)||[])[1],core=(version.match(/core:'([^']+)'/)||[])[1];
const svc=read('core/diagnostics/media-readiness.js');
assert(svc.includes(`const VERSION='${core}'`),'Media Readiness version missing');
assert(svc.includes("service:'media-readiness'"),'standard service response missing');
assert(svc.includes("gate:'SMART PHOTO FOUNDATION'"),'current readiness gate missing');
assert(svc.includes("probeTable(client,'media'"),'media table probe missing');
assert(svc.includes("probeTable(client,'gallery_photos'"),'legacy gallery probe missing');
assert(svc.includes("probeTable(client,'live_moment_status'"),'live moment probe missing');
assert(svc.includes("probeBucket(client,'luvia-media'"),'canonical bucket probe missing');
const index=read('index.html'),consoleHtml=read('intelligence/console.html'),base=read('intelligence/services/base-services.js');
assert(index.includes(`core/diagnostics/media-readiness.js?v=${build}`),'app load missing');
assert(consoleHtml.includes(`../core/diagnostics/media-readiness.js?v=${build}`),'console load missing');
assert(consoleHtml.includes('runMediaReadiness'),'console action missing');
assert(base.includes("name:'media-readiness'"),'service registration missing');
assert(base.includes("name:'media-core'"),'media core registration missing');
console.log(`Media readiness compatibility ${build}: OK`);
