const fs=require('fs');
const assert=require('assert');
const moduleText=fs.readFileSync('modules/mobility/mobility-module.js','utf8');
const moveShell=fs.readFileSync('modules/move-shell.js','utf8');
const placesShell=fs.readFileSync('modules/places-shell.js','utf8');
const definitions=fs.readFileSync('core/places/place-type-definitions.js','utf8');
const adapters=fs.readFileSync('core/places/place-adapters.js','utf8');
const gateway=fs.readFileSync('supabase/functions/luvia-gateway/index.ts','utf8');
const places=fs.readFileSync('supabase/functions/luvia-gateway/_shared/places.ts','utf8');
for(const token of ["placeType:'mobility'",'LuviaPlaceExperience.discovery','LuviaPlaceExperience.moduleShell','LuviaPlaceCollections.favoritePanel','LuviaPlaceUI.card',"registerCapabilityRenderer?.('mobility'",'SEARCH_PLANS','acceptsPlan','displayNameFor'])assert(moduleText.includes(token),`mobility module missing ${token}`);
for(const token of ["type:'mobility'",'mobilityIntelligence:true','mobilityPlanning:true',"key:'planned_at'", "renderer:'mobility'", "identity:{label:'Move-Punkt'"])assert(definitions.includes(token),`mobility definition missing ${token}`);
assert(adapters.includes("type==='mobility'?'Move nutzt die globale Place-Runtime mit eigener Domain-Shell."),'mobility adapter does not expose Move ownership');
assert(moveShell.includes('LuviaMoveShell'),'Move shell missing');
assert(moveShell.includes('places-hub-tile'),'Move shell does not reuse the shared hub tile system');
assert(!placesShell.includes("mobility:{"),'mobility still exists in Places overview');
assert(places.includes('strictDestination===false'),'broad Move search bias support missing');
assert(places.includes('evChargeOptions')&&places.includes('parkingOptions'),'mobility provider fields missing');
for(const type of ['airport','train_station','bus_station','ferry_terminal','ferry_service','subway_station','taxi_stand','car_rental','park_and_ride','electric_vehicle_charging_station'])assert(moduleText.includes(`type:'${type}'`),`exact Move search type missing: ${type}`);
for(const forbidden of ['CYCLING_ACTIONS','cycling.search','cycling.health','cycling.details'])assert(!gateway.includes(forbidden),`gateway still exposes ${forbidden}`);
for(const file of ['core/places/cycling-route-intelligence-service.js','intelligence/cycling-route-service.js','modules/cycling-routes/cycling-route-module.js','supabase/functions/luvia-gateway/_shared/cycling.ts'])assert(!fs.existsSync(file),`retired cycling file still exists: ${file}`);
console.log('Move mobility integration and cycling removal: OK');
