const fs=require('fs'),assert=require('assert');
const contract=fs.readFileSync('core/places/place-type-definitions.js','utf8');
const moduleCode=fs.readFileSync('modules/nature/nature-module.js','utf8');
const shell=fs.readFileSync('modules/places-shell.js','utf8');
const registry=fs.readFileSync('core/modules/module-registry.js','utf8');
const app=fs.readFileSync('app/app-shell.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(contract.includes("type:'nature',moduleKey:'nature'"),'Nature contract missing');
assert(contract.includes("key:'planned_at'"),'Nature timeline field missing');
assert(moduleCode.includes('LuviaPlaceExperience.discovery'),'Global discovery shell missing');
assert(moduleCode.includes('LuviaPlaceCollections.favoritePanel'),'Global favorite panel missing');
assert(moduleCode.includes('LuviaPlaceUI.card'),'Global cards missing');
assert(moduleCode.includes("registerCapabilityRenderer?.('nature'"),'Nature capability renderer missing');
assert(moduleCode.includes("placeType:'nature'"),'Canonical nature collection type missing');
assert(moduleCode.includes("type:'nature'"),'Nature cloud pipeline missing');
assert(moduleCode.includes("includedType:''"),'Nature discovery must support multiple natural Google types');
assert(shell.includes("nature:{type:'nature'"),'Nature hub tile missing');
assert(registry.includes("id:'nature'"),'Nature module registry entry missing');
assert(app.includes("window.LuviaNature?.openPlace"),'Typed nature detail routing missing');
assert(index.includes('nature-intelligence-service.js'),'Nature Intelligence not loaded');
assert(index.includes('modules/nature/nature-module.js'),'Nature module not loaded');
const adapters=fs.readFileSync('core/places/place-adapters.js','utf8');assert(adapters.includes("'shopping','nature'"),'Nature adapter not productive');
const conformance=fs.readFileSync('core/places/place-conformance-service.js','utf8');assert(conformance.includes('modules/nature/nature-module.js'),'Nature conformance missing');
console.log('Nature place integration: OK');
