'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const copy=value=>JSON.parse(JSON.stringify(value)),read=path=>fs.readFileSync(path,'utf8');
const harness=new Function('require',read('tests/trip-composer-recovery.test.cjs').split('\n(async()=>{\n  let checks=0;')[0]+'\nreturn harness;')(require);
let checks=0;const check=fn=>{fn();checks++};
(async()=>{
  const h=harness(),resolver=h.sandbox.LuviaTripPreferenceResolutionCoreV1;
  vm.runInContext(read('core/places/places-domain-contract-core.js'),h.sandbox,{filename:'core/places/places-domain-contract-core.js'});
  const profile={familyPreferences:{needs:['traveling_with_children','baby','family_friendly','stroller'],travelingWithChildren:true,stroller:true},travelStyles:['authentic','family_friendly'],dietaryPreferences:['vegetarian'],accessibilityNeeds:['wheelchair'],budgetPreference:'low'},untouched=copy(profile);
  const interpreted={ok:true,meta:{fallback:false},data:{goals:[{type:'water',label:'Ein langer Strandtag am Meer'},{type:'nightlife',label:'Live-Musik am Abend'}],hardConstraints:[{key:'adults',value:'2'},{key:'children',value:'0'}],softPreferences:[{key:'budgetLevel',value:'balanced'},{key:'mobility',value:'city_transit'},{key:'experienceWish',value:'Lokale Küche gemeinsam entdecken'}],unknowns:[],confidence:.95}};
  const brief=resolver.projectTripBrief({...h.state.data,profilePreferences:profile,participantPlan:'invite-after-creation',tripPreferences:{experiences:['hands_on','live_evenings']}},interpreted);
  check(()=>assert.equal(brief.requestPreferences.familyPreferences.stroller,false));
  check(()=>assert.deepEqual(copy(brief.requestPreferences.familyPreferences.needs),[]));
  check(()=>assert.equal(brief.requestPreferences.budgetPreference,'medium'));
  check(()=>assert.ok(brief.requestPreferences.accessibilityNeeds.includes('wheelchair')));
  check(()=>assert.ok(brief.requestPreferences.dietaryPreferences.includes('vegetarian')));
  check(()=>assert.deepEqual(profile,untouched,'An adults-only trip never changes the global profile'));
  check(()=>assert.ok(brief.tripPreferences.interests.includes('water')&&!brief.tripPreferences.interests.includes('nature'),'Beach semantics do not request generic park days'));
  check(()=>assert.equal(brief.travelOrder.geography.movementStyle,'city_transit'));
  check(()=>assert.equal(brief.travelOrder.group.preferenceCoverage.status,'awaiting-invitees'));
  check(()=>assert.equal(brief.travelOrder.group.preferenceCoverage.otherMembersConsulted,false));
  check(()=>assert.ok(brief.travelOrder.experiences.wishes.some(w=>w.includes('ausprobieren'))));
  const unknown=resolver.projectTripBrief({...h.state.data,profilePreferences:profile}, {...interpreted,data:{...interpreted.data,hardConstraints:[]}});
  check(()=>assert.equal(unknown.travelOrder.travelers.children,null));
  check(()=>assert.equal(unknown.requestPreferences.familyPreferences.stroller,true,'Unknown party is not silently converted to adults-only'));
  const normalized=h.sandbox.LuviaTripDraftCoreV1.createDraft({...h.state.data,tripPreferences:{movementStyle:'city_transit',adults:2,children:0,experiences:['hands_on'],freeTimePercent:null}});
  check(()=>assert.equal(normalized.tripPreferences.movementStyle,'city_transit'));
  check(()=>assert.equal(normalized.tripPreferences.children,0));
  check(()=>assert.deepEqual(copy(normalized.tripPreferences.experiences),['hands_on']));
  const normalizedBrief=resolver.projectTripBrief({...normalized,profilePreferences:{}},interpreted);
  check(()=>assert.equal(normalizedBrief.policy.freeTimePercent,20,'Unknown saved free-time percentage preserves the visible default'));
  const network={console,Date,JSON,URL,URLSearchParams,Map,Set,Promise,window:null,document:{documentElement:{lang:'de'}},performance:{now:()=>0}};network.window=network;network.globalThis=network;
  network.LuviaBackend={request:async()=>({ok:true,data:{places:[{id:'here:water',provider:'here',primaryType:'water_park',types:['water_park'],providerNativeTypes:['Water Park'],primaryTypeLabel:'Water Park'}]}})};
  vm.createContext(network);vm.runInContext(read('intelligence/places-service.js'),network);
  const waterPark=(await network.LuviaPlaces.textSearch('Water park',{strictDestination:false})).data.places[0];
  check(()=>assert.ok(!waterPark.types.includes('park'),'Canonical water-park evidence must not be mapped again into a passive park'));
  check(()=>assert.deepEqual(copy(waterPark.providerNativeTypes),['Water Park']));
  const raw={...h.candidate('nightlife',900),primaryType:'nightlife_spot',name:'Km 0',types:['nightlife_spot','historical_monument'],providerNativeTypes:['Historical Monument'],description:'A historic marker',address:'Calle de las Barcas'};
  const retained=h.api.retainedPoolCandidate(raw);
  check(()=>assert.deepEqual(copy(retained.providerNativeTypes),['Historical Monument']));
  check(()=>assert.equal(retained.description,'A historic marker'));
  const candidates=[raw,...Array.from({length:40},(_,i)=>({...h.candidate(['water','food','culture','activities'][i%4],i),primaryType:['beach','restaurant','art_gallery','bowling_alley'][i%4],providerNativeTypes:[['Beach','Restaurant','Art gallery','Bowling alley'][i%4]],description:'Provider description '+i}))];
  const itinerary=await h.sandbox.LuviaIntelligenceContractV1.reads.composeTripItinerary({destination:h.state.data.destination,days:h.api.itineraryDays(h.state),candidates,brief});
  const model=h.sandbox.modelCalls.find(call=>call.capability==='trip.compose');
  check(()=>assert.ok(model.request.planningContract.experienceQuality.variety.includes('WHOLE trip')));
  check(()=>assert.ok(!model.request.candidateCatalog.some(place=>place.providerPlaceId===raw.providerPlaceId),'Contradictory retrieval identity is rejected before the model request'));
  check(()=>assert.ok(model.request.candidateCatalog.some(place=>place.experienceEvidence.description.startsWith('Provider'))));
  const mealHarness=harness(),mealResolver=mealHarness.sandbox.LuviaTripPreferenceResolutionCoreV1,mealBrief=mealResolver.projectTripBrief({...mealHarness.state.data,tripPreferences:{...mealHarness.state.data.tripPreferences,interests:['food'],mealTiming:'dinner'}},{ok:true,meta:{fallback:false},data:{understanding:'Restaurants vor allem am Abend.',goals:[{type:'food',label:'Restaurants'}],hardConstraints:[],softPreferences:[{key:'movementStyle',value:'city_transit',label:'Mit Bus und Bahn'}],unknowns:[],confidence:.95}}),mealCandidates=Array.from({length:12},(_,index)=>mealHarness.candidate('food',index+1));
  const rejectedMeal=await mealHarness.sandbox.LuviaIntelligenceContractV1.reads.composeTripItinerary({destination:mealHarness.state.data.destination,days:mealHarness.api.itineraryDays(mealHarness.state),candidates:mealCandidates,brief:mealBrief});
  check(()=>assert.equal(mealHarness.sandbox.modelCalls.find(call=>call.capability==='trip.compose').request.planningContract.mealPlan.slots[0].kind,'dinner'));
  check(()=>assert.ok(rejectedMeal.contractIssues.some(issue=>issue.code==='TRIP_ITINERARY_MEAL_WINDOW_VIOLATION'),'A model cannot quietly place dinner-only restaurants at daytime hours'));
  for(const [type,label] of [['shopping_mall','Einkaufszentrum'],['marina','Hafen & Marina'],['beach','Strand'],['cocktail_bar','Cocktailbar'],['bowling_alley','Bowling'],['historical_landmark','Historischer Ort'],['vegetarian_restaurant','Vegetarisches Restaurant']])check(()=>assert.equal(h.api.placeLabel({primaryType:type,types:[type],requestCategory:type==='shopping_mall'?'shopping':type==='cocktail_bar'?'nightlife':type==='vegetarian_restaurant'?'food':'activities'}),label));
  check(()=>assert.notEqual(h.api.placeLabel({primaryType:'point_of_interest',requestCategory:'nightlife'}),'Ort zum Entdecken'));
  const parks=Array.from({length:3},(_,i)=>({...h.candidate('nature',300+i),primaryType:'park',types:['park'],providerNativeTypes:['Park']}));
  const repetitive={...copy(itinerary),days:itinerary.days.map((day,i)=>({...day,entries:[{...day.entries[0],providerPlaceId:parks[i].providerPlaceId,durationMinutes:120}]}))};
  await h.sandbox.LuviaIntelligenceContractV1.reads.auditTripItinerary({brief,candidates:[...candidates,...parks],itinerary:repetitive});
  const audit=h.sandbox.modelCalls.at(-1).request;
  check(()=>assert.equal(audit.experienceBalance.daysPerKind['park-garden'],3,'The independent audit sees recurrence across different park identities'));
  check(()=>assert.ok(audit.planningContract.experienceQuality.limits.includes('when requested')));
  await h.api.loadAiDayDraft(h.state);
  h.state.routeEditSlot=h.state.draftSelections[0].slotId;h.state.routeEditAction='time';h.api.render(h.state);
  check(()=>assert.equal((h.root.innerHTML.match(/class="lx-route-focus-panel"/g)||[]).length,1));
  check(()=>assert.ok(h.root.innerHTML.includes('data-ftc-draft-time=')));
  check(()=>assert.ok(!h.root.innerHTML.includes('data-ftc-rejection='),'One editing operation is shown at a time'));
  h.state.routeEditAction='reject';h.api.render(h.state);
  check(()=>assert.ok(h.root.innerHTML.includes('data-ftc-rejection="Zu ruhig"')));
  check(()=>assert.ok(!h.root.innerHTML.includes('data-ftc-draft-time=')));
  h.state.draftSelections.filter(item=>item.dayId===h.state.activeDay).forEach((item,i)=>item.time=i===0?'19:00':'10:00');
  const ordered=h.state.draftSelections.filter(item=>item.dayId===h.state.activeDay&&item.action!=='excluded').sort((a,b)=>a.time.localeCompare(b.time)).map(item=>item.providerPlaceId);
  check(()=>assert.deepEqual(copy(h.api.mapPlaces(h.state).map(place=>place.providerPlaceId)),copy(ordered),'Map ordinals follow the visible time-sorted day route'));
  console.log(`P17 experience quality, explicit party, evidence and A2: ${checks}/${checks} PASS`);
})().catch(error=>{console.error(error);process.exitCode=1});
