'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path'),{pathToFileURL}=require('node:url');
let checks=0;const check=fn=>{fn();checks++},read=file=>fs.readFileSync(file,'utf8'),copy=value=>JSON.parse(JSON.stringify(value));
const harness=new Function('require',read('tests/trip-composer-recovery.test.cjs').split('\n(async()=>{\n  let checks=0;')[0]+'\nreturn harness;')(require);
const ok=value=>new Response(JSON.stringify(value),{status:200,headers:{'content-type':'application/json'}});
const destination={name:'Valencia',countryCode:'ES',location:{latitude:39.4699,longitude:-.3763},canonicalCity:{name:'Valencia',center:{lat:39.4699,lng:-.3763}},searchRadiusMeters:20000};
const feature=(id,name,categories,raw={})=>({type:'Feature',properties:{place_id:id,name,categories,lat:39.4699,lon:-.3763,datasource:{raw}}});
(async()=>{
  globalThis.Deno={env:{get:name=>({SUPABASE_URL:'https://fixture.supabase.co',SUPABASE_SERVICE_ROLE_KEY:'fixture',GEOAPIFY_API_KEY:'fixture',TOMTOM_API_KEY:'fixture',HERE_API_KEY:'fixture'}[name]||'')}};
  let features=[],tomtom=[],requests=[];
  globalThis.fetch=async(url,init={})=>{const href=String(url);requests.push(href);
    if(href.includes('luvia_reserve_provider_budget'))return ok({allowed:true});
    if(href.includes('luvia_provider_outcome'))return ok(null);
    if(href.includes('api.geoapify.com/v2/places'))return ok({features});
    if(href.includes('api.tomtom.com'))return ok({results:tomtom});
    if(href.includes('hereapi.com'))return ok({items:[]});
    throw new Error('Unexpected request '+href.split('?')[0]);
  };
  const {placesAction}=await import(pathToFileURL(path.resolve('supabase/functions/luvia-gateway/_shared/places.ts')));
  const {additionalTypes}=await import(pathToFileURL(path.resolve('supabase/functions/luvia-gateway/_shared/additional-places.ts')));
  const search=(category,extra={})=>placesAction('places.text-search',{query:'Descriptive research query with more than three words',destination,options:{category,providers:['geoapify'],maxResultCount:20,maxDistanceMeters:20000,strictDestination:true,forceRefresh:true,...extra}});
  features=[feature('wrong','Palacio de las Comunicaciones',['tourism.sights']),feature('lonja','Llotja de la Seda',['tourism.sights'],{'name:es':'Lonja de la Seda'})];
  let result=await search('sights',{targetName:'Lonja de la Seda',includedTypes:['tourist_attraction'],strictTypeFiltering:true});
  check(()=>assert.deepEqual(result.data.places.map(p=>p.name),['Llotja de la Seda'],'Unrelated monuments do not fulfil a named search; provider aliases can'));
  check(()=>assert(requests.filter(url=>url.includes('api.geoapify')).every(url=>new URL(url).searchParams.get('name')==='Lonja de la Seda'),'The real URL retains a long proper name despite a strict type'));
  requests=[];features=[];
  tomtom=[{id:'target',poi:{name:'Lonja de la Seda',categories:['Important Tourist Attraction']},position:{lat:39.4699,lon:-.3763},address:{freeformAddress:'Valencia'}}];
  result=await search('sights',{providers:['auto'],targetName:'Lonja de la Seda',includedTypes:['tourist_attraction'],strictTypeFiltering:true});
  check(()=>assert.equal(result.data.places[0]?.provider,'tomtom','An empty exact primary search reaches the next configured provider'));
  check(()=>assert.equal(requests.filter(url=>url.includes('api.geoapify')).length,1,'No second unfiltered category request after an exact miss'));
  check(()=>assert(requests.some(url=>url.includes('poiSearch/Lonja%20de%20la%20Seda')),'TomTom retains the proper name'));
  requests=[];tomtom=[];
  await search('sights',{providers:['auto'],targetName:'Missing Named Landmark',includedTypes:['tourist_attraction'],strictTypeFiltering:true});
  check(()=>assert(requests.filter(url=>url.includes('hereapi.com')).every(url=>new URL(url).searchParams.get('name')==='Missing Named Landmark'||new URL(url).searchParams.get('q')==='Missing Named Landmark'),'HERE retains the proper name'));
  features=[feature('spanish','Spanish restaurant',['catering','catering.restaurant','catering.restaurant.spanish'])];
  result=await search('food');
  check(()=>assert(result.data.places[0].types.includes('spanish_restaurant')));
  check(()=>assert(!result.data.places[0].types.includes('spa'),'Spanish cuisine is never a spa'));
  features=[feature('park','Parc Plaça Constitució',['leisure','leisure.park','sport']),feature('generic','Generic sport',['sport']),feature('escape','Escape experience',['entertainment','entertainment.escape_game']),feature('bowling','Bowling experience',['entertainment.bowling_alley'])];
  result=await search('activities');
  check(()=>assert.deepEqual(result.data.places.map(p=>p.name).sort(),['Bowling experience','Escape experience'],'Activities need a specific activity type; parks and land-use parents are insufficient'));
  check(()=>assert(!additionalTypes(['Sports Clothing Retail','Clothing Store']).includes('sports_activity_location'),'A football merchandise shop is not a sports experience'));
  check(()=>assert(additionalTypes(['Sports Clothing Retail','Clothing Store']).includes('sporting_goods_store')));
  check(()=>assert(additionalTypes(['Sports Centre']).includes('sports_activity_location'),'Actual sports facilities remain available'));
  requests=[];features=[];
  await search('activities',{includedTypes:['escape_room'],strictTypeFiltering:true,userQuery:''});
  check(()=>assert(requests.some(url=>new URL(url).searchParams.get('categories')==='entertainment.escape_game'),'Specific activity intent reaches the provider taxonomy'));
  check(()=>assert(requests.filter(url=>url.includes('api.geoapify')).every(url=>!new URL(url).searchParams.has('name')),'An open experience search does not masquerade as a named venue'));

  const h=harness(),raw=h.candidate('culture',1);
  const merged=h.api.mergeAiPlaceResults(h.state,{places:[raw]}, {places:[{...raw,tripSearchTarget:'Named landmark'}]});
  check(()=>assert.equal(merged.places.length,1));
  check(()=>assert.equal(merged.places[0].tripSearchTarget,'Named landmark','Deduplication retains research provenance'));
  const twice=h.api.mergeAiPlaceResults(h.state,merged,{places:[{...raw,tripSearchTarget:'Architecture experience'}]});
  check(()=>assert.deepEqual(copy(h.api.retainedPoolCandidate(twice.places[0]).tripSearchTargets),['Named landmark','Architecture experience'],'Multiple research needs survive the checkpoint projection'));
  h.sandbox.modelOverride=(capability,request)=>{assert.equal(capability,'discovery.plan');return{ok:true,meta:{fallback:false},data:{searchPlans:[{query:'Lonja de la Seda monumento histórico',targetName:'Lonja de la Seda',includedTypes:['tourist_attraction']},{query:'actividades participativas',targetName:null,includedTypes:['escape_room']}]}}};
  const plan=await h.sandbox.LuviaIntelligenceContractV1.reads.planTripPlaceSearch({travelOrder:{mustDo:[]},userRequest:'Try something ourselves and lively evenings',destination,categories:[{types:['tourist_attraction','escape_room']}]});
  check(()=>assert.equal(plan.plans[0].targetName,'Lonja de la Seda'));
  check(()=>assert.equal(plan.plans[1].targetName,null));
  check(()=>assert.equal(h.sandbox.modelCalls.at(-1).request.originalUserRequest,'Try something ourselves and lively evenings','Research sees the original request even if the structured summary omitted a wish'));
  const network={console,Date,JSON,URL,URLSearchParams,Map,Set,Promise,document:{documentElement:{lang:'de'}},performance:{now:()=>0}};network.window=network;network.globalThis=network;
  let transmitted;network.LuviaBackend={request:async(action,payload)=>{transmitted=payload;return{ok:true,data:{places:[]}}}};vm.createContext(network);vm.runInContext(read('intelligence/places-service.js'),network);
  await network.LuviaPlaces.textSearch('Venue description',{strictDestination:false,targetName:'Lonja de la Seda'});
  check(()=>assert.equal(transmitted.options.targetName,'Lonja de la Seda','The browser wire payload preserves the explicit target'));
  for(const hostname of ['integration-luvia.example.workers.dev','abcd1234-integration-luvia.example.workers.dev','myluvia.app']){
    const browser={console,Date,JSON,Map,Set,location:{hostname},LUVIA_AUTH_CONFIG:{supabaseUrl:'https://fixture.supabase.co'},LUVIA_RUNTIME_CONFIG:{backend:{functionName:'luvia-gateway'}}};browser.window=browser;vm.createContext(browser);vm.runInContext(read('intelligence/backend-service.js'),browser);
    check(()=>assert.equal(browser.LuviaBackend.config().functionName,hostname==='myluvia.app'?'luvia-gateway':'luvia-gateway-integration','Only Integration hosts use the separately deployed Gateway'));
  }
  console.log(`P17 research identity, actual activities and Integration isolation: ${checks}/${checks} PASS`);
})().catch(error=>{console.error(error);process.exitCode=1});
