'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs');
const copy=value=>JSON.parse(JSON.stringify(value)),read=file=>fs.readFileSync(file,'utf8');
const harness=new Function('require',read('tests/trip-composer-recovery.test.cjs').split('\n(async()=>{\n  let checks=0;')[0]+'\nreturn harness;')(require);
let checks=0;const check=fn=>{fn();checks++};
(async()=>{
  const h=harness(),reads=h.sandbox.LuviaIntelligenceContractV1.reads;
  h.state.data.tripPreferences.interests=['nightlife','active','shopping'];h.sandbox.profile={travelInterests:['culture','nature']};
  h.state.aiDraft.brief={travelOrder:{categories:[{category:'nightlife'},{category:'active'},{category:'shopping'}],mustDo:['Keine täglichen Parks oder Museen'],excludedCategories:['nature','culture']},tripPreferences:copy(h.state.data.tripPreferences)};
  const untouched=copy(h.sandbox.profile),result=await h.api.readAiPlaces(h.state);
  check(()=>assert.deepEqual([...new Set(h.requests.map(item=>item.category))].sort(),['activities','nightlife','shopping']));
  check(()=>assert.deepEqual(copy(h.requests.find(item=>item.category==='shopping').includedTypes),['shopping_mall']));
  check(()=>assert.equal(h.requests.find(item=>item.category==='shopping').query,'Einkaufszentren'));
  check(()=>assert.deepEqual(h.sandbox.profile,untouched,'Trip-specific interpretation never mutates profile defaults'));
  const policy=reads.experienceSelectionPolicy({brief:h.state.aiDraft.brief});
  const place=(id,type,category=type)=>({...h.candidate(category,id),providerPlaceId:String(id),primaryType:type,types:[type]});
  const park=place(101,'park','activities'),shop=place(102,'sporting_goods_store','shopping'),mall=place(103,'shopping_mall','shopping'),mallWithParking={...place(108,'shopping_mall','shopping'),name:'Heron City',types:['shopping_mall','store','parking','parking_underground']},bar=place(104,'bar','nightlife'),bowling=place(105,'bowling_alley','activities'),marker={...place(106,'historical_monument','nightlife'),types:['historical_monument','nightlife_spot'],name:'Km 0'};
  for(const wrong of [park,shop,marker])check(()=>assert.equal(reads.tripPlaceExperienceFit({place:wrong,policy}).eligible,false));
  for(const right of [mall,mallWithParking,bar,bowling])check(()=>assert.equal(reads.tripPlaceExperienceFit({place:right,policy}).eligible,true));
  const broadSight=place(107,'tourist_attraction','sights'),touristOffice={...broadSight,providerNativeTypes:['Tourist Information Center']},resolvedSight={...broadSight,tripWebResearch:{providerPlaceId:'107',description:'A visitable historical hall with guided architectural tours and a permanent public exhibition.',source:{url:'https://example.test/hall'}}};
  check(()=>assert.equal(reads.tripPlaceExperienceFit({place:broadSight,policy:reads.experienceSelectionPolicy({travelOrder:{categories:[{category:'sights'}]}})}).eligible,false,'A broad attraction bucket alone is not a visitable experience'));
  check(()=>assert.equal(reads.tripPlaceExperienceFit({place:touristOffice,policy:reads.experienceSelectionPolicy({travelOrder:{categories:[{category:'sights'}]}})}).reason,'functional-place-not-visitor-experience'));
  check(()=>assert.equal(reads.tripPlaceExperienceFit({place:resolvedSight,policy:reads.experienceSelectionPolicy({travelOrder:{categories:[{category:'sights'}]}})}).eligible,true,'An exact provider-bound public source may resolve a broad identity'));
  check(()=>assert.equal(reads.tripPlaceExperienceFit({place:shop,policy:{...policy,shoppingStyle:'specific_shops'}}).eligible,true,'A specific shop wish remains supported'));
  const candidates=[park,shop,mall,bar,bowling,marker],original=copy(candidates),catalog=h.api.tripCompositionCandidateCatalog(h.state,candidates);
  check(()=>assert.deepEqual(copy(catalog.map(p=>p.providerPlaceId)).sort(),['103','104','105']));
  check(()=>assert.deepEqual(candidates,original,'The durable reserve is retained even when the working selection changes'));
  const existing={days:[{entries:[{providerPlaceId:shop.providerPlaceId}]}]};
  check(()=>assert.ok(h.api.tripCompositionCandidateCatalog(h.state,candidates,h.state.aiDraft.brief,existing).some(p=>p.providerPlaceId===shop.providerPlaceId),'Repair context preserves old referenced Places'));
  const quality=h.api.tripPoolQuality(h.state,[park,shop,marker]);
  check(()=>assert.equal(quality.candidateCount,0,'Wrong retrieval labels cannot make an unusable pool look complete'));
  const bad={owner:'intelligence',kind:'ai-trip-itinerary',days:[{date:'2027-06-14',entries:[park,shop,marker],freeTime:[{purpose:'Lebendiger Abend'}]}]};
  const alignment=reads.tripExperienceAlignment({brief:h.state.aiDraft.brief,candidates,itinerary:bad});
  check(()=>assert.deepEqual(copy(alignment.missing).sort(),['activities','nightlife','shopping']));
  check(()=>assert.equal(alignment.outside.length,3));
  const audited=await reads.auditTripItinerary({brief:h.state.aiDraft.brief,candidates,itinerary:bad});
  check(()=>assert.equal(audited.readyForReview,false,'A positive AI self-report cannot override absent experiences'));
  check(()=>assert.equal(audited.promiseAssessment.kept,false));
  const reserve=await reads.rankTripReserve({travelOrder:h.state.aiDraft.brief.travelOrder,candidates,mode:'replace'});
  check(()=>assert.deepEqual(copy(reserve.options.map(p=>p.providerPlaceId)).sort(),['103','104','105']));
  const good={...bad,days:[{date:'2027-06-14',entries:[mall,bar,bowling]}]},passed=await reads.auditTripItinerary({brief:h.state.aiDraft.brief,candidates,itinerary:good});
  check(()=>assert.equal(passed.readyForReview,true,'Actual coverage and the independent positive AI review pass together'));
  const naturePolicy=reads.experienceSelectionPolicy({travelOrder:{categories:[{category:'nature'}]}});
  check(()=>assert.equal(reads.tripPlaceExperienceFit({place:{...park,requestCategory:'nature'},policy:naturePolicy}).eligible,true,'An explicitly requested park holiday is not prohibited'));
  const saved=h.sandbox.LuviaTripDraftCoreV1.createDraft({...h.state.data,tripPreferences:{shoppingStyle:'specific_shops'}});
  check(()=>assert.equal(saved.tripPreferences.shoppingStyle,'specific_shops'));
  const projected=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...h.state.data,tripPreferences:{movementStyle:'city_transit'}},{ok:true,meta:{fallback:false},data:{goals:[{type:'shopping',label:'Shopping'},{type:'nature',label:'Old erroneous nature goal'}],hardConstraints:[{key:'excludeCategory',value:'nature'}],softPreferences:[],unknowns:[]}});
  check(()=>assert.deepEqual(copy(projected.travelOrder.excludedCategories),['nature']));
  check(()=>assert.ok(!projected.travelOrder.categories.some(c=>c.category==='nature')));
  check(()=>assert.equal(projected.tripPreferences.shoppingStyle,'centres'));
  check(()=>assert.equal(projected.planningAssumptions.find(a=>a.id==='shopping-style').value,'Einkaufszentren'));
  const dinnerBrief=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...h.state.data,tripPreferences:{...h.state.data.tripPreferences,interests:['food']}},{ok:true,meta:{fallback:false},data:{understanding:'Restaurants vor allem am Abend.',goals:[{type:'food',label:'Gute Restaurants'}],hardConstraints:[],softPreferences:[{key:'mealTiming',value:'dinner',label:'Eher abends essen'},{key:'movementStyle',value:'city_transit',label:'Mit Bus und Bahn'}],unknowns:[],confidence:.96}});
  check(()=>assert.equal(dinnerBrief.tripPreferences.mealTiming,'dinner'));
  check(()=>assert.deepEqual(copy(dinnerBrief.travelOrder.rhythm.mealPlan.slots),[{kind:'dinner',windowStart:'18:30',windowEnd:'21:30',venueMode:'place',importance:'preferred'}]));
  check(()=>assert.equal(dinnerBrief.planningAssumptions.find(a=>a.id==='meal-timing').value,'Eher abends'));
  check(()=>assert.equal(h.sandbox.LuviaTripDraftCoreV1.createDraft({...h.state.data,tripPreferences:{mealTiming:'lunch'}}).tripPreferences.mealTiming,'lunch'));
  console.log(`P17 intent selection, shopping meaning and factual audit: ${checks}/${checks} PASS`);
})().catch(error=>{console.error(error);process.exitCode=1});
