'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
const source=fs.readFileSync('app/first-trip-composer.js','utf8');
const input={title:'Küstenreise',symbol:'✦',destination:{name:'Scharbeutz',placeId:'scharbeutz',countryCode:'DE',latitude:54.02,longitude:10.75,timezone:'Europe/Berlin'},startDate:'2027-06-12',endDate:'2027-06-14',scheduleMode:'fixed',entryMode:'ai',feelings:[],modules:['places','journey'],tripPreferences:{interests:['food','culture','active'],budgetLevel:'balanced'},durablePreferenceProposal:{requested:false},requestBrief:''};
const clone=value=>JSON.parse(JSON.stringify(value));
function harness(){
  const storage=new Map(),requests=[],actions=[],tripCalls=[],ledger=new Map();let sequence=0,completed=0;
  const root={innerHTML:'',classList:{add(){},remove(){}},querySelector:()=>null,querySelectorAll:()=>[],addEventListener(){},removeEventListener(){}};
  const sandbox={console,Date,Intl,Math,JSON,Object,Array,Map,Set,Number,String,Boolean,Error,TypeError,Promise,crypto:{randomUUID:()=>`key-${++sequence}`},setTimeout,clearTimeout,queueMicrotask(){},requestAnimationFrame(){},navigator:{language:'de-DE'},document:{documentElement:{classList:{contains:()=>false}},body:{classList:{contains:()=>false}}}};sandbox.window=sandbox;sandbox.globalThis=sandbox;
  vm.createContext(sandbox);
  for(const file of ['core/trips/trip-draft-core.js','core/intelligence/trip-preference-resolution-core.js','core/intelligence/intelligence-domain-contract-core.js','core/intelligence/intelligence-action-contract-core.js','core/journey/journey-resilience-core.js'])vm.runInContext(fs.readFileSync(file,'utf8'),sandbox,{filename:file});
  sandbox.LuviaAI={run:async(capability,request,options)=>{
    sandbox.modelCalls=(sandbox.modelCalls||[]).concat({capability,request,options});
    if(capability==='trip.compose'){
      if(sandbox.itineraryOverride)return sandbox.itineraryOverride(capability,request,options);
      const days=(request.days||[]).map(day=>({...day,entries:[]})),catalog=request.candidateCatalog||[],chosen=catalog.slice(0,Math.max(1,catalog.length-2)),notBefore=request.planningPolicy?.notBefore||'09:30',start=Number(notBefore.slice(0,2))*60+Number(notBefore.slice(3));
      const suggestedTime=slot=>{const minutes=start+slot*180;return `${String(Math.floor(minutes/60)%24).padStart(2,'0')}:${String(minutes%60).padStart(2,'0')}`};
      chosen.forEach((place,index)=>{const day=days[Math.min(days.length-1,Math.floor(index*Math.max(1,days.length)/Math.max(1,chosen.length)))],slot=day.entries.length;day.entries.push({providerPlaceId:place.providerPlaceId,time:suggestedTime(slot),durationMinutes:90,category:place.category,reason:'Passt zum vollständigen Reiseauftrag.',certainty:'modelled',evidenceRefs:[`place:${place.providerPlaceId}:identity`],confidence:.91});});
      const remaining=catalog.slice(chosen.length),backupOptions=remaining[0]&&chosen[0]?[{dayDate:days[0].date,forProviderPlaceId:chosen[0].providerPlaceId,providerPlaceId:remaining[0].providerPlaceId,trigger:'bei Regen oder kurzfristiger Schließung',reason:'Eine belegte Alternative im selben Tagesraum.'}]:[];
      return {ok:true,meta:{fallback:false},data:{title:'Euer vollständiger Reiseentwurf',summary:'Alle Reisetage sind als zusammenhängender Entwurf geplant.',travelPromise:{summary:'Eine ruhige, vollständige Reise mit Kultur, Essen und bewussten Pausen.',commitments:['Alle Reisetage passend zu ihrer Rolle planen','Kultur, Essen und Aktivität sinnvoll verteilen'],deliberateFreeTime:'Jeder volle Tag erhält einen sichtbaren Erholungspuffer.',exclusions:[]},days:days.map(day=>({date:day.date,label:day.label,theme:'Ein stimmiger Reisetag',role:day.role,balance:{energy:'balanced',plannedMinutes:day.entries.length*90,freeTimeMinutes:60,freeTimePurpose:'Bewusste Erholung'},freeTime:day.role==='full'?[{start:'16:00',end:'17:00',purpose:'Bewusste Erholung',reason:'Der Tag soll nicht lückenlos gefüllt sein.'}]:[],entries:day.entries})),uncertaintyMap:[{subject:'Öffnungszeiten am Reisetag',kind:'opening',state:'open',reason:'Noch kein datierter Beleg.',source:'',observedAt:'',expiresAt:'',affectedDayDates:days.map(day=>day.date),providerPlaceIds:chosen.map(place=>place.providerPlaceId),evidenceRefs:[]}],bookingOrder:[{rank:1,subject:'Anreisezeiten bestätigen',providerPlaceId:'',state:'open',reason:'Sie bestimmen den belastbaren Beginn des Ankunftstags.',blocks:['Ersten Abend festlegen'],evidenceRefs:[]}],neighborhoodRecommendation:{state:'modelled',label:'Im Radius der geplanten Tagesorte',radiusKm:3,reason:'Die belegten Orte liegen in einem kompakten Tagesraum.',evidencePlaceIds:chosen.slice(0,3).map(place=>place.providerPlaceId),caveats:['Unterkünfte und echte Wege sind noch nicht geprüft.']},alternatives:remaining.slice(backupOptions.length).map(place=>place.providerPlaceId),backupOptions,uncoveredRequirements:[],warnings:[],confidence:.91}};
    }
    if(capability==='trip.compose-day-repair'){
      if(sandbox.dayRepairOverride)return sandbox.dayRepairOverride(capability,request,options);
      let cursor=0;const days=(request.days||[]).map(day=>{const entries=(request.candidateCatalog||[]).slice(cursor,cursor+day.minimumMoments).map((place,index)=>({providerPlaceId:place.providerPlaceId,time:['10:00','13:00','18:00','20:00'][index],durationMinutes:90,reason:'Gezielt für diesen offenen Reisetag repariert.'}));cursor+=day.minimumMoments;return{date:day.date,theme:'Gezielt vervollständigter Reisetag',balance:{energy:'balanced',freeTimePurpose:'Bewusste Erholung'},freeTime:day.role==='full'?[{start:'16:00',end:'17:00',purpose:'Bewusste Erholung'}]:[],entries}});
      return {ok:true,meta:{fallback:false},data:{days,reasoningSummary:'Nur die offenen Reisetage wurden repariert.',confidence:.94}};
    }
    if(capability==='trip.audit'){
      if(sandbox.auditOverride)return sandbox.auditOverride(capability,request,options);
      return {ok:true,meta:{fallback:false},data:{readyForReview:true,score:95,headline:'Vollständig, rhythmisch und räumlich stimmig.',promiseAssessment:{kept:true,summary:'Der Entwurf hält sein Reiseversprechen.',missedCommitments:[]},dimensions:[{id:'coverage',label:'Tagesabdeckung',score:100,status:'pass',summary:'Alle Tage sind geplant.'},{id:'rhythm',label:'Rhythmus',score:94,status:'pass',summary:'Die Zeiten passen.'}],issues:[],strengths:['Alle Reisetage vollständig','Plan B vorbereitet'],repairInstructions:[],confidence:.96}};
    }
    if(sandbox.modelOverride)return sandbox.modelOverride(capability,request,options);
    return {ok:true,meta:{fallback:false},data:sandbox.dialogue||{understanding:'Ruhig Kultur entdecken und vegan essen.',goals:[{type:'culture',label:'Kultur erleben',hardConstraints:[],softPreferences:[]}],hardConstraints:[{key:'dietary',value:'vegan',label:'Vegan essen'},{key:'notBefore',value:'12:00',label:'Erst ab zwölf Uhr'}],softPreferences:[{key:'pace',value:'slow',label:'Ein ruhiger Tag'},{key:'movementStyle',value:'city_transit',label:'Mit Bus und Bahn durch die Stadt'}],conflictAssessment:{status:'none',summary:'Keine wesentliche Spannung.',tensions:[]},followUpQuestion:null,summary:{headline:'Reisewunsch verstanden',intro:'Luvia plant die ganze Reise.',goalLabels:['Kultur erleben'],hardLabels:['Vegan essen','Erst ab zwölf Uhr'],softLabels:['Ein ruhiger Tag','Mit Bus und Bahn durch die Stadt']},unknowns:[],confidence:.93}};
  }};
  sandbox.calendarCalls=[];sandbox.LuviaOpenAIProvider={invoke:async(action,payload,options)=>{sandbox.calendarCalls.push({action,payload,options});if(sandbox.calendarOverride)return sandbox.calendarOverride(action,payload,options);return {ok:true,data:{owner:'intelligence',contractId:'intelligence.v1',kind:'travel-calendar-evidence',status:'verified',evidence:[]}}}};
  vm.runInContext(fs.readFileSync('core/platform/intelligence-contract-adapter.js','utf8'),sandbox);
  sandbox.LuviaPlatformPorts={get:name=>name==='StoragePort'?{get:(key,fallback)=>clone(storage.get(key)??fallback),set:(key,value)=>{if(sandbox.failStorage)return;storage.set(key,clone(value));return value},remove:key=>storage.delete(key)}:name==='AuthSessionPort'?{snapshot:()=>({user:{id:sandbox.viewer||'composer-test'}})}:null};
  sandbox.profile={dietaryPreferences:['vegetarian']};sandbox.LuviaIdentityContractV1={reads:{getPreferences:()=>sandbox.profile}};
  sandbox.LuviaTripContractV1={composition:{composeDayDraft:(...args)=>sandbox.LuviaTripDraftCoreV1.composeDayDraft(...args)},commands:{createFirstTrip:async(data,options)=>{tripCalls.push(clone(data));return {owner:'trip',action:'trip.first.create',status:'committed',tripId:'trip-1',idempotencyKey:options.idempotencyKey}}}};
  sandbox.LuviaJourneyContractV1={reads:{rehearseDay:args=>sandbox.LuviaJourneyResilienceCoreV1.rehearseDay(args)}};
  const candidate=(category,index)=>({providerPlaceId:`${category}-${index}`,name:`${category} ${index}`,requestCategory:category,primaryType:category==='food'?'restaurant':'museum',coordinates:{latitude:54.02+index*.001,longitude:10.75}});
  sandbox.LuviaPlacesContractV1={reads:{suggestDestinations:async()=>({suggestions:[]}),getDestination:async()=>null,getActiveDiscovery:()=>sandbox.cached||null,localSearchRadius:()=>5000,recommend:async options=>{requests.push(options);if(sandbox.recommend)return sandbox.recommend(options);return {places:[1,2,3,4].map(index=>candidate(options.category,index))}}}};
  sandbox.LuviaAIActionRuntime={
    prepare:(actionId,payload,options)=>{
      const validation=sandbox.LuviaIntelligenceActionContractCoreV1.validateActionInput(actionId,payload,{timeZone:options.timeZone});assert.equal(validation.valid,true,JSON.stringify(validation.issues));
      const prior=[...ledger.values()].find(item=>item.options.idempotencyKey===options.idempotencyKey);assert.ok(!prior,'successful and failed actions must use checkpoint/retry, not prepare again');
      const id='ledger-'+(++sequence);ledger.set(id,{id,actionId,payload,options,status:'proposed'});return {ledgerId:id};
    },
    execute:async(actionId,unused,options)=>{
      const item=ledger.get(options.ledgerId);assert.equal(item.actionId,actionId);actions.push(clone(item));
      if(sandbox.executeOverride){const result=await sandbox.executeOverride(item,actions.length);if(result!==undefined){item.status=result?.evidence?.status==='failed'?'failed':'outcome_unknown';return result;}}
      item.status='succeeded';return sandbox.LuviaIntelligenceActionContractCoreV1.createReceipt({actionId,status:'completed',ownerCommand:true,ledgerId:item.id,idempotencyKey:item.options.idempotencyKey,reference:{tripId:item.payload.tripId,providerPlaceId:item.payload.providerPlaceId,readbackVerified:true}});
    },
    getActionState:id=>ledger.get(id),
    retry:async(id,options)=>sandbox.LuviaAIActionRuntime.execute(ledger.get(id).actionId,{}, {...options,ledgerId:id}),
    reconcile:async(actionId,payload,options)=>{
      if(sandbox.reconcileOverride)return sandbox.reconcileOverride(actionId,payload,options);
      return sandbox.LuviaIntelligenceActionContractCoreV1.createReceipt({actionId,status:'outcome_unknown',ownerCommand:true,ledgerId:options.ledgerId,idempotencyKey:options.idempotencyKey,outcomeUnknown:true,reference:{tripId:payload.tripId,providerPlaceId:payload.providerPlaceId,readbackVerified:false}});
    }
  };
  const instrumented=source.replace('window.LuviaFirstTripComposer=Object.freeze',`window.composerTest={state:()=>mounted,render,prepareAiBrief,loadAiDayDraft,chooseHolidayWindow,briefReviewPanel,travelWindowChoicesMarkup,save,setDraftAction,swapDraftSelection,refreshDraft,readAiPlaces,confirmationProblem,persist,moveDraftSelection,mapPlaces,focusDraftPlaceOnMap,dayJourneyPanel,inspire,takeInspiration,invalidateAiPlanning,repairDestinationZone,validate,seasonalMood,linkedMedia,filmFrame,filmChoose,filmAdvance,pauseFilm,scheduleFilm,tripTrace,hydrateAiMedia,updatePreference,settledGeography,checkDayRoutes,routeReviewPanel,rehearseDraft,dayLegs,checkedRoute,destinationIdeaFit,destinationIdentityFit,resolveInspiredDestination,draftPrerequisite,itineraryDays,requiredTripCandidateCount,composeAiItinerary,auditAiItinerary,travelDna,travelDnaMarkup,tripUnderstandingMarkup,tripQualityMarkup,destinationConfirmationPanel,recordDecision,restoreDecision,timeTravelMarkup,readDraft,initialState,aiSignature,profileSignature,planningProgressPanel,planningOnline,resumeAiPlanning,mountAiPlanningLifecycle};window.LuviaFirstTripComposer=Object.freeze`);
  vm.runInContext(instrumented,sandbox,{filename:'first-trip-composer.js'});
  function mount(resume=false,onComplete=null){sandbox.LuviaFirstTripComposer.mount(root,{resume,entryMode:'ai',step:'preview',onComplete:onComplete||(()=>{completed++})});return sandbox.composerTest.state();}
  const state=mount();state.data={...state.data,...clone(input),tripPreferences:{...state.data.tripPreferences,...clone(input.tripPreferences)}};
  return {sandbox,root,state,storage,requests,actions,tripCalls,ledger,mount,api:sandbox.composerTest,candidate,get completed(){return completed}};
}

(async()=>{
  let checks=0;const checked=()=>checks++;
  // Machine-readable school-holiday evidence keeps the German authority, excludes local exceptions and fails closed.
  const holidaySource=fs.readFileSync('supabase/functions/luvia-intelligence/providers/open-holidays.ts','utf8').replace(/\bexport\s+/g,'');
  const holidaySandbox={console,Date,Math,JSON,Object,Array,Map,Set,String,Number,Boolean,Error,Promise,URL,URLSearchParams,AbortController,setTimeout,clearTimeout};holidaySandbox.globalThis=holidaySandbox;vm.createContext(holidaySandbox);vm.runInContext(`${holidaySource};globalThis.holidayApi={resolveHolidayRegion,readTravelCalendarEvidence};`,holidaySandbox,{filename:'open-holidays.ts'});
  const region=holidaySandbox.holidayApi.resolveHolidayRegion({schoolRegion:'Schleswig-Holstein'});assert.equal(region.subdivisionCode,'DE-SH');assert.equal(region.countryIsoCode,'DE');checked();
  const evidence=await holidaySandbox.holidayApi.readTravelCalendarEvidence({schoolRegion:'Schleswig-Holstein',validFrom:'2027-01-01',validTo:'2027-12-31'},{retrievedAt:'2026-09-07T10:00:00.000Z',fetcher:async url=>({ok:true,status:200,json:async()=>String(url).includes('/SchoolHolidays')?[{id:'summer-sh',startDate:'2027-07-03',endDate:'2027-08-14',name:[{language:'DE',text:'Sommerferien'}],subdivisions:[{code:'DE-SH'}],tags:[]},{id:'islands-sh',startDate:'2027-06-20',endDate:'2027-06-30',name:[{language:'DE',text:'Ferien auf den Inseln'}],subdivisions:[{code:'DE-SH'}],tags:['Exception']}]:[{id:'unity-day',startDate:'2027-10-03',endDate:'2027-10-03',name:[{language:'DE',text:'Tag der Deutschen Einheit'}],nationwide:true,tags:[]}]})});
  assert.equal(evidence.status,'verified');assert.equal(evidence.evidence.filter(item=>item.kind==='school-holiday').length,1);assert.equal(evidence.evidence.filter(item=>item.kind==='public-holiday').length,1);assert.equal(evidence.evidence.some(item=>item.sourceRef==='islands-sh'),false);assert.equal(evidence.evidence[0].authority,'Kultusministerkonferenz');assert.match(evidence.evidence[0].authorityUrl,/kmk\.org/);checked();
  await assert.rejects(()=>holidaySandbox.holidayApi.readTravelCalendarEvidence({schoolRegion:'Atlantis',validFrom:'2027-01-01',validTo:'2027-12-31'},{fetcher:async()=>({ok:true,json:async()=>[]})}),error=>error.code==='CALENDAR_REGION_UNSUPPORTED');checked();
  // Selection controls keep their DOM, scroll position and focus while arrays are copied.
  const preferences=harness();await preferences.api.loadAiDayDraft(preferences.state);
  const html=preferences.root.innerHTML,oldPreferences=Object.freeze({...preferences.state.data.tripPreferences,interests:Object.freeze(['food'])});preferences.state.data.tripPreferences=oldPreferences;
  const foodButton={dataset:{ftcTripInterest:'food'},setAttribute:(key,value)=>foodButton[key]=value};preferences.root.querySelectorAll=()=>[foodButton];
  for(let i=0;i<12;i++){preferences.api.updatePreference(preferences.state,'interests','food',{multiple:true});assert.equal(foodButton['aria-pressed'],String(i%2===1));assert.equal(preferences.root.innerHTML,html);}
  assert.deepEqual(oldPreferences.interests,['food']);checked();
  preferences.api.updatePreference(preferences.state,'food','vegan',{multiple:true});preferences.api.updatePreference(preferences.state,'food','vegan',{multiple:true});assert.equal(preferences.state.data.tripPreferences.food.includes('vegan'),false);assert.deepEqual(preferences.sandbox.profile.dietaryPreferences,['vegetarian']);checked();
  preferences.api.persist(preferences.state);preferences.sandbox.LuviaFirstTripComposer.unmount();preferences.root.querySelectorAll=()=>[];const restoredPreferences=preferences.mount(true);assert.deepEqual(Array.from(restoredPreferences.data.tripPreferences.interests),['food']);checked();
  const regionExit=harness();regionExit.state.index=0;regionExit.state.data.destination={};regionExit.state.data.inspirationCompleted=false;
  regionExit.api.settledGeography(regionExit.state,{level:3,country:'DEU',region:'SH',regionName:'Schleswig-Holstein',regionCount:16});
  assert.equal(regionExit.state.index,1);assert.equal(regionExit.state.sheetCollapsed,true,'Destination search starts as a quiet pull-up sheet over the selected region');assert.equal(regionExit.state.destinationRegion,'Schleswig-Holstein');assert.match(regionExit.root.innerHTML,/Euer Reiseziel in Schleswig-Holstein/);assert.equal(regionExit.state.data.destination.placeId,'','Region geography is not a canonical Place');checked();
  const routeTest=harness();await routeTest.api.loadAiDayDraft(routeTest.state);
  const firstDay=routeTest.state.aiDraft.draft.days[0],pair=routeTest.state.draftSelections.slice(0,2);
  routeTest.state.draftSelections=pair.map((entry,i)=>({...entry,dayId:firstDay.id,date:firstDay.date,time:i?'09:40':'09:00',durationMinutes:30,action:'planned'}));routeTest.state.activeDay=firstDay.id;
  assert.equal(routeTest.api.rehearseDraft(routeTest.state)[0].status,'attention','No verified route must not be a fabricated blocking travel time');checked();
  const routeCalls=[];routeTest.sandbox.LuviaPlacesContractV1.reads.getRoute=async(from,to,options)=>{routeCalls.push({from,to,options});return {verified:true,provider:'here',durationMinutes:25,observedAt:new Date().toISOString(),geometry:{type:'LineString',coordinates:[[from.longitude,from.latitude],[to.longitude,to.latitude]]}}};
  await routeTest.api.checkDayRoutes(routeTest.state,'WALK');assert.equal(routeCalls.length,1);assert.equal(routeTest.api.rehearseDraft(routeTest.state)[0].status,'blocked');assert.equal(routeTest.api.rehearseDraft(routeTest.state)[0].raw.routes[0].baseMinutes,25);checked();
  await routeTest.api.checkDayRoutes(routeTest.state,'WALK');assert.equal(routeCalls.length,1,'Repeated checks reuse still-current Place route evidence');checked();
  const extra={...routeTest.state.draftSelections[1],slotId:'third',providerPlaceId:'third',time:'15:00',coordinates:{latitude:54.04,longitude:10.75}};routeTest.state.draftSelections.push(extra);assert.equal(routeTest.api.rehearseDraft(routeTest.state)[0].status,'blocked','A known impossible transfer remains blocking even when another leg is unknown');routeTest.state.draftSelections.pop();checked();
  await routeTest.api.checkDayRoutes(routeTest.state,'BICYCLE');assert.equal(routeCalls.length,2);assert.equal(routeCalls[1].options.mode,'BICYCLE');assert.match(routeTest.api.routeReviewPanel(routeTest.state),/25 Min. Radweg/);checked();
  routeTest.state.draftSelections[1].time='11:00';assert.equal(routeTest.api.rehearseDraft(routeTest.state)[0].status,'ready');assert.match(routeTest.api.routeReviewPanel(routeTest.state),/Kostensumme liegt noch nicht vor/);checked();
  routeTest.state.routeChecks={};routeTest.sandbox.LuviaPlacesContractV1.reads.getRoute=async()=>({verified:false,durationMinutes:1});await routeTest.api.checkDayRoutes(routeTest.state);assert.equal(Object.keys(routeTest.state.routeChecks).length,0);assert.equal(routeTest.api.rehearseDraft(routeTest.state)[0].status,'attention');checked();
  let finishRoute;routeTest.sandbox.LuviaPlacesContractV1.reads.getRoute=(from,to)=>new Promise(resolve=>{finishRoute=()=>resolve({verified:true,provider:'here',durationMinutes:12,observedAt:new Date().toISOString(),geometry:{type:'LineString',coordinates:[[from.longitude,from.latitude],[to.longitude,to.latitude]]}})});
  const waiting=routeTest.api.checkDayRoutes(routeTest.state);routeTest.state.draftSelections[1].time='12:00';finishRoute();await waiting;assert.equal(Object.keys(routeTest.state.routeChecks).length,0,'A stale result cannot publish after the day changed');checked();
  const outOfOrder=routeTest.state.draftSelections;routeTest.state.draftSelections=[outOfOrder[1],outOfOrder[0]];routeTest.state.filmSlot=null;assert.equal(routeTest.api.filmFrame(routeTest.state).entry.time,'09:00');checked();
  const h=harness(),core=h.sandbox.LuviaTripDraftCoreV1;
  for(const patch of [{startDate:''},{endDate:''},{startDate:'2027-02-30'},{endDate:'2027-06-01'}])assert.equal(core.validateDraft({...input,...patch}).valid,false);checked();
  assert.equal(core.validateDraft({...input,scheduleMode:'flexible',startDate:'',endDate:''}).valid,true);checked();
  assert.equal(core.composeDayDraft(input,{places:[{...h.candidate('food',1),coordinates:{latitude:null,longitude:null}}]}).candidateCount,0);checked();
  await h.api.loadAiDayDraft(h.state);assert.equal(h.state.aiDraft.status,'ready');assert.equal(h.state.draftSelections.length,10);assert.equal(h.state.aiDraft.draft.days[0].entries[0].category,'food');assert.equal(h.state.aiDraft.draft.days[0].entries[1].category,'culture');checked();
  assert.ok(h.requests.every(request=>request.requirePreferenceEvidence&&request.subjectText===''&&request.providers[0]==='auto'));checked();
  const first=h.state.draftSelections[0],originalId=first.providerPlaceId;
  h.api.swapDraftSelection(h.state,first.slotId);assert.notEqual(h.state.draftSelections[0].providerPlaceId,originalId);
  const swappedId=h.state.draftSelections[0].providerPlaceId;
  h.api.setDraftAction(h.state,first.slotId,'saved');h.api.setDraftAction(h.state,h.state.draftSelections[1].slotId,'excluded');assert.equal(h.state.aiDraft.rehearsals[0].status,'attention','the fuller day retains its remaining moments after two decisions');checked();
  h.state.draftSelections[2].time='11:00';h.state.draftSelections[2].durationMinutes=135;h.api.refreshDraft(h.state);
  h.sandbox.LuviaFirstTripComposer.unmount();const restored=h.mount(true);assert.equal(restored.draftSelections[0].providerPlaceId,swappedId);assert.equal(restored.draftSelections[0].action,'saved');assert.equal(restored.draftSelections[1].action,'excluded');assert.equal(restored.draftSelections[2].time,'11:00');assert.equal(restored.draftSelections[2].durationMinutes,135);checked();
  // Stop after two writes. Re-mount from stored state and retry through the real receipt/input contracts.
  let failed=false;h.sandbox.executeOverride=(item,count)=>{if(count===3&&!failed){failed=true;return h.sandbox.LuviaIntelligenceActionContractCoreV1.createReceipt({actionId:item.actionId,status:'failed',ownerCommand:true})}};
  await h.api.save(restored);assert.equal(h.completed,0);assert.equal(h.tripCalls.length,1,restored.error);assert.equal(Object.keys(restored.confirmation.actionReceipts).length,2,restored.error);checked();
  h.sandbox.LuviaFirstTripComposer.unmount();const retry=h.mount(true);assert.equal(retry.index,5);const locked=retry.draftSelections[0].action;h.api.setDraftAction(retry,retry.draftSelections[0].slotId,'excluded');assert.equal(retry.draftSelections[0].action,locked);checked();
  await Promise.all([h.api.save(retry),h.api.save(retry)]);assert.equal(h.completed,1);assert.equal(h.tripCalls.length,1);assert.equal(h.actions.length,10);assert.equal(h.actions.filter(item=>item.payload.providerPlaceId===swappedId).length,1);assert.ok(h.actions.filter(item=>item.actionId==='places.place.plan').every(item=>item.payload.fields.metadata.durationMinutes>0));checked();
  assert.equal(h.storage.size,0);checked();
  // An unknown response is never success and never blindly retried.
  const unknown=harness();await unknown.api.loadAiDayDraft(unknown.state);unknown.sandbox.executeOverride=()=>null;await unknown.api.save(unknown.state);assert.equal(unknown.completed,0);assert.equal(unknown.state.confirmation.status,'pending');await unknown.api.save(unknown.state);assert.equal(unknown.actions.length,1);assert.match(unknown.state.error,/ohne.*doppelt|nicht erneut/);checked();
  unknown.sandbox.executeOverride=null;unknown.sandbox.reconcileOverride=(actionId,payload,options)=>unknown.sandbox.LuviaIntelligenceActionContractCoreV1.createReceipt({actionId,status:'completed',ownerCommand:true,ledgerId:options.ledgerId,idempotencyKey:options.idempotencyKey,reference:{tripId:payload.tripId,providerPlaceId:payload.providerPlaceId,readbackVerified:true}});await unknown.api.save(unknown.state);assert.equal(unknown.completed,1);assert.equal(unknown.actions.filter(item=>item.payload.providerPlaceId===unknown.state.draftSelections[0].providerPlaceId).length,1);checked();
  // A navigation error after successful persistence must not be presented as a mutation failure.
  const navigation=harness();await navigation.api.loadAiDayDraft(navigation.state);navigation.state.options.onComplete=()=>{throw Error('navigation')};await navigation.api.save(navigation.state);assert.equal(navigation.state.confirmation.status,'complete');assert.match(navigation.state.error,/sind gespeichert/);const count=navigation.actions.length;navigation.state.options.onComplete=()=>{};await navigation.api.save(navigation.state);assert.equal(navigation.actions.length,count);assert.equal(navigation.tripCalls.length,1);checked();
  // Invalid, stale or unreviewed inputs block before creating any trip.
  const invalid=harness();await invalid.api.loadAiDayDraft(invalid.state);invalid.state.data.endDate='';await invalid.api.save(invalid.state);assert.equal(invalid.tripCalls.length,0);checked();
  invalid.state.data.endDate=input.endDate;invalid.state.data.requestBrief='changed';await invalid.api.save(invalid.state);assert.equal(invalid.tripCalls.length,0);checked();
  invalid.state.data.requestBrief='';invalid.sandbox.profile={dietaryPreferences:['vegan']};await invalid.api.save(invalid.state);assert.equal(invalid.tripCalls.length,0);checked();
  const overlap=harness();await overlap.api.loadAiDayDraft(overlap.state);overlap.state.draftSelections[1].time='10:15';overlap.api.refreshDraft(overlap.state);await overlap.api.save(overlap.state);assert.equal(overlap.tripCalls.length,0);assert.match(overlap.state.error,/Überschneidungen/);checked();
  const noStorage=harness();await noStorage.api.loadAiDayDraft(noStorage.state);noStorage.sandbox.failStorage=true;await noStorage.api.save(noStorage.state);assert.equal(noStorage.tripCalls.length,0);assert.match(noStorage.state.error,/Speicherzugriff/);checked();
  // All selected categories survive, including more than the former first three.
  const categories=harness();categories.state.data.tripPreferences.interests=['food','culture','nature','shopping','nightlife','wellness','active','family'];await categories.api.readAiPlaces(categories.state);assert.equal(new Set(categories.requests.map(item=>item.category)).size,7);checked();
  const focusedRecovery=harness();focusedRecovery.state.data.tripPreferences.interests=['food'];let foodReads=0;focusedRecovery.sandbox.recommend=async options=>{foodReads++;return {places:options.refresh?[focusedRecovery.candidate('food',1),focusedRecovery.candidate('food',2)]:[]}};const recoveredPlaces=await focusedRecovery.api.readAiPlaces(focusedRecovery.state);assert.equal(foodReads,2);assert.equal(focusedRecovery.requests[1].refresh,true);assert.match(focusedRecovery.requests[1].subjectText,/vegetarian/);assert.equal(recoveredPlaces.coverage[0].status,'ready');assert.equal(recoveredPlaces.places.length,2);checked();
  const cache=harness();cache.state.data.tripPreferences.interests=['food'];cache.sandbox.cached={category:'food',places:Array.from({length:8},(_,index)=>({...cache.candidate('food',index+1),profileFit:{state:'matched'}}))};const cachedPlaces=await cache.api.readAiPlaces(cache.state);assert.equal(cache.requests.length,0);assert.equal(cachedPlaces.places.length,8);checked();
  const single=harness();single.sandbox.recommend=async options=>({places:options.category==='food'?[single.candidate('food',1)]:[]});await single.api.loadAiDayDraft(single.state);assert.equal(single.state.aiDraft.status,'error');assert.match(single.state.aiDraft.error,/erst 1 unterschiedliche Orte/);assert.equal(single.state.draftSelections.length,0,'A thin provider result must not be disguised as a complete trip');checked();
  const countRefill=harness();countRefill.state.data.endDate='2027-06-18';countRefill.sandbox.recommend=async options=>({places:(options.refresh?[101,102,103]:[1,2,3,4,5,6]).map(index=>countRefill.candidate(options.category,index))});assert.equal(countRefill.api.requiredTripCandidateCount(countRefill.state),19);await countRefill.api.loadAiDayDraft(countRefill.state);assert.equal(countRefill.state.aiDraft.status,'ready',countRefill.state.aiDraft.error||'A long trip must top up a nearly sufficient Places catalog before composition');const supplemental=countRefill.requests.filter(item=>item.refresh);assert.equal(supplemental.length,2,'Only the two least represented requested categories receive the bounded count refill');assert.equal(countRefill.sandbox.modelCalls.find(item=>item.capability==='trip.compose').request.candidateCatalog.length,24);checked();
  const stale=harness();let resolve;stale.sandbox.recommend=()=>new Promise(done=>{resolve=done});stale.state.data.tripPreferences.interests=['food'];const pending=stale.api.loadAiDayDraft(stale.state);await new Promise(done=>setTimeout(done,0));stale.sandbox.LuviaFirstTripComposer.unmount();const markup=stale.root.innerHTML;resolve({places:[stale.candidate('food',1)]});await pending;assert.equal(stale.root.innerHTML,markup);checked();
  const account=harness();await account.api.loadAiDayDraft(account.state);const create=account.sandbox.LuviaTripContractV1.commands.createFirstTrip;account.sandbox.LuviaTripContractV1.commands.createFirstTrip=async(...args)=>{const receipt=await create(...args);account.sandbox.viewer='another-viewer';return receipt};await account.api.save(account.state);assert.equal(account.actions.length,0);assert.equal(account.completed,0);assert.ok([...account.storage.keys()].every(key=>key.endsWith(':composer-test')));checked();
  const leaving=harness();await leaving.api.loadAiDayDraft(leaving.state);const beforeLeave=leaving.sandbox.LuviaTripContractV1.commands.createFirstTrip;leaving.sandbox.LuviaTripContractV1.commands.createFirstTrip=async(...args)=>{const receipt=await beforeLeave(...args);leaving.sandbox.LuviaFirstTripComposer.unmount();return receipt};await leaving.api.save(leaving.state);assert.equal(leaving.completed,0);assert.equal(leaving.state.confirmation.status,'complete');assert.equal(leaving.root.innerHTML,'');checked();
  // Actual public Intelligence adapter + browserless owner, with controlled model response.
  const intelligent=harness();intelligent.state.data.requestBrief='Vegan essen, Kultur und entspannte Tage ab zwölf.';
  await intelligent.api.loadAiDayDraft(intelligent.state);assert.equal(intelligent.state.aiDraft.status,'ready');assert.ok(intelligent.requests.length>0);assert.equal(intelligent.sandbox.modelCalls[0].capability,'planning.dialogue');assert.equal(intelligent.sandbox.modelCalls[0].options.fallback,false);assert.ok(intelligent.requests.every(item=>item.preferences.dietaryPreferences.includes('vegetarian')&&item.preferences.dietaryPreferences.includes('vegan')));checked();
  intelligent.api.persist(intelligent.state);intelligent.sandbox.LuviaFirstTripComposer.unmount();const briefReload=intelligent.mount(true);assert.equal(briefReload.aiDraft.status,'ready');assert.equal(briefReload.aiDraft.brief.source,'ai');checked();
  assert.equal(intelligent.sandbox.modelCalls.length,3);assert.deepEqual(intelligent.sandbox.modelCalls.map(item=>item.capability),['planning.dialogue','trip.compose','trip.audit']);assert.equal(intelligent.sandbox.modelCalls[1].options.tier,'fast','The first full draft uses Luna behind the unchanged strict contract');assert.equal(intelligent.sandbox.modelCalls[2].options.tier,'default','An independent Terra pass audits every Luna draft');assert.ok(briefReload.draftSelections.every(item=>item.time>='12:00'));assert.ok(briefReload.aiDraft.draft.days.every(day=>day.entries.length<=3));assert.equal(briefReload.aiDraft.draft.planningSource,'ai');assert.equal(briefReload.aiDraft.audit.readyForReview,true);checked();
  await intelligent.api.save(briefReload);assert.equal(intelligent.tripCalls[0].tripPreferences.pace,'slow');assert.equal(intelligent.completed,1);checked();
  const unsafe=harness();unsafe.state.data.requestBrief='Maximal 50 Euro am Tag';unsafe.sandbox.dialogue={understanding:'Maximal 50 Euro',goals:[{type:'food',label:'Essen'}],hardConstraints:[{key:'dailyBudget',value:'50 EUR',label:'50 Euro pro Tag'}],softPreferences:[],unknowns:[]};await unsafe.api.loadAiDayDraft(unsafe.state);assert.equal(unsafe.state.aiDraft.brief.automaticPlanningAllowed,false);assert.equal(unsafe.state.aiDraft.status,'error');assert.equal(unsafe.state.draftSelections.length,0,'An unverified hard requirement must stop the automatic plan before Places research');checked();
  const failedAI=harness();failedAI.state.data.requestBrief='Viel Neugier';failedAI.sandbox.modelOverride=()=>({ok:true,data:{goals:[]},meta:{fallback:true}});await failedAI.api.loadAiDayDraft(failedAI.state);assert.equal(failedAI.state.aiDraft.status,'error');assert.equal(failedAI.requests.length,0);checked();
  const unavailable=harness();unavailable.state.data.requestBrief='Viel Neugier';unavailable.sandbox.modelOverride=()=>{throw Error('KI nicht erreichbar')};await unavailable.api.loadAiDayDraft(unavailable.state);assert.equal(unavailable.state.aiDraft.status,'error');assert.equal(unavailable.requests.length,0);checked();
  const throttled=harness();throttled.state.data.requestBrief='Kultur am Nachmittag';throttled.sandbox.modelOverride=()=>{throw Object.assign(Error('Edge Function returned a non-2xx status code'),{code:'AI_RATE_LIMITED'})};await throttled.api.loadAiDayDraft(throttled.state);assert.equal(throttled.state.aiDraft.status,'error');assert.match(throttled.state.aiDraft.error,/keine weiteren Anfragen/);assert.doesNotMatch(throttled.root.innerHTML,/non-2xx/);assert.equal(throttled.requests.length,0);assert.equal(throttled.tripCalls.length,0);throttled.api.render(throttled.state);assert.equal(throttled.state.aiDraft.status,'error','An unchanged rejection must not retry in a render loop');checked();
  throttled.state.data.requestBrief='';throttled.api.render(throttled.state);assert.equal(throttled.state.aiDraft.status,'idle','Changed input must invalidate an old rejection');await throttled.api.loadAiDayDraft(throttled.state);assert.equal(throttled.state.aiDraft.status,'ready');assert.ok(throttled.requests.length>0);assert.equal(throttled.sandbox.modelCalls.length,3,'Explicit chip-only input skips dialogue but still uses composition and the independent audit');assert.deepEqual(throttled.sandbox.modelCalls.slice(1).map(item=>item.capability),['trip.compose','trip.audit']);checked();
  const question=harness();question.state.data.requestBrief='Nicht zu früh';question.sandbox.dialogue={understanding:'Nicht früh starten',goals:[{type:'culture',label:'Kultur'}],hardConstraints:[],softPreferences:[],followUpQuestion:{text:'Ab welcher Uhrzeit?',reason:'Für den Tagesbeginn.'},unknowns:[]};await question.api.loadAiDayDraft(question.state);assert.equal(question.state.aiDraft.brief.question.text,'Ab welcher Uhrzeit?');assert.equal(question.requests.length,0);checked();
  const movement=harness();movement.state.data.requestBrief='Sieben Tage Valencia mit Kultur und gutem Essen.';movement.sandbox.dialogue={understanding:'Sieben Tage Valencia mit Kultur und gutem Essen.',goals:[{type:'culture',label:'Kultur'},{type:'food',label:'Gutes Essen'}],hardConstraints:[],softPreferences:[],conflictAssessment:{status:'none',summary:'Keine wesentliche Spannung.',tensions:[]},followUpQuestion:null,unknowns:[],confidence:.95};await movement.api.loadAiDayDraft(movement.state);assert.equal(movement.state.aiDraft.status,'brief-ready');assert.equal(movement.state.aiDraft.brief.question.id,'movement-scope');assert.deepEqual([...movement.state.aiDraft.brief.question.options].map(item=>item.value),['near_walk','city_transit','wide_taxi_car']);assert.equal(movement.requests.length,0,'The complete AI plan must ask for an unknown high-impact movement scope before Places research');assert.match(movement.api.briefReviewPanel(movement.state),/LUVIA.?S REISEAUFTRAG|LUVIAS REISEAUFTRAG/);assert.match(movement.api.briefReviewPanel(movement.state),/Stadt mit Bus &amp; Bahn|Stadt mit Bus & Bahn/);checked();
  const conflict=harness();conflict.state.data.requestBrief='Direkt am ruhigen Strand wohnen und jede Nacht mitten im Nachtleben sein.';conflict.sandbox.dialogue={understanding:'Ruhiger Strand und tägliches Nachtleben sind beide wichtig.',goals:[{type:'water',label:'Ruhiger Strand'},{type:'nightlife',label:'Tägliches Nachtleben'}],hardConstraints:[],softPreferences:[{key:'movementStyle',value:'city_transit',label:'Bus und Bahn sind in Ordnung'}],conflictAssessment:{status:'tradeoff',summary:'Die beiden Schwerpunkte liegen in unterschiedlichen Lagen.',tensions:[{id:'beach-nightlife',label:'Welche Lage soll den Alltag bestimmen?',reason:'Strandnähe und tägliches Nachtleben passen in diesen Zielgebieten nicht gleichzeitig gleich gut.',decisionNeeded:true,variants:[{id:'beach-first',label:'Strand zuerst',preserves:'ruhige Strandnähe',relaxes:'spontane Nachtwege',effect:'Abends entsteht eine längere Rückfahrt.'},{id:'nightlife-first',label:'Abende zuerst',preserves:'kurze Wege zum Nachtleben',relaxes:'direkte Strandlage',effect:'Strandtage werden mit Bus oder Bahn erreicht.'}]}]},followUpQuestion:null,unknowns:[],confidence:.96};await conflict.api.loadAiDayDraft(conflict.state);assert.equal(conflict.state.aiDraft.status,'brief-ready');assert.match(conflict.state.aiDraft.brief.question.id,/semantic-conflict/);assert.equal(conflict.state.aiDraft.brief.question.options.length,2);assert.equal(conflict.requests.length,0);const conflictMarkup=conflict.api.briefReviewPanel(conflict.state);assert.match(conflictMarkup,/Strand zuerst/);assert.match(conflictMarkup,/Abende zuerst/);assert.match(conflictMarkup,/verschweigt den Zielkonflikt nicht/);checked();
  const transitBrief=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...input,profilePreferences:h.sandbox.profile},{ok:true,meta:{fallback:false},data:{understanding:'Valencia mit Bus und Bahn entdecken.',goals:[{type:'water',label:'Ans Meer'}],hardConstraints:[{key:'category',value:'water',label:'Strand und Meer'}],softPreferences:[{key:'movementStyle',value:'city_transit',label:'Bus und Bahn'}],conflictAssessment:{status:'none',summary:'Keine wesentliche Spannung.',tensions:[]},followUpQuestion:null,unknowns:[],confidence:.96}});assert.equal(transitBrief.question,null);assert.equal(transitBrief.travelOrder.geography.dayTripRadiusKm,20);assert.equal(transitBrief.travelOrder.geography.maximumTransferMinutes,45);assert.equal(transitBrief.travelOrder.geography.minimumDistinctAreas,3);assert.equal(transitBrief.travelOrder.categories.find(item=>item.category==='water').importance,'required');assert.equal(transitBrief.travelOrder.rhythm.freeTimePercent,20);assert.equal(transitBrief.travelOrder.rhythm.maximumConsecutiveIntenseDays,2);assert.equal(transitBrief.travelOrder.geography.baseStrategy,'single_base');assert.equal(transitBrief.planningAssumptions.find(item=>item.id==='free-time').source,'luvia-default');assert.ok(transitBrief.deferredChecks.includes('Einreisebedingungen'));assert.ok(transitBrief.deferredChecks.includes('aktuelle Verkehrsverbindungen'));checked();
  const holiday=harness();holiday.state.data.requestBrief='Mit zwei Schulkindern für zwei Nächte in den Sommerferien Schleswig-Holstein ans Meer.';holiday.sandbox.dialogue={understanding:'Zwei Erwachsene reisen mit zwei Schulkindern für zwei Nächte in den Sommerferien Schleswig-Holstein ans Meer.',goals:[{type:'water',label:'Zeit am Meer'}],hardConstraints:[{key:'children',value:'2',label:'Zwei Schulkinder'},{key:'schoolHolidayRequired',value:'true',label:'Nur in den Schulferien'},{key:'schoolHolidayRegion',value:'Schleswig-Holstein',label:'Schulferien Schleswig-Holstein'},{key:'durationNights',value:'2',label:'Zwei Nächte'}],softPreferences:[{key:'season',value:'summer',label:'Im Sommer'},{key:'movementStyle',value:'city_transit',label:'Mit Bus und Bahn'}],unknowns:[],confidence:.97};holiday.sandbox.calendarOverride=()=>({ok:true,data:{owner:'intelligence',contractId:'intelligence.v1',kind:'travel-calendar-evidence',status:'verified',region:{countryIsoCode:'DE',subdivisionCode:'DE-SH',name:'Schleswig-Holstein'},evidence:[{id:'openholidays:school-holiday:summer-sh',kind:'school-holiday',region:'Schleswig-Holstein',countryIsoCode:'DE',subdivisionCode:'DE-SH',name:'Sommerferien',startDate:'2027-07-03',endDate:'2027-08-14',verified:true,status:'verified',source:'OpenHolidays API',sourceUrl:'https://openholidaysapi.org/SchoolHolidays?countryIsoCode=DE',authority:'Kultusministerkonferenz',authorityUrl:'https://www.kmk.org/service/ferienregelung/ferienkalender.html',retrievedAt:'2026-09-07T10:00:00.000Z'}]}});await holiday.api.loadAiDayDraft(holiday.state);assert.equal(holiday.state.aiDraft.status,'brief-ready');assert.equal(holiday.calendarCalls?.length||holiday.sandbox.calendarCalls.length,1);assert.equal(holiday.sandbox.calendarCalls[0].action,'calendar.travel-evidence');assert.equal(holiday.sandbox.calendarCalls[0].payload.subdivisionCode,undefined);assert.equal(holiday.sandbox.calendarCalls[0].payload.schoolRegion,'Schleswig-Holstein');assert.equal(holiday.requests.length,0,'Places research must wait until the verified travel window is selected');assert.equal(holiday.state.aiDraft.brief.question.id,'school-holiday-period');const windowChoice=holiday.state.aiDraft.brief.travelOrder.time.suggestedWindows[0];assert.equal(windowChoice.startDate,'2027-07-03');assert.equal(windowChoice.endDate,'2027-07-05');assert.equal(windowChoice.durationNights,2);const holidayMarkup=holiday.api.briefReviewPanel(holiday.state);assert.match(holidayMarkup,/Sommerferien/);assert.match(holidayMarkup,/Kultusministerkonferenz/);assert.match(holidayMarkup,/Quelle öffnen/);assert.doesNotMatch(holidayMarkup,/textarea/);checked();
  assert.equal(await holiday.api.chooseHolidayWindow(holiday.state,windowChoice.id),true);assert.equal(holiday.state.data.startDate,'2027-07-03');assert.equal(holiday.state.data.endDate,'2027-07-05');assert.equal(holiday.state.aiDraft.status,'ready');assert.equal(holiday.sandbox.calendarCalls.length,1,'Verified evidence is reused during the same draft instead of fetched again');assert.ok(holiday.requests.length>0);holiday.api.persist(holiday.state);holiday.sandbox.LuviaFirstTripComposer.unmount();const holidayReload=holiday.mount(true);assert.equal(holidayReload.calendarEvidence[0].source,'OpenHolidays API');assert.equal(holidayReload.data.startDate,'2027-07-03');checked();
  const dates=core.composeDayDraft({...input,endDate:'2027-06-25'},{places:[1,2,3,4,5].map(i=>h.candidate('culture',i))});assert.equal(dates.days.length,14);assert.equal(dates.days.at(-1).date,'2027-06-25');assert.equal(dates.coverage.freeDays,9);assert.equal(new Set(dates.days.flatMap(day=>day.entries).map(item=>item.providerPlaceId)).size,5);checked();
  assert.throws(()=>core.composeDayDraft({...input,startDate:'2027-01-01',endDate:'2028-01-02'},{places:[]}),/366/);checked();
  const leap=core.composeDayDraft({...input,startDate:'2028-02-28',endDate:'2028-03-01'},{places:[]});assert.equal(leap.days.length,3);assert.equal(leap.days[1].date,'2028-02-29');checked();
  const moved=harness();await moved.api.loadAiDayDraft(moved.state);const movedItem=moved.state.draftSelections[0];movedItem.date=input.endDate;movedItem.dayId='day-3';movedItem.time='21:00';moved.api.refreshDraft(moved.state);assert.match(moved.state.aiDraft.rehearsals[0].summary,/3 Reisemomente/);assert.match(moved.state.aiDraft.rehearsals[2].summary,/4 Reisemomente/);checked();
  const strict=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...input,profilePreferences:h.sandbox.profile},{ok:true,meta:{fallback:false},data:{goals:[],hardConstraints:[{key:'maximumPerDay',value:'1',label:'Höchstens ein Ort'}],softPreferences:[{key:'pace',value:'active',label:'Viel entdecken'}]}});assert.equal(strict.policy.maximumPerDay,1);checked();
  const semanticResponse={ok:true,meta:{fallback:false},data:{understanding:'Zwei Erwachsene und zwei Schulkinder möchten in den Sommerferien ans Wasser, Kultur erleben, shoppen und abends einmal ausgehen.',goals:[{type:'water',label:'Zeit am Wasser'},{type:'culture',label:'Kultur erleben'},{type:'shopping',label:'Lokale Läden'},{type:'nightlife',label:'Ein besonderer Abend'}],hardConstraints:[{key:'adults',value:'2',label:'Zwei Erwachsene'},{key:'children',value:'2',label:'Zwei Kinder'},{key:'childAges',value:'7,10',label:'Kinder sind 7 und 10'},{key:'schoolHolidayRequired',value:'true',label:'Nur in den Schulferien'},{key:'schoolHolidayRegion',value:'Schleswig-Holstein',label:'Schulferien Schleswig-Holstein'},{key:'dietary',value:'vegan',label:'Veganes Essen'}],softPreferences:[{key:'accommodation',value:'Ferienwohnung am Meer',label:'Ferienwohnung am Meer'},{key:'transport',value:'Bahn',label:'Anreise mit der Bahn'},{key:'arrivalTime',value:'16:30',label:'Ankunft um 16:30 Uhr'},{key:'departureTime',value:'11:00',label:'Abreise um 11 Uhr'},{key:'arrivalRecoveryMinutes',value:'75',label:'Nach Ankunft erst ankommen'},{key:'maximumTransferMinutes',value:'35',label:'Kurze Wege'},{key:'weatherFallback',value:'true',label:'Schlechtwetter-Plan'},{key:'planBPerDay',value:'true',label:'Plan B pro Tag'},{key:'dailyBudget',value:'180 EUR',label:'Etwa 180 Euro am Tag'},{key:'reservationStyle',value:'Nur Wichtiges vorab',label:'Nur Wichtiges reservieren'},{key:'groupDecisionMode',value:'abwechselnd',label:'Wünsche abwechseln'},{key:'fairnessRequired',value:'true',label:'Alle kommen vor'},{key:'evidenceFreshness',value:'live vor Nutzung',label:'Fakten aktuell prüfen'},{key:'recheckBeforeDays',value:'2',label:'Zwei Tage vorher prüfen'},{key:'mustDo',value:'kindgerechter Strandtag',label:'Ein kindgerechter Strandtag'},{key:'freeTimePercent',value:'30',label:'Genug Freiraum'}],unknowns:[],confidence:.96}};
  const semantic=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...input,profilePreferences:h.sandbox.profile,calendarEvidence:[{id:'holiday-sh-2027',kind:'school-holiday',region:'Schleswig-Holstein',startDate:'2027-06-01',endDate:'2027-08-31',verified:true,source:'controlled-calendar'}]},semanticResponse);assert.equal(semantic.travelOrder.travelers.children,2);assert.deepEqual([...semantic.travelOrder.travelers.childAges],[7,10]);assert.equal(semantic.travelOrder.travelers.schoolHolidayRegion,'Schleswig-Holstein');assert.deepEqual([...semantic.travelOrder.travelers.holidayEvidenceIds],['holiday-sh-2027']);assert.ok(['water','culture','shopping','nightlife'].every(category=>semantic.travelOrder.categories.some(item=>item.category===category)));assert.equal(semantic.travelOrder.accommodation[0],'Ferienwohnung am Meer');assert.equal(semantic.travelOrder.transport[0],'Anreise mit der Bahn');assert.equal(semantic.travelOrder.logistics.arrival.localTime,'16:30');assert.equal(semantic.travelOrder.logistics.departure.localTime,'11:00');assert.equal(semantic.travelOrder.logistics.arrival.recoveryMinutes,75);assert.equal(semantic.travelOrder.geography.maximumTransferMinutes,35);assert.equal(semantic.travelOrder.contingency.weatherFallback,true);assert.equal(semantic.travelOrder.contingency.planBPerDay,true);assert.equal(semantic.travelOrder.budget.dailyTotal,'180 EUR');assert.equal(semantic.travelOrder.booking.reservationStyle,'Nur Wichtiges vorab');assert.equal(semantic.travelOrder.group.decisionMode,'abwechselnd');assert.equal(semantic.travelOrder.group.fairnessRequired,true);assert.equal(semantic.travelOrder.evidencePolicy.freshness,'live vor Nutzung');assert.equal(semantic.travelOrder.evidencePolicy.recheckBeforeDays,2);assert.equal(semantic.travelOrder.mustDo[0],'Ein kindgerechter Strandtag');assert.equal(semantic.automaticPlanningAllowed,true);checked();
  const missingHolidayEvidence=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...input,profilePreferences:h.sandbox.profile},semanticResponse);assert.equal(missingHolidayEvidence.automaticPlanningAllowed,false);assert.ok(missingHolidayEvidence.unresolved.some(item=>/Kalenderquelle/.test(item.label)));checked();
  const mismatchedHolidayEvidence=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...input,startDate:'2027-10-07',endDate:'2027-10-14',profilePreferences:h.sandbox.profile,calendarEvidence:[{id:'holiday-sh-2027',kind:'school-holiday',region:'Schleswig-Holstein',startDate:'2027-06-01',endDate:'2027-08-31',verified:true,source:'controlled-calendar'}]},semanticResponse);assert.equal(mismatchedHolidayEvidence.automaticPlanningAllowed,false);assert.match(mismatchedHolidayEvidence.unresolved.find(item=>item.hard)?.label,/liegt nicht vollständig/);assert.match(mismatchedHolidayEvidence.question.text,/bestätigte.*Ferienzeitraum|passenden Zeitraum/);checked();
  const monthWish=harness();monthWish.state.index=2;monthWish.state.data={...monthWish.state.data,...clone(input),startDate:'',endDate:'',requestBrief:'Wir möchten ans Meer, im Juni 2027 für sieben Tage ins Ausland, ohne langen Flug. Shopping, Nachtleben und Restaurants. Wir fliegen von Münster.'};monthWish.sandbox.dialogue={understanding:'Sieben Tage im Juni 2027 ab Münster ans Meer im Ausland, mit kurzen Flügen, Shopping, Nachtleben und Restaurants.',goals:[{type:'water',label:'Ans Meer',timeWindow:{label:'Juni 2027',start:'2027-06-01',end:'2027-06-30',flexible:true}},{type:'shopping',label:'Shopping'},{type:'nightlife',label:'Nachtleben'},{type:'food',label:'Restaurants'}],hardConstraints:[{key:'month',value:'Juni',label:'Im Juni'},{key:'year',value:'2027',label:'Im Jahr 2027'},{key:'durationDays',value:'7',label:'Sieben Tage'},{key:'countryPreference',value:'Ausland',label:'Ins Ausland'},{key:'departureOrigin',value:'Münster',label:'Abflug ab Münster'},{key:'flightPreference',value:'short',label:'Keine langen Flüge'}],softPreferences:[{key:'movementStyle',value:'city_transit',label:'Mit Bus und Bahn'}],followUpQuestion:null,unknowns:[],confidence:.97};await monthWish.api.prepareAiBrief(monthWish.state);assert.equal(monthWish.state.aiDraft.status,'brief-ready');assert.equal(monthWish.state.aiDraft.brief.question.id,'requested-travel-period');assert.equal(monthWish.state.aiDraft.brief.travelOrder.time.suggestedWindows.length,3);assert.ok(monthWish.state.aiDraft.brief.travelOrder.time.suggestedWindows.every(item=>item.durationNights===6),'A flexible whole-month model window must not override the stated seven-day duration');assert.equal(monthWish.state.aiDraft.brief.travelOrder.logistics.origin,'Münster');assert.equal(monthWish.state.aiDraft.brief.travelOrder.logistics.flightPreference,'short');assert.match(monthWish.api.travelWindowChoicesMarkup(monthWish.state),/Anfang Juni|Mitte Juni|Ende Juni/);const juneChoice=monthWish.state.aiDraft.brief.travelOrder.time.suggestedWindows[1];assert.equal(juneChoice.durationNights,6);assert.equal(await monthWish.api.chooseHolidayWindow(monthWish.state,juneChoice.id),true);assert.equal(monthWish.state.aiDraft.status,'ready');assert.equal(monthWish.sandbox.modelCalls.filter(call=>call.capability==='planning.dialogue').length,1,'The initial wish must not be interpreted again after choosing a window');assert.equal(monthWish.state.aiDraft.draft.days.length,7);checked();
  const confirmedWeek=h.sandbox.LuviaTripPreferenceResolutionCoreV1.projectTripBrief({...input,startDate:'2027-06-12',endDate:'2027-06-18',profilePreferences:h.sandbox.profile},{ok:true,meta:{fallback:false},data:{understanding:'Sieben Tage im Juni. Die angegebenen Reisedaten umfassen sechs Kalendertage, während ihr sieben Tage genannt habt.',goals:[{type:'water',label:'Ans Meer'}],hardConstraints:[{key:'durationDays',value:'7',label:'Sieben Tage'},{key:'budgetLevel',value:'open',label:'Budget offen'}],softPreferences:[{key:'movementStyle',value:'city_transit',label:'Mit Bus und Bahn'}],followUpQuestion:{text:'Meint ihr sieben Kalendertage oder sieben Übernachtungen? Die festen Daten 12.–18. Juni umfassen sechs Kalendertage.',reason:'Die genannte Reisedauer scheint dem bestätigten Zeitraum zu widersprechen.'},unknowns:[],confidence:.97}});assert.equal(confirmedWeek.travelOrder.time.durationNights,6);assert.equal(confirmedWeek.question,null,'A model may not reopen a duration conflict when confirmed inclusive dates exactly match the requested travel days');assert.match(confirmedWeek.understanding,/7 Kalendertage und 6 Übernachtungen/);assert.doesNotMatch(confirmedWeek.understanding,/umfassen sechs Kalendertage/);assert.equal(confirmedWeek.tripPreferences.budgetLevel,'open');assert.equal(confirmedWeek.automaticPlanningAllowed,true,'An open budget explicitly means that no hard budget boundary is missing');checked();
  const shiftedWeek=h.sandbox.LuviaTripPreferenceResolutionCoreV1.confirmTripBriefWindow({...clone(confirmedWeek),understanding:'Valencia vom 12. bis 18. Juni 2027, sieben Tage am Meer.'},{startDate:'2027-06-14',endDate:'2027-06-20',destinationName:'Valencia'});assert.equal(shiftedWeek.travelOrder.time.confirmedStart,'2027-06-14');assert.equal(shiftedWeek.travelOrder.time.confirmedEnd,'2027-06-20');assert.equal(shiftedWeek.travelOrder.time.durationNights,6);assert.match(shiftedWeek.understanding,/14\. bis 20\. Juni 2027/);assert.doesNotMatch(shiftedWeek.understanding,/12\. bis 18\. Juni 2027/);checked();
  const resumedShiftedWeek=h.sandbox.LuviaTripPreferenceResolutionCoreV1.confirmTripBriefWindow({...clone(shiftedWeek),understanding:'Das konkrete Zeitfenster 13.–19. Juni 2027 ist als fix angegeben.'},{startDate:'2027-06-14',endDate:'2027-06-20',destinationName:'Valencia'});assert.match(resumedShiftedWeek.understanding,/14\. bis 20\. Juni 2027/);assert.doesNotMatch(resumedShiftedWeek.understanding,/13\.–19\. Juni 2027/,'A resumed structured brief must repair a stale model-written date even when its structured dates were already current');checked();
  const restoredWindow=harness();restoredWindow.state.data.startDate='2027-06-14';restoredWindow.state.data.endDate='2027-06-20';restoredWindow.state.aiDraft={status:'ready',signature:restoredWindow.api.aiSignature(restoredWindow.state),profileSignature:restoredWindow.api.profileSignature(),brief:{...clone(confirmedWeek),understanding:'Valencia vom 12. bis 18. Juni 2027, sieben Tage am Meer.'},draft:{days:[]},places:[],rehearsals:[]};restoredWindow.api.persist(restoredWindow.state);assert.ok([...restoredWindow.storage.values()].some(item=>item?.aiDraft?.brief),'The ready semantic brief must be persisted before reload');restoredWindow.sandbox.LuviaFirstTripComposer.unmount();assert.ok(restoredWindow.api.readDraft(),`readDraft failed: ${JSON.stringify([...restoredWindow.storage])}`);const initialWindow=restoredWindow.api.initialState(restoredWindow.root,{resume:true,entryMode:'ai',step:'preview'});assert.ok(initialWindow.aiDraft.brief,`initialState lost brief: ${JSON.stringify(initialWindow.aiDraft)}`);const reconciledWindow=restoredWindow.mount(true);assert.ok(reconciledWindow.aiDraft.brief,`The ready semantic brief must survive the Composer reload: ${JSON.stringify(reconciledWindow.aiDraft)}`);assert.equal(reconciledWindow.aiDraft.brief.travelOrder.time.confirmedStart,'2027-06-14');assert.equal(reconciledWindow.aiDraft.brief.travelOrder.time.confirmedEnd,'2027-06-20');assert.match(reconciledWindow.aiDraft.brief.understanding,/14\. bis 20\. Juni 2027/);assert.doesNotMatch(reconciledWindow.aiDraft.brief.understanding,/12\. bis 18\. Juni 2027/);checked();
  const overlapping=harness();overlapping.sandbox.itineraryOverride=(capability,request)=>{let cursor=0;return {ok:true,meta:{fallback:false},data:{title:'Ungültiger Entwurf',summary:'Test',travelPromise:{summary:'Ein absichtlich widersprüchlicher Testentwurf.',commitments:['Alle Tage prüfen'],deliberateFreeTime:'Freiraum bleibt sichtbar.',exclusions:[]},days:request.days.map((day,dayIndex)=>({...day,theme:'Test',balance:{energy:'balanced',plannedMinutes:270,freeTimeMinutes:60,freeTimePurpose:'Erholung'},freeTime:day.role==='full'?[{start:'16:00',end:'17:00',purpose:'Pause',reason:'Bewusster Freiraum'}]:[],entries:request.candidateCatalog.slice(cursor,cursor+=3).map((place,index)=>({providerPlaceId:place.providerPlaceId,time:capability==='trip.compose-day-repair'||dayIndex>0?['10:00','13:00','17:00'][index]:'12:00',durationMinutes:90,category:place.category,reason:'Test',certainty:'modelled',evidenceRefs:[`place:${place.providerPlaceId}:identity`],confidence:.9}))})),uncertaintyMap:[{subject:'Testdaten',kind:'opening',state:'open',reason:'Kein Live-Beleg.',source:'',observedAt:'',expiresAt:'',affectedDayDates:request.days.map(day=>day.date),providerPlaceIds:[],evidenceRefs:[]}],bookingOrder:[],neighborhoodRecommendation:{state:'open',label:'Noch offen',radiusKm:0,reason:'Nicht Teil dieses Konflikttests.',evidencePlaceIds:[],caveats:[]},alternatives:[],uncoveredRequirements:[],warnings:[],confidence:.9}}};await overlapping.api.loadAiDayDraft(overlapping.state);assert.equal(overlapping.state.aiDraft.status,'ready');const overlapComposes=overlapping.sandbox.modelCalls.filter(call=>call.capability.startsWith('trip.compose'));assert.equal(overlapComposes.filter(call=>call.capability==='trip.compose').length,1,'A time conflict on one day must preserve the valid full draft instead of regenerating every day');assert.ok(overlapComposes.some(call=>call.capability==='trip.compose-day-repair'),'Only the affected day is repaired');assert.ok(overlapping.state.draftSelections.length>0);checked();
  const networkCalls=[],events={},net={console,Date,Math,JSON,Object,Array,Map,Set,Number,String,Boolean,Error,TypeError,Promise,Headers,AbortController,setTimeout,clearTimeout,navigator:{onLine:true},location:{hostname:'example.test'},performance:{now:()=>Date.now()},CustomEvent:class{constructor(type,options){this.type=type;this.detail=options?.detail}},isSecureContext:true,LUVIA_AUTH_CONFIG:{supabaseUrl:'https://project.example.test'},addEventListener:(name,fn)=>{events[name]=fn},dispatchEvent(){}};net.window=net;net.globalThis=net;
  net.LuviaSupabaseService={start:()=>{throw Error('Public lookup must not start or wait on Auth')}};
  net.fetch=async(url,options)=>{networkCalls.push({url,options});return {ok:true,status:200,headers:{get:()=>null},json:async()=>({ok:true,data:{destination:{placeId:'provider-roma',name:'Rom',displayName:'Rom, Italien',country:'Italien',countryCode:'IT',center:{lat:41.893,lng:12.483},timezone:'Europe/Rome'}}})}};
  vm.createContext(net);for(const file of ['core/runtime/network-guard.js','intelligence/backend-service.js','intelligence/places-service.js','core/platform/places-contract-adapter.js'])vm.runInContext(fs.readFileSync(file,'utf8'),net,{filename:file});
  net.LuviaNetworkGuard.markFailure(new Error('Failed to fetch'));assert.equal(net.LuviaNetworkGuard.canRequest(),false);
  const rom=await net.LuviaPlacesContractV1.reads.suggestDestinations('Rom',{regionCode:'DE'});assert.equal(rom.suggestions[0].text,'Rom, Italien');assert.equal(networkCalls.length,1);const sent=JSON.parse(networkCalls[0].options.body);assert.equal(sent.action,'destination.resolve');assert.equal(sent.payload.regionCode,undefined,'German browser locale must not exclude Rome');assert.equal(networkCalls[0].options.headers.Authorization,undefined);checked();
  const romDetails=await net.LuviaPlacesContractV1.reads.getDestination('provider-roma');assert.equal(romDetails.countryCode,'IT');assert.equal(romDetails.latitude,41.893);assert.equal(networkCalls.length,1,'Selected geocoding identity must not make a Google details request');checked();
  net.LuviaNetworkGuard.markFailure(new Error('Load failed'));assert.equal(net.LuviaNetworkGuard.canProbe('throttle-test'),true);assert.equal(net.LuviaNetworkGuard.canProbe('throttle-test'),false);checked();
  net.navigator.onLine=false;events.offline();await assert.rejects(net.LuviaPlacesContractV1.reads.suggestDestinations('Madrid'),error=>error.code==='NETWORK_OFFLINE');assert.equal(networkCalls.length,1);checked();
  net.navigator.onLine=true;events.online();assert.equal(net.LuviaNetworkGuard.canRequest(),true);checked();

  const builder=harness();await builder.api.loadAiDayDraft(builder.state);const lift=builder.state.draftSelections[0],destinationDay=builder.state.aiDraft.draft.days[2],readsBefore=builder.requests.length;
  builder.state.pickedSlot=lift.slotId;assert.equal(builder.api.moveDraftSelection(builder.state,lift.slotId,destinationDay.id),true);assert.equal(lift.dayId,destinationDay.id);assert.equal(lift.date,destinationDay.date);assert.equal(builder.state.pickedSlot,null);assert.equal(builder.requests.length,readsBefore);assert.equal(builder.actions.length,0);checked();
  assert.ok(builder.api.mapPlaces(builder.state).every(place=>builder.state.draftSelections.some(item=>item.providerPlaceId===place.providerPlaceId&&item.dayId===destinationDay.id)));checked();
  const priorMove=clone(builder.state.draftSelections);assert.equal(builder.api.moveDraftSelection(builder.state,lift.slotId,'absent'),false);assert.equal(builder.api.moveDraftSelection(builder.state,'absent',destinationDay.id),false);assert.deepEqual(clone(builder.state.draftSelections),priorMove);checked();
  builder.state.confirmation={status:'pending'};assert.equal(builder.api.moveDraftSelection(builder.state,lift.slotId,builder.state.aiDraft.draft.days[0].id),false);assert.deepEqual(clone(builder.state.draftSelections),priorMove);builder.state.confirmation=null;checked();
  builder.sandbox.LuviaFirstTripComposer.unmount();const restoredMove=builder.mount(true);assert.equal(restoredMove.draftSelections.find(item=>item.slotId===lift.slotId).dayId,destinationDay.id);assert.equal(builder.actions.length,0);checked();
  const opening=harness();opening.sandbox.LuviaFirstTripComposer.mount(opening.root,{resume:false,step:'welcome'});for(const label of ['Leere Reise','Mit Vorschlägen','Luvia plant alles'])assert.ok(opening.root.innerHTML.includes(label));assert.match(opening.root.innerHTML,/data-mode-chosen="false"/);opening.api.state().modeChosen=true;opening.api.state().data.entryMode='ai';opening.api.state().data.inspirationCompleted=false;opening.api.render(opening.api.state());assert.match(opening.root.innerHTML,/Eure Reise beginnt mit einem Wunsch/);assert.doesNotMatch(opening.root.innerHTML,/Noch ist alles möglich|Kompass nach Norden/);checked();
  const changedWish=harness();changedWish.state.aiDraft={status:'loading',brief:{understanding:'Alter Reiseauftrag'},places:[changedWish.candidate('food',1)]};changedWish.state.workflowId='old-workflow';changedWish.state.workflowKey='old-key';changedWish.state.workflowSnapshot={id:'old-workflow'};changedWish.state.draftSelections=[{slotId:'old-slot'}];changedWish.state.briefAnswers=[{answer:'alt'}];changedWish.api.invalidateAiPlanning(changedWish.state);assert.equal(changedWish.state.aiDraft.status,'idle');assert.equal(changedWish.state.workflowId,null);assert.equal(changedWish.state.workflowKey,'');assert.equal(changedWish.state.workflowSnapshot,null);assert.equal(changedWish.state.draftSelections.length,0);assert.equal(changedWish.state.briefAnswers.length,0);checked();
  const empty=harness();empty.state.data.entryMode='quick';empty.state.index=4;await empty.api.save(empty.state);assert.equal(empty.tripCalls.length,1,empty.state.error);assert.equal(empty.actions.length,0);assert.equal(empty.requests.length,0);checked();
  const ideas=harness();ideas.state.data.entryMode='guided';ideas.state.data.tripPreferences.movementStyle='city_transit';await ideas.api.loadAiDayDraft(ideas.state);assert.equal(ideas.state.aiDraft.status,'ready');assert.ok(ideas.state.draftSelections.every(e=>e.action==='excluded'));assert.ok(ideas.api.mapPlaces(ideas.state).length>0);assert.deepEqual(ideas.sandbox.modelCalls.slice(-2).map(item=>item.capability),['trip.compose','trip.audit'],'The guided proposal path needs composition followed by an independent audit');checked();
  ideas.api.setDraftAction(ideas.state,ideas.state.draftSelections[0].slotId,'saved');await ideas.api.save(ideas.state);assert.equal(ideas.tripCalls.length,1,ideas.state.error);assert.equal(ideas.actions.length,1);assert.equal(ideas.actions[0].actionId,'places.place.favorite');checked();
  const wish=harness();wish.sandbox.LuviaFirstTripComposer.mount(wish.root,{resume:false,step:'welcome'});const ws=wish.api.state();ws.modeChosen=true;ws.data.entryMode='ai';ws.data.inspirationCompleted=false;ws.data.inspirationBrief='Meer und viel Natur';
  wish.sandbox.dialogue={searchPlans:[{query:'Lissabon'},{query:'Rom'},{query:'Athen'},{query:'Split'},{query:'Valencia'},{query:'Lissabon'}],reasoningSummary:'Fünf unterschiedliche Richtungen'};
  wish.sandbox.LuviaPlacesContractV1.reads.suggestDestinations=async q=>({suggestions:[{placeId:q}]});
  wish.sandbox.LuviaPlacesContractV1.reads.getDestination=async id=>({owner:'places',contractId:'places.v1',placeId:id,name:id,formattedAddress:id,countryCode:id==='Lissabon'?'PT':id==='Valencia'?'ES':id==='Split'?'HR':id==='Athen'?'GR':'IT',latitude:38.7,longitude:-9.1,timezone:id==='Lissabon'?'Europe/Lisbon':'Europe/Rome'});
  await wish.api.inspire(ws);assert.equal(ws.inspiration.status,'ready');assert.equal(ws.inspiration.suggestions.length,5);assert.equal(wish.sandbox.modelCalls[0].capability,'discovery.plan');assert.equal(wish.sandbox.modelCalls[0].request.destination,null);assert.equal(wish.sandbox.modelCalls[0].request.task.includes('exactly five'),true);assert.equal(wish.sandbox.modelCalls[0].options.fallback,false);assert.equal(wish.tripCalls.length,0);checked();
  assert.equal(wish.api.destinationIdeaFit('warm ans Meer ins Ausland',{countryCode:'DE',latitude:54,longitude:10}).ok,false);assert.equal(wish.api.destinationIdeaFit('warm ans Meer ins Ausland',{countryCode:'DK',latitude:55.7,longitude:12.6}).ok,false);assert.equal(wish.api.destinationIdeaFit('warm ans Meer ins Ausland, nicht lange fliegen',{countryCode:'PT',latitude:38.7,longitude:-9.1}).ok,true);assert.equal(wish.api.destinationIdeaFit('warm ans Meer ins Ausland, nicht lange fliegen',{countryCode:'ZA',latitude:-33.9,longitude:18.4}).ok,false);checked();
  assert.equal(wish.api.destinationIdentityFit('Valencia, Spanien',{name:'Alicante',formattedAddress:'Alicante, Spanien'}),false);assert.equal(wish.api.destinationIdentityFit('Valencia, Spanien',{name:'València',formattedAddress:'València, Spanien'}),true);checked();
  const identityDetails={alicante:{owner:'places',contractId:'places.v1',placeId:'alicante',name:'Alicante',formattedAddress:'Alicante, Spanien',countryCode:'ES',latitude:38.34,longitude:-.48,timezone:'Europe/Madrid'},valencia:{owner:'places',contractId:'places.v1',placeId:'valencia',name:'València',formattedAddress:'València, Spanien',countryCode:'ES',latitude:39.47,longitude:-.38,timezone:'Europe/Madrid'}};wish.sandbox.LuviaPlacesContractV1.reads.suggestDestinations=async()=>({suggestions:[{placeId:'alicante'},{placeId:'valencia'}]});wish.sandbox.LuviaPlacesContractV1.reads.getDestination=async id=>identityDetails[id];const resolvedValencia=await wish.api.resolveInspiredDestination(wish.sandbox.LuviaPlacesContractV1,'Valencia, Spanien',{reason:'Stadt und Meer'});assert.equal(resolvedValencia.placeId,'valencia');assert.equal(resolvedValencia.inspirationReason,'Stadt und Meer');checked();
  let finish;wish.sandbox.modelOverride=()=>new Promise(r=>{finish=r});const pendingWish=wish.api.inspire(ws);await new Promise(r=>setTimeout(r,0));ws.data.inspirationCompleted=true;ws.loadSequence++;finish({ok:true,data:{searchPlans:[{query:'Stale'}]}});await pendingWish;assert.equal(ws.data.destination.placeId,'');assert.ok(!ws.inspiration.suggestions.some(p=>p.name==='Stale'));checked();
  ws.data.inspirationCompleted=false;wish.sandbox.modelOverride=()=>Promise.reject(Object.assign(Error('quota'),{code:'credit_balance_exhausted'}));await wish.api.inspire(ws);assert.equal(ws.inspiration.status,'error');assert.match(ws.inspiration.error,/API-Kontingent/);assert.equal(ws.data.inspirationBrief,'Meer und viel Natur');checked();
  const tz=harness();tz.state.data.destination.timezone='';tz.state.index=2;tz.sandbox.LuviaPlacesContractV1.reads.suggestDestinations=async()=>({suggestions:[{placeId:'scharbeutz'}]});tz.sandbox.LuviaPlacesContractV1.reads.getDestination=async()=>({owner:'places',contractId:'places.v1',...input.destination});await tz.api.repairDestinationZone(tz.state);assert.equal(tz.state.data.destination.timezone,'Europe/Berlin');assert.equal(tz.api.validate(tz.state),null);checked();
  const needs=harness();needs.state.data.tripPreferences.food=['vegan'];needs.state.data.tripPreferences.accessibility=['wheelchair'];needs.state.data.tripPreferences.mobility=['cycling'];needs.state.data.tripPreferences.movementStyle='city_transit';needs.sandbox.cached={category:'food',places:[1,2,3,4].map(i=>({...needs.candidate('food',i),profileFit:{state:'matched'}}))};await needs.api.readAiPlaces(needs.state);assert.ok(needs.requests.length);assert.deepEqual(clone(needs.requests[0].preferences.dietaryPreferences),['vegetarian','vegan']);assert.deepEqual(clone(needs.requests[0].preferences.accessibilityNeeds),['wheelchair']);assert.deepEqual(clone(needs.requests[0].preferences.mobilityPreferences),['cycling']);assert.equal(needs.requests[0].parallelFastQueries,true);assert.equal(needs.requests[0].fastQueryLimit,1);assert.equal(needs.requests[0].diversity.minimumQueryVariants,1);assert.equal(needs.requests[0].maxDistanceMeters,20000);assert.equal(needs.requests[0].tripComposition.spatialScope.minimumDistinctAreas,3);assert.deepEqual(needs.sandbox.profile,{dietaryPreferences:['vegetarian']});checked();
  const profileCategories=harness();profileCategories.state.data.tripPreferences.interests=[];profileCategories.state.data.tripPreferences.food=[];profileCategories.sandbox.profile={travelInterests:['nature','shopping'],dietaryPreferences:['vegetarian']};profileCategories.sandbox.recommend=async()=>({places:[]});await profileCategories.api.readAiPlaces(profileCategories.state);assert.deepEqual([...new Set(profileCategories.requests.map(request=>request.category))],['nature','shopping','food']);assert.ok(profileCategories.requests.every(request=>request.refresh===false),'profile-only gaps must not delay the initial plan with focused retries');checked();
  const parallelCategories=harness();parallelCategories.state.data.tripPreferences.interests=['food','culture','nature','shopping','nightlife','wellness','active'];let activeReads=0,maximumParallelReads=0;parallelCategories.sandbox.recommend=options=>new Promise(resolve=>{activeReads++;maximumParallelReads=Math.max(maximumParallelReads,activeReads);setTimeout(()=>{activeReads--;resolve({places:[parallelCategories.candidate(options.category,1)]})},5)});await parallelCategories.api.readAiPlaces(parallelCategories.state);assert.equal(maximumParallelReads,7,'explicit trip categories must start together instead of waiting in serial batches');assert.equal(parallelCategories.requests.length,7);checked();
  const dna=needs.api.travelDna(needs.state);assert.equal(dna.length,6);assert.equal(dna.find(item=>item.key==='food').source,'Reise + Profil');assert.equal(dna.find(item=>item.key==='access').source,'Reise');assert.match(needs.api.travelDnaMarkup(needs.state),/EURE REISE-DNA/);assert.match(needs.api.travelDnaMarkup(needs.state),/Sie steuert Kategorien, Reihenfolge und Tagesrhythmus/);checked();
  const timeTravel=harness();timeTravel.state.modeChosen=true;timeTravel.state.data.entryMode='ai';timeTravel.state.index=0;assert.equal(timeTravel.api.recordDecision(timeTravel.state,'welcome'),true);timeTravel.state.index=2;timeTravel.state.data.startDate='2027-08-02';timeTravel.state.data.endDate='2027-08-08';assert.equal(timeTravel.api.recordDecision(timeTravel.state,'dates'),true);const dateSnapshot=timeTravel.state.decisionTrail.at(-1);timeTravel.state.index=3;timeTravel.state.data.requestBrief='Viel Kultur und ruhige Abende';timeTravel.state.draftSelections=[{slotId:'later-choice'}];timeTravel.state.aiDraft={status:'ready',draft:{days:[]},places:[]};assert.equal(timeTravel.api.recordDecision(timeTravel.state,'brief'),true);assert.match(timeTravel.api.timeTravelMarkup(timeTravel.state),/Bisherige Auswahl/);assert.doesNotMatch(timeTravel.api.timeTravelMarkup(timeTravel.state),/>Zeitreise</);assert.equal(timeTravel.api.restoreDecision(timeTravel.state,dateSnapshot.id),true);assert.equal(timeTravel.state.index,2);assert.equal(timeTravel.state.data.startDate,'2027-08-02');assert.equal(timeTravel.state.data.requestBrief,'');assert.equal(timeTravel.state.aiDraft.status,'idle');assert.equal(timeTravel.state.draftSelections.length,0);assert.equal(timeTravel.actions.length,0);assert.equal(timeTravel.tripCalls.length,0);assert.equal(timeTravel.state.decisionTrail.length,2);timeTravel.api.persist(timeTravel.state);timeTravel.sandbox.LuviaFirstTripComposer.unmount();const restoredTimeTravel=timeTravel.mount(true);assert.equal(restoredTimeTravel.decisionTrail.length,2);checked();
  needs.state.aiDraft={status:'error',signature:JSON.stringify({})};needs.api.render(needs.state);assert.equal(needs.api.validate(needs.state)[0],'Entwurf noch nicht bereit');assert.match(needs.root.innerHTML,/data-ftc-next[^>]*disabled/);checked();

  // Living world: latitude/date mood is never a weather forecast.
  const season=h.api.seasonalMood;
  assert.equal(season(input).key,'summer');assert.equal(season({...input,destination:{latitude:-34}}).key,'winter');checked();
  assert.equal(season({...input,startDate:'2027-12-10',destination:{latitude:-34}}).key,'summer');assert.equal(season({...input,startDate:'2027-03-10',destination:{latitude:54}}).key,'spring');checked();
  for(const latitude of [0,10,-10])assert.equal(season({...input,destination:{latitude}}).key,'tropical');checked();
  for(const patch of [{startDate:'2027-02-30'},{startDate:''},{scheduleMode:'flexible'},{destination:{latitude:null}},{destination:{latitude:200}}])assert.equal(season({...input,...patch}).key,'open');checked();
  // A film cursor is presentation only; all stations remain the canonical draft.
  const film=harness();await film.api.loadAiDayDraft(film.state);const filmDraft=clone(film.state.draftSelections),filmReads=film.requests.length,frame=film.api.filmFrame(film.state);
  assert.equal(frame.day.id,film.state.aiDraft.draft.days[0].id);assert.equal(frame.entry.slotId,film.state.draftSelections[0].slotId);checked();
  film.api.filmAdvance(film.state,1);assert.equal(film.api.filmFrame(film.state).index,1);assert.deepEqual(clone(film.state.draftSelections),filmDraft);assert.equal(film.requests.length,filmReads);assert.equal(film.actions.length,0);checked();
  const firstDayCount=film.state.draftSelections.filter(item=>item.dayId===film.state.aiDraft.draft.days[0].id).length;for(let index=1;index<firstDayCount;index+=1)film.api.filmAdvance(film.state,1);assert.equal(film.api.filmFrame(film.state).dayIndex,1);film.api.filmAdvance(film.state,-1);assert.equal(film.api.filmFrame(film.state).index,firstDayCount-1);assert.equal(film.api.filmFrame(film.state).dayIndex,0);checked();
  film.api.filmChoose(film.state,{dayId:film.state.aiDraft.draft.days[2].id});film.state.filmPlaying=true;for(let guard=0;film.state.filmPlaying&&guard<10;guard+=1)film.api.filmAdvance(film.state,1,false,{automatic:true});assert.equal(film.state.filmPlaying,false);assert.equal(film.api.filmAdvance(film.state,1),false);checked();
  film.state.filmPlaying=true;film.api.setDraftAction(film.state,film.state.draftSelections[0].slotId,'saved');assert.equal(film.state.filmPlaying,false);checked();
  const emptyDay={id:'film-empty',date:'2027-06-15',label:'Tag 4',entries:[]};film.state.aiDraft.draft={...film.state.aiDraft.draft,days:[...film.state.aiDraft.draft.days,emptyDay]};film.api.filmChoose(film.state,{dayId:emptyDay.id});assert.equal(film.api.filmFrame(film.state).entry,null);assert.match(film.root.innerHTML,/Dieser Tag braucht noch einen Moment/);assert.equal(film.api.mapPlaces(film.state).length,0);checked();
  film.state.filmPlaying=true;film.sandbox.document.hidden=true;film.api.scheduleFilm(film.state);assert.equal(film.state.filmPlaying,false);assert.equal(film.state.filmTimer,0);film.sandbox.document.hidden=false;checked();
  const target=film.state.draftSelections[0];film.api.moveDraftSelection(film.state,target.slotId,emptyDay.id);assert.equal(film.api.filmFrame(film.state).entry.slotId,target.slotId);assert.equal(film.actions.length,0);assert.equal(film.requests.length,filmReads);checked();
  film.api.filmChoose(film.state,{dayId:film.state.aiDraft.draft.days[1].id});const cursor=film.api.filmFrame(film.state);film.api.persist(film.state);film.sandbox.LuviaFirstTripComposer.unmount();const resumeFilm=film.mount(true);assert.equal(film.api.filmFrame(resumeFilm).entry.slotId,cursor.entry.slotId);assert.equal(resumeFilm.filmPlaying,false);checked();
  const trace=harness();await trace.api.loadAiDayDraft(trace.state);trace.state.activeDay='all';const beforeTrace=trace.api.tripTrace(trace.state),firstTraceCount=beforeTrace[0].length;assert.equal(beforeTrace.length,3);assert.ok(firstTraceCount>=3);trace.api.setDraftAction(trace.state,trace.state.draftSelections[0].slotId,'saved');assert.equal(trace.api.tripTrace(trace.state)[0].length,firstTraceCount-1);assert.equal(trace.actions.length,0);checked();
  const routeFocus=harness();await routeFocus.api.loadAiDayDraft(routeFocus.state);const focusEntry=routeFocus.state.draftSelections.find(entry=>entry.dayId==='day-2'),selectedPins=[],cameraMoves=[],mapNode={replaceWith(){}},mapStage={classList:{add(){},remove(){}}};assert.ok(routeFocus.api.mapPlaces(routeFocus.state).every(place=>Number.isInteger(place.compassTone)&&place.compassTone>=0&&place.compassTone<12),'Every Composer Place projected onto the map must carry its stable category tone from the Luvia Compass');routeFocus.state.mapSignature=routeFocus.state.aiDraft.signature;routeFocus.state.mapProjection={update(){},select:id=>selectedPins.push(id),setTrace(){},map:{flyTo:options=>cameraMoves.push(options)},destroy(){}};routeFocus.root.querySelector=selector=>selector==='[data-ftc-ai-map]'?mapNode:selector==='.lx-map-stage'?mapStage:null;routeFocus.sandbox.requestAnimationFrame=callback=>callback();assert.equal(routeFocus.api.focusDraftPlaceOnMap(routeFocus.state,focusEntry.slotId,{origin:'card'}),true);assert.equal(routeFocus.state.activeDay,focusEntry.dayId);assert.equal(routeFocus.state.filmSlot,focusEntry.slotId);assert.deepEqual(selectedPins,[focusEntry.providerPlaceId]);assert.equal(cameraMoves.length,1);assert.equal(cameraMoves[0].center[0],focusEntry.coordinates.longitude);assert.equal(cameraMoves[0].center[1],focusEntry.coordinates.latitude);assert.match(routeFocus.root.innerHTML,new RegExp(`lx-route-stop[^>]+is-map-selected[^>]+data-ftc-ai-place="${focusEntry.providerPlaceId}"`));assert.match(routeFocus.root.innerHTML,/data-ftc-free-route/,'Purposeful free time must be a visible route stop rather than an apparent planning gap');checked();
  const mobileResume=harness();let workflowStarts=0,workflowReads=0,workflow={id:'workflow-mobile-resume',phase:'started',phaseState:{}};mobileResume.sandbox.LuviaOpenAIProvider.startTripWorkflow=async()=>{workflowStarts++;return clone(workflow)};mobileResume.sandbox.LuviaOpenAIProvider.readTripWorkflow=async()=>{workflowReads++;return clone(workflow)};mobileResume.sandbox.LuviaOpenAIProvider.checkpointTripWorkflow=async(id,phase,patch)=>{assert.equal(id,workflow.id);workflow={...workflow,phase,phaseState:{...workflow.phaseState,...clone(patch)}};return clone(workflow)};await mobileResume.api.loadAiDayDraft(mobileResume.state);const callsBeforeResume=mobileResume.sandbox.modelCalls.length,idempotencyBeforeResume=mobileResume.state.idempotencyKey,retryGenerationBeforeResume=mobileResume.state.aiRetryGeneration;mobileResume.state.aiDraft={...mobileResume.state.aiDraft,status:'loading',phase:'audit',loadingStartedAt:new Date(Date.now()-95000).toISOString(),serverPending:true};const progress=mobileResume.api.planningProgressPanel(mobileResume.state,mobileResume.state.aiDraft);assert.match(progress,/Wünsche verstehen/);assert.match(progress,/Passende Places finden/);assert.match(progress,/Alle Tage komponieren/);assert.match(progress,/Reise unabhängig prüfen/);assert.match(progress,/Details verbessern/);assert.match(progress,/Das dauert länger als üblich/);assert.equal(mobileResume.api.resumeAiPlanning(mobileResume.state,'foreground'),true);assert.equal(mobileResume.state.aiDraft.connectionState,'reconnecting');await new Promise(resolve=>setTimeout(resolve,260));assert.equal(mobileResume.state.aiDraft.status,'ready');assert.equal(mobileResume.state.idempotencyKey,idempotencyBeforeResume,'foreground resume must retain the semantic request id');assert.equal(mobileResume.state.aiRetryGeneration,retryGenerationBeforeResume,'foreground resume must not authorize a new paid generation');assert.equal(workflowStarts,1,'foreground resume must reuse the existing server workflow');assert.ok(workflowReads>=1,'foreground resume must reconcile the existing server workflow');assert.equal(mobileResume.sandbox.modelCalls.length,callsBeforeResume,'an already completed server phase must not be recomputed after foreground resume');checked();
  const offlineResume=harness();offlineResume.sandbox.navigator.onLine=false;offlineResume.state.aiDraft={status:'loading',phase:'itinerary',signature:offlineResume.api.aiSignature(offlineResume.state),profileSignature:offlineResume.api.profileSignature(),brief:null,places:[],rehearsals:[],loadingStartedAt:new Date().toISOString()};const offlineCalls=offlineResume.sandbox.modelCalls?.length||0;await offlineResume.api.loadAiDayDraft(offlineResume.state,{force:true});assert.equal(offlineResume.state.aiDraft.status,'loading');assert.equal(offlineResume.state.aiDraft.connectionState,'offline');assert.equal(offlineResume.sandbox.modelCalls?.length||0,offlineCalls,'offline foreground recovery must not start a model request');assert.match(offlineResume.api.planningProgressPanel(offlineResume.state,offlineResume.state.aiDraft),/Verbindung unterbrochen/);checked();
  const photo={providerPlaceId:'food-1',url:'https://images.example.test/place.jpg',attribution:'Ortsfotograf',verified:true};assert.ok(h.api.linkedMedia({place:{providerPlaceId:'food-1'},image:photo},'food-1'));checked();
  for(const card of [{place:{providerPlaceId:'wrong'},image:photo},{place:{providerPlaceId:'food-1'},image:{...photo,providerPlaceId:'wrong'}},{place:{providerPlaceId:'food-1'},image:{...photo,url:'javascript:alert(1)'}},{place:{providerPlaceId:'food-1'},image:null}])assert.equal(h.api.linkedMedia(card,'food-1'),null);checked();
  const selectedDestination=harness();selectedDestination.state.index=1;selectedDestination.state.data.inspirationCompleted=true;selectedDestination.state.data.destination={...selectedDestination.state.data.destination,inspirationReason:'Valencia verbindet Stadt, Meer und kurze Wege.',inspirationSignals:['Meer','Kultur','kurze Wege']};selectedDestination.api.render(selectedDestination.state);assert.equal(selectedDestination.requests.length,0,'A selected AI destination must not trigger a premature Places preview');assert.equal(selectedDestination.actions.length,0);assert.doesNotMatch(selectedDestination.root.innerHTML,/Hier könnte eure Reise beginnen|Galerie am Meer|Naturpfad 1|Ortsbild noch offen/);assert.match(selectedDestination.root.innerHTML,/Valencia verbindet Stadt, Meer und kurze Wege/);assert.match(selectedDestination.root.innerHTML,/Konkrete Orte erscheinen erst im vollständigen KI-Reiseentwurf/);checked();
  const repair=harness();let auditCount=0;repair.sandbox.auditOverride=(capability,request)=>{auditCount++;return auditCount===1?{ok:true,meta:{fallback:false},data:{readyForReview:false,score:62,headline:'Der erste Entwurf braucht eine Korrektur.',dimensions:[{id:'rhythm',label:'Rhythmus',score:40,status:'blocked',summary:'Zu eng.'}],issues:[{code:'DAY_TOO_DENSE',severity:'blocked',dayDate:input.startDate,providerPlaceIds:[],message:'Der Ankunftstag ist zu dicht.',suggestedRepair:'Entferne einen Termin am Ankunftstag.'}],strengths:[],repairInstructions:['Entferne einen Termin am Ankunftstag.'],confidence:.94}}:{ok:true,meta:{fallback:false},data:{readyForReview:true,score:93,headline:'Der korrigierte Entwurf ist bereit.',dimensions:[{id:'rhythm',label:'Rhythmus',score:93,status:'pass',summary:'Stimmig.'}],issues:[],strengths:['Ankunftstag entlastet'],repairInstructions:[],confidence:.96}}};await repair.api.loadAiDayDraft(repair.state);assert.equal(repair.state.aiDraft.status,'ready');assert.equal(repair.state.aiDraft.qualityAttempts,2);assert.equal(repair.state.aiDraft.audit.score,93);const repairCalls=repair.sandbox.modelCalls.filter(item=>item.capability.startsWith('trip.compose'));assert.deepEqual(repairCalls.map(call=>call.capability),['trip.compose','trip.compose-day-repair']);assert.equal(repairCalls[0].options.tier,'fast');assert.equal(repairCalls[1].options.tier,'default','A dated audit blocker repairs only its day with Terra');assert.deepEqual(clone(repairCalls[1].request.days.map(day=>day.date)),[input.startDate]);assert.deepEqual(clone(repairCalls[1].request.repairInstructions),['Entferne einen Termin am Ankunftstag.']);assert.ok(repairCalls[1].request.excludedProviderPlaceIds.length>0,'Places from preserved days cannot be reused by the repaired day');assert.equal(repair.actions.length,0);checked();
  const partialRepair=harness();let partialAuditCount=0;partialRepair.sandbox.auditOverride=()=>{partialAuditCount++;return partialAuditCount===1?{ok:true,meta:{fallback:false},data:{readyForReview:false,score:58,headline:'Zwei Tage brauchen eine Korrektur.',promiseAssessment:{kept:true,summary:'Das Versprechen bleibt erreichbar.',missedCommitments:[]},dimensions:[{id:'rhythm',label:'Rhythmus',score:50,status:'blocked',summary:'Zwei Tage prüfen.'}],issues:[{code:'ARRIVAL_DENSE',severity:'blocked',dayDate:input.startDate,providerPlaceIds:[],message:'Ankunft entlasten.',suggestedRepair:'Ankunftstag entlasten.'},{code:'FULL_DENSE',severity:'blocked',dayDate:'2027-06-13',providerPlaceIds:[],message:'Mittleren Tag entlasten.',suggestedRepair:'Mittleren Tag entlasten.'}],strengths:[],repairInstructions:['Zwei Tage entlasten.'],confidence:.9}}:{ok:true,meta:{fallback:false},data:{readyForReview:true,score:94,headline:'Beide Tage sind repariert.',promiseAssessment:{kept:true,summary:'Das Versprechen wird gehalten.',missedCommitments:[]},dimensions:[{id:'rhythm',label:'Rhythmus',score:94,status:'pass',summary:'Stimmig.'}],issues:[],strengths:['Die Reise wurde als Ganzes neu ausbalanciert'],repairInstructions:[],confidence:.95}}};await partialRepair.api.loadAiDayDraft(partialRepair.state);assert.equal(partialRepair.state.aiDraft.status,'ready','Several failed days must be recomposed together within one bounded model call');const partialCalls=partialRepair.sandbox.modelCalls.filter(item=>item.capability.startsWith('trip.compose'));assert.deepEqual(partialCalls.map(call=>call.capability),['trip.compose','trip.compose']);assert.deepEqual(clone(partialCalls[1].request.days.map(day=>day.date)),clone(partialCalls[0].request.days.map(day=>day.date)),'The holistic repair must receive the complete trip contract');assert.deepEqual(clone(partialCalls[1].request.repairInstructions),['Zwei Tage entlasten.']);assert.equal(partialCalls[1].options.tier,'deep','A holistic multi-day repair escalates directly to the strongest quality tier');assert.equal(partialCalls[1].request.existingItinerary,undefined);assert.equal(partialCalls[1].request.repairDayDates,undefined);checked();
  const manualRetry=harness();manualRetry.state.data.requestBrief='Ruhig Kultur entdecken und vegan essen.';await manualRetry.api.loadAiDayDraft(manualRetry.state);const preservedCandidateIds=manualRetry.state.aiDraft.places.map(place=>place.providerPlaceId),placeReadCount=manualRetry.requests.length;manualRetry.state.aiDraft={...manualRetry.state.aiDraft,status:'error',audit:null,qualityAttempts:3,retryEscalated:true,repairDayDates:[input.startDate],repairInstructions:['Nur den Ankunftstag entlasten.'],contractRejections:[{code:'DAY_REJECTED'}],error:'Voriger Workflow ausgeschöpft.',errorCode:'AI_WORKFLOW_BUDGET_EXHAUSTED'};manualRetry.api.persist(manualRetry.state);assert.equal(manualRetry.api.readDraft().aiDraft.errorCode,'AI_WORKFLOW_BUDGET_EXHAUSTED','A terminal planning state must survive reload without silently restarting paid work');manualRetry.sandbox.modelCalls=[];await manualRetry.api.loadAiDayDraft(manualRetry.state,{force:true,confirmedBrief:true});assert.equal(manualRetry.state.aiDraft.status,'ready',manualRetry.state.aiDraft.error||'A visible retry must finish in one strong bounded whole-trip lane');assert.equal(manualRetry.requests.length,placeReadCount,'A fresh repair workflow must retain a sufficient local Places catalog instead of researching it again');assert.deepEqual(manualRetry.sandbox.modelCalls.map(call=>call.capability),['trip.compose','trip.audit'],'A user-authorized retry after budget exhaustion must run one holistic plan and one independent audit');assert.equal(manualRetry.sandbox.modelCalls[0].options.tier,'deep');assert.deepEqual(clone(manualRetry.sandbox.modelCalls[0].request.repairInstructions),['Nur den Ankunftstag entlasten.']);assert.deepEqual(clone(manualRetry.sandbox.modelCalls[0].request.candidateCatalog.map(place=>place.providerPlaceId)),clone(preservedCandidateIds),'The strong retry must reuse the already researched Places catalog');checked();
  const thinDay=harness();thinDay.sandbox.itineraryOverride=(capability,request)=>{let cursor=0;const days=request.days.map(day=>{const entries=request.candidateCatalog.slice(cursor,cursor+day.minimumMoments).map((place,index)=>({providerPlaceId:place.providerPlaceId,time:['10:00','13:00','18:00','20:00'][index],durationMinutes:90,reason:'Passt zum Reiseauftrag.'}));cursor+=day.minimumMoments;return{date:day.date,theme:'Ein vollständiger Tag',balance:{energy:'balanced',freeTimePurpose:'Bewusste Pause'},freeTime:day.role==='full'?[{start:'16:00',end:'17:00',purpose:'Erholung'}]:[],entries}});days[1].entries.pop();const chosen=days.flatMap(day=>day.entries.map(entry=>entry.providerPlaceId));return{ok:true,meta:{fallback:false},data:{title:'Struktureller Reparaturtest',summary:'Ein Tag ist absichtlich zu dünn.',travelPromise:{summary:'Eine ausgewogene Reise.',commitments:['Alle Tage vollständig planen'],deliberateFreeTime:'Volle Tage behalten Pausen.',exclusions:[]},days,uncertaintyMap:[],bookingOrder:[],neighborhoodRecommendation:{state:'modelled',label:'Kompakter Radius',radiusKm:3,reason:'Aus Tagesorten abgeleitet.',evidencePlaceIds:chosen.slice(0,3),caveats:[]},alternatives:[],backupOptions:[],warnings:[],confidence:.9}}};await thinDay.api.loadAiDayDraft(thinDay.state);assert.equal(thinDay.state.aiDraft.status,'ready','A structurally thin day is repaired without regenerating valid days');const thinCalls=thinDay.sandbox.modelCalls.filter(item=>item.capability.startsWith('trip.compose'));assert.deepEqual(thinCalls.map(call=>call.capability),['trip.compose','trip.compose-day-repair']);assert.deepEqual(clone(thinCalls[1].request.days.map(day=>day.date)),[input.startDate.replace(/12$/,'13')]);assert.equal(thinDay.state.aiDraft.draft.days[1].entries.length,3);checked();
  const duplicateRepair=harness();let duplicateAttempt=0;duplicateRepair.sandbox.itineraryOverride=(capability,request)=>{duplicateAttempt++;let cursor=0;const chosen=[];const days=request.days.map(day=>{const entries=request.candidateCatalog.slice(cursor,cursor+day.minimumMoments).map((place,index)=>({providerPlaceId:place.providerPlaceId,time:['10:00','13:00','17:00','19:00'][index],durationMinutes:90,category:place.category,reason:'Passt zum Reiseauftrag.',certainty:'modelled',evidenceRefs:[`place:${place.providerPlaceId}:identity`],confidence:.91}));cursor+=day.minimumMoments;chosen.push(...entries.map(entry=>entry.providerPlaceId));return {...day,theme:'Ein ausgewogener Tag',balance:{energy:'balanced',plannedMinutes:entries.length*90,freeTimeMinutes:60,freeTimePurpose:'Bewusste Pause'},freeTime:day.role==='full'?[{start:'15:00',end:'16:00',purpose:'Erholung',reason:'Freiraum bleibt geplant.'}]:[],entries};});if(duplicateAttempt===1&&days[0]?.entries[0]&&days[1]?.entries[0])days[1].entries[0].providerPlaceId=days[0].entries[0].providerPlaceId;return {ok:true,meta:{fallback:false},data:{title:'Valider Reparaturtest',summary:'Alle Tage sind geplant.',travelPromise:{summary:'Eine ausgewogene Reise mit bewussten Pausen.',commitments:['Alle Tage vollständig planen'],deliberateFreeTime:'Volle Tage behalten sichtbare Pausen.',exclusions:[]},days,uncertaintyMap:[],bookingOrder:[],neighborhoodRecommendation:{state:'modelled',label:'Kompakter Radius',radiusKm:3,reason:'Aus den Tagesorten abgeleitet.',evidencePlaceIds:chosen.slice(0,3),caveats:['Wege bleiben zu prüfen.']},alternatives:[],backupOptions:[],uncoveredRequirements:[],warnings:[],confidence:.9}}};await duplicateRepair.api.loadAiDayDraft(duplicateRepair.state);assert.equal(duplicateRepair.state.aiDraft.status,'ready','A duplicate Place in one model attempt must be repaired instead of aborting the full plan');const duplicateComposes=duplicateRepair.sandbox.modelCalls.filter(item=>item.capability.startsWith('trip.compose'));assert.deepEqual(duplicateComposes.map(call=>call.capability),['trip.compose','trip.compose-day-repair']);assert.deepEqual(duplicateComposes.map(call=>call.options.tier),['fast','default']);assert.ok(duplicateComposes[1].request.repairInstructions.some(item=>/verwendet.*erneut/.test(item)));checked();
  const evidenceGapAudit=harness();evidenceGapAudit.sandbox.auditOverride=()=>({ok:true,meta:{fallback:false},data:{readyForReview:false,score:81,headline:'Plan bereit mit offenen Live-Fakten.',promiseAssessment:{kept:false,summary:'Ankunft und kinderwagentaugliche Zugänge sind wegen fehlender Flug- und Zugangsdaten noch nicht belastbar.',missedCommitments:['Ankunftspuffer noch nicht belegt','Kinderwagenzugang noch nicht verifiziert']},dimensions:[{id:'evidence',label:'Faktenlage',score:70,status:'blocked',summary:'Live-Daten fehlen.'}],issues:[{code:'LIVE_DATA_MISSING',severity:'blocked',dayDate:input.startDate,providerPlaceIds:[],message:'Die Randtagspuffer sind wegen fehlender Flugdaten noch nicht belastbar.',suggestedRepair:'Flugdaten nach Buchung ergänzen.'}],strengths:['Alle Tage vollständig'],repairInstructions:['Flugdaten nach Buchung ergänzen.'],confidence:.9}});await evidenceGapAudit.api.loadAiDayDraft(evidenceGapAudit.state);assert.equal(evidenceGapAudit.state.aiDraft.status,'ready','Missing live evidence remains visible uncertainty and must not trigger futile regeneration');assert.equal(evidenceGapAudit.state.aiDraft.audit.issues[0].severity,'attention');assert.equal(evidenceGapAudit.state.aiDraft.audit.promiseAssessment.kept,true);checked();
  const attentionAudit=harness();attentionAudit.sandbox.auditOverride=()=>({ok:true,meta:{fallback:false},data:{readyForReview:false,score:86,headline:'Bereit mit offenen Prüfhinweisen.',promiseAssessment:{kept:true,summary:'Das Reiseversprechen wird eingehalten.',missedCommitments:[]},dimensions:[{id:'evidence',label:'Aktualität',score:72,status:'attention',summary:'Öffnungen bleiben zu prüfen.'}],issues:[{code:'OPENING_RECHECK',severity:'attention',dayDate:input.startDate,providerPlaceIds:[],message:'Öffnungszeiten vor der Reise erneut prüfen.',suggestedRepair:''}],strengths:['Vollständig geplant'],repairInstructions:[],confidence:.94}});await attentionAudit.api.loadAiDayDraft(attentionAudit.state);assert.equal(attentionAudit.state.aiDraft.status,'ready','Attention-only audit findings stay visible without blocking a structurally valid plan');assert.equal(attentionAudit.state.aiDraft.audit.readyForReview,true);assert.equal(attentionAudit.state.aiDraft.audit.issues[0].severity,'attention');checked();
  const wrongPhoto=harness();await wrongPhoto.api.loadAiDayDraft(wrongPhoto.state);wrongPhoto.sandbox.LuviaPlacesContractV1.reads.getCard=async id=>({place:{providerPlaceId:'elsewhere'},image:{...photo,providerPlaceId:id}});await wrongPhoto.api.hydrateAiMedia(wrongPhoto.state,wrongPhoto.state.aiDraft.signature);assert.ok(wrongPhoto.state.draftSelections.every(e=>!e.imageUrl));checked();
  console.log(`Trip Composer: ${checks} behavioral recovery, validation, category and receipt checks passed (real Trip/Intelligence/Journey rules; controlled provider/storage/write adapters).`);
})().catch(error=>{console.error(error);process.exitCode=1});
