const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const integration=read('core/booking/booking-integration.js');
const control=read('app/control-center/booking-control-center.js');
const inbox=read('app/control-center/booking-inbox.js');
const migration=read('supabase/migrations/20260812115500_core_v4_81_0_booking_timeline_modify_cancel_conversation_lifecycle.sql');
const caps=read('core/platform/capability-registry.js');
assert(integration.includes("const VERSION='1.17.0'"));
for(const api of ['bookingTimeline','conversationPreferences','setConversationPreference','modifyBooking','cancelBooking'])assert(integration.includes(api),`missing ${api}`);
assert(!integration.includes("return transition(id,'cancelled'"),'legacy cancel must not directly force cancelled');
assert(integration.includes("bookingStatusChanged:false"),'email fallback must not claim final status');
assert(integration.includes("awaitingProviderReply:true"),'fallback must remain pending');
assert(control.includes('Booking Timeline'));
assert(control.includes('data-bcc-modify'));
assert(control.includes('data-bcc-cancel'));
assert(control.includes('evidenceDrivenFinalStatus:true'));
assert(control.includes("api.modifyBooking"));
assert(control.includes("api.cancelBooking"));
assert(inbox.includes("data-bi-filter=\"archive\""));
assert(inbox.includes("data-bi-pref=\"delete\""));
assert(inbox.includes('hardDeletesMessageTruth:false'));
assert(inbox.includes("window.confirm('Chat wirklich aus deiner Inbox löschen?"));
assert(migration.includes('create table if not exists public.booking_conversation_preferences'));
assert(migration.includes('luvia_booking_timeline_v1'));
assert(migration.includes('luvia_booking_record_mutation_fallback'));
assert(!/delete\s+from\s+public\.booking_messages/i.test(migration),'conversation delete must never hard-delete messages');
assert(!/delete\s+from\s+public\.booking_events/i.test(migration),'conversation delete must never delete audit events');
for(const id of ['booking.timeline','booking.mutations','booking.conversation.lifecycle'])assert(caps.includes(`id:'${id}'`),`missing capability ${id}`);
console.log('LUVIA_V13_81_0_BOOKING_TIMELINE_MODIFY_CANCEL_CONVERSATION_LIFECYCLE_OK');
