const fs=require('fs');
const assert=require('assert');
const js=fs.readFileSync('app/control-center/booking-control-center.js','utf8');
const css=fs.readFileSync('app/control-center/booking-control-center.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const version=fs.readFileSync('intelligence/kernel/version.js','utf8');
assert(js.includes("const VERSION='2.0.1'"));
assert(js.includes('data-bcc-action-execute="modify"'));
assert(js.includes('data-bcc-action-execute="cancel"'));
assert(js.includes("closest?.('[data-bcc-action-execute]')"));
assert(js.includes('mutationPayload(mode,form)'));
assert(js.indexOf('const payload=mutationPayload(mode,form)') < js.indexOf('actionBusy=true'));
assert(js.includes("if(!selectedBookingId&&rows.length&&!isMobile())"));
assert(js.includes('data-bcc-bookings-back'));
assert(js.includes('← Alle Buchungen'));
assert(js.includes('mobileBookingsFirst:true'));
assert(js.includes('mobileDetailNavigation:true'));
assert(js.includes('explicitMutationClick:true'));
assert(css.includes('.bcc.is-mobile-detail .bcc-list'));
assert(css.includes('.bcc:not(.is-mobile-detail) .bcc-detail{display:none}'));
assert(index.includes('app/control-center/booking-control-center.js?v=13.81.1'));
assert(sw.includes('luvia-shell-v13.81.1'));
assert(version.includes("core:'4.81.1'"));
assert(version.includes("build:'13.81.1'"));
console.log('LUVIA_V13_81_1_ACTION_RELIABILITY_MOBILE_BOOKING_DRILLDOWN_OK');
