const fs=require('fs'),vm=require('vm'),assert=require('assert');
const inbox=fs.readFileSync('app/control-center/booking-inbox.js','utf8');
const integration=fs.readFileSync('core/booking/booking-integration.js','utf8');
const shell=fs.readFileSync('app/app-shell.js','utf8');
const manifest=fs.readFileSync('app/control-center/control-center-manifest.js','utf8');
assert(inbox.includes("ownsMessageTruth:false"),'Inbox must not own message truth');
assert(inbox.includes("source:'booking-core'"),'Inbox must declare Booking Core source');
assert(inbox.includes("providerIndependent:true"),'Inbox must be provider independent');
assert(!inbox.includes(".from('booking_messages')"),'Inbox surface must not query booking_messages directly');
assert(!inbox.includes('.from("booking_messages")'),'Inbox surface must not query booking_messages directly');
assert(integration.includes('async function conversation(id)'),'Booking integration must expose conversation API');
assert(integration.includes("client.from('booking_message_intelligence')"),'Booking integration owns intelligence read seam');
assert(integration.includes("client.from('booking_email_threads')"),'Booking integration owns thread read seam');
assert(shell.includes("view==='control-center-inbox'"),'App shell must register inbox surface');
assert(manifest.includes("path:'/control-center/inbox',status:'available-v13.79'"),'Manifest must expose v13.79 inbox route');
const context={window:{LuviaProductModuleRegistry:{mount(){},unmount(){}},LuviaTripStore:{snapshot:()=>({trips:[],activeTripId:null})}},localStorage:{getItem(){return null},setItem(){}},console,setTimeout(){},Intl,Date,JSON,Map,Set,Object,String,Number,Boolean,Error};context.window.window=context.window;vm.createContext(context);vm.runInContext(inbox,context);
const d=context.window.LuviaBookingInbox.diagnostics();
assert.strictEqual(d.ownsMessageTruth,false);assert.strictEqual(d.ownsBookingTruth,false);assert.strictEqual(d.source,'booking-core');assert.strictEqual(d.providerIndependent,true);assert.strictEqual(d.composerTransport,'planned-v13.80');
console.log('LUVIA_V13_79_0_BOOKING_INBOX_CONVERSATIONS_OK');
