const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8');
const must=(cond,msg)=>{if(!cond)throw new Error(msg);console.log('PASS',msg)};
const index=read('index.html');
const shell=read('app/app-shell.js');
const sw=read('sw.js');
const client=read('core/booking/booking-availability.js');
const version=read('intelligence/kernel/version.js');
const migration=read('supabase/migrations/20260809093000_core_v4_61_2_availability_client_shell_integration_fix.sql');
must(index.includes('core/booking/booking-availability.js?v=13.61.2'),'availability client is in active index shell');
must(index.includes('data-luvia-booking-availability="true"'),'availability shell marker');
must(sw.includes("'core/booking/booking-availability.js'"),'availability client is in service-worker app shell');
must(sw.includes("CACHE='luvia-shell-v13.61.2'"),'new service-worker cache generation');
must(shell.includes('function ensureBookingAvailabilityClient()'),'app shell fallback loader');
must(shell.includes("BOOKING_AVAILABILITY_SRC='core/booking/booking-availability.js?v=13.61.2'"),'fallback uses current cache-busted client');
must(client.includes('window.LuviaBookingAvailability=Object.freeze'),'availability global registration');
must(client.includes('check,readiness,normalizeInput'),'availability public API');
must(version.includes("core:'4.61.2'")&&version.includes("build:'13.61.2'"),'build/core version');
must(migration.includes("'luvia_core','4.61.2'")&&migration.includes("'luvia_build','13.61.2'"),'release health metadata');
console.log('LUVIA_V13_61_2_AVAILABILITY_CLIENT_SHELL_INTEGRATION_OK');
