const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const mig=read('supabase/migrations/20260809185500_core_v4_68_1_email_recipient_validation_readiness_guard_fix.sql');
const send=read('supabase/functions/booking-email-send/index.ts');
const runtime=read('supabase/functions/booking-email-runtime/index.ts');
const browser=read('core/booking/booking-email-v2.js');
const index=read('index.html'),shell=read('app/app-shell.js'),sw=read('sw.js'),kernel=read('intelligence/kernel/version.js'),force=read('force-update.html');

assert(mig.includes('luvia_booking_email_recipient_validation'));
assert(mig.includes('EMAIL_ASSET_OR_FILE_REFERENCE'));
assert(mig.includes('BOOKING_PROVIDER_EMAIL_DOMAIN'));
assert(mig.includes('EMAIL_INVALID'));
assert(mig.includes('VENUE_EMAIL_NOT_VERIFIED'));
assert(mig.includes("jpg|jpeg|png|gif|webp|svg|ico"));
assert(mig.includes("v_validation := public.luvia_booking_email_recipient_validation(v_email)"));
assert(mig.includes("public.luvia_booking_email_recipient_validation(b.contact->>'email')"));
assert(send.includes("admin.rpc('luvia_booking_email_verified_candidate'"));
assert(send.includes("core:'4.68.1'"));
assert(runtime.includes("build:'13.68.1'"));
assert(runtime.includes("core:'4.68.1'"));
assert(browser.includes("const VERSION='1.0.1'"));
assert(index.includes('booking-email-v2.js?v=13.68.1'));
assert(shell.includes("BOOKING_EMAIL_V2_SRC='core/booking/booking-email-v2.js?v=13.68.1'"));
assert(sw.includes("const CACHE='luvia-shell-v13.68.1'"));
assert(kernel.includes("core:'4.68.1'"));
assert(kernel.includes("build:'13.68.1'"));
assert(force.includes('appv=13.68.1'));
console.log('LUVIA_V13_68_1_EMAIL_RECIPIENT_VALIDATION_READINESS_GUARD_FIX_OK');
