const fs=require('fs');
const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const fn=read('supabase/functions/booking-provider-reservation-mutation/index.ts');
const migration=read('supabase/migrations/20260809131500_core_v4_63_1_early_mutation_audit_fix.sql');
const index=read('index.html');
const shell=read('app/app-shell.js');
const sw=read('sw.js');
const version=read('intelligence/kernel/version.js');

assert(fn.includes("const VERSION='1.0.1'"));
assert(fn.includes("const BUILD='13.63.1'"));
assert(fn.includes("const CORE='4.63.1'"));
assert(fn.includes("const block=async(error:string"));
assert(fn.indexOf("const {data:created,error:createError}") < fn.indexOf("if(bookingState==='cancelled')return await block"));
assert(fn.indexOf("const {data:created,error:createError}") < fn.indexOf("if(!ref||!reservationReference)return await block('PROVIDER_RESERVATION_REFERENCE_REQUIRED')"));
assert(fn.includes("error_code:error"));
assert(fn.includes("finished_at:new Date().toISOString()"));
assert(migration.includes('alter column provider_id drop not null'));
assert(migration.includes('alter column reservation_reference drop not null'));
assert(migration.includes("'luvia_core','4.63.1'"));
assert(migration.includes("'luvia_build','13.63.1'"));
assert(index.includes('booking-reservation-mutation.js?v=13.63.1'));
assert(shell.includes('booking-reservation-mutation.js?v=13.63.1'));
assert(sw.includes("luvia-shell-v13.63.1"));
assert(version.includes("core:'4.63.1'"));
assert(version.includes("build:'13.63.1'"));
assert(!fn.includes(".from('bookings').update({status:'cancelled'"));
console.log('LUVIA_V13_63_1_EARLY_MUTATION_AUDIT_FIX_OK');
