const fs=require('fs');const assert=require('assert');
const integration=fs.readFileSync('core/booking/booking-integration.js','utf8');
const js=fs.readFileSync('app/control-center/booking-control-center.js','utf8');
const css=fs.readFileSync('app/control-center/booking-control-center.css','utf8');
const shellCss=fs.readFileSync('luvia-app-shell.css','utf8');
const index=fs.readFileSync('index.html','utf8');
const sw=fs.readFileSync('sw.js','utf8');
const version=fs.readFileSync('intelligence/kernel/version.js','utf8');
assert(integration.includes("const VERSION='1.17.1'"));
assert(integration.includes("'BOOKING_STATE_NOT_MODIFIABLE','BOOKING_STATE_NOT_CANCELLABLE'"),'state guards must be eligible for safe thread fallback');
assert(integration.includes('THREAD_MUTATION_REQUEST_STATES'));
assert(integration.includes('assertThreadFallbackAllowed'));
assert(integration.includes("'ready','forwarded','requested','awaiting_reply','alternative_proposed','needs_action','requires_action','review_required','confirmed'"));
assert(!integration.includes("THREAD_MUTATION_REQUEST_STATES=new Set(['cancelled'"));
assert(js.includes("const VERSION='2.0.2'"));
assert(js.includes('mutationErrorText(error,mode)'));
assert(js.includes("EMAIL_THREAD_REQUIRED:'Für diese Buchung gibt es keinen bestehenden Anbieter-Thread"));
assert(js.includes('mutationStateFallback:true'));
assert(js.includes('mobileActionSafeArea:true'));
const modalZ=Number((css.match(/\.bcc-action-sheet\{position:fixed;inset:0;z-index:(\d+)/)||[])[1]);
const navZ=Number((shellCss.match(/\.luvia-shell-nav\{position:fixed!important;[^}]*z-index:(\d+)/)||[])[1]);
assert(Number.isFinite(modalZ)&&Number.isFinite(navZ));
assert(modalZ>navZ,`modal z-index ${modalZ} must exceed shell nav ${navZ}`);
assert(css.includes('max-height:100dvh'));
assert(css.includes('.bcc-action-buttons{position:sticky;bottom:0'));
assert(css.includes('env(safe-area-inset-bottom)'));
assert(index.includes('app/control-center/booking-control-center.js?v=13.81.2'));
assert(sw.includes('luvia-shell-v13.81.2'));
assert(version.includes("core:'4.81.2'"));
assert(version.includes("build:'13.81.2'"));
console.log('LUVIA_V13_81_2_MUTATION_STATE_FALLBACK_MOBILE_ACTION_SAFE_AREA_OK');
