const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const migration=read('supabase/migrations/20260809163500_core_v4_65_0_reservation_mutation_recovery_reconciliation.sql');
const edge=read('supabase/functions/booking-provider-reservation-reconcile/index.ts');
const mutation=read('supabase/functions/booking-provider-reservation-mutation/index.ts');
const status=read('supabase/functions/booking-provider-reservation-mutation-status/index.ts');
const client=read('core/booking/booking-reservation-recovery.js');
const index=read('index.html'),shell=read('app/app-shell.js'),sw=read('sw.js'),version=read('intelligence/kernel/version.js');
assert(migration.includes('booking_reservation_mutation_reconciliation_attempts'));
assert(migration.includes('booking_reservation_mutation_reconciliation_queue_v1'));
assert(migration.includes("'reconciled'"));
assert(migration.includes('reconciliation_attempt_count'));
assert(migration.includes('luvia_booking_finalize_mutation_reconciliation_from_event'));
assert(migration.includes("v_source in ('provider_api','provider_webhook','provider_polling')"));
assert(migration.includes("new.source in ('provider_api','provider_webhook','provider_polling')"));
assert(edge.includes("const VERSION='1.0.0',BUILD='13.65.0',CORE='4.65.0'"));
assert(edge.includes("action:'get_reservation'"));
assert(!edge.includes("action:'cancel_reservation'"));
assert(!edge.includes("action:'update_reservation'"));
assert(!edge.includes("action:'create_reservation'"));
assert(edge.includes('neverReplayMutation:true'));
assert(edge.includes("p_source:'provider_polling'"));
assert(edge.includes('PARTNER_REQUIRED'));
assert(edge.includes('RECONCILIATION_AWAITING_WEBHOOK'));
assert(edge.includes('RECONCILIATION_STATUS_READ_TRANSPORT_NOT_IMPLEMENTED'));
assert(mutation.includes("const VERSION='1.2.0'"));
assert(mutation.includes("const BUILD='13.65.0'"));assert(mutation.includes("const CORE='4.65.0'"));
assert(mutation.includes("existing?.state==='reconciled'"));
assert(status.includes("BUILD='13.65.0',CORE='4.65.0'"));
assert(client.includes('window.LuviaBookingReservationRecovery'));
for(const fn of ['get','list','reconcile','history'])assert(client.includes(`async function ${fn}`));
assert(index.includes('booking-reservation-recovery.js?v=13.65.0'));
assert(shell.includes("BOOKING_RESERVATION_RECOVERY_SRC='core/booking/booking-reservation-recovery.js?v=13.65.0'"));
assert(shell.includes('ensureBookingReservationRecoveryClient'));
assert(sw.includes("luvia-shell-v13.65.0"));assert(sw.includes('core/booking/booking-reservation-recovery.js'));
assert(version.includes("core:'4.65.0'"));assert(version.includes("build:'13.65.0'"));
console.log('LUVIA_V13_65_0_RESERVATION_RECOVERY_RECONCILIATION_OK');
