const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const mig=fs.readFileSync(path.join(root,'supabase/migrations/20260810161000_core_v4_70_0_conversion_runtime_commercial_event_ingestion.sql'),'utf8');
const conversion=fs.readFileSync(path.join(root,'core/booking/booking-correlation-conversion.js'),'utf8');
const monetization=fs.readFileSync(path.join(root,'core/booking/booking-monetization.js'),'utf8');
const version=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
assert(mig.includes('create table if not exists public.booking_commercial_events'));
assert(mig.includes('booking_commercial_events_provider_event_uidx'));
assert(mig.includes('on conflict do nothing returning * into e'));
assert(mig.includes('COMMERCIAL_EVENT_INSERT_CONFLICT'));
assert(mig.includes('luvia_booking_ingest_commercial_event'));
assert(mig.includes('luvia_booking_process_commercial_event'));
assert(mig.includes('luvia_booking_verify_and_replay_commercial_event'));
assert(mig.includes("processing_state='pending_verification'"));
assert(mig.includes("processing_state='pending_partner_activation'"));
assert(mig.includes("processing_state='pending_unmatched'"));
assert(mig.includes("resolution_reason='PROVIDER_NOT_MONETIZABLE'"));
assert(mig.includes("if p.commercial_status<>'active' then"));
assert(mig.includes("raise exception 'COMMERCIAL_EVENT_MUTATED_BOOKING_STATUS'"));
assert(mig.includes("'bookingStatusChanged',false"));
assert(mig.includes("'reservationConfirmed',false"));
assert(mig.includes('public.luvia_booking_report_conversion('));
assert(mig.includes('public.luvia_booking_reconcile_conversion_report('));
assert(mig.includes('commercial_event_count'));
assert(mig.includes('pending_commercial_event_count'));
assert(conversion.includes("const VERSION='1.1.0'"));
assert(conversion.includes('COMMERCIAL_EVENT_KINDS'));
assert(conversion.includes('commercialEventIsConfirmation:false'));
assert(monetization.includes("const VERSION='1.1.0'"));
assert(monetization.includes('commercialEventCount'));
assert(monetization.includes('commercialWritesAreServerOnly:true'));
assert(version.includes("core:'4.70.0'"));
assert(version.includes("build:'13.70.0'"));
assert(index.includes('core/booking/booking-correlation-conversion.js?v=13.70.0'));
assert(index.includes('core/booking/booking-monetization.js?v=13.70.0'));
console.log('LUVIA_V13_70_0_CONVERSION_RUNTIME_COMMERCIAL_EVENT_INGESTION_OK');
