const fs=require('fs');
const assert=require('assert');
const migration=fs.readFileSync('supabase/migrations/20260808181500_core_v4_51_0_booking_correlation_conversion_foundation.sql','utf8');
const integration=fs.readFileSync('core/booking/booking-integration.js','utf8');
const correlation=fs.readFileSync('core/booking/booking-correlation-conversion.js','utf8');
const index=fs.readFileSync('index.html','utf8');
const kernel=fs.readFileSync('intelligence/kernel/version.js','utf8');
function has(text,needle,msg){assert(text.includes(needle),msg||`missing ${needle}`)}
has(migration,'create table if not exists public.booking_correlations','correlation table missing');
has(migration,'correlation_token uuid not null default gen_random_uuid() unique','durable token missing');
has(migration,'create table if not exists public.booking_conversion_reports','conversion reports missing');
has(migration,'bookingStatusChanged', 'conversion must explicitly state booking status unchanged');
has(migration,"'reservationConfirmed',false",'conversion must not imply confirmation');
has(migration,'luvia_booking_link_recent_place_handoff','recent handoff linker missing');
has(migration,'luvia_booking_link_correlation','token linker missing');
has(migration,'luvia_booking_report_conversion','conversion intake missing');
has(migration,'luvia_booking_get_handoff_correlation','handoff correlation lookup missing');
has(migration,'conversion_report_id uuid references public.booking_conversion_reports','conversion report foreign key missing');
has(migration,'CORRELATION_PROVIDER_MISMATCH','provider mismatch guard missing');
has(migration,'booking_correlation_conversion_summary','correlation summary missing');
has(migration,'external_event_id','idempotency event id missing');
has(integration,'linkRecentPlaceHandoff(ready.id,place)','created bookings must attempt correlation');
has(integration,'correlationJourney','correlation query API missing');
has(integration,'conversionReports','conversion query API missing');
has(correlation,'conversionIsConfirmation:false','client semantics unsafe');
has(correlation,'correlationMayExistWithoutBooking:true','pre-booking correlation semantic missing');
has(index,'booking-correlation-conversion.js?v=13.51.0','new module not loaded');
has(kernel,"core:'4.51.0'",'core version not bumped');
has(kernel,"build:'13.51.0'",'build version not bumped');
console.log('LUVIA_V13_51_0_BOOKING_CORRELATION_CONVERSION_FOUNDATION_OK');
