const fs=require('fs'),assert=require('assert');
const mig=fs.readFileSync('supabase/migrations/20260810134000_core_v4_69_0_attribution_core_monetization_foundation.sql','utf8');
const mod=fs.readFileSync('core/booking/booking-monetization.js','utf8');
const integration=fs.readFileSync('core/booking/booking-integration.js','utf8');
const index=fs.readFileSync('index.html','utf8');
assert(mig.includes('create table if not exists public.booking_monetization_profiles'));
assert(mig.includes('commercial_signal_can_confirm_reservation'));
assert(mig.includes('luvia_booking_prepare_monetized_handoff'));
assert(mig.includes('v_handoff_id:=public.luvia_booking_record_place_handoff'));
assert(mig.includes('booking_monetization_runtime_v1'));
assert(mig.includes('booking_status_changed_by_commercial'));
assert(mig.includes("('quandoo','Quandoo','partner_required','agent_attribution','agent_id'"));
assert(!mig.includes('commission_rate numeric'));
assert(mod.includes('commercialSignalCanConfirmReservation:false'));
assert(mod.includes('commissionCanConfirmReservation:false'));
assert(mod.includes('conversionCanConfirmReservation:false'));
assert(integration.includes("luvia_booking_prepare_monetized_handoff"));
assert(integration.includes("luvia_booking_record_place_handoff"));
assert(integration.includes('legacyFallback:true'));
assert(index.includes('core/booking/booking-monetization.js?v=13.69.0'));
console.log('LUVIA_V13_69_0_ATTRIBUTION_MONETIZATION_FOUNDATION_OK');
