const fs=require('fs');const assert=require('assert');
const root=require('path').resolve(__dirname,'..');
const read=p=>fs.readFileSync(require('path').join(root,p),'utf8');
const fn=read('supabase/functions/booking-provider-connection-health/index.ts');
const mig=read('supabase/migrations/20260809082800_core_v4_60_0_provider_connection_secrets_readiness_admin_activation_control.sql');
const client=read('core/booking/booking-provider-connections.js');
assert(fn.includes("const VERSION='4.0.0'"));
assert(fn.includes("'set_activation_control'"));
assert(fn.includes("ADMIN_ACTIVATION_APPROVAL_REQUIRED"));
assert(fn.includes("LIVE_PROBE_STALE_OR_MISSING"));
assert(fn.includes('requiredSecretCount:secret.required'));
assert(fn.includes('configuredSecretCount:secret.configured'));
assert(!fn.includes('secretValues:'));
assert(!fn.includes('secretValue:'));
assert(fn.includes('secretValuesStored:false'));
assert(mig.includes('booking_provider_connection_readiness_v6'));
assert(mig.includes('booking_provider_activation_controls'));
assert(mig.includes('booking_provider_admin_actions'));
assert(mig.includes('revoke all on public.booking_provider_activation_controls from public,anon,authenticated'));
assert(mig.includes("interval '10 minutes'"));
assert(client.includes("booking_provider_connection_readiness_v6"));
console.log('LUVIA_V13_60_0_PROVIDER_SECRETS_ADMIN_ACTIVATION_OK');
