const fs=require('fs');
const read=p=>fs.readFileSync(p,'utf8');
const must=(cond,msg)=>{if(!cond)throw new Error(msg);console.log('PASS',msg)};
const mig=read('supabase/migrations/20260809090200_core_v4_61_0_provider_availability_runtime_v1.sql');
const fn=read('supabase/functions/booking-provider-availability/index.ts');
const client=read('core/booking/booking-availability.js');
const version=read('intelligence/kernel/version.js');
must(mig.includes('booking_availability_requests'),'availability request audit table');
must(mig.includes('booking_availability_snapshots'),'availability snapshots');
must(mig.includes('booking_provider_availability_readiness_v1'),'availability readiness view');
must(mig.includes('revoke all on public.booking_availability_requests from public,anon,authenticated'),'audit storage is service-role only');
must(fn.includes("availability_runtime_state!=='ready'"),'readiness gate before provider call');
must(fn.includes("return json({ok:false,expected:true"),'expected-state transport normalization');
must(fn.includes('setTimeout(()=>controller.abort(),6500)'),'bounded provider timeout');
must(fn.includes('providerSlotReference'),'provider slot reference preserved');
must(!fn.includes('fakeSlot')&&!fn.includes('generateSlots'),'no fake slot generation');
must(client.includes("functions.invoke('booking-provider-availability'"),'browser client uses canonical availability function');
must(version.includes("core:'4.61.1'")&&version.includes("build:'13.61.1'"),'build/core version');
console.log('LUVIA_V13_61_1_PROVIDER_AVAILABILITY_RUNTIME_OK');
