const fs=require('fs');
const assert=require('assert');
const root=require('path').resolve(__dirname,'..');
const read=p=>fs.readFileSync(require('path').join(root,p),'utf8');
const mig=read('supabase/migrations/20260809214500_core_v4_68_5_placeholder_email_detection_verified_candidate_ranking_fix.sql');
const resolver=read('supabase/functions/booking-contact-resolve/index.ts');
const runtime=read('supabase/functions/booking-email-runtime/index.ts');
const client=read('core/booking/booking-email-v2.js');
const sw=read('sw.js');
const index=read('index.html');
assert(mig.includes('luvia_booking_is_placeholder_email'));
assert(mig.includes("'PLACEHOLDER_EMAIL'"));
assert(mig.includes("verification_status='rejected'"));
assert(mig.includes('legacyContactMatch'));
assert(mig.includes("'luvia_core','4.68.5'"));
assert(mig.includes("'luvia_build','13.68.5'"));
assert(resolver.includes("const VERSION='1.3.1'"));
assert(resolver.includes("return 'PLACEHOLDER_EMAIL'"));
assert(runtime.includes("build:'13.68.5',core:'4.68.5'"));
assert(client.includes("const VERSION='1.0.4'"));
assert(sw.includes("const CACHE='luvia-shell-v13.68.5'"));
assert(index.includes('booking-email-v2.js?v=13.68.5'));
console.log('LUVIA_V13_68_5_PLACEHOLDER_EMAIL_RANKING_OK');
