const fs=require('fs'),vm=require('vm'),assert=require('assert');
const context={window:{LuviaPreferenceSchema:{normalizePreferences:x=>x,summary:()=>[{label:'Vegetarisch'},{label:'Mit Kinderwagen'}]}},console};vm.createContext(context);
vm.runInContext(fs.readFileSync('core/places/global-place-contracts.js','utf8'),context);
const C=context.window.LuviaGlobalPlaceContracts;
assert.equal(C.version,'4.50.0');
assert(C.categories.accommodation&&C.categories.photo,'Universal Direkt-entdecken categories missing');
assert.equal(C.intentFor('Etwas finden, das nicht jeder Tourist kennt','activities').key,'hidden_gem');
assert.equal(C.accepts({id:'mass',name:'Palais de Tokyo',types:['museum'],userRatingCount:6000},'activities','Etwas finden, das nicht jeder Tourist kennt',{}),false);
assert.equal(C.accepts({id:'gem',name:'Petite Ceinture Secret Garden',types:['tourist_attraction'],userRatingCount:340},'activities','Etwas finden, das nicht jeder Tourist kennt',{}),true);
let r=C.relevance({id:'veg',name:'Veggie Place',types:['restaurant'],features:{servesVegetarianFood:true}},'vegetarisch essen','food',{dietaryPreferences:['vegetarian']});
assert(r.reasons.some(x=>/ausdrücklich belegt/.test(x))&&!r.reasons.some(x=>/nicht eindeutig verifiziert/.test(x)),'Conflicting vegetarian evidence');
const places=fs.readFileSync('core/places/places-final-foundation.js','utf8');
assert(places.includes("|;+/i).map(clean)"),'Comma subordinate-clause fix missing');
assert(places.includes('window.LuviaAI.interpretDiscovery'),'AI discovery planning missing');
assert(places.includes('window.LuviaAI.rankCandidates'),'AI candidate ranking missing');
const booking=fs.readFileSync('core/booking/booking-status-attribution-v2.js','utf8');
assert(booking.includes("NON_CONFIRMING=new Set(['handoff','affiliate_callback'])"),'Non-confirming attribution rule missing');
const migration=fs.readFileSync('supabase/migrations/20260808172000_core_v4_50_0_booking_status_attribution_v2.sql','utf8');
for(const token of ['booking_status_signals','booking_attribution_events_v2','NON_CONFIRMING_SOURCE','booking_handoff_events_v2_mirror','booking_affiliate_clicks_v2_mirror','booking_affiliate_conversions_v2_mirror'])assert(migration.includes(token),token);
console.log('LUVIA_V13_50_0_BOOKING_STATUS_ATTRIBUTION_V2_OK');
console.log('LUVIA_V13_50_0_REISEKOMPASS_UNIVERSAL_PLACES_PRECISION_OK');
