const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const mig=fs.readFileSync(path.join(root,'supabase/migrations/20260810214500_core_v4_71_0_production_commission_revenue_lifecycle.sql'),'utf8');
const monetization=fs.readFileSync(path.join(root,'core/booking/booking-monetization.js'),'utf8');
const reconciliation=fs.readFileSync(path.join(root,'core/booking/booking-reconciliation-provider-return.js'),'utf8');
const version=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');

assert(mig.includes('create table if not exists public.booking_commission_state_events'));
assert(mig.includes('create or replace function public.luvia_booking_commission_transition_allowed'));
assert(mig.includes('create or replace function public.luvia_booking_apply_commission_lifecycle'));
assert(mig.includes("when p_from='paid' then p_to='disputed'"),'paid must not move backwards except to dispute');
assert(mig.includes("raise exception 'COMMISSION_TRANSITION_INVALID:%->%'"));
assert(mig.includes("raise exception 'COMMISSION_PAID_AMOUNT_CONFLICT'"));
assert(mig.includes("v_is_commission_event:=e.event_kind like 'commission_%'"));
assert(mig.includes("'COMMISSION_CONVERSION_AMBIGUOUS'"));
assert(mig.includes("'COMMISSION_CONVERSION_NOT_FOUND'"));
assert(mig.includes('v_reconciliation_result:=public.luvia_booking_apply_commission_lifecycle('));
assert(mig.includes('create or replace view public.booking_commission_runtime_v1'));
assert(mig.includes('create or replace view public.booking_commission_revenue_summary_v1'));
assert(mig.includes("sum(case when state='paid' then settled_amount else 0 end) paid_commission_amount"));
assert(mig.includes("raise exception 'COMMERCIAL_EVENT_MUTATED_BOOKING_STATUS'"));
assert(mig.includes("'bookingStatusChanged',false"));
assert(mig.includes("'reservationConfirmed',false"));
assert(!mig.includes('commission_rate'),'must not invent/store inferred commission rates in v13.71.0');
assert(monetization.includes("const VERSION='1.2.0'"));
assert(monetization.includes('commissionEventsAttachToExistingConversion:true'));
assert(monetization.includes('paidCommissionUsesSettledFactsOnly:true'));
assert(reconciliation.includes('commissionTransitionAudit:true'));
assert(version.includes("core:'4.71.0'"));
assert(version.includes("build:'13.71.0'"));
assert(index.includes('?v=13.71.0'));
assert(sw.includes("luvia-shell-v13.71.0"));
console.log('LUVIA_V13_71_0_PRODUCTION_COMMISSION_REVENUE_LIFECYCLE_OK');
