const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const migration=read('supabase/migrations/20260809154500_core_v4_64_0_reservation_lifecycle_synchronization.sql');
const mutation=read('supabase/functions/booking-provider-reservation-mutation/index.ts');
const statusFn=read('supabase/functions/booking-provider-reservation-mutation-status/index.ts');
const client=read('core/booking/booking-reservation-mutation-status.js');
const index=read('index.html'),shell=read('app/app-shell.js'),sw=read('sw.js'),version=read('intelligence/kernel/version.js');
assert(migration.includes('booking_reservation_mutation_status_events'));
assert(migration.includes('luvia_booking_ingest_reservation_mutation_status'));
assert(migration.includes('booking_reservation_mutation_lifecycle_v1'));
assert(migration.includes("'pending','accepted','rejected','alternative_proposed','cancelled','failed','unknown'"));
assert(migration.includes('reconciliation_required'));
assert(migration.includes('provider_outcome_known'));
assert(migration.includes("if v_luvia is not null and v_source <> 'system'"));
assert(migration.includes('luvia_booking_ingest_status_signal'));
assert(migration.includes("v_action='cancel' and v_mutation='cancelled'"));
assert(mutation.includes("const VERSION='1.1.0'"));
assert(mutation.includes("const BUILD='13.64.0'"));
assert(mutation.includes("const CORE='4.64.0'"));
assert(mutation.includes("recordLifecycle('pending','system','CALLING_PROVIDER'"));
assert(mutation.includes("recordLifecycle('unknown','system'"));
assert(mutation.includes('normalizedMutationLifecycle'));
assert(mutation.includes("action==='cancel'&&['cancel_request_accepted','cancellation_requested','cancel_pending'].includes(p)"));
assert(mutation.includes("recordLifecycle(mutationLifecycleState,'provider_api'"));
assert(!mutation.includes(".from('bookings').update({status:"));
assert(!mutation.includes("update({status:'cancelled'"));
assert(statusFn.includes('booking_reservation_mutation_status_events'));
assert(statusFn.includes("mode!=='get'&&mode!=='history'"));
assert(statusFn.includes("MUTATION_REQUEST_NOT_ACCESSIBLE"));
assert(mutation.indexOf("const {data:created,error:createError}") < mutation.indexOf("if(bookingState==='cancelled')return await block"));
assert(mutation.indexOf("const {data:created,error:createError}") < mutation.indexOf("if(!ref||!reservationReference)return await block('PROVIDER_RESERVATION_REFERENCE_REQUIRED')"));
assert(client.includes('window.LuviaBookingReservationMutationStatus'));
assert(client.includes('get,history,normalize'));
assert(index.includes('booking-reservation-mutation-status.js?v=13.64.0'));
assert(shell.includes('ensureBookingReservationMutationStatusClient'));
assert(shell.includes('booking-reservation-mutation-status.js?v=13.64.0'));
assert(sw.includes("luvia-shell-v13.64.0"));
assert(sw.includes('core/booking/booking-reservation-mutation-status.js'));
assert(version.includes("core:'4.64.0'"));assert(version.includes("build:'13.64.0'"));
console.log('LUVIA_V13_64_0_RESERVATION_LIFECYCLE_SYNCHRONIZATION_OK');
