const assert=require('assert');
const fs=require('fs');
const path=require('path');
const root=path.resolve(__dirname,'..');
const mig=fs.readFileSync(path.join(root,'supabase/migrations/20260810193500_core_v4_70_2_early_commercial_correlation_pending_replay_fix.sql'),'utf8');
const version=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const corrPos=mig.indexOf("if e.correlation_token is not null then");
const profilePos=mig.indexOf("select * into p from public.booking_monetization_profiles where provider_id=e.provider_id;");
assert(corrPos>0 && profilePos>corrPos,'correlation must resolve before commercial readiness');
assert(mig.includes("set correlation_id=c.id,correlation_token=c.correlation_token"));
assert(mig.includes("processing_state='pending_partner_activation'"));
assert(mig.includes("resolution_reason='COMMERCIAL_PARTNER_NOT_ACTIVE'"));
assert(mig.includes('create or replace function public.luvia_booking_replay_commercial_event'));
assert(mig.includes("existing.processing_state in ('pending_partner_activation','pending_unmatched','failed','received')"));
assert(mig.includes("'duplicate',true,'replayed'"));
assert(mig.includes("raise exception 'COMMERCIAL_EVENT_MUTATED_BOOKING_STATUS'"));
assert(mig.includes("'bookingStatusChanged',false"));
assert(mig.includes("'reservationConfirmed',false"));
assert(version.includes("core:'4.70.2'"));
assert(version.includes("build:'13.70.2'"));
assert(index.includes('?v=13.70.2'));
console.log('LUVIA_V13_70_2_EARLY_COMMERCIAL_CORRELATION_PENDING_REPLAY_OK');
