const fs=require('fs');const assert=require('assert');
const root=process.cwd();
const read=p=>fs.readFileSync(p,'utf8');
const mig=read('supabase/migrations/20260809073000_core_v4_57_0_provider_activation_runtime_email_ownership_guard.sql');
const contact=read('supabase/functions/booking-contact-resolve/index.ts');
const health=read('supabase/functions/booking-provider-connection-health/index.ts');
const version=read('intelligence/kernel/version.js');
assert(version.includes("core:'4.57.0'"));assert(version.includes("build:'13.57.0'"));
assert(mig.includes('booking_provider_connection_readiness_v3'));
assert(mig.includes('booking_provider_connection_events'));
assert(mig.includes('luvia_booking_is_provider_email_domain'));
assert(mig.includes("verification_status='rejected'"));
assert(contact.includes("const VERSION='1.2.0'"));
assert(contact.includes('BOOKING_PROVIDER_EMAIL_DOMAIN'));
assert(contact.includes("delete sanitizedContact.email"));
assert(health.includes("const VERSION='1.1.0'"));
assert(health.includes("ready_to_activate"));
assert(health.includes("CREDENTIALS_CONFIGURED_PROBE_REQUIRED"));
assert(!health.includes("creds==='configured'?'connected'"));
console.log('LUVIA_V13_57_0_PROVIDER_ACTIVATION_EMAIL_OWNERSHIP_OK');
