const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const fn=read('supabase/functions/booking-provider-connection-health/index.ts');
const mig=read('supabase/migrations/20260809080500_core_v4_59_0_provider_activation_orchestrator_expected_state_cleanup.sql');
const conn=read('core/booking/booking-provider-connections.js');
const ver=read('intelligence/kernel/version.js');
assert(fn.includes("'orchestrate'"));
assert(fn.includes("expected('SERVICE_ROLE_REQUIRED'"));
assert(fn.includes("return json({ok:false,expected:true" ) || fn.includes("const expected="));
assert(fn.includes('backoffMinutes'));
assert(fn.includes("state:'ready_to_probe'"));
assert(fn.includes('booking_provider_activation_runs'));
assert(fn.includes("body?.allowActivation===true"));
assert(fn.includes("body?.confirmActivation===true"));
assert(mig.includes('booking_provider_connection_readiness_v5'));
assert(mig.includes('consecutive_probe_failures'));
assert(mig.includes('next_probe_at'));
assert(mig.includes('booking_provider_activation_runs'));
assert(conn.includes('orchestrate'));
assert(conn.includes('booking_provider_connection_readiness_v5'));
assert(ver.includes("core:'4.59.0'"));
assert(ver.includes("build:'13.59.0'"));
console.log('LUVIA_V13_59_0_PROVIDER_ACTIVATION_ORCHESTRATOR_EXPECTED_STATE_CLEANUP_OK');
