const fs=require('fs');const assert=require('assert');
const read=p=>fs.readFileSync(p,'utf8');
const migration=read('supabase/migrations/20260809113000_core_v4_63_0_reservation_modify_cancel_runtime_v1.sql');
const fn=read('supabase/functions/booking-provider-reservation-mutation/index.ts');
const client=read('core/booking/booking-reservation-mutation.js');
const caps=read('core/booking/booking-provider-capabilities.js');
const index=read('index.html');const shell=read('app/app-shell.js');const sw=read('sw.js');const version=read('intelligence/kernel/version.js');
assert(migration.includes('supports_modify_reservation'));
assert(migration.includes('supports_cancel_reservation'));
assert(migration.includes('booking_reservation_modify_requests'));
assert(migration.includes('booking_reservation_cancel_requests'));
assert(migration.includes('booking_provider_reservation_modify_readiness_v1'));
assert(migration.includes('booking_provider_reservation_cancel_readiness_v1'));
assert(migration.includes('unique(booking_id,idempotency_key)'));
assert(migration.includes("where provider_id='zenchef'"));
assert(migration.includes("provider_id in ('opentable','sevenrooms','resy')"));
assert(fn.includes("modify:{zenchef:'update_reservation'}"));
assert(fn.includes("cancel:{opentable:'cancel_reservation',sevenrooms:'cancel_reservation',resy:'cancel_reservation'}"));
assert(fn.includes('PROVIDER_RESERVATION_REFERENCE_REQUIRED'));
assert(fn.includes('BOOKING_PROVIDER_REFERENCE_MISMATCH'));
assert(fn.includes('RESERVATION_MUTATION_RECONCILIATION_REQUIRED'));
assert(fn.includes('ambiguousProviderOutcome:true'));
assert(fn.includes("p_source:'provider_api'"));
assert(fn.includes('luvia_booking_ingest_status_signal'));
assert(fn.includes("p_reference_state:'cancelled'"));
assert(!fn.includes("update({status:'cancelled'"));
assert(!fn.includes('fakeReservation'));
assert(client.includes('window.LuviaBookingReservationMutation'));
assert(client.includes('modify,cancel,readiness'));
assert(caps.includes('modifyReservation:true,cancelReservation:false'));
assert(caps.includes('modifyReservation:false,cancelReservation:true'));
assert(index.includes('booking-reservation-mutation.js?v=13.63.0'));
assert(shell.includes('ensureBookingReservationMutationClient'));
assert(sw.includes('core/booking/booking-reservation-mutation.js'));
assert(sw.includes("luvia-shell-v13.63.0"));
assert(version.includes("core:'4.63.0'"));assert(version.includes("build:'13.63.0'"));
console.log('LUVIA_V13_63_0_RESERVATION_MODIFY_CANCEL_RUNTIME_OK');
