const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const version=read('intelligence/kernel/version.js');
const migration=read('supabase/migrations/20260809074500_core_v4_58_0_provider_credential_activation_live_probe_runtime.sql');
const fn=read('supabase/functions/booking-provider-connection-health/index.ts');
const client=read('core/booking/booking-provider-connections.js');
assert(version.includes("core:'4.58.0'"));
assert(version.includes("build:'13.58.0'"));
assert(migration.includes('booking_provider_probe_runs'));
assert(migration.includes('booking_provider_connection_readiness_v4'));
assert(migration.includes("'running'"));
assert(fn.includes("(action==='probe'||action==='activate')&&!isService"));
assert(fn.includes('ACTIVATION_CONFIRMATION_REQUIRED'));
assert(fn.includes("method:'GET'"));
assert(fn.includes("'X-Quandoo-AuthToken':token"));
assert(fn.includes('setTimeout(()=>controller.abort(),5000)'));
assert(fn.includes('QUANDOO_PROBE_MERCHANT_ID'));
assert(!fn.includes('console.log(token)'));
assert(client.includes('async function probe(providerId)'));
assert(client.includes('async function activate(providerId'));
assert(client.includes("booking_provider_connection_readiness_v4"));
console.log('LUVIA_V13_58_0_PROVIDER_CREDENTIAL_ACTIVATION_LIVE_PROBE_RUNTIME_OK');
