const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');
const mig66=read('supabase/migrations/20260809170500_core_v4_66_0_email_booking_v2_request_runtime.sql');
const mig67=read('supabase/migrations/20260809172000_core_v4_67_0_email_booking_v2_thread_reply_status.sql');
const mig68=read('supabase/migrations/20260809174000_core_v4_68_0_email_booking_v2_completion_recovery.sql');
const send=read('supabase/functions/booking-email-send/index.ts');
const inbound=read('supabase/functions/booking-email-inbound/index.ts');
const runtime=read('supabase/functions/booking-email-runtime/index.ts');
const browser=read('core/booking/booking-email-v2.js');
const index=read('index.html'),shell=read('app/app-shell.js'),sw=read('sw.js'),kernel=read('intelligence/kernel/version.js');
assert(mig66.includes('booking_email_requests'));
assert(mig66.includes('luvia_booking_email_verified_candidate'));
assert(mig66.includes('BOOKING_PROVIDER_EMAIL_DOMAIN'));
assert(mig66.includes('VENUE_EMAIL_NOT_VERIFIED'));
assert(mig67.includes('booking_email_threads'));
assert(mig67.includes('booking_email_delivery_events'));
assert(mig67.includes('luvia_booking_match_inbound_v2'));
assert(mig67.includes('luvia_booking_process_inbound_intelligence_v2'));
assert(mig67.includes('luvia_booking_ingest_status_signal_internal'));
assert(!mig67.includes("update public.bookings set\n  status="));
assert(mig68.includes('booking_email_recovery_queue_v2'));
assert(mig68.includes('No automatic resend')||mig68.includes('No automatic resend.'.toLowerCase())===false);
assert(send.includes('userApproved!==true'));
assert(send.includes('luvia_booking_email_verified_candidate'));
assert(send.includes('booking_email_requests'));
assert(send.includes('booking_email_threads'));
assert(inbound.includes('luvia_booking_match_inbound_v2'));
assert(inbound.includes('luvia_booking_process_inbound_intelligence_v2'));
assert(inbound.includes('luvia_booking_email_mark_delivery'));
assert(runtime.includes("action==='readiness'"));
assert(runtime.includes("action==='history'"));
assert(browser.includes('window.LuviaBookingEmailV2'));
for(const method of ['readiness','get','history','queue','send'])assert(browser.includes(method));
assert(index.includes('booking-email-v2.js?v=13.68.0'));
assert(shell.includes('ensureBookingEmailV2Client'));
assert(sw.includes("luvia-shell-v13.68.0"));assert(sw.includes('core/booking/booking-email-v2.js'));
assert(kernel.includes("core:'4.68.0'"));assert(kernel.includes("build:'13.68.0'"));
console.log('LUVIA_V13_68_0_EMAIL_BOOKING_V2_OK');
