const fs=require('fs'),vm=require('vm'),assert=require('assert');
const inbox=fs.readFileSync('app/control-center/booking-inbox.js','utf8');
const integration=fs.readFileSync('core/booking/booking-integration.js','utf8');
const manifest=fs.readFileSync('app/control-center/control-center-manifest.js','utf8');
const migration=fs.readFileSync('supabase/migrations/20260812104500_core_v4_80_0_booking_actions_intelligence.sql','utf8');
const replyFn=fs.readFileSync('supabase/functions/booking-email-reply/index.ts','utf8');
const config=fs.readFileSync('supabase/config.toml','utf8');
assert(inbox.includes("composerTransport:'booking-email-reply-v1'"),'Inbox must expose live reply transport');
assert(inbox.includes('accept_alternative'),'Alternative accept action missing');
assert(inbox.includes('decline_alternative'),'Alternative decline action missing');
assert(inbox.includes("action:'answer'"),'requires_action answer flow missing');
assert(!inbox.includes(".from('booking_messages')"),'Inbox surface must not query message truth directly');
assert(integration.includes('async function reply(id,'),'Booking integration reply seam missing');
assert(integration.includes("client.functions.invoke('booking-email-reply'"),'Reply must use dedicated Edge Function');
assert(integration.includes('async function resolveIntelligence'),'Intelligence resolution seam missing');
assert(integration.includes('async function performIntelligenceAction'),'Action orchestration seam missing');
assert(migration.includes('review_state'),'Persistent intelligence review state missing');
assert(migration.includes('luvia_booking_resolve_message_intelligence'),'Intelligence resolution RPC missing');
assert(migration.includes('booking_message_intelligence_review_state_sync'),'Future action-required intelligence must auto-open review state');
assert(migration.includes("'booking.message.intelligence.resolved'"),'Action audit event missing');
assert(replyFn.includes("from('booking_email_threads')"),'Reply function must require existing thread');
assert(replyFn.includes("rpc('luvia_booking_record_message'"),'Reply function must store through canonical message RPC');
assert(replyFn.includes("reply_to:thread.reply_alias"),'Reply-To alias threading missing');
assert(replyFn.includes("state:'awaiting_reply'"),'Thread state must move to awaiting_reply');
assert(replyFn.includes("rpc('luvia_booking_resolve_message_intelligence'"),'Reply must persist related intelligence action');
assert(config.includes('[functions.booking-email-reply]')&&config.includes('verify_jwt = true'),'Reply function JWT guard missing');
assert(manifest.includes("path:'/control-center/inbox',status:'available-v13.79'"),'Manifest must expose v13.80 Inbox');
const context={window:{LuviaProductModuleRegistry:{mount(){},unmount(){}},LuviaTripStore:{snapshot:()=>({trips:[],activeTripId:null})}},localStorage:{getItem(){return null},setItem(){}},console,setTimeout(){},Intl,Date,JSON,Map,Set,Object,String,Number,Boolean,Error};context.window.window=context.window;vm.createContext(context);vm.runInContext(inbox,context);const d=context.window.LuviaBookingInbox.diagnostics();assert.strictEqual(d.ownsMessageTruth,false);assert.strictEqual(d.ownsBookingTruth,false);assert.strictEqual(d.composerTransport,'booking-email-reply-v1');assert.strictEqual(d.intelligenceActions,true);
console.log('LUVIA_V13_80_0_BOOKING_ACTIONS_INTELLIGENCE_OK');
