const fs=require('fs');
const path=require('path');
const assert=(v,m)=>{if(!v)throw new Error(m)};
const root=path.resolve(__dirname,'..');
const resolver=fs.readFileSync(path.join(root,'supabase/functions/booking-contact-resolve/index.ts'),'utf8');
const mig=fs.readFileSync(path.join(root,'supabase/migrations/20260809201500_core_v4_68_4_contact_resolver_candidate_bridge_legacy_contact_verification_fix.sql'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const shell=fs.readFileSync(path.join(root,'app/app-shell.js'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const kernel=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');

assert(resolver.includes("const VERSION='1.3.0'"),'resolver version');
assert(!resolver.includes("if(existing&&!isProviderEmail(existing))return json({ok:true,resolved:true,channel:'email',value:existing,reason:'CONTACT_ALREADY_PRESENT'})"),'legacy early return removed');
assert(resolver.includes("legacyEmail=(existing&&!isProviderEmail(existing)&&validEmail(existing))?existing:''"),'legacy email captured');
assert(resolver.includes("legacyContactMatch:isLegacyMatch"),'legacy evidence');
assert(resolver.includes("candidateBridge:isLegacyMatch?'legacy_booking_contact_verified':'discovered_official_contact'"),'candidate bridge metadata');
assert(resolver.includes("p_verification_status:'verified'"),'verified only from discovered page');
assert(resolver.includes("p_is_public:true")&&resolver.includes("p_is_official:true"),'public official flags');
assert(resolver.includes("isProviderEmail(existing)"),'provider guard retained');
assert(resolver.includes("LEGACY_CONTACT_REQUIRES_OFFICIAL_VERIFICATION"),'no website safe failure');
assert(resolver.includes("LEGACY_CONTACT_NOT_PUBLISHED_ON_OFFICIAL_SOURCE"),'unverified legacy result');
assert(resolver.includes("LEGACY_CONTACT_VERIFIED_AND_BRIDGED"),'verified bridge result');
assert(resolver.includes("luvia_booking_upsert_candidate"),'central candidate upsert');
assert(resolver.includes("luvia_booking_resolve_channel"),'central channel resolution');
assert(mig.includes("'luvia_core','4.68.4'"),'migration core');
assert(mig.includes("'luvia_build','13.68.4'"),'migration build');
assert(index.includes('booking-email-v2.js?v=13.68.4'),'index cache bust');
assert(shell.includes("BOOKING_EMAIL_V2_SRC='core/booking/booking-email-v2.js?v=13.68.4'"),'shell cache bust');
assert(sw.includes("const CACHE='luvia-shell-v13.68.4'"),'service worker cache');
assert(kernel.includes("core:'4.68.4'")&&kernel.includes("build:'13.68.4'"),'kernel version');
console.log('LUVIA_V13_68_4_CONTACT_RESOLVER_CANDIDATE_BRIDGE_OK');
