const fs=require('fs'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const fn=fs.readFileSync(path.join(root,'supabase/functions/booking-email-reply/index.ts'),'utf8');
const js=fs.readFileSync(path.join(root,'app/control-center/booking-inbox.js'),'utf8');
const css=fs.readFileSync(path.join(root,'app/control-center/booking-inbox.css'),'utf8');
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');
const sw=fs.readFileSync(path.join(root,'sw.js'),'utf8');
const version=fs.readFileSync(path.join(root,'intelligence/kernel/version.js'),'utf8');
assert(fn.includes("if(!verified?.ok)"),'reply must honor RPC ok field');
assert(!fn.includes('verified?.verified||!verified?.autoUsable'),'obsolete RPC shape must not be used');
assert(fn.includes("reason:verified?.reason||'VENUE_EMAIL_NOT_VERIFIED'"),'verification reason should remain observable');
assert(js.includes("const isMobile=()=>Boolean(window.matchMedia?.('(max-width: 780px)')?.matches)"),'mobile detection missing');
assert(js.includes("if(!selectedBookingId&&threads.length&&!isMobile())"),'mobile inbox must not auto-open a thread');
assert(js.includes('data-bi-inbox-back'),'mobile inbox back action missing');
assert(js.includes('mobileInboxFirst:true')&&js.includes('mobileBackNavigation:true'),'mobile diagnostics missing');
assert(css.includes('.bi-mobile-inbox-back{display:none')&&css.includes('@media(max-width:780px){.bi-mobile-inbox-back{display:inline-flex'),'mobile back styling missing');
assert(index.includes('booking-inbox.js?v=13.80.2'),'index cache busting wrong');
assert(sw.includes('luvia-shell-v13.80.2'),'service worker cache wrong');
assert(version.includes("core:'4.80.2'")&&version.includes("build:'13.80.2'"),'kernel version wrong');
console.log('LUVIA_V13_80_2_REPLY_VERIFICATION_MOBILE_INBOX_OK');
