(()=>{'use strict';
const MODULE_ID='attractions',VERSION='4.6.2';
const QUICK=[['✨','Entdecken','Sehenswürdigkeiten und Aktivitäten'],['🏛️','Sehenswürdigkeiten','Sehenswürdigkeiten'],['🖼️','Museen','Museen'],['🎡','Aktivitäten','Freizeitaktivitäten'],['🌳','Parks','Parks und Gärten'],['🔭','Aussicht','Aussichtspunkte'],['👨‍👩‍👧','Familie','familienfreundliche Aktivitäten'],['🌦️','Indoor & Outdoor','Indoor und Outdoor Aktivitäten']];
const state={root:null,trip:null,query:'Sehenswürdigkeiten und Aktivitäten',filter:'Entdecken',options:{},results:[],entities:[],searchMap:new Map(),routeCache:new Map(),loading:false,error:null,visibleCount:6};
const esc=v=>window.LuviaPlaceExperience?.esc?.(v)||String(v??'');
const tripId=()=>state.trip?.tripId||state.trip?.id||window.LuviaTripStore?.snapshot?.().activeTrip?.id;
const destination=()=>state.trip?.destination?.name||state.trip?.destinationName||window.LuviaDestination?.getActive?.()?.canonicalCity?.name||'eurem Reiseziel';
const place=e=>e?.place||e||{},link=e=>e?.tripPlace||e?.trip_place||{};
const ext=e=>{const legacy=e?.extension||e?.attraction||{},id=link(e)?.id||e?.tripPlaceId;const cloud=id?window.LuviaTripPlaceData?.recordForTripPlace?.(id)?.fields||{}:{};return {...legacy,...cloud}};
const providerId=p=>String(p?.providerPlaceId||p?.provider_place_id||p?.sourceId||p?.source_id||p?.id||'').replace(/^places\//,'');
const fmtDistance=m=>{m=Number(m);if(!Number.isFinite(m))return null;return m<1000?`${Math.round(m/50)*50} m`:`${(m/1000).toFixed(m<10000?1:0).replace('.',',')} km`};
function normalized(p,l={}){return {...p,id:p.id||p.placeId||providerId(p),placeId:p.id||p.placeId,primaryType:'attraction',symbol:'✨',lifecycle:l.status||p.lifecycleStatus||'discovered',address:p.shortAddress||p.formattedAddress||p.formatted_address||p.address||'',description:p.editorialSummary||p.description||'',matchScore:p.matchScore||p.match_score||Math.max(50,Math.min(96,Math.round((Number(p.rating)||3.8)*17))),metadata:{...(p.metadata||{}),tripPlaceId:l.id}}}
async function photoUris(photos,max=6){const out=[];for(const photo of (photos||[]).slice(0,max)){try{if(photo.uri||photo.url){out.push({uri:photo.uri||photo.url});continue}const r=await window.LuviaPlaces.photo(photo.name,{maxWidthPx:1200,maxHeightPx:900});if(r?.data?.photoUri)out.push({uri:r.data.photoUri})}catch{}}return out}
async function hydrate(places){await Promise.all((places||[]).slice(0,20).map(async p=>{if(!p._cardPhotoUri&&p.photos?.length){const x=await photoUris(p.photos,1);if(x[0])p._cardPhotoUri=x[0].uri}const origin=window.LuviaTravelContext?.snapshot?.()?.location;if(!origin||!p.location||!window.LuviaPlaces?.route)return;const key=providerId(p);try{let route=state.routeCache.get(key);if(!route){route=(await window.LuviaPlaces.route(origin,p.location))?.data||null;if(route)state.routeCache.set(key,route)}if(route?.walk?.distanceMeters||route?.drive?.distanceMeters){const meters=route.walk?.distanceMeters||route.drive?.distanceMeters;p.route=route;p.gpsDistanceMeters=meters;p.distanceMeters=meters}}catch{}}))}
function intelligence(p,e=null){const base=window.LuviaPlaceIntelligence?.analyze?.('attraction',p,{trip:state.trip,destination:destination(),extension:ext(e)})||{};return{...base,score:base.score||p.matchScore||75,distanceLabel:base.distanceLabel||fmtDistance(p.distanceMeters),warnings:base.warnings||[]}}
function resultCard(p,added=false){p=normalized(p);const intel=intelligence(p),rating=p.rating?`${Number(p.rating).toFixed(1).replace('.',',')} ★ · ${p.userRatingCount||0} Bewertungen`:'';p.description=[rating,p.description].filter(Boolean).join(' · ');return window.LuviaPlaceUI.card(p,{className:'rv2-search-card rv2-search-card-intelligent',openAttribute:`data-place-card-open="result:${esc(providerId(p))}"`,media:p._cardPhotoUri?`<div class="rv2-card-media"><img src="${esc(p._cardPhotoUri)}" alt="${esc(p.name)}" loading="eager" fetchpriority="high" decoding="sync"></div>`:`<div class="rv2-card-media is-placeholder"><span>✨</span></div>`,intelligence:intel,actions:`<button type="button" class="rv2-detail-button primary" data-place-card-open="result:${esc(providerId(p))}">Warum passt das?</button><button type="button" data-import="${esc(providerId(p))}" ${added?'disabled':''}>${added?'Favorit ✓':'♡ Favorit'}</button>`})}
function savedCard(e){const p=normalized(place(e),link(e)),l=link(e),intel=intelligence(p,e);const rating=p.rating?`${Number(p.rating).toFixed(1).replace('.',',')} ★ · ${p.userRatingCount||0} Bewertungen`:'';p.description=[rating,p.description].filter(Boolean).join(' · ');return window.LuviaPlaceUI.card(p,{className:'rv2-search-card rv2-search-card-intelligent',openAttribute:`data-place-card-open="saved:${esc(l.id)}"`,media:p._cardPhotoUri?`<div class="rv2-card-media"><img src="${esc(p._cardPhotoUri)}" alt="${esc(p.name)}" loading="eager" fetchpriority="high"></div>`:`<div class="rv2-card-media is-placeholder"><span>✨</span></div>`,intelligence:intel,actions:`<button type="button" class="rv2-detail-button primary" data-place-card-open="saved:${esc(l.id)}">Warum passt das?</button><button type="button" data-favorite="${esc(l.id)}">${l.is_favorite?'♥ Favorit':'♡ Favorit'}</button>`})}
function scheduledItems(){return (window.LuviaTripPlaceData?.dateEntries?.('attraction')||[]).map(e=>({id:e.id,tripPlaceId:e.tripPlaceId,dataKey:e.dataKey,title:e.title,time:`${new Date(e.startAt).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})} · ${new Date(e.startAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr`,entry:e}))}
function timelineAction(l){return window.LuviaPlaceUIActions.actionButtons({favorite:Boolean(l?.is_favorite),planned:Boolean(ext({tripPlace:l||{}}).starts_at),favoriteAttr:l?.id?'data-fav':'data-import-detail',planAttr:'data-plan-attraction'})}
function defaultDate(){const start=state.trip?.startDate||new Date().toISOString().slice(0,10);return start}
function openPlanning(p,l,e){return window.LuviaPlaceUIActions.openTimelineDialog({type:'attraction',tripId:tripId(),place:p,entity:e,tripPlace:l,importEntity:async()=>importOne(providerId(p),{silent:true,status:'planned',favorite:false}),onSaved:async()=>{await load()}})}
async function load(){try{await window.LuviaTripPlaceData?.hydrate?.(tripId());const r=await window.LuviaPlaceEntities.list({tripId:tripId(),type:'attraction'});state.entities=(r?.data?.entities||[]).filter(e=>link(e).status!=='archived');await hydrate(state.entities.map(place));state.error=null}catch(e){state.error=e.message||String(e)}render()}
async function search(query=state.query,options={}){state.visibleCount=6;state.query=String(query||'Sehenswürdigkeiten und Aktivitäten').trim()||'Sehenswürdigkeiten und Aktivitäten';state.options=options;state.loading=true;state.error=null;render();try{const r=await window.LuviaPlaceEntities.searchPlaces({tripId:tripId(),type:'attraction',query:`${state.query} ${destination()}`,maxResultCount:16,strictDestination:true,minRating:options.minRating,sortBy:options.sortBy||'relevance',openNow:options.openNow||false});state.results=r?.data?.places||[];await hydrate(state.results);state.searchMap=new Map(state.results.map(p=>[providerId(p),p]))}catch(e){state.error=e.message||String(e)}state.loading=false;render()}
async function importOne(id,{silent=false,status='idea',favorite=true}={}){try{const response=await window.LuviaPlaceEntities.importPlace(id,{tripId:tripId(),type:'attraction',tripPlace:{status,isFavorite:favorite},extension:{attractionType:state.filter.toLowerCase()}});await load();const entity=state.entities.find(e=>providerId(place(e))===String(id))||response?.data?.entity||response?.data?.tripPlaceEntity||null;if(!silent)window.LuviaUIKit?.toast?.('Aktivität als Favorit gespeichert.',{type:'success'});return entity}catch(e){state.error=e.message||String(e);render();throw e}}
async function detail(raw,l=null,e=null){let p=normalized(raw,l||{});const overlay=window.LuviaPlaceDetail.openLoading({typeLabel:'Aktivität'});const firstEntity=e||{place:p,tripPlace:l||{},extension:{}};window.LuviaPlaceDetail.update(overlay,{place:p,photos:p._cardPhotoUri?[{uri:p._cardPhotoUri}]:[],intelligence:intelligence(p,e),destination:destination(),typeLabel:'Aktivität',primaryActions:timelineAction(l),lifecycle:{title:'Aktivitäts-Lebenszyklus',status:l?.status||'discovered',order:['discovered','favorite','planned','visited','rated']},capabilityContent:'',alternativesContent:'<p class="rv2-muted">Weitere Details werden geladen …</p>'});bindDetail(overlay,p,l,e);try{const prepared=await window.LuviaPlaceDetails.prepare(providerId(p),{regionCode:'DE',photoLimit:6,seedPlace:p});p=normalized({...p,...prepared.place},l||{});const photos=prepared.photos?.length?prepared.photos:await photoUris(p.photos);const intel=intelligence(p,e),alts=(state.results||[]).filter(a=>providerId(a)!==providerId(p)).slice(0,3);const alternatives=alts.length?`<div class="rv2-alternatives">${alts.map(a=>`<button type="button" class="luv-place-alternative" data-place-alternative="${esc(providerId(a))}"><span><strong>${esc(a.name||'Alternative')}</strong><small>Alternative aus der aktuellen Suche</small></span><b>${esc(intelligence(a).score)} %</b></button>`).join('')}</div>`:'<p class="rv2-muted">Noch keine Alternativen verfügbar.</p>';window.LuviaPlaceDetail.update(overlay,{place:p,photos,intelligence:intel,destination:destination(),typeLabel:'Aktivität',primaryActions:timelineAction(l),lifecycle:{title:'Aktivitäts-Lebenszyklus',status:l?.status||'discovered',order:['discovered','favorite','planned','visited','rated']},capabilityContent:'',alternativesContent:alternatives});bindDetail(overlay,p,l,e)}catch(error){console.warn('[Luvia Attractions] Details konnten nicht vollständig geladen werden.',error)}}
function bindDetail(overlay,p,l,e){const root=overlay.node;root.querySelector('[data-import-detail]')?.addEventListener('click',async ev=>{ev.stopPropagation();const imported=await importOne(providerId(p),{silent:true});overlay.close();if(imported)detail(place(imported),link(imported),imported)});root.querySelector('[data-fav]')?.addEventListener('click',async ev=>{ev.stopPropagation();await window.LuviaPlaceCollections.setFavorite({tripId:tripId(),placeType:'attraction',tripPlaceId:l.id,entity:e,isFavorite:!l.is_favorite,status:l.status||'idea'});overlay.close();load()});root.querySelector('[data-plan-attraction]')?.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();openPlanning(p,l,e)});root.querySelectorAll('[data-place-alternative]').forEach(button=>button.addEventListener('click',()=>{const a=state.searchMap.get(button.dataset.placeAlternative);if(a)detail(a)}))}
function bind(){const r=state.root;r.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);search(f.get('query'),{minRating:f.get('minRating')?Number(f.get('minRating')):null,sortBy:f.get('sortBy'),openNow:f.get('openNow')==='on'})};r.onclick=async e=>{const more=e.target.closest('[data-place-more]');if(more){state.visibleCount=Math.min(state.results.length,state.visibleCount+6);render();return}const refresh=e.target.closest('[data-place-refresh]');if(refresh){search(state.query,state.options);return}const quick=e.target.closest('[data-place-query]');if(quick){state.filter=quick.dataset.placeQuery;search(quick.dataset.placeQuery,state.options);return}const imp=e.target.closest('[data-import]');if(imp){e.preventDefault();e.stopPropagation();importOne(imp.dataset.import);return}const fav=e.target.closest('[data-favorite]');if(fav){e.preventDefault();e.stopPropagation();const x=state.entities.find(y=>String(link(y).id)===String(fav.dataset.favorite));await window.LuviaPlaceCollections.setFavorite({tripId:tripId(),placeType:'attraction',tripPlaceId:link(x).id,entity:x,isFavorite:!link(x).is_favorite,status:link(x).status||'idea'});await load();return}const clear=e.target.closest('[data-place-clear-favorites]');if(clear){await window.LuviaPlaceCollections.clearFavorites('attraction',{tripId:tripId()});await load();return}const open=e.target.closest('[data-place-card-open]');if(open&&!e.target.closest('[data-import],[data-favorite]')){const [kind,id]=String(open.dataset.placeCardOpen||'').split(':');if(kind==='result'){const p=state.searchMap.get(id);if(p)detail(p)}else{const x=state.entities.find(y=>String(link(y).id)===id);if(x)detail(place(x),link(x),x)}return}const scheduled=e.target.closest('[data-place-schedule]');if(scheduled){const ev=scheduledItems().find(x=>String(x.id)===String(scheduled.dataset.placeSchedule));if(ev)openPlace({tripPlaceId:ev.tripPlaceId,placeId:ev.entry?.placeId});return}const edit=e.target.closest('[data-place-edit-schedule]');if(edit){const ev=scheduledItems().find(x=>String(x.id)===String(edit.dataset.placeEditSchedule));if(ev)window.LuviaTimelineCore?.editEntry?.(ev.entry,()=>render());return}const remove=e.target.closest('[data-place-remove-schedule]');if(remove){const ev=scheduledItems().find(x=>String(x.id)===String(remove.dataset.placeRemoveSchedule));if(ev)await window.LuviaTripPlaceData.updateDateFields(ev.tripPlaceId,{[ev.dataKey]:null},{tripId:tripId()});await window.LuviaTimelineCore?.hydrate?.(tripId());render()}};r.onpointerover=e=>{const card=e.target.closest('[data-place-card-open^="result:"]');if(card){const id=String(card.dataset.placeCardOpen||'').split(':')[1];if(id)window.LuviaPlaceDetails?.prefetch?.([id],{regionCode:'DE'})}};r.onfocusin=r.onpointerover}
async function mount(instance,context={}){state.root=instance?.roots?.[0]||document.querySelector('#attractions-module');state.trip=context.trip||instance?.trip||window.LuviaTripStore?.snapshot?.().activeTrip;render();await load();if(!state.results.length)await search('Sehenswürdigkeiten und Aktivitäten',{sortBy:'relevance'});return instance}
function unmount(){state.root=null;state.trip=null}
async function openPlace(payload={}){const e=state.entities.find(x=>String(link(x).id)===String(payload.tripPlaceId)||String(place(x).id)===String(payload.placeId));if(e){detail(place(e),link(e),e);return true}return false}
window.addEventListener('luvia:open-place',e=>{if(e.detail?.type==='attraction')openPlace(e.detail)});window.addEventListener('luvia:trip-place-data-changed',()=>state.root&&render());window.addEventListener('luvia:place-collection-changed',e=>{if(state.root&&e.detail?.placeType==='attraction')load()});
window.LuviaAttractions=Object.freeze({version:VERSION,load,search,openPlace});window.LuviaModules?.register({id:MODULE_ID,order:70,group:'Places',icon:'✨',title:'Sehenswürdigkeiten & Aktivitäten',description:'Orte und Erlebnisse entdecken, speichern und planen.',selectors:['#attractions-module'],version:VERSION,mount,unmount});
})();
