import { createClient } from 'https://esm.sh/@supabase/supabase-js@2';
const cors={'Access-Control-Allow-Origin':'https://myluvia.app','Access-Control-Allow-Headers':'authorization, x-client-info, apikey, content-type','Access-Control-Allow-Methods':'POST, OPTIONS','Vary':'Origin'};const json=(d:unknown,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{...cors,'content-type':'application/json; charset=utf-8'}});const clean=(v:unknown)=>String(v??'').trim();
Deno.serve(async(req)=>{if(req.method==='OPTIONS')return new Response(null,{status:204,headers:cors});try{if(req.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405);const u=Deno.env.get('SUPABASE_URL'),a=Deno.env.get('SUPABASE_ANON_KEY');if(!u||!a)return json({error:'SUPABASE_ENV_MISSING'},500);const auth=req.headers.get('Authorization')||'';if(!auth)return json({error:'AUTH_REQUIRED'},401);const db=createClient(u,a,{global:{headers:{Authorization:auth}},auth:{persistSession:false,autoRefreshToken:false}});const body=await req.json();const action=clean(body.action||'get');const bookingId=clean(body.bookingId);const tripId=clean(body.tripId);
 if(action==='readiness'){if(!bookingId)return json({error:'BOOKING_ID_REQUIRED'},400);const {data,error}=await db.from('booking_email_readiness_v2').select('*').eq('booking_id',bookingId).maybeSingle();if(error)return json({error:'EMAIL_READINESS_FAILED',details:error.message},500);return json({ok:true,version:'1.0.1',build:'13.68.1',core:'4.68.1',readiness:data});}
 if(action==='get'){if(!bookingId)return json({error:'BOOKING_ID_REQUIRED'},400);const {data,error}=await db.from('booking_email_runtime_v2').select('*').eq('booking_id',bookingId).maybeSingle();if(error)return json({error:'EMAIL_RUNTIME_GET_FAILED',details:error.message},500);return json({ok:true,version:'1.0.1',build:'13.68.1',core:'4.68.1',runtime:data});}
 if(action==='history'){if(!bookingId)return json({error:'BOOKING_ID_REQUIRED'},400);const [{data:messages,error:me},{data:requests,error:re},{data:delivery,error:de}]=await Promise.all([db.from('booking_messages').select('*').eq('booking_id',bookingId).eq('channel','email').order('created_at',{ascending:true}),db.from('booking_email_requests').select('*').eq('booking_id',bookingId).order('created_at',{ascending:true}),db.from('booking_email_delivery_events').select('*').eq('booking_id',bookingId).order('received_at',{ascending:true})]);if(me||re||de)return json({error:'EMAIL_HISTORY_FAILED',details:me?.message||re?.message||de?.message},500);return json({ok:true,version:'1.0.1',build:'13.68.1',core:'4.68.1',messages:messages||[],requests:requests||[],deliveryEvents:delivery||[]});}
 if(action==='queue'){let q=db.from('booking_email_recovery_queue_v2').select('*');if(tripId)q=q.eq('trip_id',tripId);const {data,error}=await q.limit(100);if(error)return json({error:'EMAIL_QUEUE_FAILED',details:error.message},500);return json({ok:true,version:'1.0.1',build:'13.68.1',core:'4.68.1',items:data||[]});}
 return json({error:'EMAIL_RUNTIME_ACTION_INVALID'},400);
}catch(e){return json({error:'BOOKING_EMAIL_RUNTIME_UNHANDLED',details:e instanceof Error?e.message:String(e)},500);}});
