(() => {
  'use strict';
  const listeners=new Set();
  let client=null,tripId=null,activityChannel=null,presenceChannel=null,heartbeatTimer=null,refreshTimer=null,started=false,watchPromise=null,watchToken=0;
  const state={activities:[],presence:[],loaded:false,syncing:false,error:null,lastUpdatedAt:null};
  const DEVICE_KEY='luvia.device.id.v1';
  const deviceId=()=>{let id=localStorage.getItem(DEVICE_KEY);if(!id){id=(crypto.randomUUID?.()||`device-${Date.now()}-${Math.random().toString(36).slice(2)}`);localStorage.setItem(DEVICE_KEY,id)}return id};
  const profile=()=>window.LuviaProfileService?.snapshot?.().profile||{};
  const auth=()=>window.ParisAuth?.getState?.()||{};
  const snapshot=()=>Object.freeze({tripId,activities:structuredClone(state.activities),presence:structuredClone(state.presence),loaded:state.loaded,syncing:state.syncing,error:state.error,lastUpdatedAt:state.lastUpdatedAt});
  function emit(reason='changed'){const value=snapshot();listeners.forEach(fn=>{try{fn(value)}catch(e){console.warn('[LuviaCollaboration]',e)}});window.dispatchEvent(new CustomEvent('luvia:collaboration-changed',{detail:{...value,reason}}));return value}
  function clearTimers(){if(heartbeatTimer)clearInterval(heartbeatTimer);if(refreshTimer)clearTimeout(refreshTimer);heartbeatTimer=refreshTimer=null}
  async function rpc(name,params){const r=await client.rpc(name,params);if(r.error)throw r.error;return r.data}
  async function refresh({silent=false}={}){if(!client||!tripId||!auth().authenticated)return snapshot();if(!silent){state.syncing=true;emit('refreshing')}try{const [activities,presence]=await Promise.all([rpc('luvia_list_trip_activity',{p_trip_id:tripId,p_limit:40}),rpc('luvia_list_trip_presence',{p_trip_id:tripId})]);state.activities=activities||[];state.presence=presence||[];state.loaded=true;state.syncing=false;state.error=null;state.lastUpdatedAt=new Date().toISOString();return emit('refreshed')}catch(error){state.loaded=true;state.syncing=false;state.error=error;console.warn('[LuviaCollaboration] Live-Daten nicht verfügbar.',error);return emit('refresh-failed')}}
  function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(()=>refresh({silent:true}),120)}
  async function heartbeat(){if(!client||!tripId||!auth().authenticated||document.visibilityState==='hidden')return;try{await rpc('luvia_presence_heartbeat',{p_trip_id:tripId,p_device_id:deviceId(),p_display_name:profile().displayName||null,p_current_view:window.LuviaApp?.activeView?.()||'dashboard',p_metadata:{build:'11.9.0',platform:navigator.userAgentData?.platform||navigator.platform||'web'}})}catch(error){console.warn('[LuviaPresence]',error)}}
  async function leave(){if(!client||!tripId||!auth().authenticated)return;try{await rpc('luvia_presence_leave',{p_trip_id:tripId,p_device_id:deviceId()})}catch{}}
  function subscribeRealtime(id){activityChannel=client.channel(`luvia-activity-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'trip_activity_events',filter:`trip_id=eq.${id}`},scheduleRefresh).subscribe();presenceChannel=client.channel(`luvia-presence-${id}`).on('postgres_changes',{event:'*',schema:'public',table:'trip_presence',filter:`trip_id=eq.${id}`},scheduleRefresh).subscribe()}
  async function watchTrip(id){id=id||null;if(id===tripId&&activityChannel&&presenceChannel)return state.loaded?snapshot():refresh();const token=++watchToken;watchPromise=(async()=>{clearTimers();if(activityChannel)await client?.removeChannel?.(activityChannel);if(presenceChannel)await client?.removeChannel?.(presenceChannel);if(token!==watchToken)return snapshot();activityChannel=presenceChannel=null;tripId=id;state.activities=[];state.presence=[];state.loaded=false;state.error=null;if(!id)return emit('trip-cleared');emit('trip-changing');subscribeRealtime(id);await heartbeat();if(token!==watchToken)return snapshot();heartbeatTimer=setInterval(heartbeat,30000);return refresh()})();return watchPromise}
  async function record(eventType,title,{body=null,entityType=null,entityId=null,metadata={}}={}){if(!tripId)throw new Error('Keine aktive Reise.');const id=await rpc('luvia_record_trip_activity',{p_trip_id:tripId,p_event_type:eventType,p_title:title,p_body:body,p_entity_type:entityType,p_entity_id:entityId,p_metadata:{...metadata,actorName:metadata.actorName||profile().displayName||null}});scheduleRefresh();return id}
  async function stop({keepClient=false}={}){clearTimers();await leave();if(activityChannel)await client?.removeChannel?.(activityChannel);if(presenceChannel)await client?.removeChannel?.(presenceChannel);activityChannel=presenceChannel=null;tripId=null;state.activities=[];state.presence=[];state.loaded=false;if(!keepClient){client=null;started=false}return emit('stopped')}
  async function start(c){client=c||client||await window.LuviaSupabaseService.start();if(started)return snapshot();started=true;document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){heartbeat();scheduleRefresh()}else leave()});window.addEventListener('pagehide',()=>leave());window.addEventListener('online',()=>{heartbeat();scheduleRefresh()});window.addEventListener('luvia:restaurants-v2-updated',e=>{const detail=e.detail||{};if(detail.databaseEvent)return;if(detail.tripId&&detail.tripId===tripId)record('restaurant.updated',detail.entityImport?'Restaurant gespeichert':'Restaurantplanung aktualisiert',{entityType:'restaurant',metadata:{mode:detail.mode||null}}).catch(console.warn)});window.addEventListener('luvia:trip-created',e=>{const t=e.detail?.trip;if(t?.id===tripId)record('trip.created','Reise wurde erstellt',{entityType:'trip',entityId:t.id}).catch(console.warn)});window.addEventListener('luvia:trip-changed',e=>{const t=e.detail;if((t?.id||t?.tripId)===tripId)record('trip.updated','Reise wurde bearbeitet',{entityType:'trip',entityId:t.id||t.tripId}).catch(console.warn)});return snapshot()}
  window.LuviaCollaboration=Object.freeze({version:'1.1.0',start,stop,watchTrip,refresh,heartbeat,record,snapshot,subscribe(fn){listeners.add(fn);fn(snapshot());return()=>listeners.delete(fn)}});
})();
