(() => {
'use strict';
const VERSION='4.28.5.2',BUILD='13.28.5.2';let host=null,clusters=[],items=[],unsub=null,timer=null;const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function urlFor(item){try{return await window.LuviaMediaCore.signedUrl(item,1800)||''}catch{return''}}
function reason(c){const n=c.mediaIds?.length||0,related=items.filter(x=>c.mediaIds?.includes(x.id)),known=related.map(x=>x.placeId&&window.LuviaPlaceCore?.getPlace?.(x.placeId)).find(Boolean),trip=window.LuviaTripStore?.snapshot?.().activeTrip||{},destination=trip.destination?.name||trip.destinationName||'';if(known)return `${n} Fotos wurden bei ${known.name||known.title} zu einem gemeinsamen Moment gruppiert.`;if(c.hasLocation&&destination)return `${n} Fotos wurden anhand von Aufnahmezeit und Standort im Reisekontext ${destination} gruppiert.`;return `${n} Fotos wurden anhand ihrer Aufnahmezeit zu einem gemeinsamen Moment gruppiert.`}
async function render(){if(!host)return;items=await window.LuviaMediaCore.list({type:'image'});clusters=await window.LuviaMediaClustering.listPersisted();const visible=clusters.filter(c=>c.state!=='dismissed'&&c.mediaIds?.length);host.innerHTML=`<section class="lv-albums-view"><header class="lv-albums-hero"><span>🖼️ Smart Albums</span><h1>Eure gemeinsamen Fotomomente</h1><p>Luvia bündelt zusammengehörige Fotos automatisch. Änderungen erscheinen still in Echtzeit.</p><button type="button" data-albums-analyze>Neu analysieren</button></header><div class="lv-album-grid">${visible.length?visible.map(c=>`<article class="lv-album-card" data-cluster="${esc(c.id)}" tabindex="0" role="button"><div class="lv-album-collage">${c.mediaIds.slice(0,4).map(id=>`<span data-album-photo="${esc(id)}"></span>`).join('')}</div><small>${c.mediaIds.length} Fotos</small><h2>${esc(c.title||'Gemeinsamer Fotomoment')}</h2><p>${esc(reason(c))}</p><div><button data-memory="${esc(c.id)}">Erinnerung prüfen</button><button data-dismiss="${esc(c.id)}">Auflösen</button></div></article>`).join(''):'<div class="lv-albums-empty"><b>✨</b><h2>Noch keine Fotomomente</h2><p>Mindestens zwei zeitlich passende Fotos erzeugen automatisch ein Album.</p></div>'}</div></section>`;await Promise.all([...host.querySelectorAll('[data-album-photo]')].map(async n=>{const item=items.find(x=>x.id===n.dataset.albumPhoto),url=item&&await urlFor(item);if(url)n.style.backgroundImage=`url("${url}")`}));bind()}
function bind(){host.querySelector('[data-albums-analyze]')?.addEventListener('click',async()=>{await window.LuviaMediaClustering.syncGenerated(window.LuviaMediaClustering.generate(items));await render()});host.querySelectorAll('[data-cluster]').forEach(card=>{card.onclick=e=>{if(e.target.closest('[data-memory],[data-dismiss]'))return;open(card.dataset.cluster)};card.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){e.preventDefault();open(card.dataset.cluster)}}});host.querySelectorAll('[data-memory]').forEach(b=>b.onclick=async()=>{const p=await window.LuviaAIMemoryBridge.analyze(b.dataset.memory);alert(`${p.title}\n\n${p.explanation}`)});host.querySelectorAll('[data-dismiss]').forEach(b=>b.onclick=async()=>{if(!confirm('Fotomoment auflösen?'))return;await window.LuviaMediaClustering.dissolve(b.dataset.dismiss);await window.LuviaTimelineCore?.removePhotoMemoryByCluster?.(b.dataset.dismiss);await render()})}
async function open(id){const c=clusters.find(x=>String(x.id)===String(id));if(!c)return;const chosen=items.filter(x=>c.mediaIds.includes(x.id)),overlay=document.createElement('div');overlay.className='lv-photo-overlay';overlay.innerHTML=`<section class="lv-album-dialog"><button class="lv-album-close" data-close aria-label="Schließen">×</button><span>🖼️ Album</span><h2>${esc(c.title||'Gemeinsamer Fotomoment')}</h2><p>${esc(reason(c))}</p><div>${chosen.map(x=>`<button data-photo="${esc(x.id)}"><img alt="" data-img="${esc(x.id)}"></button>`).join('')}</div></section>`;document.body.appendChild(overlay);document.body.classList.add('lv-photo-modal-open');await Promise.all(chosen.map(async x=>{const u=await urlFor(x),img=overlay.querySelector(`[data-img="${CSS.escape(x.id)}"]`);if(img&&u)img.src=u}));const close=()=>{overlay.remove();document.body.classList.remove('lv-photo-modal-open')};overlay.querySelector('[data-close]').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};overlay.querySelectorAll('[data-photo]').forEach(b=>b.onclick=()=>{const id=b.dataset.photo;close();window.LuviaGalleryView?.openPhoto?.(id)})}
async function mount(target){host=target;await render();unsub=await window.LuviaMediaClustering.subscribe(()=>{clearTimeout(timer);timer=setTimeout(render,500)});return unmount}async function unmount(){clearTimeout(timer);await unsub?.();unsub=null;if(host)host.innerHTML='';host=null}
window.LuviaAlbumsView=Object.freeze({version:VERSION,build:BUILD,mount,unmount});
})();