(() => {
  'use strict';
  let root,activeView='dashboard',mountedRestaurant=false,unsubscribeTrip=null,unsubscribeAuth=null,unsubscribeProfile=null,unsubscribeCollaboration=null,collaborationFrame=0,authHydration=0,lastAuthUserId=null,pendingPlaceOpen=null,todayRenderFrame=0;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const snap=()=>window.LuviaTripStore.snapshot(),activeTrip=()=>snap().activeTrip,profile=()=>window.LuviaProfileService?.snapshot?.().profile||{};
  const date=v=>v?new Date(v+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}):'';
  const initials=p=>(p.displayName||p.email||'L').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
  const avatar=p=>p.avatarUrl?`<img class="lv-header-avatar" src="${esc(p.avatarUrl)}" alt="Profil">`:`<span class="lv-header-avatar" style="--avatar:${esc(p.avatarColor||'#ee6f83')}">${esc(initials(p))}</span>`;
  function bootScreen(text='Luvia wird vorbereitet …'){root.innerHTML=`<main class="lv-boot"><div class="lv-boot-card"><span class="lv-logo"></span><h1>Luvia</h1><p>${esc(text)}</p></div></main>`}
  function errorScreen(error){root.innerHTML=`<main class="lv-empty"><section class="lv-card"><span class="lv-logo"></span><h1>Start nicht möglich</h1><div class="lv-error">${esc(error?.message||error||'Unbekannter Fehler')}</div><div class="lv-actions"><button class="lv-primary" data-retry>Erneut versuchen</button><a class="lv-secondary" href="intelligence/console.html">Developer Console</a></div></section></main>`}
  async function signedOut(){if(await window.LuviaJoinFlow?.renderIfPending?.(root,window.ParisAuth.getState(),profile()))return;root.innerHTML=`<main class="lv-auth lv-card"><header class="lv-auth-head"><span class="lv-logo"></span><h1>Willkommen bei Luvia</h1><p>Gemeinsam reisen. Für immer erinnern.</p></header><div class="lv-auth-slot" data-auth-slot></div></main>`;window.ParisAuthUI.renderAuthForm(root.querySelector('[data-auth-slot]'),'login')}
  async function noTrips(){if(await window.LuviaJoinFlow?.renderIfPending?.(root,window.ParisAuth.getState(),profile()))return;root.innerHTML=`<main class="lv-empty"><section class="lv-card"><span class="lv-logo"></span><h1>Eure erste Reise wartet</h1><p>Erstellt eine Reise und legt Reiseziel, Zeitraum, Stil und Module fest.</p><div class="lv-actions" style="justify-content:center"><button class="lv-primary" data-create>Reise erstellen</button><button class="lv-secondary" data-join-code>Einladungscode eingeben</button><button class="lv-secondary" data-profile-open="hub">Profil</button><button class="lv-secondary" data-signout>Abmelden</button></div></section></main>`}
  function dashboard(t){const destination=t.destination?.formattedAddress||t.destination?.name||'Reiseziel noch offen',dates=t.startDate?(t.endDate?`${date(t.startDate)} – ${date(t.endDate)}`:`Ab ${date(t.startDate)}`):'Zeitraum noch offen',p=profile();return `<section class="lv-dashboard"><article class="lv-card lv-hero"><span class="lv-kicker">Aktive Reise</span><div class="lv-titleline"><span class="lv-symbol">${esc(t.symbol||'❤️')}</span><div><h1>${esc(t.title||'Unsere Reise')}</h1><div class="lv-meta"><span>📍 ${esc(destination)}</span><span>📅 ${esc(dates)}</span></div></div></div><div class="lv-actions"><button class="lv-primary" data-view="restaurants">Restaurants öffnen</button><button class="lv-secondary" data-invite>Personen einladen</button><button class="lv-secondary" data-edit>Reise bearbeiten</button><button class="lv-secondary" data-profile-open="trips">Reise wechseln</button></div></article><div class="lv-grid" data-widget-grid>${window.LuviaDashboardWidgets.render({trip:t,profile:p,esc})}</div></section>`}
  function dock(t){const modules=window.LuviaModuleRegistry.enabledForTrip(t);return `<div class="lv-dock-wrap"><nav class="lv-dock"><button class="lv-nav ${activeView==='dashboard'?'on':''}" data-view="dashboard">🏠 Dashboard</button>${modules.map(id=>{const m=window.LuviaModuleRegistry.get(id);return `<button class="lv-nav ${activeView===id?'on':''}" data-view="${id}">${m.icon} ${esc(m.title)}</button>`}).join('')}</nav></div>`}

  const moduleForPlaceType=type=>({restaurant:'restaurants',accommodation:'accommodations',attraction:'attractions',photo_spot:'photo-spots',activity:'activities',shopping:'shopping',nature:'nature',family:'family',mobility:'mobility',transit:'transit',custom:'custom-places'}[type]||null);
  function placeOpenPayload(element){return{type:element.dataset.placeType||'custom',placeId:element.dataset.placeId||'',providerPlaceId:element.dataset.providerPlaceId||'',tripPlaceId:element.dataset.tripPlaceId||'',title:element.dataset.placeTitle||''};}
  async function resolvePlaceForAction(payload){
    const direct=payload.placeId&&window.LuviaPlaceCore?.getPlace?.(payload.placeId);
    if(direct)return direct;
    const places=window.LuviaPlaceCore?.getPlaces?.({tripId:activeTrip()?.id||activeTrip()?.tripId})||[];
    let match=places.find(p=>String(p.id||'')===String(payload.placeId||'')||String(p.sourceId||p.providerPlaceId||'')===String(payload.providerPlaceId||'')||String(p.metadata?.tripPlaceId||'')===String(payload.tripPlaceId||'')||(payload.title&&p.name===payload.title));
    if(match)return match;
    if(payload.type==='restaurant'&&window.LuviaRestaurants?.list){
      const response=await window.LuviaRestaurants.list({tripId:activeTrip()?.id||activeTrip()?.tripId});
      const entries=(response?.data?.entities||[]).map(window.LuviaRestaurants.entityToEntry);
      const entry=entries.find(item=>String(item.placeId||'')===String(payload.placeId||'')||String(item.providerPlaceId||'')===String(payload.providerPlaceId||'')||String(item.tripPlaceId||'')===String(payload.tripPlaceId||'')||(payload.title&&item.name===payload.title));
      if(entry)match=window.LuviaPlaceCore?.registerPlace?.(entry,{primaryType:'restaurant'});
    }
    return match||null;
  }
  async function deliverPlaceOpen(payload){if(!payload)return false;const moduleId=moduleForPlaceType(payload.type);if(moduleId==='restaurants'&&window.LuviaRestaurantsV2?.openPlace)return Boolean(await window.LuviaRestaurantsV2.openPlace(payload));window.dispatchEvent(new CustomEvent('luvia:open-place',{detail:payload}));return true;}
  async function openPlace(payload){payload={...payload,returnView:activeView};pendingPlaceOpen=payload;const moduleId=moduleForPlaceType(payload.type);const enabled=moduleId&&window.LuviaModuleRegistry?.get?.(moduleId);if(enabled){await show(moduleId);await new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)));if(pendingPlaceOpen===payload){const delivered=await deliverPlaceOpen(payload);if(delivered)pendingPlaceOpen=null;}return;}window.dispatchEvent(new CustomEvent('luvia:open-place',{detail:payload}));}
  function dashboardContext(){const t=activeTrip();return t?{trip:t,profile:profile(),esc}:null;}
  function updateTodayWidget(){if(activeView!=='dashboard')return;cancelAnimationFrame(todayRenderFrame);todayRenderFrame=requestAnimationFrame(()=>{const article=root?.querySelector('[data-widget-id="today"]'),context=dashboardContext();if(!article||!context)return;const html=window.LuviaDashboardWidgets?.renderOne?.('today',context);if(typeof html!=='string')return;const previousHeight=article.getBoundingClientRect().height;article.style.minHeight=`${previousHeight}px`;const swap=()=>{article.innerHTML=html;article.classList.remove('is-live-refreshing');article.classList.add('is-live-settling');article.animate?.([{opacity:.78,transform:'translateY(2px)'},{opacity:1,transform:'none'}],{duration:220,easing:'cubic-bezier(.22,.8,.24,1)'});setTimeout(()=>{article.classList.remove('is-live-settling');article.style.minHeight=''},240)};article.classList.add('is-live-refreshing');if(document.startViewTransition){article.style.viewTransitionName='luvia-today-widget';document.startViewTransition(swap).finished.finally(()=>{article.style.viewTransitionName='';article.style.minHeight=''})}else setTimeout(swap,70)});}

  async function unmountCurrent(){if(mountedRestaurant){await window.LuviaModules?.unmountModule?.('restaurants');mountedRestaurant=false}}
  async function show(view='dashboard'){const t=activeTrip();if(!t)return render();await unmountCurrent();activeView=view;const stage=root.querySelector('[data-stage]');if(!stage)return render();if(view==='restaurants'){stage.innerHTML='<section class="lv-module-host lv-module-entering"><div class="lv-module-intro" role="status" aria-live="polite"><div class="lv-module-intro-icon">🍽️</div><strong>Restaurants</strong><span>Worauf habt ihr heute Lust?</span></div><div id="restaurants-module"></div></section>';try{window.LuviaDestination?.refresh?.();await window.LuviaModules.mountModule('restaurants',t);mountedRestaurant=true;if(pendingPlaceOpen?.type==='restaurant'){const payload=pendingPlaceOpen;pendingPlaceOpen=null;requestAnimationFrame(()=>deliverPlaceOpen(payload).catch(console.error));}const host=stage.querySelector('.lv-module-host');const introStarted=performance.now();requestAnimationFrame(()=>{const elapsed=performance.now()-introStarted;setTimeout(()=>host?.classList.add('is-ready'),Math.max(1100-elapsed,0));setTimeout(()=>host?.classList.remove('lv-module-entering'),Math.max(1750-elapsed,650))})}catch(error){console.error(error);stage.innerHTML='<section class="lv-card" style="padding:24px"><h2>Restaurants</h2><div class="lv-error">Das Restaurantmodul konnte nicht geöffnet werden.</div></section>'}}else{activeView='dashboard';stage.innerHTML=dashboard(t)}root.querySelector('.lv-dock-wrap')?.remove();root.querySelector('.lv-shell')?.insertAdjacentHTML('beforeend',dock(t));window.scrollTo({top:0,behavior:'instant'});}
  function ready(){const t=activeTrip(),p=profile();if(!t)return noTrips();window.LuviaTheme.apply(t);root.innerHTML=`<div class="lv-shell"><header class="lv-header"><span class="lv-logo"></span><div class="lv-trip"><strong>${esc(t.title||'Unsere Reise')}</strong><small>${esc(t.destination?.name||'Reiseziel offen')}</small></div><span class="lv-spacer"></span><button class="lv-icon" data-invite>＋ <span class="lv-label">Einladen</span></button><button class="lv-profile-trigger" data-profile-open="hub">${avatar(p)}<span><b>${esc(p.displayName||'Profil')}</b><small>${esc(t.title||'Reise')}</small></span></button></header><main class="lv-stage" data-stage></main></div>`;show(activeView)}
  async function render(){const auth=window.ParisAuth.getState();if(auth.loading)return bootScreen();if(!auth.authenticated)return signedOut();const s=snap();if(!s.loaded)return bootScreen('Reisen werden geladen …');if(window.LuviaJoinFlow?.pending?.())return window.LuviaJoinFlow.renderIfPending(root,auth,profile());if(!s.hasTrips||!s.hasActiveTrip)return noTrips();return ready()}
  async function hydrateForAuth(client,authState){const run=++authHydration;if(!authState?.authenticated){lastAuthUserId=null;render();return}const userId=authState.user?.id||null;bootScreen('Profil und Reisen werden aus der Cloud geladen …');await Promise.all([window.LuviaTripStore.loadRemote(client,{authoritative:true}),window.LuviaProfileService.load(client)]);if(run!==authHydration)return;const p=profile();if(p.activeTripId&&snap().trips.some(t=>t.id===p.activeTripId))window.LuviaTripStore.setActive(p.activeTripId);else if(snap().activeTripId&&p.activeTripId!==snap().activeTripId)await window.LuviaProfileService.setActiveTrip(snap().activeTripId);lastAuthUserId=userId;if(window.LuviaJoinFlow?.pending?.()){await window.LuviaJoinFlow.renderIfPending(root,authState,profile());return}window.LuviaRuntime.refresh();window.LuviaTheme.apply(activeTrip());window.LuviaDestination?.refresh?.();await window.LuviaCollaboration?.watchTrip?.(snap().activeTripId);activeView=p.defaultView||'dashboard';render()}
  async function bootstrap(){bootScreen();try{const client=await window.LuviaSupabaseService.start();await window.LuviaJoinFlow?.start?.(client);await window.LuviaCollaboration?.start?.(client);window.LuviaTripStore.initialize();await window.LuviaDestination?.init?.();window.LuviaPWA?.register?.().catch(e=>console.warn('[LuviaPWA]',e));unsubscribeTrip?.();unsubscribeAuth?.();unsubscribeProfile?.();unsubscribeCollaboration?.();unsubscribeTrip=window.LuviaTripStore.subscribe(s=>{if(s.activeTripId&&profile().activeTripId!==s.activeTripId&&window.ParisAuth.getState().authenticated)window.LuviaProfileService.setActiveTrip(s.activeTripId).catch(console.warn);if(window.LuviaCollaboration?.snapshot?.().tripId!==s.activeTripId)window.LuviaCollaboration?.watchTrip?.(s.activeTripId).catch?.(console.warn);if(activeView==='restaurants'&&mountedRestaurant)return;render()});unsubscribeProfile=window.LuviaProfileService.subscribe(()=>{window.LuviaTheme.apply(activeTrip());window.LuviaCollaboration?.heartbeat?.();if(root?.querySelector('.lv-shell')&&activeView!=='restaurants')render()});unsubscribeCollaboration=window.LuviaCollaboration?.subscribe?.(state=>{if(!state?.tripId||activeView!=='dashboard'||!root?.querySelector('.lv-shell'))return;cancelAnimationFrame(collaborationFrame);collaborationFrame=requestAnimationFrame(()=>ready())});unsubscribeAuth=window.ParisAuth.onChange(state=>{const uid=state?.user?.id||null;if(state?.authenticated&&uid!==lastAuthUserId)hydrateForAuth(client,state).catch(errorScreen);else render()});await hydrateForAuth(client,window.ParisAuth.getState())}catch(error){console.error('[LuviaApp]',error);errorScreen(error)}}
  async function openDialog(name,payload){try{if(!window.LuviaUI?.has?.(name))throw new Error(`Dialog ${name} ist noch nicht verfügbar.`);await window.LuviaUI.open(name,payload)}catch(error){console.error('[LuviaUI]',name,error);const message=error?.message||'Der Dialog konnte nicht geöffnet werden.';window.LuviaUIKit?.toast?.(message,{type:'error'})||alert(message)}}
  function bind(){root.addEventListener('click',e=>{const placeTarget=e.target.closest('[data-place-open]');if(placeTarget){e.preventDefault();return openPlace(placeOpenPayload(placeTarget)).catch(console.error)}if(e.target.closest('[data-retry]'))return bootstrap();if(e.target.closest('[data-create]'))return window.LuviaTripCreator.open();if(e.target.closest('[data-signout]'))return window.ParisAuth.signOut();if(e.target.closest('[data-join-code]'))return window.LuviaJoinFlow?.openCodeEntry?.();if(e.target.closest('[data-invite]'))return openDialog('trip.invite',activeTrip());if(e.target.closest('[data-edit]'))return openDialog('trip.edit',activeTrip());const po=e.target.closest('[data-profile-open]');if(po)return window.LuviaProfileFoundation.open(po.dataset.profileOpen||'hub');const view=e.target.closest('[data-view]')?.dataset.view;if(view)return show(view)})}
  document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'&&activeView==='restaurants'){window.LuviaDestination?.refresh?.();const host=root?.querySelector('#restaurants-module');if(!host||!host.childElementCount){mountedRestaurant=false;show('restaurants').catch(console.error)}}});window.addEventListener('pageshow',()=>{if(activeView==='restaurants')window.LuviaDestination?.refresh?.()});window.addEventListener('luvia:members-changed',()=>{if(activeView==='dashboard'&&root?.querySelector('.lv-shell'))ready()});window.addEventListener('luvia:restaurant-intelligence-changed',()=>{if(activeView==='dashboard'&&root?.querySelector('.lv-shell'))ready()});window.addEventListener('luvia:schedule-intelligence-changed',()=>{if(activeView==='dashboard'&&root?.querySelector('.lv-shell'))window.LuviaTodayIntelligence?.refresh?.({refreshSchedule:false}).catch?.(()=>{})});window.addEventListener('luvia:today-intelligence-changed',()=>window.LuviaLiveDayCompanion?.refresh?.({refreshToday:false}).catch?.(()=>{}));window.addEventListener('luvia:live-day-changed',()=>{if(activeView==='dashboard'&&root?.querySelector('.lv-shell'))updateTodayWidget()});window.addEventListener('luvia:theme-changed',event=>{const accent=event.detail?.palette?.accent;if(!accent)return;document.documentElement.style.setProperty('--module-accent',accent);document.querySelectorAll('#restaurants-module,.lv-module-host,.lv-dashboard').forEach(el=>{el.style.setProperty('--trip-accent',accent);el.style.setProperty('--module-accent',accent);el.style.setProperty('--rv2-accent',accent)})});
  window.addEventListener('luvia:place-overlay-closed',event=>{if(event.detail?.returnView==='dashboard'&&activeView!=='dashboard')show('dashboard').catch(console.error)});window.LuviaApp=Object.freeze({version:'11.7.0',bootstrap,render,show,openPlace,activeView:()=>activeView});window.addEventListener('DOMContentLoaded',()=>{root=document.getElementById('app');bind();bootstrap()},{once:true});
})();
