(() => {
  'use strict';
  let root,activeView='dashboard',mountedRestaurant=false,unsubscribeTrip=null,unsubscribeAuth=null,unsubscribeProfile=null,authHydration=0,lastAuthUserId=null;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
  const snap=()=>window.LuviaTripStore.snapshot(),activeTrip=()=>snap().activeTrip,profile=()=>window.LuviaProfileService?.snapshot?.().profile||{};
  const date=v=>v?new Date(v+'T12:00:00').toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'}):'';
  const initials=p=>(p.displayName||p.email||'L').split(/\s+/).map(x=>x[0]).join('').slice(0,2).toUpperCase();
  const avatar=p=>p.avatarUrl?`<img class="lv-header-avatar" src="${esc(p.avatarUrl)}" alt="Profil">`:`<span class="lv-header-avatar" style="--avatar:${esc(p.avatarColor||'#ee6f83')}">${esc(initials(p))}</span>`;
  function bootScreen(text='Luvia wird vorbereitet …'){root.innerHTML=`<main class="lv-boot"><div class="lv-boot-card"><span class="lv-logo"></span><h1>Luvia</h1><p>${esc(text)}</p></div></main>`}
  function errorScreen(error){root.innerHTML=`<main class="lv-empty"><section class="lv-card"><span class="lv-logo"></span><h1>Start nicht möglich</h1><div class="lv-error">${esc(error?.message||error||'Unbekannter Fehler')}</div><div class="lv-actions"><button class="lv-primary" data-retry>Erneut versuchen</button><a class="lv-secondary" href="intelligence/console.html">Developer Console</a></div></section></main>`}
  function signedOut(){root.innerHTML=`<main class="lv-auth lv-card"><header class="lv-auth-head"><span class="lv-logo"></span><h1>Willkommen bei Luvia</h1><p>Gemeinsam reisen. Für immer erinnern.</p></header><div class="lv-auth-slot" data-auth-slot></div></main>`;window.ParisAuthUI.renderAuthForm(root.querySelector('[data-auth-slot]'),'login')}
  function noTrips(){root.innerHTML=`<main class="lv-empty"><section class="lv-card"><span class="lv-logo"></span><h1>Eure erste Reise wartet</h1><p>Erstellt eine Reise und legt Reiseziel, Zeitraum, Stil und Module fest.</p><div class="lv-actions" style="justify-content:center"><button class="lv-primary" data-create>Reise erstellen</button><button class="lv-secondary" data-profile-open="hub">Profil</button><button class="lv-secondary" data-signout>Abmelden</button></div></section></main>`}
  function dashboard(t){const destination=t.destination?.formattedAddress||t.destination?.name||'Reiseziel noch offen',dates=t.startDate?(t.endDate?`${date(t.startDate)} – ${date(t.endDate)}`:`Ab ${date(t.startDate)}`):'Zeitraum noch offen',p=profile();return `<section class="lv-dashboard"><article class="lv-card lv-hero"><span class="lv-kicker">Aktive Reise</span><div class="lv-titleline"><span class="lv-symbol">${esc(t.symbol||'❤️')}</span><div><h1>${esc(t.title||'Unsere Reise')}</h1><div class="lv-meta"><span>📍 ${esc(destination)}</span><span>📅 ${esc(dates)}</span></div></div></div><div class="lv-actions"><button class="lv-primary" data-view="restaurants">Restaurants öffnen</button><button class="lv-secondary" data-invite>Personen einladen</button><button class="lv-secondary" data-edit>Reise bearbeiten</button><button class="lv-secondary" data-profile-open="trips">Reise wechseln</button></div></article><div class="lv-grid" data-widget-grid>${window.LuviaDashboardWidgets.render({trip:t,profile:p,esc})}</div></section>`}
  function dock(t){const modules=window.LuviaModuleRegistry.enabledForTrip(t);return `<div class="lv-dock-wrap"><nav class="lv-dock"><button class="lv-nav ${activeView==='dashboard'?'on':''}" data-view="dashboard">🏠 Dashboard</button>${modules.map(id=>{const m=window.LuviaModuleRegistry.get(id);return `<button class="lv-nav ${activeView===id?'on':''}" data-view="${id}">${m.icon} ${esc(m.title)}</button>`}).join('')}<button class="lv-nav" data-profile-open="hub">👤 Profil</button></nav></div>`}
  async function unmountCurrent(){if(mountedRestaurant){await window.LuviaModules?.unmountModule?.('restaurants');mountedRestaurant=false}}
  async function show(view='dashboard'){const t=activeTrip();if(!t)return render();await unmountCurrent();activeView=view;const stage=root.querySelector('[data-stage]');if(!stage)return render();if(view==='restaurants'){stage.innerHTML='<section class="lv-module-host"><div id="restaurants-module"></div></section>';try{window.LuviaDestination?.refresh?.();await window.LuviaModules.mountModule('restaurants',t);mountedRestaurant=true}catch(error){console.error(error);stage.innerHTML='<section class="lv-card" style="padding:24px"><h2>Restaurants</h2><div class="lv-error">Das Restaurantmodul konnte nicht geöffnet werden.</div></section>'}}else{activeView='dashboard';stage.innerHTML=dashboard(t)}root.querySelector('.lv-dock-wrap')?.remove();root.querySelector('.lv-shell')?.insertAdjacentHTML('beforeend',dock(t));window.scrollTo({top:0,behavior:'instant'});}
  function ready(){const t=activeTrip(),p=profile();if(!t)return noTrips();window.LuviaTheme.apply(t);root.innerHTML=`<div class="lv-shell"><header class="lv-header"><span class="lv-logo"></span><div class="lv-trip"><strong>${esc(t.title||'Unsere Reise')}</strong><small>${esc(t.destination?.name||'Reiseziel offen')}</small></div><span class="lv-spacer"></span><button class="lv-icon" data-invite>＋ <span class="lv-label">Einladen</span></button><button class="lv-profile-trigger" data-profile-open="hub">${avatar(p)}<span><b>${esc(p.displayName||'Profil')}</b><small>${esc(t.title||'Reise')}</small></span></button></header><main class="lv-stage" data-stage></main></div>`;show(activeView)}
  function render(){const auth=window.ParisAuth.getState();if(auth.loading)return bootScreen();if(!auth.authenticated)return signedOut();const s=snap();if(!s.loaded)return bootScreen('Reisen werden geladen …');if(!s.hasTrips||!s.hasActiveTrip)return noTrips();return ready()}
  async function hydrateForAuth(client,authState){const run=++authHydration;if(!authState?.authenticated){lastAuthUserId=null;render();return}const userId=authState.user?.id||null;bootScreen('Profil und Reisen werden aus der Cloud geladen …');await Promise.all([window.LuviaTripStore.loadRemote(client,{authoritative:true}),window.LuviaProfileService.load(client)]);if(run!==authHydration)return;const p=profile();if(p.activeTripId&&snap().trips.some(t=>t.id===p.activeTripId))window.LuviaTripStore.setActive(p.activeTripId);else if(snap().activeTripId&&p.activeTripId!==snap().activeTripId)await window.LuviaProfileService.setActiveTrip(snap().activeTripId);lastAuthUserId=userId;window.LuviaRuntime.refresh();window.LuviaTheme.apply(activeTrip());window.LuviaDestination?.refresh?.();activeView=p.defaultView||'dashboard';render()}
  async function bootstrap(){bootScreen();try{const client=await window.LuviaSupabaseService.start();window.LuviaTripStore.initialize();await window.LuviaDestination?.init?.();window.LuviaPWA?.register?.().catch(e=>console.warn('[LuviaPWA]',e));unsubscribeTrip?.();unsubscribeAuth?.();unsubscribeProfile?.();unsubscribeTrip=window.LuviaTripStore.subscribe(s=>{if(s.activeTripId&&profile().activeTripId!==s.activeTripId&&window.ParisAuth.getState().authenticated)window.LuviaProfileService.setActiveTrip(s.activeTripId).catch(console.warn);if(activeView==='restaurants'&&mountedRestaurant)return;render()});unsubscribeProfile=window.LuviaProfileService.subscribe(()=>{window.LuviaTheme.apply(activeTrip());if(root?.querySelector('.lv-shell')&&activeView!=='restaurants')render()});unsubscribeAuth=window.ParisAuth.onChange(state=>{const uid=state?.user?.id||null;if(state?.authenticated&&uid!==lastAuthUserId)hydrateForAuth(client,state).catch(errorScreen);else render()});await hydrateForAuth(client,window.ParisAuth.getState())}catch(error){console.error('[LuviaApp]',error);errorScreen(error)}}
  function bind(){root.addEventListener('click',e=>{if(e.target.closest('[data-retry]'))return bootstrap();if(e.target.closest('[data-create]'))return window.LuviaTripCreator.open();if(e.target.closest('[data-signout]'))return window.ParisAuth.signOut();if(e.target.closest('[data-invite]'))return window.LuviaTripExperience.openInvite(activeTrip());if(e.target.closest('[data-edit]'))return window.LuviaTripExperience.openEdit(activeTrip());const po=e.target.closest('[data-profile-open]');if(po)return window.LuviaProfileFoundation.open(po.dataset.profileOpen||'hub');const view=e.target.closest('[data-view]')?.dataset.view;if(view)return show(view)})}
  window.LuviaApp=Object.freeze({version:'11.3.0',bootstrap,render,show});window.addEventListener('DOMContentLoaded',()=>{root=document.getElementById('app');bind();bootstrap()},{once:true});
})();
