(() => {
  'use strict';
  const VERSION='4.28.3',BUILD='13.28.3';
  let host=null,items=[],clusters=[],polaroids={},urls=[],unsubMedia=null,unsubClusters=null,busy=false,pending=false,loadTimer=null,activeItemId=null;
  const esc=v=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
  const dateKey=v=>{const d=new Date(v);return Number.isNaN(d.getTime())?'unknown':`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  const fmtDate=v=>v?new Intl.DateTimeFormat('de-DE',{weekday:'long',day:'2-digit',month:'long',year:'numeric'}).format(new Date(v)):'Ohne Datum';
  const fmtTime=v=>v?new Intl.DateTimeFormat('de-DE',{hour:'2-digit',minute:'2-digit'}).format(new Date(v)):'–';
  const displayName=x=>x.displayName||suggestName(x)||'Reisefoto';
  const suggestName=x=>{const d=new Date(x.capturedAt);if(Number.isNaN(d.getTime()))return'Reisefoto';const h=d.getHours(),part=h<6?'Nachtmoment':h<11?'Morgenmoment':h<14?'Mittagsmoment':h<18?'Nachmittagsmoment':h<22?'Abendmoment':'Nachtmoment';return`${part} · ${new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit'}).format(d)}`};
  const editCss=x=>{const e=x.editSettings||{},filter=e.filter||'none',preset={none:'',warm:'sepia(.18) saturate(1.12)',cool:'hue-rotate(8deg) saturate(1.08)',mono:'grayscale(1)',vivid:'saturate(1.35) contrast(1.08)',soft:'contrast(.92) saturate(.9)'}[filter]||'';return`brightness(${Number(e.brightness??100)}%) contrast(${Number(e.contrast??100)}%) saturate(${Number(e.saturation??100)}%) ${preset}`.trim()};
  const rotation=x=>Number(x.editSettings?.rotation||0);
  const revoke=()=>{urls.forEach(u=>URL.revokeObjectURL?.(u));urls=[]};
  function shell(){return `<section class="lv-gallery-view"><header class="lv-gallery-hero"><div><span>📸 Realtime Galerie</span><h1>Eure gemeinsamen Reisefotos</h1><p>Automatisch nach Reisetagen und Momenten sortiert – mit Favoriten, Polaroids und Fotoeditor.</p></div><button type="button" class="lv-gallery-upload" data-gallery-add>Fotos hinzufügen</button><input class="lv-gallery-file-input" type="file" accept="image/*,.jpg,.jpeg,.png,.webp,.heic,.heif,.avif" multiple data-gallery-input></header><div class="lv-gallery-status" data-gallery-status>Galerie wird geladen …</div><section class="lv-gallery-section"><div class="lv-gallery-section-head"><div><span>✨ Realtime erkannt</span><h2>Gemeinsame Fotomomente</h2></div><button type="button" data-gallery-refresh>Neu analysieren</button></div><div data-gallery-clusters></div></section><section class="lv-gallery-section"><div class="lv-gallery-section-head"><div><span>⭐ Auswahl</span><h2>Favoriten</h2></div><strong data-favorite-count>0</strong></div><div class="lv-favorites" data-gallery-favorites></div></section><section class="lv-gallery-section"><div class="lv-gallery-section-head"><div><span>🗓️ Nach Reisetagen</span><h2>Reisefotos</h2></div><strong data-gallery-count>0 Fotos</strong></div><div data-gallery-days></div></section></section>`}
  async function urlFor(item){try{const u=await window.LuviaMediaCore.signedUrl(item,1800);if(u)urls.push(u);return u||''}catch{return''}}
  function status(text,type=''){const el=host?.querySelector('[data-gallery-status]');if(el){el.textContent=text;el.dataset.state=type}}
  function showError(e){console.error('[LuviaGalleryView]',e);status(e?.message||'Galerie konnte nicht aktualisiert werden.','error')}
  function scheduleLoad(reason='Realtime'){clearTimeout(loadTimer);loadTimer=setTimeout(()=>load({reason}),120)}
  async function tripDays(){const ctx=await window.LuviaMediaCore.getContext(),t=ctx.trip||{},start=t.start_date||t.startDate||t.startsAt||t.start_at,end=t.end_date||t.endDate||t.endsAt||t.end_at;if(!start||!end)return[];const a=new Date(start),b=new Date(end),out=[];if(Number.isNaN(a.getTime())||Number.isNaN(b.getTime()))return[];a.setHours(12,0,0,0);b.setHours(12,0,0,0);for(let d=new Date(a);d<=b;d.setDate(d.getDate()+1))out.push(dateKey(d));return out}
  function card(item,compact=false){return `<article class="lv-gallery-photo ${compact?'is-compact':''}" data-photo="${esc(item.id)}"><button type="button" class="lv-photo-open" data-photo-open="${esc(item.id)}"><span class="lv-gallery-photo-image" data-photo-image="${esc(item.id)}" style="filter:${esc(editCss(item))};transform:rotate(${rotation(item)}deg)"><i>Bild wird geladen …</i></span></button><div class="lv-photo-meta"><strong>${esc(displayName(item))}</strong><small>${esc(fmtTime(item.capturedAt))}</small></div><div class="lv-photo-actions"><button type="button" data-photo-favorite="${esc(item.id)}" class="${item.favorite?'is-on':''}" title="Favorit">${item.favorite?'★':'☆'}</button><button type="button" data-photo-edit="${esc(item.id)}" title="Bearbeiten">✎</button><button type="button" data-photo-remove="${esc(item.id)}" title="Löschen">×</button></div></article>`}
  async function hydrateImages(root,list){for(const item of list){for(const el of root.querySelectorAll(`[data-photo-image="${CSS.escape(item.id)}"]`)){const u=await urlFor(item);if(u){el.style.backgroundImage=`url("${u}")`;el.querySelector('i')?.remove()}else el.innerHTML='<i>Vorschau nicht verfügbar</i>'}}}
  function bindPhotoActions(root){root.querySelectorAll('[data-photo-open]').forEach(b=>b.onclick=()=>openLightbox(b.dataset.photoOpen));root.querySelectorAll('[data-photo-favorite]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await window.LuviaMediaCore.toggleFavorite(b.dataset.photoFavorite);scheduleLoad('Favorit')});root.querySelectorAll('[data-photo-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openEditor(b.dataset.photoEdit)});root.querySelectorAll('[data-photo-remove]').forEach(b=>b.onclick=async e=>{e.stopPropagation();if(confirm('Foto wirklich entfernen?')){await window.LuviaMediaCore.remove(b.dataset.photoRemove);scheduleLoad('Löschen')}})}
  async function renderFavorites(){const out=host?.querySelector('[data-gallery-favorites]'),fav=items.filter(x=>x.favorite);host.querySelector('[data-favorite-count]').textContent=String(fav.length);if(!fav.length){out.innerHTML='<div class="lv-inline-empty">Noch keine Favoriten – tippe bei einem Foto auf ☆.</div>';return}out.innerHTML=fav.map(x=>card(x,true)).join('');await hydrateImages(out,fav);bindPhotoActions(out)}
  async function renderDays(){const out=host?.querySelector('[data-gallery-days]'),days=await tripDays(),daySet=new Set(days),groups=[];for(const k of days)groups.push({key:k,label:fmtDate(`${k}T12:00:00`),items:items.filter(x=>x.dayKey===k)});const other=items.filter(x=>!daySet.has(x.dayKey));if(other.length)groups.push({key:'other',label:'Sonstige Reisebilder',items:other});if(!groups.length){out.innerHTML='<div class="lv-gallery-empty"><b>📷</b><h3>Noch keine Reisefotos</h3></div>';return}out.innerHTML=groups.map(g=>{const hero=g.key!=='other'&&polaroids[g.key]?g.items.find(x=>x.id===polaroids[g.key]):null;return `<details class="lv-day-group"><summary><span>${esc(g.label)}</span><b>${g.items.length} Foto${g.items.length===1?'':'s'}</b><i>⌄</i></summary><div class="lv-day-content">${hero?`<div class="lv-polaroid"><div data-photo-image="${esc(hero.id)}" style="filter:${esc(editCss(hero))};transform:rotate(${rotation(hero)}deg)"></div><strong>Polaroid des Tages</strong><small>${esc(displayName(hero))}</small></div>`:''}<div class="lv-gallery-grid">${g.items.map(card).join('')}</div></div></details>`}).join('');await hydrateImages(out,items);bindPhotoActions(out);out.querySelectorAll('.lv-polaroid').forEach(p=>p.onclick=()=>{const id=p.querySelector('[data-photo-image]')?.dataset.photoImage;if(id)openLightbox(id)})}
  function clusterReason(c){const related=items.filter(x=>c.mediaIds?.includes(x.id)),gps=related.filter(x=>x.latitude!=null&&x.longitude!=null).length;if(gps===related.length&&related.length)return`${related.length} Fotos in kurzer Folge mit Standortdaten.`;if(gps>0)return`${related.length} Fotos in kurzer Folge; Standortdaten teilweise vorhanden.`;return`${related.length} Fotos innerhalb weniger Minuten; keine Standortdaten vorhanden.`}
  async function renderClusters(){const out=host?.querySelector('[data-gallery-clusters]'),visible=clusters.filter(c=>c.state!=='dismissed'&&c.mediaIds?.length);if(!visible.length){out.innerHTML='<div class="lv-gallery-empty compact"><b>✨</b><h3>Noch keine Fotomomente</h3><p>Mehrere Fotos innerhalb von 20 Minuten werden automatisch gruppiert.</p></div>';return}out.innerHTML=`<div class="lv-cluster-grid">${visible.map(c=>`<article class="lv-cluster-card"><div class="lv-cluster-collage">${c.mediaIds.slice(0,4).map(id=>`<span data-cluster-image="${esc(id)}"></span>`).join('')}<b>${c.mediaIds.length} Fotos</b></div><div class="lv-cluster-copy"><small>${esc(fmtDate(c.start_at))} · ${esc(fmtTime(c.start_at))}</small><h3>${esc(c.title||'Gemeinsamer Fotomoment')}</h3><p>${esc(clusterReason(c))}</p><div><button type="button" data-memory-bridge="${esc(c.id)}">Erinnerung prüfen</button><button type="button" data-cluster-dismiss="${esc(c.id)}">Auflösen</button></div></div></article>`).join('')}</div>`;for(const c of visible)for(const id of c.mediaIds.slice(0,4)){const item=items.find(x=>x.id===id),el=out.querySelector(`[data-cluster-image="${CSS.escape(id)}"]`);if(item&&el){const u=await urlFor(item);if(u)el.style.backgroundImage=`url("${u}")`}}out.querySelectorAll('[data-memory-bridge]').forEach(b=>b.onclick=()=>openMemoryBridge(b.dataset.memoryBridge));out.querySelectorAll('[data-cluster-dismiss]').forEach(b=>b.onclick=async()=>{if(confirm('Automatische Gruppierung auflösen?')){await window.LuviaMediaClustering.dissolve(b.dataset.clusterDismiss);scheduleLoad('Cluster')}})}
  async function openLightbox(id){activeItemId=id;const item=items.find(x=>x.id===id);if(!item)return;const u=await urlFor(item),overlay=document.createElement('div');overlay.className='lv-photo-overlay';overlay.innerHTML=`<section class="lv-photo-dialog"><button data-close>×</button><div class="lv-photo-large"><img src="${esc(u)}" alt="${esc(displayName(item))}" style="filter:${esc(editCss(item))};transform:rotate(${rotation(item)}deg)"></div><footer><div><strong>${esc(displayName(item))}</strong><small>${esc(fmtDate(item.capturedAt))} · ${esc(fmtTime(item.capturedAt))}</small></div><button data-light-fav>${item.favorite?'★ Favorit':'☆ Favorit'}</button><button data-light-edit>✎ Bearbeiten</button></footer></section>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('[data-close]').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()};overlay.querySelector('[data-light-fav]').onclick=async()=>{await window.LuviaMediaCore.toggleFavorite(id);close();scheduleLoad('Favorit')};overlay.querySelector('[data-light-edit]').onclick=()=>{close();openEditor(id)}}
  function editorControls(e){return `<label>Helligkeit <input type="range" min="50" max="150" value="${Number(e.brightness??100)}" data-ed="brightness"><output>${Number(e.brightness??100)}%</output></label><label>Kontrast <input type="range" min="50" max="150" value="${Number(e.contrast??100)}" data-ed="contrast"><output>${Number(e.contrast??100)}%</output></label><label>Sättigung <input type="range" min="0" max="180" value="${Number(e.saturation??100)}" data-ed="saturation"><output>${Number(e.saturation??100)}%</output></label><label>Filter <select data-ed="filter"><option value="none">Original</option><option value="warm">Warm</option><option value="cool">Kühl</option><option value="vivid">Lebendig</option><option value="soft">Soft</option><option value="mono">Schwarzweiß</option></select></label>`}
  async function openEditor(id){const item=items.find(x=>x.id===id);if(!item)return;const validPolaroidDay=(await tripDays()).includes(item.dayKey);const u=await urlFor(item),e={brightness:100,contrast:100,saturation:100,filter:'none',rotation:0,...item.editSettings},overlay=document.createElement('div');overlay.className='lv-photo-overlay';overlay.innerHTML=`<section class="lv-editor-dialog"><button data-close>×</button><h2>Foto bearbeiten</h2><div class="lv-editor-preview"><img src="${esc(u)}"></div><div class="lv-editor-name"><input value="${esc(item.displayName||'')}" placeholder="Titel des Fotos" data-edit-name><button type="button" data-name-suggestion>Vorschlag: ${esc(suggestName(item))}</button></div><div class="lv-editor-controls">${editorControls(e)}<button type="button" data-rotate>↻ 90° drehen</button></div><div class="lv-editor-actions"><button data-reset>Zurücksetzen</button><button data-polaroid ${validPolaroidDay?'':'disabled'} title="Nur für einen echten Reisetag verfügbar">Polaroid des Tages</button><button class="primary" data-save>Speichern</button></div></section>`;document.body.appendChild(overlay);const img=overlay.querySelector('img'),filterSel=overlay.querySelector('[data-ed="filter"]');filterSel.value=e.filter||'none';const state={...e};const apply=()=>{img.style.filter=editCss({editSettings:state});img.style.transform=`rotate(${Number(state.rotation||0)}deg)`};apply();overlay.querySelectorAll('input[type=range]').forEach(r=>r.oninput=()=>{state[r.dataset.ed]=Number(r.value);r.nextElementSibling.textContent=`${r.value}%`;apply()});filterSel.onchange=()=>{state.filter=filterSel.value;apply()};overlay.querySelector('[data-rotate]').onclick=()=>{state.rotation=(Number(state.rotation||0)+90)%360;apply()};overlay.querySelector('[data-name-suggestion]').onclick=()=>overlay.querySelector('[data-edit-name]').value=suggestName(item);overlay.querySelector('[data-reset]').onclick=()=>{Object.assign(state,{brightness:100,contrast:100,saturation:100,filter:'none',rotation:0});overlay.remove();openEditor(id)};overlay.querySelector('[data-polaroid]').onclick=async()=>{await window.LuviaMediaCore.setPolaroid(id,item.dayKey);status('Polaroid des Tages gespeichert.','ready');overlay.remove();scheduleLoad('Polaroid')};overlay.querySelector('[data-save]').onclick=async()=>{await window.LuviaMediaCore.update(id,{displayName:overlay.querySelector('[data-edit-name]').value,editSettings:state});overlay.remove();status('Fotoänderungen gespeichert.','ready');scheduleLoad('Editor')};const close=()=>overlay.remove();overlay.querySelector('[data-close]').onclick=close;overlay.onclick=e=>{if(e.target===overlay)close()}}
  async function openMemoryBridge(clusterId){try{if(!window.LuviaAIMemoryBridge)throw new Error('AI Memory Bridge ist nicht geladen.');const proposal=await window.LuviaAIMemoryBridge.analyze(clusterId),overlay=document.createElement('div');overlay.className='lv-photo-overlay';overlay.innerHTML=`<section class="lv-editor-dialog"><button data-close>×</button><span>✨ AI Memory Bridge</span><h2>${esc(proposal.title)}</h2><p>${esc(proposal.explanation)}</p><div class="lv-inline-empty"><b>Warum wurde dieser Moment erkannt?</b><ul>${(proposal.evidenceSummary?.facts||proposal.context?.summary?.facts||[]).map(f=>`<li>${esc(f)}</li>`).join('')}</ul></div>${proposal.actions.map((a,i)=>`<label class="lv-memory-option"><input type="checkbox" data-memory-action="${i}" checked><span><b>${esc(a.label)}</b><small>${Math.round((a.confidence||0)*100)} % Sicherheit</small></span></label>`).join('')}<div class="lv-editor-actions"><button data-cancel>Abbrechen</button><button class="primary" data-confirm>Bestätigen & verknüpfen</button></div></section>`;document.body.appendChild(overlay);const close=()=>overlay.remove();overlay.querySelector('[data-close]').onclick=close;overlay.querySelector('[data-cancel]').onclick=close;overlay.querySelector('[data-confirm]').onclick=async()=>{const selected=proposal.actions.filter((_,i)=>overlay.querySelector(`[data-memory-action="${i}"]`)?.checked);await window.LuviaAIMemoryBridge.apply(proposal,{confirmed:true,selectedActions:selected});close();status('Erinnerung wurde bestätigt und verknüpft.','ready');scheduleLoad('Memory Bridge')}}catch(e){showError(e)}}
  async function load(){if(!host)return;if(busy){pending=true;return}busy=true;pending=false;status('Galerie wird in Echtzeit aktualisiert …');try{items=await window.LuviaMediaCore.list({type:'image'});polaroids=await window.LuviaMediaCore.listPolaroids();const generated=window.LuviaMediaClustering.generate(items);clusters=await window.LuviaMediaClustering.syncGenerated(generated);host.querySelector('[data-gallery-count]').textContent=`${items.length} Foto${items.length===1?'':'s'}`;revoke();await renderClusters();await renderFavorites();await renderDays();status(`${items.length} Fotos · ${clusters.filter(c=>c.state!=='dismissed'&&c.mediaIds?.length).length} Fotomomente · Realtime aktiv`,'ready')}catch(e){showError(e)}finally{busy=false;if(pending)scheduleLoad('Nachlauf')}}
  async function upload(files){const list=[...files];if(!list.length)return;status(`${list.length} Foto${list.length===1?'':'s'} werden hochgeladen …`);for(let i=0;i<list.length;i++){status(`Upload ${i+1}/${list.length}: ${list[i].name||'Foto'}`);await window.LuviaMediaCore.upload(list[i])}await load()}
  async function mount(target){host=target;host.innerHTML=shell();const input=host.querySelector('[data-gallery-input]');host.querySelector('[data-gallery-add]').onclick=()=>{try{input.showPicker?input.showPicker():input.click()}catch{input.click()}};input.onchange=async()=>{const files=[...input.files];input.value='';try{await upload(files)}catch(e){showError(e)}};host.querySelector('[data-gallery-refresh]').onclick=()=>load();unsubMedia=await window.LuviaMediaCore.subscribe(()=>scheduleLoad('Media Realtime'));unsubClusters=await window.LuviaMediaClustering.subscribe(()=>scheduleLoad('Cluster Realtime'));await load();return()=>unmount()}
  async function unmount(){clearTimeout(loadTimer);await unsubMedia?.();await unsubClusters?.();unsubMedia=unsubClusters=null;revoke();if(host)host.innerHTML='';host=null}
  window.LuviaGalleryView=Object.freeze({version:VERSION,build:BUILD,mount,unmount,refresh:load});
})();
