(() => {
'use strict';
type Media=any;
type Model={title?:string;story?:string;media?:Media[];weights?:Record<string,number>;cover?:string;days?:any[];voices?:any[];sensory?:{food?:string;people?:string;weather?:string};destination?:string};
const clean=(html='')=>{const d=document.createElement('div');d.innerHTML=html;return (d.textContent||'').replace(/\s+/g,' ').trim()};
const mediaContract=()=>{const runtime=window as any;return runtime.LuviaMediaContractV1||runtime.LuviaMediaContract||null};
async function signed(m:Media){if(!m?.id)return'';try{return await mediaContract()?.reads?.signedUrl?.(m.id,3600)||''}catch{return''}}
async function image(m:Media){const u=await signed(m);if(!u)return null;return await new Promise<HTMLImageElement|null>(r=>{const im=new Image();im.crossOrigin='anonymous';im.onload=()=>r(im);im.onerror=()=>r(null);im.src=u})}
function selected(model:Model,n=8){const arr=[...(model.media||[])];return arr.sort((a,b)=>{const ca=String(a.id)===String(model.cover)?5:0,cb=String(b.id)===String(model.cover)?5:0;return(cb+(model.weights?.[String(b.id)]||2))-(ca+(model.weights?.[String(a.id)]||2))}).slice(0,n)}
function fit(ctx:CanvasRenderingContext2D,im:HTMLImageElement,x:number,y:number,w:number,h:number,zoom=1){const s=Math.max(w/im.naturalWidth,h/im.naturalHeight)*zoom,iw=im.naturalWidth*s,ih=im.naturalHeight*s;ctx.drawImage(im,x+(w-iw)/2,y+(h-ih)/2,iw,ih)}
function rounded(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,r:number){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function wrap(ctx:CanvasRenderingContext2D,t:string,x:number,y:number,w:number,line:number,max=6){let cur='',lines=0;for(const word of String(t||'').split(/\s+/)){const test=cur?cur+' '+word:word;if(ctx.measureText(test).width>w&&cur){ctx.fillText(cur,x,y);y+=line;lines++;cur=word;if(lines>=max-1)break}else cur=test}if(cur&&lines<max)ctx.fillText(cur,x,y);return y}
function plate(ctx:CanvasRenderingContext2D,x:number,y:number,w:number,h:number,alpha=.78){ctx.save();rounded(ctx,x,y,w,h,30);ctx.fillStyle=`rgba(14,19,25,${alpha})`;ctx.fill();ctx.restore()}
function dl(blob:Blob,name:string){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove()},2000)}
function canvas(w=1080,h=1920){const c=document.createElement('canvas');c.width=w;c.height=h;return c}
async function blob(c:HTMLCanvasElement,type='image/png',quality=.94){return await new Promise<Blob>((r,j)=>c.toBlob(b=>b?r(b):j(new Error('Export konnte nicht erzeugt werden.')),type,quality))}
async function storyFrames(model:Model){const medias=selected(model,7),ims=await Promise.all(medias.map(image));const title=model.title||`Unsere Reise${model.destination?' nach '+model.destination:''}`;const story=clean(model.story||'');const voice=(model.voices||[]).map(v=>clean(v.answer_text||v.answerText||'')).find(Boolean)||story;const frames:Blob[]=[];
  // Frame 1: cinematic cover + secondary memory inset
  {const c=canvas(),x=c.getContext('2d')!;x.fillStyle='#121820';x.fillRect(0,0,c.width,c.height);if(ims[0])fit(x,ims[0]!,0,0,1080,1920,1.05);const g=x.createLinearGradient(0,650,0,1920);g.addColorStop(0,'rgba(10,15,20,.04)');g.addColorStop(1,'rgba(10,15,20,.82)');x.fillStyle=g;x.fillRect(0,500,1080,1420);if(ims[1]){x.save();rounded(x,690,130,290,420,28);x.clip();fit(x,ims[1]!,690,130,290,420,1.05);x.restore();x.strokeStyle='rgba(255,255,255,.8)';x.lineWidth=6;rounded(x,690,130,290,420,28);x.stroke()}x.fillStyle='#fff';x.font='800 82px system-ui';wrap(x,title,76,1320,920,92,4);x.font='600 28px system-ui';x.fillStyle='rgba(255,255,255,.86)';x.fillText('LUVIA · GEMEINSAM ERINNERN',76,1810);frames.push(await blob(c))}
  // Frame 2: mixed scrapbook collage, not one image
  {const c=canvas(),x=c.getContext('2d')!;x.fillStyle='#f2e6d5';x.fillRect(0,0,1080,1920);const slots=[[60,110,470,630],[555,110,465,410],[555,545,465,500],[60,765,470,440]];for(let i=0;i<slots.length;i++){const im=ims[i+1]||ims[i];if(!im)continue;const [sx,sy,sw,sh]=slots[i];x.save();rounded(x,sx,sy,sw,sh,26);x.clip();fit(x,im!,sx,sy,sw,sh,1.04);x.restore()}plate(x,70,1265,940,470,.84);x.fillStyle='#fff';x.font='800 54px system-ui';wrap(x,title,110,1350,860,62,3);x.font='500 31px system-ui';x.fillStyle='rgba(255,255,255,.9)';wrap(x,voice||story||'Eure Reise. Eure Bilder. Eure Geschichte.',110,1510,860,44,5);x.font='700 22px system-ui';x.fillStyle='rgba(255,255,255,.72)';const bits=[model.sensory?.food,model.sensory?.weather,model.sensory?.people].filter(Boolean).slice(0,3);x.fillText(bits.length?bits.join(' · '):'LUVIA MEMORY STORY',110,1690);frames.push(await blob(c))}
  // Frame 3: voices + trip detail + photo strip
  {const c=canvas(),x=c.getContext('2d')!;const grad=x.createLinearGradient(0,0,1080,1920);grad.addColorStop(0,'#c9e6ed');grad.addColorStop(1,'#e8c99e');x.fillStyle=grad;x.fillRect(0,0,1080,1920);x.fillStyle='#173346';x.font='800 72px system-ui';wrap(x,'Was von dieser Reise bleibt',70,160,900,82,3);let y=430;const quotes=(model.voices||[]).map(v=>({name:v.displayName||v.name||'Reisender',text:clean(v.answer_text||v.answerText||''),reaction:v.reaction||'♥'})).filter(v=>v.text).slice(0,3);for(const q of quotes.length?quotes:[{name:'Eure Geschichte',text:story||'Einige Augenblicke brauchen keine große Erklärung.',reaction:'♥'}]){plate(x,70,y,940,210,.72);x.fillStyle='#fff';x.font='700 28px system-ui';x.fillText(`${q.reaction} ${q.name}`,105,y+58);x.font='500 30px system-ui';wrap(x,q.text,105,y+112,850,40,3);y+=240}const stripY=1370,sw=290,gap=28;for(let i=0;i<3;i++){const im=ims[i];if(!im)continue;const sx=70+i*(sw+gap);x.save();rounded(x,sx,stripY,sw,390,24);x.clip();fit(x,im,sx,stripY,sw,390,1.04);x.restore()}x.fillStyle='#173346';x.font='700 22px system-ui';x.fillText('LUVIA · MEMORY STORY SET',70,1845);frames.push(await blob(c))}
  return frames;
}
function crcTable(){const table=new Uint32Array(256);for(let n=0;n<256;n++){let c=n;for(let k=0;k<8;k++)c=(c&1)?0xedb88320^(c>>>1):c>>>1;table[n]=c>>>0}return table}const CRC=crcTable();
function crc32(data:Uint8Array){let c=0xffffffff;for(const b of data)c=CRC[(c^b)&255]^(c>>>8);return(c^0xffffffff)>>>0}
function u16(v:number){return new Uint8Array([v&255,(v>>>8)&255])}function u32(v:number){return new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255])}
function concat(parts:Uint8Array[]){const n=parts.reduce((a,b)=>a+b.length,0),out=new Uint8Array(n);let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
async function zip(files:{name:string;blob:Blob}[]){const enc=new TextEncoder(),locals:Uint8Array[]=[],central:Uint8Array[]=[];let offset=0;for(const f of files){const name=enc.encode(f.name),data=new Uint8Array(await f.blob.arrayBuffer()),crc=crc32(data),local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),name,data]);locals.push(local);central.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(data.length),u32(data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const cd=concat(central),body=concat(locals),end=concat([u32(0x06054b50),u16(0),u16(0),u16(files.length),u16(files.length),u32(cd.length),u32(body.length),u16(0)]);return new Blob([body,cd,end],{type:'application/zip'})}
async function exportStory(model:Model){const frames=await storyFrames(model);const z=await zip(frames.map((b,i)=>({name:`luvia-story-${String(i+1).padStart(2,'0')}.png`,blob:b})));dl(z,`luvia-story-set-${Date.now()}.zip`);return true}
async function exportPost(model:Model){const medias=selected(model,5),ims=await Promise.all(medias.map(image));const c=canvas(1080,1350),x=c.getContext('2d')!;x.fillStyle='#efe2d2';x.fillRect(0,0,1080,1350);const slots=[[50,50,620,690],[695,50,335,330],[695,405,335,335]];for(let i=0;i<slots.length;i++){if(!ims[i])continue;const [a,b,w,h]=slots[i];x.save();rounded(x,a,b,w,h,24);x.clip();fit(x,ims[i]!,a,b,w,h,1.03);x.restore()}plate(x,50,780,980,500,.80);x.fillStyle='#fff';x.font='800 58px system-ui';wrap(x,model.title||'Unsere Erinnerung',90,875,900,66,3);x.font='500 29px system-ui';x.fillStyle='rgba(255,255,255,.90)';wrap(x,clean(model.story||'').slice(0,420),90,1035,900,40,4);x.font='700 20px system-ui';x.fillStyle='rgba(255,255,255,.72)';x.fillText('LUVIA · GEMEINSAM ERINNERN',90,1230);dl(await blob(c),'luvia-post-'+Date.now()+'.png');return true}
function mp4Mime(){const candidates=['video/mp4;codecs=avc1.42E01E','video/mp4;codecs=h264','video/mp4'];return candidates.find(t=>(window as any).MediaRecorder?.isTypeSupported?.(t))||null}
async function exportMp4(model:Model,kind:'reel'|'film'='reel'){const mime=mp4Mime();if(!mime)throw new Error('Dieser Browser kann MP4/H.264 nicht direkt erzeugen. Luvia erstellt bewusst keinen WebM-Ersatz. Bitte den Export in aktuellem Edge/Chrome auf Windows testen.');const c=canvas(720,1280),x=c.getContext('2d')!,fps=30,stream=(c as any).captureStream(fps),rec=new MediaRecorder(stream,{mimeType:mime,videoBitsPerSecond:kind==='film'?8_000_000:6_000_000}),chunks:Blob[]=[];rec.ondataavailable=e=>e.data.size&&chunks.push(e.data);const done=new Promise<void>(r=>rec.onstop=()=>r());const media=selected(model,kind==='film'?10:7),ims=await Promise.all(media.map(image)),duration=kind==='film'?1.6:1.15;rec.start(500);for(let i=0;i<Math.max(1,ims.length);i++){const im=ims[i],frames=Math.round(duration*fps);for(let f=0;f<frames;f++){const p=f/(frames-1),ease=p*p*(3-2*p);x.fillStyle='#10161d';x.fillRect(0,0,720,1280);if(im){const zoom=1.03+ease*.08,s=Math.max(720/im.naturalWidth,1280/im.naturalHeight)*zoom,iw=im.naturalWidth*s,ih=im.naturalHeight*s;const panX=Math.sin(i*1.7)*30*ease,panY=Math.cos(i*1.3)*22*ease;x.globalAlpha=Math.min(1,p*6, (1-p)*6);x.drawImage(im,(720-iw)/2+panX,(1280-ih)/2+panY,iw,ih);x.globalAlpha=1}const g=x.createLinearGradient(0,650,0,1280);g.addColorStop(0,'rgba(8,12,16,0)');g.addColorStop(1,'rgba(8,12,16,.84)');x.fillStyle=g;x.fillRect(0,580,720,700);plate(x,34,900,652,300,.62);x.fillStyle='#fff';x.font='800 42px system-ui';wrap(x,model.title||'Unsere Erinnerung',64,970,590,48,3);const quote=clean((model.voices||[])[i%(Math.max(1,(model.voices||[]).length))]?.answer_text||model.story||'').slice(0,150);x.font='500 22px system-ui';x.fillStyle='rgba(255,255,255,.9)';wrap(x,quote,64,1110,590,30,3);x.font='700 15px system-ui';x.fillStyle='rgba(255,255,255,.7)';x.fillText(kind==='film'?'LUVIA MEMORY FILM':'LUVIA REEL',64,1230);await new Promise(r=>setTimeout(r,1000/fps))}}rec.stop();await done;const out=new Blob(chunks,{type:mime});dl(out,`luvia-${kind}-${Date.now()}.mp4`);return true}
(window as any).LuviaMemoryExportEngine=Object.freeze({version:'1.0.0',exportStory,exportPost,exportReel:(m:Model)=>exportMp4(m,'reel'),exportFilm:(m:Model)=>exportMp4(m,'film'),mp4Supported:()=>Boolean(mp4Mime())});
})();
