type JsonSchema=Record<string,unknown>;
const stringArray={type:'array',items:{type:'string'}};
const action={type:'object',additionalProperties:false,properties:{id:{type:'string'},label:{type:'string'},capability:{type:'string'},kind:{type:'string'}},required:['id','label','capability','kind']};
const toolCall={type:'object',additionalProperties:false,properties:{id:{type:'string'},name:{type:'string'},arguments:{type:'object',additionalProperties:true}},required:['id','name','arguments']};
const schemas:Record<string,JsonSchema>={
  orchestrator_step:{type:'object',additionalProperties:false,properties:{kind:{type:'string',enum:['tool_calls','final']},toolCalls:{type:'array',items:toolCall},result:{type:'object',additionalProperties:true},reasoningSummary:{type:'string'}},required:['kind','toolCalls','result','reasoningSummary']},
  assistant_response:{type:'object',additionalProperties:false,properties:{answer:{type:'string'},suggestedActions:{type:'array',items:action}},required:['answer','suggestedActions']},
  planning_dialogue:{type:'object',additionalProperties:false,properties:{understanding:{type:'string'},goals:{type:'array',items:{type:'object',additionalProperties:false,properties:{type:{type:'string'},label:{type:'string'},hardConstraints:{type:'array',items:{type:'object',additionalProperties:false,properties:{key:{type:'string'},value:{type:'string'},label:{type:'string'}},required:['key','value','label']}},softPreferences:{type:'array',items:{type:'object',additionalProperties:false,properties:{key:{type:'string'},value:{type:'string'},label:{type:'string'}},required:['key','value','label']}},timeWindow:{type:['object','null'],additionalProperties:false,properties:{label:{type:'string'},start:{type:'string'},end:{type:'string'},flexible:{type:'boolean'}},required:['label','start','end','flexible']},source:{type:'string'}},required:['type','label','hardConstraints','softPreferences','timeWindow','source']}},hardConstraints:{type:'array',items:{type:'object',additionalProperties:false,properties:{key:{type:'string'},value:{type:'string'},label:{type:'string'}},required:['key','value','label']}},softPreferences:{type:'array',items:{type:'object',additionalProperties:false,properties:{key:{type:'string'},value:{type:'string'},label:{type:'string'}},required:['key','value','label']}},followUpQuestion:{type:['object','null'],additionalProperties:false,properties:{text:{type:'string'},reason:{type:'string'},options:{type:'array',items:{type:'object',additionalProperties:false,properties:{label:{type:'string'},value:{type:'string'}},required:['label','value']}},allowFreeText:{type:'boolean'}},required:['text','reason','options','allowFreeText']},summary:{type:'object',additionalProperties:false,properties:{headline:{type:'string'},intro:{type:'string'},goalLabels:stringArray,hardLabels:stringArray,softLabels:stringArray},required:['headline','intro','goalLabels','hardLabels','softLabels']},unknowns:stringArray,confidence:{type:'number'}},required:['understanding','goals','hardConstraints','softPreferences','followUpQuestion','summary','unknowns','confidence']},
  trip_itinerary:{type:'object',additionalProperties:false,properties:{title:{type:'string'},summary:{type:'string'},days:{type:'array',items:{type:'object',additionalProperties:false,properties:{date:{type:'string'},label:{type:'string'},theme:{type:'string'},entries:{type:'array',items:{type:'object',additionalProperties:false,properties:{providerPlaceId:{type:'string'},time:{type:'string'},durationMinutes:{type:'number'},category:{type:'string'},reason:{type:'string'},confidence:{type:'number'}},required:['providerPlaceId','time','durationMinutes','category','reason','confidence']}},required:['date','label','theme','entries']}},alternatives:stringArray,uncoveredRequirements:stringArray,warnings:stringArray,confidence:{type:'number'}},required:['title','summary','days','alternatives','uncoveredRequirements','warnings','confidence']},
  discovery_plan:{type:'object',additionalProperties:false,properties:{followUpQuestion:{type:['object','null'],additionalProperties:false,properties:{text:{type:'string'},options:{type:'array',items:{type:'object',additionalProperties:false,properties:{label:{type:'string'},value:{type:'string'}},required:['label','value']}}},required:['text','options']},searchPlans:{type:'array',items:{type:'object',additionalProperties:false,properties:{query:{type:'string'},includedTypes:stringArray,weight:{type:'number'}},required:['query','includedTypes','weight']}},preferredSignals:stringArray,mustHave:stringArray,excludedSignals:stringArray,reasoningSummary:{type:'string'},confidence:{type:'number'}},required:['followUpQuestion','searchPlans','preferredSignals','mustHave','excludedSignals','reasoningSummary','confidence']},
  candidate_ranking:{type:'object',additionalProperties:false,properties:{rankings:{type:'array',items:{type:'object',additionalProperties:false,properties:{entityId:{type:'string'},score:{type:'number'},confidence:{type:'number'},reasons:stringArray,unknowns:stringArray},required:['entityId','score','confidence','reasons','unknowns']}},summary:{type:'string'}},required:['rankings','summary']},
  dashboard_brief:{type:'object',additionalProperties:false,properties:{headline:{type:'string'},message:{type:'string'},highlights:stringArray,suggestedActions:{type:'array',items:action}},required:['headline','message','highlights','suggestedActions']},
  timeline_proposal:{type:'object',additionalProperties:false,properties:{title:{type:'string'},explanation:{type:'string'},changes:{type:'array',items:{type:'object',additionalProperties:false,properties:{action:{type:'string',enum:['add','update','remove']},eventId:{type:'string'},date:{type:'string'},time:{type:'string'},title:{type:'string'},durationMinutes:{type:'number'},reason:{type:'string'}},required:['action','eventId','date','time','title','durationMinutes','reason']}},warnings:stringArray,confidence:{type:'number'}},required:['title','explanation','changes','warnings','confidence']},
  memory_signals:{type:'object',additionalProperties:false,properties:{signals:{type:'array',items:{type:'object',additionalProperties:false,properties:{signalKey:{type:'string'},category:{type:'string',enum:['dietary','travel_interests','travel_styles','activities','entertainment','dining','mobility','atmosphere','travel_pace','budget','family','accessibility']},value:{type:'object',additionalProperties:false,properties:{label:{type:'string'}},required:['label']},confidence:{type:'number'},evidence:{type:'string'}},required:['signalKey','category','value','confidence','evidence']}}},required:['signals']},
  media_cluster_titles:{type:'object',additionalProperties:false,properties:{titles:{type:'array',minItems:3,maxItems:10,items:{type:'string'}}},required:['titles']},
  media_description:{type:'object',additionalProperties:false,properties:{title:{type:'string'},description:{type:'string'},visibleSubjects:stringArray,confidence:{type:'number'}},required:['title','description','visibleSubjects','confidence']},
  memory_composition:{type:'object',additionalProperties:false,properties:{titles:{type:'array',minItems:4,maxItems:10,items:{type:'string'}},story:{type:'string'},shortCaption:{type:'string'},highlights:{type:'array',items:{type:'string'}},evidenceUsed:{type:'array',items:{type:'string'}}},required:['titles','story','shortCaption','highlights','evidenceUsed']},
  summary:{type:'object',additionalProperties:false,properties:{summary:{type:'string'}},required:['summary']}
};
export function outputSchema(name:string){const schema=schemas[name];if(!schema)throw Object.assign(new Error('OUTPUT_SCHEMA_NOT_FOUND'),{code:'OUTPUT_SCHEMA_NOT_FOUND',status:500});return schema}
