(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=(v,max=120000)=>{let text;try{text=JSON.stringify(v,(key,value)=>{if(Array.isArray(value)&&value.length>100)return [...value.slice(0,100),`… ${value.length-100} weitere Einträge`];return value},2)}catch(error){text=JSON.stringify({error:'Diagnose konnte nicht serialisiert werden',message:error?.message||String(error)},null,2)}return text.length>max?text.slice(0,max)+'\n… Ausgabe gekürzt …':text};
const row=(a,b,c='')=>`<div class="dc-row"><span>${esc(a)}</span><strong class="${c}">${esc(b)}</strong></div>`;
const stateClass=s=>s==='ready'?'ok':s==='failed'?'fail':'warn';
const stateLabel=s=>({ready:'Bereit',failed:'Fehlgeschlagen',warning:'Warnung',offline:'Offline',registered:'Registriert',initializing:'Startet',stopped:'Gestoppt',disabled:'Deaktiviert',destroyed:'Entfernt'})[s]||s;
const state={serviceTests:new Map(),eventSearch:'',eventName:'',logLevel:'',logSearch:'',unsubs:[]};
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),2600)}
function fmtTime(v){return v?new Date(v).toLocaleString('de-DE'):'–'}
function bytes(v){if(!Number.isFinite(v))return '–';if(v<1024)return v+' B';if(v<1048576)return (v/1024).toFixed(1)+' KB';return (v/1048576).toFixed(1)+' MB'}
function browserName(){const ua=navigator.userAgent;if(/Edg\//.test(ua))return 'Microsoft Edge';if(/Chrome\//.test(ua))return 'Google Chrome';if(/Firefox\//.test(ua))return 'Mozilla Firefox';if(/Safari\//.test(ua))return 'Safari';return navigator.appName||'Unbekannt'}
function osName(){const ua=navigator.userAgent;if(/Windows NT 10/.test(ua))return 'Windows 10/11';if(/Mac OS X/.test(ua))return 'macOS';if(/Android/.test(ua))return 'Android';if(/iPhone|iPad/.test(ua))return 'iOS/iPadOS';if(/Linux/.test(ua))return 'Linux';return navigator.platform||'Unbekannt'}
async function snapshot(){await Promise.race([LuviaKernel.waitUntilReady().catch(()=>null),new Promise(resolve=>setTimeout(resolve,2500))]);const kernel=await LuviaKernel.diagnostics();const list=LuviaServiceRegistry.list();const services={version:LuviaServiceRegistry.version,status:'ready',count:list.length,ready:list.filter(x=>x.state==='ready').length,failed:list.filter(x=>x.state==='failed').length,startOrder:(()=>{try{return LuviaServiceRegistry.order()}catch{return list.map(x=>x.name)}})(),services:list};return{kernel,services,env:LuviaEnvironment.snapshot(),data:LuviaData.snapshot(),events:LuviaKernelEvents.diagnostics(),logs:LuviaKernelLogger.diagnostics(),destination:LuviaDestinationContext.getActive(),platform:LuviaPlatform.snapshot()}}
function renderOverview(s){const k=s.kernel;$('#overviewMetrics').innerHTML=`<div class="dc-metric"><small>Core</small><b>${esc(k.version.core)}</b></div><div class="dc-metric"><small>Build</small><b>${esc(k.version.build)}</b></div><div class="dc-metric"><small>Services bereit</small><b>${s.services.ready}/${s.services.count}</b></div><div class="dc-metric"><small>Events</small><b>${s.events.historyCount}</b></div><div class="dc-metric"><small>Logs</small><b>${s.logs.entries}</b></div>`;$('#systemInfo').innerHTML=row('Kernel',k.status.ready?'Bereit':k.status.phase,k.status.ready?'ok':'warn')+row('Gesamtzustand',k.healthy?'Gesund':'Prüfen',k.healthy?'ok':'warn')+row('Environment',s.env.name,'ok')+row('Base URL',s.env.baseUrl)+row('Sicherer Kontext',s.env.secureContext?'Ja':'Nein',s.env.secureContext?'ok':'warn')+row('Online',navigator.onLine?'Ja':'Nein',navigator.onLine?'ok':'warn')+row('Reiseziel',s.destination.displayName||s.destination.name||'Nicht erkannt');$('#runtimeInfo').innerHTML=row('Browser',navigator.userAgent)+row('Sprache',navigator.language)+row('Viewport',innerWidth+' × '+innerHeight)+row('PWA',s.env.isPwa?'Ja':'Nein',s.env.isPwa?'ok':'')+row('Native',s.env.isNative?'Ja':'Vorbereitet',s.env.isNative?'ok':'warn')+row('Startreihenfolge',s.services.startOrder.join(' → '))}
function renderServices(s){$('#serviceGrid').innerHTML=s.services.services.map(x=>{const t=state.serviceTests.get(x.name);return `<article class="service-card"><div class="service-title"><div><h3>${esc(x.name)}</h3><small>${esc(x.description)}</small></div><span class="dc-badge ${stateClass(x.state)}">${esc(stateLabel(x.state))}</span></div>${row('Version',x.version)+row('Abhängigkeiten',x.dependencies.length?x.dependencies.join(', '):'keine')+row('Startzeit',fmtTime(x.startedAt))+row('Init',x.metrics.initMs==null?'–':x.metrics.initMs+' ms')}${t?`<div class="service-result">${row('Letzter Test',t.running?'Läuft …':(t.ok?'Erfolgreich':'Fehlgeschlagen'),t.running?'warn':t.ok?'ok':'fail')+(!t.running?row('Dauer',t.durationMs+' ms')+row('Zeitpunkt',fmtTime(t.completedAt)):'')}</div>`:''}<div class="dc-card-actions" style="margin-top:12px"><button data-service-test="${esc(x.name)}" ${t?.running?'disabled':''}>${t?.running?'Test läuft …':'Testen'}</button><button class="secondary" data-service-detail="${esc(x.name)}">Diagnose</button></div></article>`}).join('')}

function renderPlaces(){const d=window.LuviaPlaceCore?.diagnostics?.();if(!d)return;$('#placeCoreStatus').innerHTML=row('Status',d.status,'ok')+row('Version',d.version,'ok')+row('Geladene Places',d.placeCount)+row('Registrierte Typen',d.registry.registeredTypes,d.registry.registeredTypes===12?'ok':'warn')+row('Registrierte Adapter',d.registry.registeredAdapters,d.registry.registeredAdapters===12?'ok':'warn');const c=d.restaurantCompatibility;$('#placeRestaurantStatus').innerHTML=row('Compatibility Layer',c.active?'Aktiv':'Aus',c.active?'warn':'ok')+row('Normalisierte Restaurants',c.normalized)+row('Fehlerhafte Datensätze',c.failed,c.failed?'fail':'ok')+row('Mapping',c.mapping);$('#placeAdapterGrid').innerHTML=d.registry.adapters.map(a=>`<article class="service-card"><div class="service-title"><div><h3>${esc(a.key)}</h3><small>Adapter ${esc(a.version)}</small></div><span class="dc-badge ${a.state==='ready'?'ok':a.state==='failed'?'fail':'warn'}">${esc(a.state)}</span></div>${row('Source Data',a.sourceData?'Ja':'Noch nicht',a.sourceData?'ok':'warn')}${a.reason?row('Hinweis',a.reason):''}</article>`).join('');const p=d.presence||{},t=d.timeline||{};if($('#presenceStatus'))$('#presenceStatus').innerHTML=row('Status',p.enabled?'Aktiv':'Bereit',p.enabled?'ok':'warn')+row('Berechtigung',p.permission||'unknown',p.permission==='denied'?'fail':p.permission==='granted'?'ok':'warn')+row('Verfolgte Places',p.trackedPlaces||0)+row('Aktive Aufenthalte',p.activeSessions?.length||0)+row('Erkannte Besuche',p.metrics?.visited||0);if($('#timelineStatus'))$('#timelineStatus').innerHTML=row('Status',t.status||'not_loaded',t.status==='ready'?'ok':'warn')+row('Ereignisse',t.eventCount||0)+row('Realtime',t.realtime?'Aktiv':'Bereit',t.realtime?'ok':'warn')+row('Offline Queue',t.metrics?.queued||0,t.metrics?.queued?'warn':'ok');$('#placeSnapshot').textContent=pretty(d)}


function renderBookingCore(){
 const api=window.LuviaBookingCoreDiagnostics;if(!api||!$('#bookingCoreOverview'))return;
 const d=api.snapshot();
 $('#bookingCoreBadge').textContent=d.healthy?'Gesund':'Prüfen';$('#bookingCoreBadge').className='dc-badge '+(d.healthy?'ok':'warn');
 $('#bookingCoreOverview').innerHTML=row('Core','Booking Core','ok')+row('Diagnose-Version',d.version,'ok')+row('Build',d.build,'ok')+row('Gesamtstatus',d.status,d.healthy?'ok':'warn')+row('Provider registriert',d.providerCount)+row('Teilbereiche bereit',`${d.groups.filter(g=>g.status==='ready').length}/${d.groups.length}`,d.groups.every(g=>g.status==='ready')?'ok':'warn');
 $('#bookingCoreGroups').innerHTML=d.groups.map(g=>`<article class="service-card"><div class="service-title"><div><h3>${esc(g.label)}</h3><small>${g.available}/${g.total} Komponenten verfügbar</small></div><span class="dc-badge ${g.status==='ready'?'ok':'warn'}">${esc(g.status)}</span></div><div>${g.components.map(k=>row(k,window.LuviaBookingCoreDiagnostics?((({foundation:'Foundation',reservation:'Reservation',email:'Email',providers:'Provider',commercial:'Commercial'})[g.key])||'geladen'):'–')).join('')}</div></article>`).join('');
 const o=d.orchestration||{};$('#bookingProviderStatus').innerHTML=row('Orchestration',o.status||'unavailable',o.status==='ready'?'ok':'warn')+row('Ranking',o.ranking||'–')+row('Commercial Weight Cap',o.commercialWeightCapped??'–')+row('Direkter guter Weg schlägt Commercial-only',o.directWinsCommercialOnly?'Ja':'Nein',o.directWinsCommercialOnly?'ok':'fail');
 $('#bookingOrchestrationSnapshot').textContent=pretty(o);
 $('#bookingPolicyStatus').innerHTML=Object.entries(d.policies).map(([k,v])=>row(k,v?'Aktiv':'Fehlt',v?'ok':'fail')).join('');
}

async function renderToday(){const t=window.LuviaTodayIntelligence?.diagnostics?.()||{},p=window.LuviaPresenceVisitCore?.diagnostics?.()||{},c=window.LuviaCrossModuleRecommendations?.diagnostics?.()||{};if(!$('#todayStatus'))return;$('#todayStatus').innerHTML=row('Status',t.status||'unavailable',t.status==='unavailable'?'warn':'ok')+row('Datum',t.date||'–')+row('Current',t.current?.title||'–')+row('Next',t.next?.title||'–')+row('Upcoming',t.upcoming?.length||0)+row('Konflikte',t.conflicts?.length||0,t.conflicts?.length?'warn':'ok');$('#todayLocation').innerHTML=row('Global aktiviert',p.preferenceEnabled?'Ja':'Nein',p.preferenceEnabled?'ok':'warn')+row('Watcher',p.enabled?'Aktiv':'Inaktiv',p.enabled?'ok':'warn')+row('Berechtigung',p.permission||'unknown',p.permission==='granted'?'ok':p.permission==='denied'?'fail':'warn')+row('Place-Typen',p.placeTypes?.join(', ')||'–')+row('Getrackte Places',p.trackedPlaces||0)+row('Aktive Aufenthalte',p.activeSessions?.length||0);$('#todaySuggestions').textContent=pretty({freeWindows:t.freeWindows||[],suggestions:t.suggestions||[],slots:c.slots||{}});$('#todayTrace').textContent=pretty(t);$('#todaySync').innerHTML=row('Online',navigator.onLine?'Ja':'Nein',navigator.onLine?'ok':'warn')+row('Today Cache',t.sourceState?.schedule||'–')+row('Recommendations',c.offline?'Cache/Offline':'Live',c.offline?'warn':'ok')+row('Letzter GPS-Sync',p.metrics?.lastSyncAt||'–');}
async function renderCore4(){const api=window.LuviaCore4Diagnostics;if(!api||!$('#core4Health'))return;const health=api.healthSnapshot();const healthy=health.health.servicesReady===health.health.servicesTotal&&health.health.placeTypes===12&&health.health.adapters===12;const d={...health,adapters:api.adapterHealth?.()||[],compatibility:api.compatibilityAudit?.()||{},schedule:api.scheduleTrace?.()||{},recommendations:api.recommendationTrace?.()||{},visits:api.visitTrace?.()||{},cache:api.cacheAudit?.()||{},performance:api.performance?.()||{},lastSmoke:null};$('#core4HealthBadge').textContent=healthy?'Gesund':'Prüfen';$('#core4HealthBadge').className='dc-badge '+(healthy?'ok':'warn');$('#core4Health').innerHTML=row('Version',d.version,'ok')+row('Build',d.build,'ok')+row('Services',`${d.health.servicesReady}/${d.health.servicesTotal}`,d.health.servicesReady===d.health.servicesTotal?'ok':'warn')+row('Place-Typen',d.health.placeTypes,d.health.placeTypes===12?'ok':'warn')+row('Adapter',d.health.adapters,d.health.adapters===12?'ok':'warn')+row('Schedule Events',d.health.scheduleEvents)+row('Timeline Events',d.health.timelineEvents)+row('Today Status',d.health.todayStatus,d.health.todayStatus==='unavailable'?'warn':'ok')+row('Today Konflikte',d.health.todayConflicts,d.health.todayConflicts?'warn':'ok');$('#core4Adapters').innerHTML=(d.adapters||[]).map(a=>row(a.key||a.type||'Adapter',a.state||'unknown',a.state==='ready'?'ok':a.state==='failed'?'fail':'warn')).join('')||row('Adapter','Keine Daten','warn');$('#core4Compatibility').innerHTML=Object.entries(d.compatibility||{}).map(([key,value])=>row(key,`${value.state} · ${value.decision}`,value.state==='missing'?'fail':value.required?'warn':'ok')).join('');$('#core4Schedule').textContent=pretty(d.schedule);$('#core4Recommendations').textContent=pretty(d.recommendations);$('#core4Visits').textContent=pretty(d.visits);$('#core4Cache').textContent=pretty(d.cache);$('#core4Performance').textContent=pretty(d.performance);if(d.lastSmoke)$('#core4Smoke').textContent=pretty(d.lastSmoke);const verification=window.LuviaCloudOnlyPlaceVerification?.snapshot?.();if($('#cloudOnlyVerificationStatus'))$('#cloudOnlyVerificationStatus').innerHTML=verification?row('API','Geladen','ok')+row('Cloud-only',verification.cloudOnly?'Ja':'Prüfen',verification.cloudOnly?'ok':'warn')+row('Lokale Fachschlüssel',verification.forbiddenLocalDomainKeys?.length||0,verification.forbiddenLocalDomainKeys?.length?'fail':'ok'):row('API','Nicht geladen','fail')}
function renderEvents(){let records=LuviaKernelEvents.history(100).slice().reverse();if(state.eventName)records=records.filter(r=>r.event.name===state.eventName);if(state.eventSearch){const q=state.eventSearch.toLowerCase();records=records.filter(r=>pretty(r).toLowerCase().includes(q))}const names=[...new Set(LuviaKernelEvents.history(300).map(r=>r.event.name))].sort();$('#eventNameFilter').innerHTML='<option value="">Alle Eventnamen</option>'+names.map(n=>`<option ${n===state.eventName?'selected':''}>${esc(n)}</option>`).join('');$('#eventTable').innerHTML=records.length?records.map(r=>`<tr><td>${esc(new Date(r.event.at).toLocaleTimeString('de-DE'))}</td><td><b>${esc(r.event.name)}</b><br><small>${esc(r.event.id)}</small></td><td>${r.listenerCount}</td><td class="${r.errorCount?'fail':'ok'}">${r.successCount}/${r.errorCount}</td><td>${r.durationMs} ms</td><td><button class="secondary" data-event-detail="${esc(r.event.id)}">Details</button></td></tr>`).join(''):'<tr><td colspan="6" class="dc-empty">Noch keine passenden Events.</td></tr>';const d=LuviaKernelEvents.diagnostics(),healthy=d.stats.failedDeliveries===0;$('#eventStats').innerHTML=`<div class="health-line"><span class="health-dot ${healthy?'':'warn'}"></span><strong class="${healthy?'ok':'warn'}">${healthy?'Gesund':'Historische Listener-Fehler vorhanden'}</strong></div>`+row('Aktive Abonnements',d.subscriptionCount,d.subscriptionCount?'ok':'')+row('Event-Historie',d.historyCount)+row('Gesendet seit Reset',d.stats.emitted,'ok')+row('Zugestellt seit Reset',d.stats.delivered,'ok')+row('Listener-Fehler seit Reset',d.stats.failedDeliveries,d.stats.failedDeliveries?'warn':'ok')+row('Letztes Event',d.lastEvent?fmtTime(d.lastEvent.at):'–')}
function storageEntries(storage){const out=[];for(let i=0;i<storage.length;i++){const key=storage.key(i),value=storage.getItem(key);out.push({key,size:new Blob([value||'']).size,preview:(value||'').slice(0,180)})}return out}
function renderData(s){$('#dataStats').innerHTML=row('Data Layer',LuviaData.version,'ok')+row('Cache-Schlüssel',s.data.cacheKeys.length,'ok')+row('Sync Queue',s.data.queueCount,s.data.queueCount?'warn':'ok')+row('Local Storage',localStorage.length)+row('Session Storage',sessionStorage.length)+row('Online',navigator.onLine?'Ja':'Nein',navigator.onLine?'ok':'warn');const entries=[...storageEntries(localStorage).map(x=>({...x,area:'localStorage'})),...storageEntries(sessionStorage).map(x=>({...x,area:'sessionStorage'}))];$('#storageTable').innerHTML=entries.length?entries.map(x=>`<tr><td>${esc(x.area)}</td><td>${esc(x.key)}</td><td>${bytes(x.size)}</td><td>${esc(x.preview)}</td></tr>`).join(''):'<tr><td colspan="4" class="dc-empty">Keine Browser-Speichereinträge.</td></tr>';$('#dataSnapshot').textContent=pretty(s.data)}
function renderLogs(){let logs=LuviaKernelLogger.list({level:state.logLevel}).slice().reverse();if(state.logSearch){const q=state.logSearch.toLowerCase();logs=logs.filter(x=>pretty(x).toLowerCase().includes(q))}$('#logTable').innerHTML=logs.length?logs.map(x=>`<tr><td>${esc(new Date(x.at).toLocaleTimeString('de-DE'))}</td><td><span class="dc-badge ${x.level==='error'?'fail':x.level==='warn'?'warn':''}">${esc(x.level)}</span></td><td>${esc(x.source)}</td><td><b>${esc(x.message)}</b><br><small>${esc(x.context?pretty(x.context).slice(0,220):'')}</small></td></tr>`).join(''):'<tr><td colspan="4" class="dc-empty">Keine passenden Logeinträge.</td></tr>';const errors=LuviaKernelLogger.list({level:'error'}).slice().reverse();$('#errorCenter').innerHTML=errors.length?errors.slice(0,20).map(x=>`<div class="service-result"><b>${esc(x.source)} · ${esc(fmtTime(x.at))}</b><div>${esc(x.message)}</div></div>`).join(''):'<div class="dc-empty">Keine Kernel-Fehler protokolliert.</div>'}
function renderDeployment(){const s=LuviaPlatform.snapshot(),b=s.build,overrides=s.featureFlagOverrides||{};$('#deploymentInfo').innerHTML=row('Core',b.core,'ok')+row('Build',b.build,'ok')+row('Name',b.name)+row('Release-Kanal',b.channel,'ok')+row('Environment',b.environment)+row('Veröffentlicht',b.releasedAt)+row('Build-Zeit',fmtTime(b.builtAt))+row('Hostname',s.environment.hostname||'lokal')+row('Base URL',s.environment.baseUrl);$('#runtimeConfigInfo').innerHTML=row('Quelle',s.source,s.source==='runtime-config.json'?'ok':'warn')+row('Geladen',fmtTime(s.loadedAt))+row('Wartungsmodus',s.maintenance.enabled?'Aktiv':'Aus',s.maintenance.enabled?'warn':'ok')+row('Assets',s.endpoints.assets)+row('Intelligence',s.endpoints.intelligence||'Nicht konfiguriert',s.endpoints.intelligence?'ok':'warn')+(s.lastError?row('Letzter Fehler',s.lastError,'warn'):'');$('#featureFlagGrid').innerHTML=Object.entries(s.featureFlags).map(([name,value])=>`<article class="service-card"><div class="service-title"><div><h3>${esc(name)}</h3><small>Runtime Feature Flag</small></div><span class="dc-badge ${value?'ok':'warn'}">${value?'Aktiv':'Aus'}</span></div>${Object.prototype.hasOwnProperty.call(overrides,name)?'<div class="feature-override">Lokaler Browser-Override aktiv</div>':''}<div class="dc-card-actions" style="margin-top:12px"><button class="${value?'secondary':''}" data-feature-flag="${esc(name)}" data-value="${value?'false':'true'}">${value?'Deaktivieren':'Aktivieren'}</button></div></article>`).join('')}
function capabilityItem(label,value,cls=''){return `<div class="capability-item"><span>${esc(label)}</span><strong class="${cls}">${esc(value)}</strong></div>`}
function renderPlatform(s){const nav=navigator,p=LuviaPlatform.snapshot(),cap=p.capabilities,conn=nav.connection;$('#platformInfo').innerHTML=row('Environment',s.env.name,'ok')+row('Hostname',s.env.hostname||'lokal')+row('Base Path',s.env.basePath)+row('PWA-Modus',s.env.isPwa?'Aktiv':'Nicht aktiv')+row('Standalone',matchMedia('(display-mode: standalone)').matches?'Ja':'Nein')+row('Touchpunkte',nav.maxTouchPoints||0)+row('Online',nav.onLine?'Ja':'Nein',nav.onLine?'ok':'warn');$('#urlInspector').innerHTML=Object.entries(p.endpoints).map(([k,v])=>row(k.charAt(0).toUpperCase()+k.slice(1),v||'Nicht konfiguriert',v?'ok':'warn')).join('');const cards=[['Browser',capabilityItem('Browser',browserName())+capabilityItem('Betriebssystem',osName())+capabilityItem('Sprache',nav.language)],['Anzeige',capabilityItem('Auflösung',screen.width+' × '+screen.height)+capabilityItem('Viewport',innerWidth+' × '+innerHeight)+capabilityItem('DPR',String(devicePixelRatio))],['Netzwerk',capabilityItem('Typ',conn?.effectiveType||'Unbekannt')+capabilityItem('Downlink',conn?.downlink!=null?conn.downlink+' MBit/s':'–')+capabilityItem('Latenz',conn?.rtt!=null?conn.rtt+' ms':'–')+capabilityItem('Datensparen',conn?.saveData?'Ja':'Nein',conn?.saveData?'warn':'ok')],['Hardware',capabilityItem('Threads',nav.hardwareConcurrency||'–')+capabilityItem('Arbeitsspeicher',nav.deviceMemory?nav.deviceMemory+' GB':'Nicht verfügbar')+capabilityItem('Touchpunkte',nav.maxTouchPoints||0)],['Funktionen',Object.entries({ServiceWorker:cap.serviceWorker,'Web Share':cap.share,Geolocation:cap.geolocation,Clipboard:cap.clipboard,Benachrichtigungen:cap.notifications,'Wake Lock':cap.wakeLock,Vibration:cap.vibration,Kamera:cap.camera,Mikrofon:cap.microphone}).map(([k,v])=>capabilityItem(k,v?'Unterstützt':'Nicht unterstützt',v?'ok':'warn')).join('')]];$('#capabilityCards').innerHTML=cards.map(([title,body])=>`<article class="capability-card"><h3>${esc(title)}</h3><div class="capability-list">${body}</div></article>`).join('');$('#capabilityJson').textContent=pretty({userAgent:nav.userAgent,platform:nav.platform,languages:nav.languages,hardwareConcurrency:nav.hardwareConcurrency,deviceMemory:nav.deviceMemory||null,connection:conn?{effectiveType:conn.effectiveType,downlink:conn.downlink,rtt:conn.rtt,saveData:conn.saveData}:null,screen:{width:screen.width,height:screen.height,pixelRatio:devicePixelRatio},capabilities:cap,urls:p.endpoints})}

function renderRecommendations(){
 const api=window.LuviaRecommendations,d=api?.diagnostics?.()||{metrics:{},adapters:[],providers:[],constraints:[],settings:{}},m=d.metrics||{},ctx=d.context||{},group=ctx.group||{};
 const metrics=$('#recommendationMetrics');if(!metrics)return;
 metrics.innerHTML=`<div class="dc-metric"><small>Engine</small><b>${esc(d.version||'–')}</b></div><div class="dc-metric"><small>Regeln</small><b>${esc(d.ruleVersion||'–')}</b></div><div class="dc-metric"><small>Erzeugt</small><b>${m.generated||0}</b></div><div class="dc-metric"><small>Blockiert</small><b>${m.blocked||0}</b></div><div class="dc-metric"><small>Angenommen</small><b>${m.accepted||0}</b></div><div class="dc-metric"><small>Abgelehnt</small><b>${m.rejected||0}</b></div>`;
 const presence=window.LuviaPresenceVisitCore?.diagnostics?.()||{},liveLocation=ctx.travel?.location||presence.lastPosition||window.LuviaTravelContext?.snapshot?.()?.location||null,locationLabel=liveLocation?'GPS verfügbar':presence.preferenceEnabled?(window.LUVIA_DIAGNOSTICS_MODE?'In der App aktiviert':'Warte auf GPS'):'Im Profil deaktiviert';$('#recommendationContext').innerHTML=row('Reise',ctx.trip?.name||ctx.tripId||'Keine aktive Reise')+row('Modul',ctx.module||'–')+row('Reisephase',ctx.travel?.phase||'–')+row('Reisetag',ctx.travel?.tripDay||'–')+row('Standort',locationLabel,liveLocation?'ok':presence.preferenceEnabled?'warn':'')+row('Teilnehmer',group.participantCount||0)+row('Ernährungsweisen',(group.dietary||[]).join(', ')||'Keine')+row('Harte Anforderungen',Object.entries(group.hardRequirements||{}).filter(([,v])=>Array.isArray(v)?v.length:Boolean(v)).map(([k])=>k).join(', ')||'Keine');
 const settings=d.settings||{};$('#recommendationControls').innerHTML=`<label class="dc-control"><input type="checkbox" id="recEnabled" ${settings.enabled!==false?'checked':''}> Engine aktiv</label><label class="dc-control"><input type="checkbox" id="recPersonalization" ${settings.personalization!==false?'checked':''}> Personalisierung</label><label class="dc-control"><input type="checkbox" id="recLocation" ${settings.useLocation!==false?'checked':''}> Standort im Score</label><label class="dc-control"><input type="checkbox" id="recLearning" ${settings.learning!==false?'checked':''}> Lernsignale erfassen</label><label class="dc-control"><input type="checkbox" id="recDebug" ${settings.debug?'checked':''}> Debug-Modus</label><label>Max. Entfernung (m)<input id="recMaxDistance" type="number" value="${Number(settings.maxDistanceMeters||30000)}"></label><label>Minimaler Score<input id="recMinimumScore" type="number" min="0" max="100" value="${Number(settings.minimumScore||0)}"></label>`;
 $('#recommendationAdapters').innerHTML=[...(d.adapters||[]).map(a=>row(`Adapter · ${a}`,'Aktiv','ok')),...(d.providers||[]).map(a=>row(`Provider · ${a}`,'Aktiv','ok'))].join('')||'<div class="dc-empty">Noch keine Adapter oder Provider registriert.</div>';
 $('#recommendationConstraints').innerHTML=(d.constraints||[]).map(a=>row(a,'Aktiv','ok')).join('')+row('Generische Core-Constraints','Aktiv','ok');
 const first=d.lastResult?.[0];$('#recommendationScore').innerHTML=first?row('Kandidat',first.candidate?.name||first.entityId)+row('Gesamtscore',`${first.score} %`,first.status==='blocked'?'fail':'ok')+row('Gruppen-Match',first.groupMatch?.groupScore!=null?`${first.groupMatch.groupScore} %`:'–')+row('Status',first.status,first.status==='blocked'?'fail':'ok'):'<div class="dc-empty">Noch keine Berechnung vorhanden.</div>';
 $('#recommendationSnapshot').textContent=pretty(first?{reasons:first.reasons,warnings:first.warnings,constraints:first.constraints,groupMatch:first.groupMatch,components:first.scoreComponents,context:first.contextSnapshot}:{lastRunAt:m.lastRunAt,lastError:m.lastError,cacheKeys:d.cacheKeys});
 $('#recommendationDecisionLog').innerHTML=(d.lastEvents||[]).slice(0,20).map(e=>row(new Date(e.createdAt).toLocaleTimeString('de-DE'),`${e.eventType} · ${e.entityType||''} ${e.entityId||''}`)).join('')||'<div class="dc-empty">Noch keine Recommendation-Ereignisse.</div>';
}

async function renderAll(){const s=await snapshot();renderOverview(s);const id=document.querySelector('.dc-panel.active')?.id?.replace('panel-','')||'overview';if(id==='services')renderServices(s);else if(id==='events')renderEvents();else if(id==='data')renderData(s);else if(id==='logs')renderLogs();else if(id==='deployment')renderDeployment();else if(id==='platform'||id==='pwa')renderPlatform(s);else if(id==='recommendations')renderRecommendations();else if(id==='places')renderPlaces();else if(id==='today')setTimeout(()=>renderToday().catch(error=>{console.error('[Luvia Today Diagnostics]',error);toast('Today-Diagnose konnte nicht geladen werden.')}),0);else if(id==='core4')setTimeout(()=>renderCore4().catch(error=>{console.error('[Luvia Diagnostics]',error);toast('Core-4-Diagnose konnte nicht geladen werden.')}),0);else if(id==='booking')setTimeout(()=>renderBookingCore(),0);else if(id==='snapshot')$('#rawSnapshot').textContent=pretty(s)}
function activate(id){$$('.dc-tab').forEach(x=>x.classList.toggle('active',x.dataset.tab===id));$$('.dc-panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+id));location.hash=id;setTimeout(()=>renderAll(),0)}
$$('.dc-tab').forEach(x=>x.onclick=()=>activate(x.dataset.tab));
$('#serviceGrid').addEventListener('click',async e=>{const test=e.target.closest('[data-service-test]'),detail=e.target.closest('[data-service-detail]');if(test){const name=test.dataset.serviceTest;state.serviceTests.set(name,{running:true});renderServices(await snapshot());const result=await LuviaServiceRegistry.runTest(name);state.serviceTests.set(name,{...result,running:false,completedAt:new Date().toISOString()});toast(`${name}: ${result.ok?'Test erfolgreich':'Test fehlgeschlagen'}`);renderServices(await snapshot())}if(detail){const d=await LuviaServiceRegistry.diagnostics(detail.dataset.serviceDetail);$('#modalTitle').textContent=detail.dataset.serviceDetail+' Diagnose';$('#modalCode').textContent=pretty(d);$('#detailDialog').showModal()}});
$('#eventTable').addEventListener('click',e=>{const b=e.target.closest('[data-event-detail]');if(!b)return;const r=LuviaKernelEvents.history(300).find(x=>x.event.id===b.dataset.eventDetail);$('#modalTitle').textContent='Event-Details';$('#modalCode').textContent=pretty(r);$('#detailDialog').showModal()});
$('#eventSearch').oninput=e=>{state.eventSearch=e.target.value;renderEvents()};$('#eventNameFilter').onchange=e=>{state.eventName=e.target.value;renderEvents()};$('#logSearch').oninput=e=>{state.logSearch=e.target.value;renderLogs()};$('#logLevel').onchange=e=>{state.logLevel=e.target.value;renderLogs()};
$('#emitEvent').onclick=async()=>{const name=$('#customEventName').value.trim()||'developer.console.test';let payload={source:'developer-console'};try{const raw=$('#customEventPayload').value.trim();if(raw)payload=JSON.parse(raw)}catch(e){toast('Payload ist kein gültiges JSON');return}await LuviaKernelEvents.emit(name,payload,{source:'developer-console'});toast('Event gesendet');renderEvents()};
$('#clearEvents').onclick=()=>{if(LuviaKernelEvents.clearDiagnostics)LuviaKernelEvents.clearDiagnostics();else{LuviaKernelEvents.clearHistory();LuviaKernelEvents.resetStats?.()}renderEvents();toast('Event-Historie und Statistik geleert')};
$('#clearLogs').onclick=()=>{LuviaKernelLogger.clear();renderLogs();toast('Logs geleert')};$('#flushQueue').onclick=async()=>{const r=await LuviaData.flush();toast('Sync Queue verarbeitet');$('#dataSnapshot').textContent=pretty(r);await renderAll()};$('#clearQueue').onclick=()=>{LuviaData.clearQueue();toast('Sync Queue geleert');renderAll()};$('#clearCaches').onclick=async()=>{if('caches'in window){for(const key of await caches.keys())await caches.delete(key)}toast('Browser-Caches geleert');renderAll()};
$('#featureFlagGrid').addEventListener('click',e=>{const b=e.target.closest('[data-feature-flag]');if(!b)return;LuviaPlatform.setLocalFlag(b.dataset.featureFlag,b.dataset.value==='true');renderDeployment();toast('Feature Flag aktualisiert')});$('#reloadRuntimeConfig').onclick=async()=>{await LuviaPlatform.load();renderDeployment();renderPlatform(await snapshot());toast('Runtime-Konfiguration neu geladen')};$('#clearFlagOverrides').onclick=async()=>{await LuviaPlatform.clearLocalFlags();renderDeployment();toast('Lokale Flag-Overrides gelöscht')};$('#runDomainDeploymentTest').onclick=async()=>{const out=$('#domainDeploymentResult');out.innerHTML=row('Test','Läuft …','warn');try{const r=await LuviaDomainDeploymentTest.run();const labels={cnamePresent:'CNAME myluvia.app',canonicalHost:'Canonical Host',https:'HTTPS',rootBasePath:'Root Base Path',productionDetection:'Production-Erkennung',runtimeConfig:'Runtime-Konfiguration',authRedirect:'Auth-Redirect',noGithubPathOnProduction:'Keine /Luvia/-Pfade'};out.innerHTML=Object.entries(r.checks).map(([k,v])=>row(labels[k]||k,v?'Erfolgreich':(k==='canonicalHost'&&r.mode==='pre-migration'?'Noch nicht umgeschaltet':'Fehlgeschlagen'),v?'ok':(k==='canonicalHost'&&r.mode==='pre-migration'?'warn':'fail'))).join('')+row('Modus',r.mode==='production'?'Produktion':'Vorbereitung',r.mode==='production'?'ok':'warn');toast(r.ok?'Domain-Deployment erfolgreich':'Domain-Deployment geprüft') }catch(e){out.innerHTML=row('Domain-Test','Fehlgeschlagen','fail')+row('Fehler',e.message||String(e),'fail')}};
$('#runPlatformTest').onclick=async()=>{const out=$('#platformTestResult');out.innerHTML=row('Test','Läuft …','warn');const r=await LuviaPlatformTest.run();out.innerHTML=Object.entries(r.checks).map(([k,v])=>row(k,v?'Erfolgreich':'Fehlgeschlagen',v?'ok':'fail')).join('');toast(r.ok?'Platform-Test erfolgreich':'Platform-Test fehlgeschlagen')};
$('#toggleCapabilityRaw').onclick=()=>{const pre=$('#capabilityJson'),hidden=pre.classList.toggle('is-hidden');$('#toggleCapabilityRaw').textContent=hidden?'Rohdaten anzeigen':'Rohdaten ausblenden'};
if($('#startPresence'))$('#startPresence').onclick=async()=>{try{await window.LuviaPresenceVisitCore.start();toast('GPS-Erkennung gestartet');renderPlaces();}catch(e){toast(e.message)}};if($('#stopPresence'))$('#stopPresence').onclick=()=>{window.LuviaPresenceVisitCore.stop();toast('GPS-Erkennung gestoppt');renderPlaces();};$('#exportJson').onclick=async()=>{const s=await snapshot();const blob=new Blob([pretty({exportedAt:new Date().toISOString(),snapshot:s,eventHistory:LuviaKernelEvents.history(300),logs:LuviaKernelLogger.list()})],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`luvia-diagnostics-${new Date().toISOString().replace(/[:.]/g,'-')}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Diagnose exportiert')};

$('#refreshBookingCore')?.addEventListener('click',()=>{renderBookingCore();toast('Booking-Core-Diagnose aktualisiert')});
$('#runBookingCoreTests')?.addEventListener('click',async()=>{const b=$('#runBookingCoreTests'),out=$('#bookingCoreTestResult');b.disabled=true;b.textContent='Tests laufen …';try{const result=await window.LuviaBookingCoreDiagnostics?.run({remote:false});out.textContent=pretty(result);toast(result?.ok?'Booking Core Tests erfolgreich':'Booking Core Tests mit Fehlern')}catch(error){out.textContent=pretty({ok:false,error:error?.message||String(error)});toast('Booking Core Tests fehlgeschlagen')}finally{b.disabled=false;b.textContent='Booking Core testen';renderBookingCore()}});
$('#runBookingRemoteTests')?.addEventListener('click',async()=>{const b=$('#runBookingRemoteTests'),out=$('#bookingCoreTestResult');b.disabled=true;b.textContent='Backend wird geprüft …';try{const result=await window.LuviaBookingCoreDiagnostics?.run({remote:true});out.textContent=pretty(result);toast(result?.ok?'Booking Backend Readiness erfolgreich':'Booking Backend Readiness prüfen')}catch(error){out.textContent=pretty({ok:false,error:error?.message||String(error)});toast('Booking Backend Readiness fehlgeschlagen')}finally{b.disabled=false;b.textContent='Backend-Readiness prüfen';renderBookingCore()}});
$('#refreshCore4')?.addEventListener('click',()=>{renderCore4();toast('Core-4-Diagnose aktualisiert')});
$('#runCore4Smoke')?.addEventListener('click',async()=>{const b=$('#runCore4Smoke');b.disabled=true;b.textContent='Tests laufen …';const result=await window.LuviaCore4Diagnostics?.runSmokeTests?.();$('#core4Smoke').textContent=pretty(result);b.disabled=false;b.textContent='Smoke Tests starten';renderCore4();toast(result?.ok?'Core 4 Smoke Tests erfolgreich':'Core 4 Smoke Tests mit Fehlern')});
$('#runCloudOnlyVerification')?.addEventListener('click',async()=>{const b=$('#runCloudOnlyVerification'),out=$('#cloudOnlyVerificationResult');b.disabled=true;b.textContent='Prüfung läuft …';try{const result=await window.LuviaCloudOnlyPlaceVerification.run({rehydrate:true});out.textContent=pretty(result);toast(result?.passed?'Cloud-only Place Verification erfolgreich':'Cloud-only Place Verification fehlgeschlagen')}catch(error){out.textContent=pretty({passed:false,error:error?.message||String(error)});toast('Cloud-only Place Verification fehlgeschlagen')}finally{b.disabled=false;b.textContent='Cloud-only prüfen';renderCore4()}});
$('#invalidateRecommendations')?.addEventListener('click',()=>{window.LuviaRecommendations?.invalidate?.('developer-console');renderRecommendations();toast('Recommendation-Cache invalidiert')});
$('#testRecommendations')?.addEventListener('click',async()=>{const result=await window.LuviaRecommendations?.get?.({module:'restaurants',intent:'now',candidates:[{id:'test',name:'Vegetarisches Rooftop',rating:4.7,distanceMeters:800,openNow:true,features:{servesVegetarianFood:true,reservable:true,childrenAllowed:true}}],persist:false});renderRecommendations();toast(result?.length?'Engine-Test erfolgreich':'Engine-Test ohne Ergebnis')});
$('#saveRecommendationControls')?.addEventListener('click',()=>{window.LuviaRecommendations?.configure?.({enabled:$('#recEnabled').checked,personalization:$('#recPersonalization').checked,useLocation:$('#recLocation').checked,learning:$('#recLearning').checked,debug:$('#recDebug').checked,maxDistanceMeters:Number($('#recMaxDistance').value||30000),minimumScore:Number($('#recMinimumScore').value||0)});renderRecommendations();toast('Recommendation-Einstellungen gespeichert')});
$('#resetRecommendationLearning')?.addEventListener('click',()=>{window.LuviaRecommendations?.resetLearning?.();renderRecommendations();toast('Lernhistorie zurückgesetzt')});
$('#simulateRecommendations')?.addEventListener('click',()=>{const active=window.LuviaRecommendations?.diagnostics?.().simulation;window.LuviaRecommendations?.simulate?.(active?null:{intent:'now',availableMinutes:90,group:{participantCount:3,hardRequirements:{baby:true,dietary:['vegetarisch']},participants:[{name:'Fabian',dietary:['vegetarisch']},{name:'Luisa',dietary:['vegetarisch']},{name:'Liv',needs:{baby:true}}]}});renderRecommendations();toast(active?'Simulation beendet':'Testkontext aktiv')});
$('#refreshConsole').onclick=renderAll;$('#closeDialog').onclick=()=>$('#detailDialog').close();
state.unsubs.push(LuviaKernelLogger.subscribe(()=>{if($('#panel-logs').classList.contains('active'))renderLogs()}));window.addEventListener('luvia:kernel-event',()=>{if($('#panel-events').classList.contains('active'))renderEvents()});window.addEventListener('online',renderAll);window.addEventListener('offline',renderAll);
activate((location.hash||'#overview').slice(1));
})();

window.addEventListener('DOMContentLoaded',()=>{document.getElementById('todayRefresh')?.addEventListener('click',async()=>{await window.LuviaCrossModuleRecommendations?.refresh?.();await window.LuviaTodayIntelligence?.refresh?.();renderToday()});document.getElementById('todayGpsStart')?.addEventListener('click',async()=>{await window.LuviaPresenceVisitCore?.setGlobalEnabled?.(true);renderToday()});document.getElementById('todayGpsStop')?.addEventListener('click',async()=>{await window.LuviaPresenceVisitCore?.setGlobalEnabled?.(false);renderToday()});});
