(function(){
'use strict';
const VERSION='4.17.1-guided-strict-discovery';
const listeners=new Set();
const state={initialized:false,requests:0,successes:0,failures:0,cacheHits:0,lastRequestAt:null,lastSuccessAt:null,lastError:null,lastResult:null,recent:[]};
const now=()=>new Date().toISOString();
const clean=v=>String(v??'').trim();
const num=(v,fallback=null)=>Number.isFinite(Number(v))?Number(v):fallback;
function emit(type,detail){const event={type,at:now(),detail};listeners.forEach(fn=>{try{fn(event);}catch{}});window.LuviaKernelEvents?.emit?.(`places.${type}`,detail);}
function remember(entry){state.recent.unshift(entry);state.recent=state.recent.slice(0,20);}
function activeDestination(){return window.LuviaDestination?.getActive?.()||null;}
function destinationContext(destination){const d=destination||activeDestination();if(!d)return null;const center=d.center||d.location||d.coordinates||null;const name=clean(d.name||d.displayName||'');const country=clean(d.country||'');const displayName=[name,country&&country.toLowerCase()!==name.toLowerCase()?country:''].filter(Boolean).join(', ');return{id:d.id||null,name,displayName,country,countryCode:d.countryCode||d.country?.code||'',placeId:d.placeId||null,primaryType:d.primaryType||d.rawType||'',canonicalCity:d.canonicalCity||{name,placeId:d.placeId||null,center:center||null,viewport:d.viewport||null,country,countryCode:d.countryCode||''},landmarkContext:d.landmarkContext||null,location:center?{latitude:Number(center.latitude??center.lat),longitude:Number(center.longitude??center.lng)}:null,viewport:d.viewport||null,searchRadiusMeters:num(d.searchRadiusMeters,20000),radiusSource:d.radiusSource||'default',timezone:d.timezone||'',timezoneName:d.timezoneName||'',timezoneStatus:d.timezoneStatus||'',timezoneError:d.timezoneError||'',languageCodes:Array.isArray(d.languageCodes)?[...d.languageCodes]:[],currency:d.currency||'',locale:d.locale||'',flagEmoji:d.flagEmoji||'',provider:d.provider||d.source||null,isResolved:Boolean(d.isResolved||center)};}
function normalizeOptions(options={}){return{languageCode:clean(options.languageCode||document.documentElement.lang||'de').slice(0,10)||'de',regionCode:clean(options.regionCode||'DE').toUpperCase().slice(0,2),maxResultCount:Math.max(1,Math.min(20,num(options.maxResultCount,10))),includedType:clean(options.includedType||''),includedTypes:Array.isArray(options.includedTypes)?options.includedTypes.map(clean).filter(Boolean).slice(0,50):[],excludedTypes:Array.isArray(options.excludedTypes)?options.excludedTypes.map(clean).filter(Boolean).slice(0,50):[],includedPrimaryTypes:Array.isArray(options.includedPrimaryTypes)?options.includedPrimaryTypes.map(clean).filter(Boolean).slice(0,50):[],excludedPrimaryTypes:Array.isArray(options.excludedPrimaryTypes)?options.excludedPrimaryTypes.map(clean).filter(Boolean).slice(0,50):[],strictTypeFiltering:options.strictTypeFiltering===true,openNow:options.openNow===true,minRating:num(options.minRating,null),priceLevels:Array.isArray(options.priceLevels)?options.priceLevels.slice(0,5):[],locationBias:options.locationBias||null,locationRestriction:options.locationRestriction||null,rankPreference:clean(options.rankPreference||''),sessionToken:clean(options.sessionToken||''),minUserRatingCount:Math.max(0,num(options.minUserRatingCount,0)),vegetarianOnly:options.vegetarianOnly===true,maxDistanceMeters:Math.max(0,num(options.maxDistanceMeters,0)),sortBy:clean(options.sortBy||'relevance'),landmarkContext:options.landmarkContext||null,strictDestination:options.strictDestination!==false,providers:Array.isArray(options.providers)?options.providers.slice(0,4):['google','foursquare'],profileContext:options.profileContext||null,intentContext:options.intentContext||null};}
async function call(action,payload={}){if(!window.LuviaBackend)throw Object.assign(new Error('LuviaBackend API fehlt.'),{code:'BACKEND_UNAVAILABLE'});const started=performance.now();state.requests++;state.lastRequestAt=now();emit('request.started',{action});try{const response=await window.LuviaBackend.request(action,payload);const durationMs=Math.round((performance.now()-started)*100)/100;state.successes++;state.lastSuccessAt=now();state.lastError=null;state.lastResult=response?.data||null;if(response?.meta?.cache?.hit)state.cacheHits++;remember({action,ok:true,durationMs,cacheHit:Boolean(response?.meta?.cache?.hit),at:now(),count:Array.isArray(response?.data?.places)?response.data.places.length:null});emit('request.succeeded',{action,durationMs,cacheHit:Boolean(response?.meta?.cache?.hit)});return response;}catch(error){state.failures++;state.lastError={code:error.code||'PLACES_REQUEST_FAILED',message:error.message,status:error.status||0,at:now()};remember({action,ok:false,error:state.lastError.code,at:now()});emit('request.failed',{action,...state.lastError});throw error;}}
async function resolvedDestination(input,options={}){const initial=(typeof input==='string'?{name:input,destinationName:input}:input)||activeDestination();if(!initial)return null;if(initial.center||initial.location)return destinationContext(initial);if(window.LuviaDestination?.ensureResolved){const resolved=await window.LuviaDestination.ensureResolved(initial,{refresh:options.refreshDestination===true});return destinationContext(resolved);}return destinationContext(initial);}
async function textSearch(query,options={}){const text=clean(query);if(text.length<2)throw Object.assign(new Error('Suchbegriff muss mindestens zwei Zeichen enthalten.'),{code:'INVALID_QUERY'});const opts=normalizeOptions(options);const destination=await resolvedDestination(options.destination,options);if(opts.strictDestination&&(!destination?.location&&!destination?.viewport))throw Object.assign(new Error('Das aktive Reiseziel konnte nicht geografisch aufgelöst werden.'),{code:'DESTINATION_LOCATION_REQUIRED'});if(destination?.countryCode&&!options.regionCode)opts.regionCode=destination.countryCode;return call('places.text-search',{query:text,options:opts,destination});}
async function nearbySearch(options={}){const d=await resolvedDestination(options.destination,options);const location=options.location||d?.location;if(!location||!Number.isFinite(Number(location.latitude??location.lat))||!Number.isFinite(Number(location.longitude??location.lng)))throw Object.assign(new Error('Für Nearby Search werden Zielkoordinaten benötigt.'),{code:'LOCATION_REQUIRED'});return call('places.nearby-search',{location:{latitude:Number(location.latitude??location.lat),longitude:Number(location.longitude??location.lng)},radius:Math.max(50,Math.min(50000,num(options.radius,d?.searchRadiusMeters||3000))),options:normalizeOptions(options),destination:d});}
async function autocomplete(input,options={}){const text=clean(input);if(text.length<2)return{ok:true,data:{suggestions:[]},meta:{local:true}};const destination=options.destination?await resolvedDestination(options.destination,options):null;return call('places.autocomplete',{input:text,options:normalizeOptions(options),destination});}
async function details(placeId,options={}){const id=clean(placeId).replace(/^places\//,'');if(!id)throw Object.assign(new Error('Place-ID fehlt.'),{code:'PLACE_ID_REQUIRED'});const o=normalizeOptions(options);return call('places.details',{placeId:id,languageCode:o.languageCode,regionCode:o.regionCode});}
async function photo(photoName,options={}){const name=clean(photoName);if(!/^places\/[^/]+\/photos\/[^/]+$/.test(name))throw Object.assign(new Error('Ungültiger Photo-Ressourcenname.'),{code:'INVALID_PHOTO_NAME'});return call('places.photo',{photoName:name,maxWidthPx:Math.max(1,Math.min(1600,num(options.maxWidthPx,800))),maxHeightPx:options.maxHeightPx?Math.max(1,Math.min(1600,num(options.maxHeightPx,800))):null});}
async function route(origin,destination,options={}){return call('routes.compute',{origin,destination,...options});}
async function health(){return call('places.health',{});}
function diagnostics(){return{version:VERSION,initialized:state.initialized,backendAvailable:Boolean(window.LuviaBackend),destination:destinationContext(),metrics:{requests:state.requests,successes:state.successes,failures:state.failures,cacheHits:state.cacheHits},lastRequestAt:state.lastRequestAt,lastSuccessAt:state.lastSuccessAt,lastError:state.lastError,lastResult:state.lastResult,recent:[...state.recent]};}
async function testContract(options={}){const checks={api:true,backend:Boolean(window.LuviaBackend),destinationApi:Boolean(window.LuviaDestination),destinationResolver:typeof window.LuviaDestination?.ensureResolved==='function',methods:['textSearch','nearbySearch','autocomplete','details','photo','route','health'].every(k=>typeof api[k]==='function'),normalization:normalizeOptions({maxResultCount:99}).maxResultCount===20};let remote={skipped:true};if(options.remote===true){try{remote=await health();checks.remote=remote?.ok!==false;}catch(error){remote={ok:false,code:error.code,message:error.message};checks.remote=false;}}return{ok:Object.values(checks).every(Boolean),message:'Places Gateway, automatische Zielauflösung, geografische Einschränkung und Backend-Vertrag geprüft.',checks,remote,diagnostics:diagnostics()};}
function subscribe(listener){if(typeof listener!=='function')return()=>{};listeners.add(listener);return()=>listeners.delete(listener);}
function init(){state.initialized=true;emit('ready',{version:VERSION});return api;}
const api=Object.freeze({version:VERSION,init,textSearch,nearbySearch,autocomplete,details,photo,route,health,diagnostics,testContract,subscribe,activeDestination,resolvedDestination});
window.LuviaPlaces=api;window.LuviaPlacesGateway=api;init();
})();
