(function(){
  'use strict';
  const VERSION='3.0.2.2-runtime-consistency';
  const FALLBACK_BUILD=Object.freeze({core:'3.0.2.2',build:'11.2.2',name:'Runtime Configuration Consistency',releasedAt:'2026-07-27',builtAt:'2026-07-27T13:45:00+02:00'});
  const currentBuild=()=>window.LuviaKernelVersion||window.LuviaCoreVersion||FALLBACK_BUILD;
  const DEFAULTS=Object.freeze({schemaVersion:1,maintenance:{enabled:false,message:''},endpoints:{intelligence:'',assets:'',api:'',media:'',auth:''},featureFlags:{developerConsole:true,pwa:false,native:false,places:true,ai:false,recommendations:false,mediaV2:false,automation:false,platformLayer:true},limits:{eventHistory:300,logHistory:500},release:{channel:'development'}});
  const state={config:structuredClone(DEFAULTS),source:'defaults',loadedAt:null,lastError:null,listeners:new Set()};
  const env=()=>window.LuviaEnvironment?.current?.()||{};
  const clone=v=>v===undefined?undefined:structuredClone(v);
  const merge=(a,b)=>{const out={...a};for(const [k,v] of Object.entries(b||{}))out[k]=v&&typeof v==='object'&&!Array.isArray(v)?merge(a?.[k]||{},v):v;return out};
  class PlatformError extends Error{constructor(code,message,details={}){super(message);this.name='LuviaPlatformError';this.code=code;this.details=details}}
  const normalizeError=(error,fallback='platform_error')=>error instanceof PlatformError?error:new PlatformError(error?.code||fallback,error?.message||String(error),{cause:error});
  const safeCall=(fn,fallback)=>{try{return fn()}catch{return fallback}};
  const emit=()=>{const snap=snapshot();state.listeners.forEach(fn=>{try{fn(snap)}catch(e){console.error(e)}});window.dispatchEvent(new CustomEvent('luvia:platform-config-changed',{detail:snap}))};
  function detectChannel(){const e=env();return e.isProduction?'production':e.isStaging?'staging':e.isGitHubPages?'preview':'development'}
  function build(){const central=currentBuild();return Object.freeze({...FALLBACK_BUILD,...central,channel:state.config.release?.channel||central.channel||detectChannel(),environment:env().name||'unknown'})}
  async function load(options={}){const override=window.LUVIA_RUNTIME_CONFIG||{};const url=options.url||window.LuviaEnvironment?.resolveUrl?.('intelligence/runtime-config.json')||'runtime-config.json';let remote={};try{const response=await fetch(url,{cache:'no-store'});if(response.ok){remote=await response.json();state.source='runtime-config.json'}else state.source='defaults';state.lastError=null}catch(error){state.lastError=error.message;state.source='defaults'}state.config=merge(merge(DEFAULTS,remote),override);if(!state.config.release?.channel)state.config.release={...(state.config.release||{}),channel:detectChannel()};applyLocalOverrides();state.loadedAt=new Date().toISOString();emit();return snapshot()}
  function get(path,fallback){if(!path)return clone(state.config);let value=state.config;for(const part of String(path).split('.')){if(value==null||!(part in value))return fallback;value=value[part]}return clone(value)}
  function localOverrides(){try{return JSON.parse(localStorage.getItem('luvia:feature-flag-overrides')||'{}')}catch{return {}}}
  function flag(name,fallback=false){const value=state.config.featureFlags?.[name];return typeof value==='boolean'?value:fallback}
  function setLocalFlag(name,value){const data=localOverrides();data[name]=Boolean(value);localStorage.setItem('luvia:feature-flag-overrides',JSON.stringify(data));state.config.featureFlags={...state.config.featureFlags,...data};emit();return flag(name)}
  function applyLocalOverrides(){state.config.featureFlags={...state.config.featureFlags,...localOverrides()}}
  function clearLocalFlags(){localStorage.removeItem('luvia:feature-flag-overrides');return load()}
  function endpoint(name,fallback=''){const configured=state.config.endpoints?.[name];if(configured)return configured;const e=env(),base=e.baseUrl||fallback;if(name==='base'||name==='app')return base;if(name==='assets')return window.LuviaEnvironment?.resolveUrl?.('assets/')||base;if(name==='media')return window.LuviaEnvironment?.resolveUrl?.('media/')||base;if(name==='auth')return window.LuviaEnvironment?.authRedirectUrl?.('index.html')||base;if(name==='api'||name==='intelligence'){const auth=window.LUVIA_AUTH_CONFIG||window.LUVIA_CONFIG||{};const url=auth.supabaseUrl||auth.url||'';if(!url)return fallback;return name==='intelligence'?url.replace(/\/$/,'')+'/functions/v1/luvia-gateway':url.replace(/\/$/,'')}return fallback}
  function urls(){return{base:endpoint('base'),app:endpoint('app'),assets:endpoint('assets'),api:endpoint('api'),intelligence:endpoint('intelligence'),media:endpoint('media'),auth:endpoint('auth')}}
  function detectOs(){const ua=navigator.userAgent||'';if(/iPad|iPhone|iPod/.test(ua)||navigator.platform==='MacIntel'&&navigator.maxTouchPoints>1)return'ios';if(/Android/.test(ua))return'android';if(/Win/.test(navigator.platform))return'windows';if(/Mac/.test(navigator.platform))return'macos';if(/Linux/.test(navigator.platform))return'linux';return'unknown'}
  function capabilities(){const n=navigator;return{web:true,pwa:Boolean(env().isPwa),native:Boolean(env().isNative),serviceWorker:'serviceWorker'in n,share:'share'in n,geolocation:'geolocation'in n,clipboard:Boolean(n.clipboard?.writeText),notifications:'Notification'in window,permissions:'permissions'in n,wakeLock:'wakeLock'in n,vibration:'vibrate'in n,mediaDevices:Boolean(n.mediaDevices),camera:Boolean(n.mediaDevices?.getUserMedia),microphone:Boolean(n.mediaDevices?.getUserMedia),files:true,secureContext:window.isSecureContext,online:n.onLine,touch:n.maxTouchPoints>0}}

  const environment=Object.freeze({snapshot(){const c=capabilities();return{runtime:env().isNative?'native':'web',mode:env().isPwa?'pwa':'browser',os:detectOs(),mobile:/Mobi|Android|iPhone|iPad/i.test(navigator.userAgent),touch:c.touch,online:navigator.onLine,language:navigator.language||'de-DE',timezone:Intl.DateTimeFormat().resolvedOptions().timeZone||'',capabilities:c,build:build()}}});
  const device=Object.freeze({snapshot:()=>environment.snapshot(),isMobile:()=>environment.snapshot().mobile,isTouch:()=>environment.snapshot().touch,os:()=>detectOs()});
  const storage=Object.freeze({
    async get(key,fallback=null,{scope='local'}={}){try{const backend=scope==='session'?sessionStorage:localStorage;const raw=backend.getItem(key);return raw===null?fallback:JSON.parse(raw)}catch(error){throw normalizeError(error,'storage_read_failed')}},
    async set(key,value,{scope='local'}={}){try{const backend=scope==='session'?sessionStorage:localStorage;backend.setItem(key,JSON.stringify(value));return value}catch(error){throw normalizeError(error,'storage_write_failed')}},
    async remove(key,{scope='local'}={}){try{const backend=scope==='session'?sessionStorage:localStorage;backend.removeItem(key);return true}catch(error){throw normalizeError(error,'storage_remove_failed')}},
    async has(key,options){return(await this.get(key,Symbol.for('missing'),options))!==Symbol.for('missing')},
    async clear({scope='local',prefix=''}={}){const backend=scope==='session'?sessionStorage:localStorage;if(!prefix){backend.clear();return true}Object.keys(backend).filter(k=>k.startsWith(prefix)).forEach(k=>backend.removeItem(k));return true},
    diagnostics(){return{adapter:'web-storage',localEntries:localStorage.length,sessionEntries:sessionStorage.length,available:true}}
  });
  const networkListeners=new Set();
  const networkNotify=()=>{const s=network.snapshot();networkListeners.forEach(fn=>safeCall(()=>fn(s)));window.dispatchEvent(new CustomEvent('luvia:platform-network-changed',{detail:s}))};
  window.addEventListener('online',networkNotify);window.addEventListener('offline',networkNotify);
  const network=Object.freeze({isOnline:()=>navigator.onLine,snapshot:()=>({status:navigator.onLine?'online':'offline',online:navigator.onLine,effectiveType:navigator.connection?.effectiveType||'unknown',downlink:navigator.connection?.downlink??null,saveData:Boolean(navigator.connection?.saveData)}),subscribe(fn){networkListeners.add(fn);return()=>networkListeners.delete(fn)},async check(url=location.origin,{timeoutMs=5000}={}){if(!navigator.onLine)return{online:false,status:'offline'};const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),timeoutMs);try{await fetch(url,{method:'HEAD',cache:'no-store',signal:controller.signal});return{online:true,status:'online'}}catch{return{online:false,status:'limited'}}finally{clearTimeout(timer)}}});
  const lifecycleListeners={resume:new Set(),pause:new Set(),visibility:new Set()};
  const lifecycleState=()=>document.visibilityState==='visible'?'active':'background';
  document.addEventListener('visibilitychange',()=>{const type=document.visibilityState==='visible'?'resume':'pause';lifecycleListeners[type].forEach(fn=>safeCall(()=>fn()));lifecycleListeners.visibility.forEach(fn=>safeCall(()=>fn(lifecycleState())));window.dispatchEvent(new CustomEvent('luvia:platform-lifecycle',{detail:{state:lifecycleState()}}))});
  const lifecycle=Object.freeze({state:lifecycleState,onResume(fn){lifecycleListeners.resume.add(fn);return()=>lifecycleListeners.resume.delete(fn)},onPause(fn){lifecycleListeners.pause.add(fn);return()=>lifecycleListeners.pause.delete(fn)},subscribe(fn){lifecycleListeners.visibility.add(fn);return()=>lifecycleListeners.visibility.delete(fn)},snapshot:()=>({state:lifecycleState(),visibility:document.visibilityState})});
  const navigation=Object.freeze({go(target,{replace=false,state=null}={}){if(!target)throw new PlatformError('invalid_target','Navigationsziel fehlt.');if(/^https?:\/\//i.test(target))return this.openExternal(target);replace?history.replaceState(state,'',target):history.pushState(state,'',target);window.dispatchEvent(new PopStateEvent('popstate',{state}));return true},back(){history.back();return true},openExternal(url){const parsed=new URL(url,location.href);if(!/^https?:$/.test(parsed.protocol))throw new PlatformError('unsupported_protocol','Nur HTTP- und HTTPS-Links sind erlaubt.');window.open(parsed.href,'_blank','noopener,noreferrer');return true},openMaps({lat,lng,label=''}){const q=lat!=null&&lng!=null?`${lat},${lng}`:label;if(!q)throw new PlatformError('invalid_location','Kein Karten-Ziel vorhanden.');return this.openExternal(`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(q)}`)},reload(){location.reload()},current:()=>({href:location.href,path:location.pathname,search:location.search,hash:location.hash})});
  const clipboard=Object.freeze({isSupported:()=>Boolean(navigator.clipboard?.writeText),async write(text){try{if(navigator.clipboard?.writeText)return await navigator.clipboard.writeText(String(text));const area=document.createElement('textarea');area.value=String(text);area.hidden=true;document.body.appendChild(area);area.select();const ok=document.execCommand('copy');area.remove();if(!ok)throw new Error('Copy fehlgeschlagen');return true}catch(error){throw normalizeError(error,'clipboard_write_failed')}}});
  const sharing=Object.freeze({isSupported:()=>Boolean(navigator.share),async share(data){try{if(navigator.share){await navigator.share(data);return{method:'native-share'}}if(data.url||data.text){await clipboard.write([data.text,data.url].filter(Boolean).join('\n'));return{method:'clipboard'}}throw new PlatformError('share_unavailable','Keine teilbaren Inhalte vorhanden.')}catch(error){if(error?.name==='AbortError')throw new PlatformError('user_cancelled','Teilen wurde abgebrochen.');throw normalizeError(error,'share_failed')}}});
  const permissions=Object.freeze({async query(name){if(!navigator.permissions?.query)return'unsupported';try{const result=await navigator.permissions.query({name});return result.state||'unknown'}catch{return'unknown'}},async request(name){if(name==='notifications')return notifications.requestPermission();if(name==='location'){await locationService.getCurrent();return'granted'}return'unsupported'}});
  const locationService=Object.freeze({isSupported:()=>Boolean(navigator.geolocation),getCurrent({accuracy='balanced',timeoutMs=10000,maximumAgeMs=30000}={}){if(!navigator.geolocation)return Promise.reject(new PlatformError('unsupported','Standort wird nicht unterstützt.'));return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(pos=>resolve({latitude:pos.coords.latitude,longitude:pos.coords.longitude,accuracy:pos.coords.accuracy,altitude:pos.coords.altitude,heading:pos.coords.heading,speed:pos.coords.speed,timestamp:pos.timestamp}),err=>reject(new PlatformError(err.code===1?'permission_denied':err.code===2?'position_unavailable':'timeout',err.message||'Standort konnte nicht ermittelt werden.')),{enableHighAccuracy:accuracy==='high',timeout:timeoutMs,maximumAge:maximumAgeMs}))}});
  const notifications=Object.freeze({isSupported:()=>('Notification'in window),getPermission:()=>('Notification'in window?Notification.permission:'unsupported'),async requestPermission(){if(!('Notification'in window))return'unsupported';return Notification.requestPermission()}});
  const files=Object.freeze({pick({accept=[],multiple=false}={}){return new Promise((resolve,reject)=>{try{const input=document.createElement('input');input.type='file';input.multiple=multiple;if(accept.length)input.accept=accept.join(',');input.style.display='none';input.onchange=()=>{const result=[...(input.files||[])];input.remove();resolve(result)};input.oncancel=()=>{input.remove();resolve([])};document.body.appendChild(input);input.click()}catch(error){reject(normalizeError(error,'file_pick_failed'))}})},download({blob,url,filename='download'}){const href=blob?URL.createObjectURL(blob):url;if(!href)throw new PlatformError('missing_file','Keine Datei zum Herunterladen vorhanden.');const a=document.createElement('a');a.href=href;a.download=filename;a.rel='noopener';a.click();if(blob)setTimeout(()=>URL.revokeObjectURL(href),1000);return true}});
  const adapter=Object.freeze({name:'web-adapter',version:'1.0.0',runtime:'web'});
  function snapshot(){return{version:VERSION,build:build(),environment:env(),platformEnvironment:environment.snapshot(),adapter,source:state.source,loadedAt:state.loadedAt,lastError:state.lastError,maintenance:clone(state.config.maintenance),featureFlags:clone(state.config.featureFlags),featureFlagOverrides:localOverrides(),endpoints:urls(),limits:clone(state.config.limits),capabilities:capabilities(),services:{storage:storage.diagnostics(),network:network.snapshot(),lifecycle:lifecycle.snapshot(),permissions:{supported:Boolean(navigator.permissions)},notifications:{supported:notifications.isSupported(),permission:notifications.getPermission()}}}}
  function subscribe(fn){state.listeners.add(fn);return()=>state.listeners.delete(fn)}
  window.LuviaPlatform=Object.freeze({version:VERSION,PlatformError,normalizeError,adapter,load,get,flag,setLocalFlag,clearLocalFlags,endpoint,urls,capabilities,snapshot,build,subscribe,detectChannel,localOverrides,environment,device,storage,network,lifecycle,navigation,clipboard,sharing,location:locationService,permissions,notifications,files});
  applyLocalOverrides();window.dispatchEvent(new CustomEvent('luvia:platform-ready',{detail:snapshot()}));
})();
