(function(){
'use strict';
const VERSION='3.5.1-restaurant-workspace';
const state={searches:0,imports:0,lists:0,lifecycleUpdates:0,feedback:0,successes:0,failures:0,lastImport:null,lastError:null};
const clean=v=>String(v??'').trim();
function tripId(input){return clean(input||window.LuviaTripContext?.getActiveTrip?.()?.tripId||window.LuviaTripContext?.getSnapshot?.()?.tripId||'');}
function enrichDistance(place){if(!place||typeof place!=='object')return place;const distance=window.LuviaTravelContext?.distanceTo?.(place.location||{latitude:place.latitude,longitude:place.longitude});return Number.isFinite(distance)?{...place,distanceMeters:distance}:place;}
async function search(query,options={}){state.searches++;try{const supplied=options.destination||null;const active=window.LuviaPlaces?.activeDestination?.()||null;const suppliedHasGeo=Boolean(supplied?.location||supplied?.center||supplied?.viewport);const destination=suppliedHasGeo?supplied:(active||supplied);const landmarkContext=options.landmarkContext||destination?.landmarkContext||null;const request={...options,destination,landmarkContext,strictDestination:true,maxResultCount:options.maxResultCount||10,sortBy:options.sortBy||'relevance'};if(!options.includedType)delete request.includedType;const response=await window.LuviaPlaces.textSearch(query,request);if(Array.isArray(response?.data?.places))response.data.places=response.data.places.map(enrichDistance);return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function importPlace(providerPlaceId,options={}){const id=tripId(options.tripId);if(!id)throw Object.assign(new Error('Aktive Reise hat keine gültige Trip-ID.'),{code:'TRIP_ID_REQUIRED'});state.imports++;try{const response=await window.LuviaBackend.request('restaurant.import',{tripId:id,providerPlaceId:clean(providerPlaceId),languageCode:options.languageCode||'de',regionCode:options.regionCode||window.LuviaPlaces?.activeDestination?.()?.countryCode||'DE',tripPlace:options.tripPlace||{},restaurant:options.restaurant||{}});state.successes++;state.lastImport=response.data;window.LuviaKernelEvents?.emit?.('restaurants.imported',response.data);window.dispatchEvent(new CustomEvent('luvia:restaurant-imported',{detail:response.data}));return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function list(options={}){const id=tripId(options.tripId);if(!id)return{ok:true,data:{entities:[]},meta:{local:true}};state.lists++;try{return await window.LuviaBackend.request('restaurant.list',{tripId:id});}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function updateLifecycle(tripPlaceId,status,patch={},options={}){const id=tripId(options.tripId);if(!id||!tripPlaceId)throw new Error('Reise oder Restaurant-Verknüpfung fehlt.');state.lifecycleUpdates++;try{const response=await window.LuviaBackend.request('restaurant.lifecycle.update',{tripId:id,tripPlaceId,status,patch});state.successes++;window.dispatchEvent(new CustomEvent('luvia:restaurant-lifecycle-changed',{detail:{tripId:id,status,entity:response.data}}));return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function recordFeedback({placeId=null,providerPlaceId=null,decision='shown',matchScore=null,reasons=[],context={}}={},options={}){const id=tripId(options.tripId);if(!id)return null;state.feedback++;try{return await window.LuviaBackend.request('restaurant.feedback',{tripId:id,placeId,providerPlaceId,decision,matchScore,reasons,context});}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};console.warn('[LuviaRestaurants] Feedback konnte nicht gespeichert werden.',error);return null;}}
async function health(){return window.LuviaBackend.request('restaurant.health',{});}
function entityToEntry(entity){const p=entity?.place||{},tp=entity?.tripPlace||{},r=entity?.restaurant||{},meta=r.metadata||{};const location={latitude:p.latitude,longitude:p.longitude};const distance=window.LuviaTravelContext?.distanceTo?.(location);return{id:tp.id||r.id||p.id,tripPlaceId:tp.id,entity:true,placeId:p.id,providerPlaceId:p.provider_place_id,name:tp.custom_name||p.name||'Restaurant',date:tp.planned_date||r.reservation_date||'',time:tp.planned_time||r.reservation_time||'',description:tp.custom_description||tp.user_notes||r.personal_notes||'',symbol:tp.custom_symbol||'🍽️',address:p.address||'',latitude:p.latitude,longitude:p.longitude,distanceMeters:distance,mapsUrl:p.maps_url||'',website:p.website||'',phone:p.phone||'',rating:p.rating,userRatingCount:p.rating_count,priceLevel:p.price_level,reservationStatus:r.reservation_status||tp.status||'idea',reservationDate:r.reservation_date||'',reservationTime:r.reservation_time||'',reservationName:r.reservation_name||'',confirmationNumber:r.confirmation_number||'',reservationUrl:r.reservation_url||'',reservationNotes:r.reservation_notes||'',lifecycleStatus:tp.lifecycle_status||'saved',visitedAt:tp.visited_at||null,personalRating:r.personal_rating||null,personalNotes:r.personal_notes||tp.user_notes||'',recommendedVisitTime:r.recommended_visit_time||'',recommendationReason:r.recommendation_reason||'',isFavorite:tp.is_favorite===true,tripStatus:tp.status||'idea',memoryStatus:tp.memory_status||'none',travelBookStatus:tp.travel_book_status||'none',metadata:meta,history:entity?.history||[],menu:{enabled:Boolean(r.menu_url),label:'Speisekarte',original:r.menu_url||'',assetId:'',assetName:'',pages:[]},rawEntity:entity};}
function diagnostics(){return{version:VERSION,metrics:{...state}};}
window.LuviaRestaurants=Object.freeze({version:VERSION,search,importPlace,list,updateLifecycle,recordFeedback,health,entityToEntry,enrichDistance,diagnostics});
window.LuviaKernelEvents?.emit?.('restaurants.service.ready',{version:VERSION});
})();
