(function(){
'use strict';
const VERSION='2.13.0-architecture-separation';
const state={searches:0,imports:0,lists:0,successes:0,failures:0,lastImport:null,lastError:null};
const clean=v=>String(v??'').trim();
function tripId(input){return clean(input||window.LuviaTripContext?.getActiveTrip?.()?.tripId||window.LuviaTripContext?.getSnapshot?.()?.tripId||'');}
async function search(query,options={}){state.searches++;try{const supplied=options.destination||null;const active=window.LuviaPlaces?.activeDestination?.()||null;const suppliedHasGeo=Boolean(supplied?.location||supplied?.center||supplied?.viewport);const destination=suppliedHasGeo?supplied:(active||supplied);const landmarkContext=options.landmarkContext||destination?.landmarkContext||null;const request={...options,destination,landmarkContext,strictDestination:true,maxResultCount:options.maxResultCount||10,sortBy:options.sortBy||'relevance'};if(!options.includedType)delete request.includedType;return await window.LuviaPlaces.textSearch(query,request);}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function importPlace(providerPlaceId,options={}){const id=tripId(options.tripId);if(!id)throw Object.assign(new Error('Aktive Reise hat keine gültige Trip-ID.'),{code:'TRIP_ID_REQUIRED'});state.imports++;try{const response=await window.LuviaBackend.request('restaurant.import',{tripId:id,providerPlaceId:clean(providerPlaceId),languageCode:options.languageCode||'de',regionCode:options.regionCode||window.LuviaPlaces?.activeDestination?.()?.countryCode||'DE',tripPlace:options.tripPlace||{},restaurant:options.restaurant||{}});state.successes++;state.lastImport=response.data;window.LuviaKernelEvents?.emit?.('restaurants.imported',response.data);window.dispatchEvent(new CustomEvent('luvia:restaurant-imported',{detail:response.data}));return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function list(options={}){const id=tripId(options.tripId);if(!id)return{ok:true,data:{entities:[]},meta:{local:true}};state.lists++;try{return await window.LuviaBackend.request('restaurant.list',{tripId:id});}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function health(){return window.LuviaBackend.request('restaurant.health',{});}
function entityToEntry(entity){const p=entity?.place||{},tp=entity?.tripPlace||{},r=entity?.restaurant||{};return{id:tp.id||r.id||p.id,entity:true,placeId:p.id,providerPlaceId:p.provider_place_id,name:tp.custom_name||p.name||'Restaurant',date:tp.planned_date||r.reservation_date||'',time:tp.planned_time||r.reservation_time||'',description:tp.custom_description||tp.user_notes||'',symbol:tp.custom_symbol||'🍽️',address:p.address||'',mapsUrl:p.maps_url||'',website:p.website||'',phone:p.phone||'',rating:p.rating,userRatingCount:p.rating_count,priceLevel:p.price_level,reservationStatus:r.reservation_status||tp.status||'idea',isFavorite:tp.is_favorite===true,tripStatus:tp.status||'idea',menu:{enabled:Boolean(r.menu_url),label:'Speisekarte',original:r.menu_url||'',assetId:'',assetName:'',pages:[]},rawEntity:entity};}
function diagnostics(){return{version:VERSION,metrics:{...state}};}
window.LuviaRestaurants=Object.freeze({version:VERSION,search,importPlace,list,health,entityToEntry,diagnostics});
window.LuviaKernelEvents?.emit?.('restaurants.service.ready',{version:VERSION});
})();
