(function(){
'use strict';
const VERSION='4.6.0-universal-place-core';
const state={searches:0,imports:0,lists:0,lifecycleUpdates:0,feedback:0,successes:0,failures:0,lastImport:null,lastError:null};
const clean=v=>String(v??'').trim();
function tripId(input){return clean(input||window.LuviaTripContext?.getActiveTrip?.()?.tripId||window.LuviaTripContext?.getSnapshot?.()?.tripId||'');}
function enrichDistance(place){if(!place||typeof place!=='object')return place;const context=window.LuviaTravelContext?.snapshot?.()||{};const hasGps=Boolean(context.location&&Number.isFinite(Number(context.location.latitude))&&Number.isFinite(Number(context.location.longitude)));const distance=hasGps?window.LuviaTravelContext?.distanceTo?.(place.location||{latitude:place.latitude,longitude:place.longitude}):null;return{...place,distanceMeters:Number.isFinite(distance)?distance:null,distanceSource:Number.isFinite(distance)?'gps':'unavailable'};}
async function search(query,options={}){state.searches++;try{const response=await window.LuviaPlaceEntities.searchPlaces({...options,type:'restaurant',query});if(Array.isArray(response?.data?.places)){response.data.places=response.data.places.map(enrichDistance);const quick=response.data.places.slice();queueMicrotask(async()=>{try{let enriched=quick;if(window.LuviaRecommendations){const recs=await window.LuviaRecommendations.get({module:'restaurants',tripId:tripId(options.tripId),intent:options.intent||'for-you',candidates:quick,persist:options.persistRecommendations!==false,limit:quick.length,context:{partySize:options.partySize||null,hasBaby:Boolean(options.hasBaby)}});const byId=new Map(recs.map(r=>[r.entityId,r]));enriched=quick.map(place=>{const r=byId.get(String(place.id||place.providerPlaceId||''));return r?{...place,matchScore:r.score,recommendation:r}:place})}if(window.LuviaRestaurantIntelligence)enriched=await window.LuviaRestaurantIntelligence.enhance(enriched,{intent:options.intent||'for-you'});window.dispatchEvent(new CustomEvent('luvia:restaurant-search-enriched',{detail:{query,places:enriched}}))}catch(_){}})}return response}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error}}
async function importPlace(providerPlaceId,options={}){const id=tripId(options.tripId);if(!id)throw Object.assign(new Error('Aktive Reise hat keine gültige Trip-ID.'),{code:'TRIP_ID_REQUIRED'});state.imports++;try{const response=await window.LuviaPlaceEntities.importPlace(providerPlaceId,{tripId:id,type:'restaurant',languageCode:options.languageCode,regionCode:options.regionCode,tripPlace:options.tripPlace||{},extension:options.restaurant||{}});state.successes++;state.lastImport=response.data;window.LuviaKernelEvents?.emit?.('restaurants.imported',response.data);window.dispatchEvent(new CustomEvent('luvia:restaurant-imported',{detail:response.data}));return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function list(options={}){const id=tripId(options.tripId);if(!id)return{ok:true,data:{entities:[]},meta:{cloud:true}};state.lists++;try{const response=await window.LuviaPlaceEntities.list({tripId:id,type:'restaurant'});response.data.entities=(response.data.entities||[]).map(e=>({...e,restaurant:e.restaurant||e.extension||{}}));return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function updateLifecycle(tripPlaceId,status,patch={},options={}){const id=tripId(options.tripId);if(!id||!tripPlaceId)throw new Error('Reise oder Restaurant-Verknüpfung fehlt.');const cleanPatch=Object.fromEntries(Object.entries(patch||{}).filter(([,value])=>value!==undefined&&value!==null));state.lifecycleUpdates++;try{const genericPatch={isFavorite:cleanPatch.isFavorite,plannedDate:cleanPatch.plannedDate,plannedTime:cleanPatch.plannedTime,userNotes:cleanPatch.userNotes};const hasRestaurantPatch=Object.keys(cleanPatch).some(k=>!['isFavorite','plannedDate','plannedTime','userNotes'].includes(k));const response=hasRestaurantPatch?await window.LuviaBackend.request('restaurant.lifecycle.update',{tripId:id,tripPlaceId,status,patch:cleanPatch}):await window.LuviaPlaceEntities.updateLifecycle(tripPlaceId,status,genericPatch,{tripId:id});state.successes++;window.dispatchEvent(new CustomEvent('luvia:restaurant-lifecycle-changed',{detail:{tripId:id,status,entity:response.data}}));return response;}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};throw error;}}
async function recordFeedback({placeId=null,providerPlaceId=null,decision='shown',matchScore=null,reasons=[],context={}}={},options={}){const id=tripId(options.tripId);if(!id)return null;state.feedback++;try{return await window.LuviaBackend.request('restaurant.feedback',{tripId:id,placeId,providerPlaceId,decision,matchScore,reasons,context});}catch(error){state.failures++;state.lastError={code:error.code,message:error.message};console.warn('[LuviaRestaurants] Feedback konnte nicht gespeichert werden.',error);return null;}}
async function remove(tripPlaceId,options={}){const id=tripId(options.tripId);if(!id||!tripPlaceId)throw new Error('Reise oder Restaurant-Verknüpfung fehlt.');return window.LuviaPlaceEntities.remove(tripPlaceId,{tripId:id});}
async function history(options={}){const id=tripId(options.tripId);if(!id)throw new Error('Aktive Reise fehlt.');return window.LuviaBackend.request('restaurant.history',{tripId:id});}
async function clear(scope='saved',options={}){const id=tripId(options.tripId);if(!id)throw new Error('Aktive Reise fehlt.');if(!['saved','favorites'].includes(scope))throw new Error('Ungültiger Löschbereich.');return window.LuviaBackend.request('restaurant.clear',{tripId:id,scope});}
async function health(){return window.LuviaBackend.request('restaurant.health',{});}
function entityToEntry(entity){const p=entity?.place||{},tp=entity?.tripPlace||{},r=entity?.restaurant||entity?.extension||{},meta=r.metadata||{};const location={latitude:p.latitude,longitude:p.longitude};const context=window.LuviaTravelContext?.snapshot?.()||{};const distance=context.location?window.LuviaTravelContext?.distanceTo?.(location):null;return{id:tp.id||r.id||p.id,tripPlaceId:tp.id,entity:true,placeId:p.id,providerPlaceId:p.provider_place_id,name:tp.custom_name||(!/^(restaurant|unbenannter ort|unbekannter ort)$/i.test(String(p.name||'').trim())?p.name:null)||meta.displayName||p.name||'Restaurant',date:tp.planned_date||r.reservation_date||'',time:tp.planned_time||r.reservation_time||'',description:tp.custom_description||tp.user_notes||r.personal_notes||'',symbol:tp.custom_symbol||'🍽️',address:p.address||'',latitude:p.latitude,longitude:p.longitude,distanceMeters:Number.isFinite(distance)?distance:null,distanceSource:Number.isFinite(distance)?'gps':'unavailable',mapsUrl:p.maps_url||'',website:p.website||'',phone:p.phone||'',rating:p.rating,userRatingCount:p.rating_count,priceLevel:p.price_level,reservationStatus:r.reservation_status||tp.status||'idea',reservationDate:r.reservation_date||'',reservationTime:r.reservation_time||'',reservationName:r.reservation_name||'',confirmationNumber:r.confirmation_number||'',reservationUrl:r.reservation_url||'',reservationNotes:r.reservation_notes||'',lifecycleStatus:tp.lifecycle_status||'saved',visitedAt:tp.visited_at||null,personalRating:r.personal_rating||null,personalNotes:r.personal_notes||tp.user_notes||'',recommendedVisitTime:r.recommended_visit_time||'',recommendationReason:r.recommendation_reason||'',isFavorite:tp.is_favorite===true,tripStatus:tp.status||'idea',memoryStatus:tp.memory_status||'none',travelBookStatus:tp.travel_book_status||'none',metadata:meta,history:entity?.history||[],menu:{enabled:Boolean(r.menu_url),label:'Speisekarte',original:r.menu_url||'',assetId:'',assetName:'',pages:[]},rawEntity:entity};}
function diagnostics(){return{version:VERSION,metrics:{...state}};}
window.LuviaRestaurants=Object.freeze({version:VERSION,search,importPlace,list,history,updateLifecycle,remove,clear,recordFeedback,health,entityToEntry,enrichDistance,diagnostics});
window.LuviaKernelEvents?.emit?.('restaurants.service.ready',{version:VERSION});
})();
