import { placesAction } from './places.ts';
type Client={rpc:(name:string,args:Record<string,unknown>)=>Promise<{data:any,error:any}>};
const TYPES=new Set(['restaurant','accommodation','attraction','photo_spot','activity','shopping','nature','family','mobility','transit','custom']);
const metrics={imports:0,lists:0,updates:0,accommodationUpdates:0,removes:0,failures:0};
function dbPlace(place:any,type:string,roles:string[]){return{provider:'google-places',provider_place_id:String(place?.id||'').replace(/^places\//,''),name:place?.name||place?.displayName||'',address:place?.formattedAddress||place?.shortAddress||'',latitude:place?.location?.latitude??null,longitude:place?.location?.longitude??null,maps_url:place?.mapsUri||null,website:place?.website||null,phone:place?.phone||null,rating:place?.rating??null,rating_count:place?.userRatingCount??0,price_level:Number.isFinite(Number(place?.priceLevel))?Number(place.priceLevel):null,categories:Array.isArray(place?.types)?place.types:[],attributes:{primaryType:place?.primaryType||null,businessStatus:place?.businessStatus||null,openNow:place?.openNow??null,features:place?.features||{}},opening_hours:place?.openingHours||[],raw_provider_data:place?.raw||place,source_updated_at:new Date().toISOString(),primary_type:type,roles,capabilities:['recommendations','nearby','alternatives','timeline','visit_detection','notes','photos','favorites','ratings','memories','realtime'],source:'google_places',source_id:String(place?.id||'').replace(/^places\//,''),metadata:{provider:'google-places'}};}
export async function placeEntityAction(action:string,payload:any,client:Client){
 if(action==='place.health')return{data:{status:'ok',service:'universal-place-entities',version:'4.9.0.1',metrics}};
 const tripId=String(payload?.tripId||'');if(!tripId)throw Object.assign(new Error('Trip-ID fehlt.'),{code:'TRIP_ID_REQUIRED',status:400});
 if(action==='place.list'){const {data,error}=await client.rpc('luvia_list_place_entities',{p_trip_id:tripId,p_primary_type:payload?.primaryType||null,p_role:payload?.role||null,p_status:payload?.status||null});if(error)throw Object.assign(new Error(error.message),{code:'PLACE_LIST_FAILED',status:400});metrics.lists++;return{data:{entities:Array.isArray(data)?data:[]}};}
 if(action==='place.accommodation.update'){const {data,error}=await client.rpc('luvia_upsert_accommodation',{p_trip_id:tripId,p_trip_place_id:String(payload?.tripPlaceId||''),p_status:String(payload?.status||'saved'),p_accommodation:payload?.accommodation||{}});if(error)throw Object.assign(new Error(error.message),{code:'ACCOMMODATION_UPDATE_FAILED',status:400});metrics.accommodationUpdates++;return{data};}
 if(action==='place.lifecycle.update'){const {data,error}=await client.rpc('luvia_update_place_lifecycle',{p_trip_id:tripId,p_trip_place_id:String(payload?.tripPlaceId||''),p_status:String(payload?.status||''),p_patch:payload?.patch||{}});if(error)throw Object.assign(new Error(error.message),{code:'PLACE_UPDATE_FAILED',status:400});metrics.updates++;return{data};}
 if(action==='place.remove'){const {data,error}=await client.rpc('luvia_remove_place_from_trip',{p_trip_id:tripId,p_trip_place_id:String(payload?.tripPlaceId||'')});if(error)throw Object.assign(new Error(error.message),{code:'PLACE_REMOVE_FAILED',status:400});metrics.removes++;return{data:{removed:Boolean(data)}};}
 if(action!=='place.import')throw Object.assign(new Error('Place-Aktion unbekannt.'),{code:'ACTION_NOT_FOUND',status:404});
 const type=String(payload?.primaryType||'custom');if(!TYPES.has(type))throw Object.assign(new Error('Place-Typ ist ungültig.'),{code:'PLACE_TYPE_INVALID',status:400});
 const providerPlaceId=String(payload?.providerPlaceId||'').replace(/^places\//,'');if(!providerPlaceId)throw Object.assign(new Error('Provider Place-ID fehlt.'),{code:'PLACE_ID_REQUIRED',status:400});
 metrics.imports++;
 try{const details=await placesAction('places.details',{placeId:providerPlaceId,languageCode:payload?.languageCode||'de',regionCode:payload?.regionCode||'DE'});const place=details?.data?.place;if(!place?.id)throw Object.assign(new Error('Ort wurde beim Provider nicht gefunden.'),{code:'PLACE_NOT_FOUND',status:404});const extension=payload?.extension&&typeof payload.extension==='object'?payload.extension:{};const {data,error}=await client.rpc('luvia_import_place_entity',{p_trip_id:tripId,p_place:dbPlace(place,type,Array.isArray(payload?.roles)?payload.roles:[]),p_trip_place:{...payload?.tripPlace,module_key:'places'},p_extension:extension});if(error)throw Object.assign(new Error(error.message),{code:'PLACE_IMPORT_FAILED',status:400});if(type!=='restaurant'&&data?.tripPlace?.id&&Object.keys(extension).length){const {error:extensionError}=await client.rpc('luvia_upsert_trip_place_fields',{p_trip_id:tripId,p_trip_place_id:String(data.tripPlace.id),p_place_id:data?.place?.id||null,p_place_type:type,p_fields:{...extension,place_name:data?.place?.name||place?.name||null}});if(extensionError)throw Object.assign(new Error(extensionError.message),{code:'PLACE_EXTENSION_PERSIST_FAILED',status:400});}return{data:{success:true,...data,providerPlace:place}};}catch(error){metrics.failures++;throw error;}
}
