const VERSION='4.12.0';
const TIMEOUT_MS=6500;
const CACHE_TTL_MS=15*60_000;
const memory=new Map<string,{expires:number,value:any}>();
const clean=(v:unknown)=>String(v??'').trim();
const num=(v:unknown)=>{const n=Number(v);return Number.isFinite(n)?n:null};
const configured=()=>Boolean(clean(Deno.env.get('TRAILFORKS_APP_ID'))&&clean(Deno.env.get('TRAILFORKS_APP_SECRET')));
const endpoint=()=>clean(Deno.env.get('TRAILFORKS_TRAILS_ENDPOINT')||'https://www.trailforks.com/api/1/trails');
function cacheGet(key:string){const x=memory.get(key);if(!x)return null;if(x.expires<Date.now()){memory.delete(key);return null}return x.value}
function cachePut(key:string,value:any){memory.set(key,{expires:Date.now()+CACHE_TTL_MS,value});return value}
function center(payload:any){const d=payload?.destination||{};const l=d.location||d.center||d.coordinates||{};const latitude=num(l.latitude??l.lat),longitude=num(l.longitude??l.lng);if(latitude===null||longitude===null)throw Object.assign(new Error('Reiseziel besitzt keine Koordinaten.'),{code:'DESTINATION_COORDINATES_MISSING',status:400});return{latitude,longitude}}
function difficultyLabel(value:unknown){const raw=clean(value).toLowerCase();return({green:'Leicht',blue:'Mittel',black:'Schwer','double black':'Sehr schwer',1:'Leicht',2:'Mittel',3:'Schwer',4:'Sehr schwer'} as any)[raw]||clean(value)||'Vor Ort prüfen'}
function arrayFrom(body:any){if(Array.isArray(body))return body;for(const key of ['data','trails','results','items']){if(Array.isArray(body?.[key]))return body[key];if(Array.isArray(body?.data?.[key]))return body.data[key]}return[]}
function geometryFrom(item:any){const raw=item?.track?.coordinates||item?.geometry?.coordinates||item?.coords||item?.track||[];if(!Array.isArray(raw))return[];return raw.map((p:any)=>Array.isArray(p)?{lat:Number(p[1]),lon:Number(p[0]),elevation:num(p[2])}:{lat:Number(p.lat??p.latitude),lon:Number(p.lon??p.lng??p.longitude),elevation:num(p.ele??p.elevation)}).filter((p:any)=>Number.isFinite(p.lat)&&Number.isFinite(p.lon))}
function normalize(item:any,destinationName:string){const id=clean(item.trailid||item.trail_id||item.id||item.slug);const name=clean(item.title||item.name||item.trail_name)||'Trailforks MTB-Trail';const lat=num(item.lat??item.latitude??item.location?.lat??item.location?.latitude);const lon=num(item.lon??item.lng??item.longitude??item.location?.lon??item.location?.longitude);const distanceKm=num(item.distance??item.distance_km??item.length);const distanceMeters=distanceKm===null?null:Math.round(distanceKm*(distanceKm<500?1000:1));const geometry=geometryFrom(item);const url=clean(item.url||item.web_url||item.trail_url)||(id?`https://www.trailforks.com/trails/${encodeURIComponent(id)}/`:'https://www.trailforks.com/');const difficulty=difficultyLabel(item.difficulty||item.difficulty_title||item.rating);const rating=num(item.rating_score??item.rating??item.stars);const reviews=num(item.rating_count??item.reviews??item.votes)||0;return{
 id:`trailforks-${id||crypto.randomUUID()}`,providerPlaceId:`trailforks-${id||crypto.randomUUID()}`,provider:'trailforks',source:'trailforks',sourceId:id,name,displayName:name,formattedAddress:clean(item.region_name||item.city||destinationName),shortAddress:clean(item.region_name||item.city||destinationName),description:clean(item.description||item.summary)||'Kuratierter Mountainbike-Trail aus Trailforks.',editorialSummary:clean(item.description||item.summary)||'Trailforks-Trail mit Community- und Regionsdaten.',location:{latitude:lat,longitude:lon},primaryType:'cycling_route',primaryTypeLabel:'Mountainbike-Trail',types:['cycling_route','mtb','trailforks','curated_trail'],mapsUri:url,website:url,rating,userRatingCount:reviews,openNow:null,photos:[],matchScore:98,routeData:{profile:'mtb',profileLabel:'Mountainbike-Trail',resultKind:'curated_trail',resultKindLabel:'Trailforks Trail',matchTier:'exact',isCompleteRoute:true,canLoadDetails:false,curated:true,roundTrip:Boolean(item.loop||item.roundtrip),distanceMeters,estimatedDurationMinutes:num(item.time_minutes??item.duration_minutes),elevationGainMeters:num(item.ascent??item.climb??item.elevation_gain),elevationLossMeters:num(item.descent??item.elevation_loss),difficulty,surface:clean(item.surface),trailStatus:clean(item.status||item.condition),direction:clean(item.direction),geometrySegments:geometry.length?[geometry]:[],geometryPointCount:geometry.length,qualityScore:98,dataConfidence:'hoch',source:'Trailforks',attribution:'Trail data © Trailforks; Nutzung gemäß genehmigtem API-Zugang'},raw:{provider:'trailforks',trail:item}}}
export function trailforksDiagnostics(){return{version:VERSION,configured:configured(),endpoint:endpoint(),timeoutMs:TIMEOUT_MS,cacheTtlMs:CACHE_TTL_MS}}
export async function trailforksSearch(payload:any){const c=center(payload);const destinationName=clean(payload?.destination?.displayName||payload?.destination?.name);const radiusKm=Math.max(5,Math.min(300,Math.round(Number(payload?.radiusMeters||150000)/1000)));const limit=Math.max(1,Math.min(50,Number(payload?.maxResultCount||30)));const key=JSON.stringify([c,radiusKm,limit,clean(payload?.query)]);const hit=cacheGet(key);if(hit)return{data:hit,cache:{hit:true,key}};if(!configured()){const value={routes:[],provider:'trailforks',configured:false,warning:'Trailforks ist vorbereitet, aber TRAILFORKS_APP_ID und TRAILFORKS_APP_SECRET fehlen noch.',summary:{selectedCount:0,resultMode:'not_configured'}};return{data:value,cache:{hit:false,key}}}
 const url=new URL(endpoint());url.searchParams.set('app_id',clean(Deno.env.get('TRAILFORKS_APP_ID')));url.searchParams.set('app_secret',clean(Deno.env.get('TRAILFORKS_APP_SECRET')));url.searchParams.set('lat',String(c.latitude));url.searchParams.set('lon',String(c.longitude));url.searchParams.set('radius',String(radiusKm));url.searchParams.set('rows',String(limit));url.searchParams.set('activitytype','1');url.searchParams.set('scope','full');if(clean(payload?.query))url.searchParams.set('q',clean(payload.query));
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort('trailforks-timeout'),TIMEOUT_MS);try{const response=await fetch(url,{headers:{Accept:'application/json','User-Agent':`Luvia-Travel-App/${VERSION}`},signal:controller.signal});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body?.message||body?.error||`Trailforks ${response.status}`),{code:'TRAILFORKS_REQUEST_FAILED',status:response.status});const routes=arrayFrom(body).map((item:any)=>normalize(item,destinationName));const value={routes,provider:'trailforks',configured:true,summary:{selectedCount:routes.length,resultMode:'approved_api'},attribution:'Trail data © Trailforks',generatedAt:new Date().toISOString()};cachePut(key,value);return{data:value,cache:{hit:false,key}}}finally{clearTimeout(timer)}}
