(()=>{'use strict';
const MODULE_ID='mobility',VERSION='4.14.0';
const QUICK=[['🧭','Entdecken','Mobilität Verkehr Bahnhöfe Parken und Laden'],['🚆','Bahn & Fernverkehr','Bahnhof Fernbahnhof Zug und Bahn'],['🚇','Metro & U-Bahn','Metro U-Bahn Stadtbahn'],['🚌','Bus & Tram','Busbahnhof Bushaltestelle Straßenbahn Tram'],['⛴️','Fähren','Fährterminal Fähre Hafen'],['✈️','Flughäfen','Flughafen Airport Terminal'],['🚕','Taxi','Taxistand Taxi Service'],['🅿️','Parken','Parkhaus Parkplatz Park and Ride'],['🚗','Mietwagen','Mietwagen Autovermietung'],['⚡','E-Laden','Elektroauto Ladestation E-Bike Ladestation'],['🚲','Bike-Sharing','Bike Sharing Leihfahrrad Station']];
const SEARCH_PLANS=Object.freeze({
 'Entdecken':[{type:'train_station',query:'Bahnhof'},{type:'subway_station',query:'Metro U-Bahn'},{type:'bus_station',query:'Busbahnhof'},{type:'parking',query:'Parken'},{type:'electric_vehicle_charging_station',query:'Ladestation'}],
 'Bahn & Fernverkehr':[{type:'train_station',query:'Bahnhof'},{type:'train_ticket_office',query:'Bahntickets'}],
 'Metro & U-Bahn':[{type:'subway_station',query:'Metro U-Bahn'},{type:'light_rail_station',query:'Stadtbahn'}],
 'Bus & Tram':[{type:'bus_station',query:'Busbahnhof'},{type:'bus_stop',query:'Bushaltestelle'},{type:'tram_stop',query:'Straßenbahn Tram'}],
 'Fähren':[{type:'ferry_terminal',query:'Fährterminal'},{type:'ferry_service',query:'Fähre'}],
 'Flughäfen':[{type:'airport',query:'Flughafen'},{type:'international_airport',query:'Internationaler Flughafen'}],
 'Taxi':[{type:'taxi_stand',query:'Taxistand'},{type:'taxi_service',query:'Taxi Service'}],
 'Parken':[{type:'park_and_ride',query:'Park and Ride'},{type:'parking_garage',query:'Parkhaus'},{type:'parking_lot',query:'Parkplatz'},{type:'parking',query:'Parken'}],
 'Mietwagen':[{type:'car_rental',query:'Mietwagen'}],
 'E-Laden':[{type:'electric_vehicle_charging_station',query:'Elektroauto Ladestation'},{type:'ebike_charging_station',query:'E-Bike Ladestation'}],
 'Bike-Sharing':[{type:'bike_sharing_station',query:'Bike Sharing Station'}]
});
const PLAN_BY_QUERY=Object.freeze(Object.fromEntries(QUICK.map(([,label,query])=>[query,SEARCH_PLANS[label]||[]])));
const state={root:null,trip:null,query:'Mobilität Verkehr Bahnhöfe Parken und Laden',filter:'Mobilität Verkehr Bahnhöfe Parken und Laden',options:{},results:[],entities:[],searchMap:new Map(),routeCache:new Map(),loading:false,error:null,visibleCount:6};
const esc=v=>window.LuviaPlaceExperience?.esc?.(v)||String(v??'');
const activeTrip=()=>state.trip||window.LuviaTripStore?.snapshot?.().activeTrip||window.LuviaTripContext?.getActiveTrip?.()||null;
const tripId=()=>activeTrip()?.tripId||activeTrip()?.id||window.LuviaTripStore?.snapshot?.().activeTripId;
const destination=()=>state.trip?.destination?.name||state.trip?.destinationName||window.LuviaDestination?.getActive?.()?.canonicalCity?.name||'eurem Reiseziel';
const place=e=>e?.place||e||{},link=e=>e?.tripPlace||e?.trip_place||{};
const ext=e=>{const legacy=e?.extension||e?.mobility||{},id=link(e)?.id||e?.tripPlaceId;const cloud=id?window.LuviaTripPlaceData?.recordForTripPlace?.(id)?.fields||{}:{};return {...legacy,...cloud}};
const providerId=p=>String(p?.providerPlaceId||p?.provider_place_id||p?.sourceId||p?.source_id||p?.id||'').replace(/^places\//,'');
const fmtDistance=m=>{m=Number(m);if(!Number.isFinite(m))return null;return m<1000?`${Math.round(m/50)*50} m`:`${(m/1000).toFixed(m<10000?1:0).replace('.',',')} km`};
function normalized(p,l={}){return {...p,id:p.id||p.placeId||providerId(p),placeId:p.id||p.placeId,primaryType:'mobility',symbol:'🚉',lifecycle:l.status||p.lifecycleStatus||'discovered',address:p.shortAddress||p.formattedAddress||p.formatted_address||p.address||'',description:p.editorialSummary||p.description||'',matchScore:p.matchScore||p.match_score||Math.max(50,Math.min(96,Math.round((Number(p.rating)||3.8)*17))),metadata:{...(p.metadata||{}),tripPlaceId:l.id}}}
async function photoUris(photos,max=6){const out=[];for(const photo of (photos||[]).slice(0,max)){try{if(photo.uri||photo.url){out.push({uri:photo.uri||photo.url});continue}const r=await window.LuviaPlaces.photo(photo.name,{maxWidthPx:1200,maxHeightPx:900});if(r?.data?.photoUri)out.push({uri:r.data.photoUri})}catch{}}return out}
async function hydrate(places){await Promise.all((places||[]).slice(0,20).map(async p=>{if(!p._cardPhotoUri&&p.photos?.length){const x=await photoUris(p.photos,1);if(x[0])p._cardPhotoUri=x[0].uri}const origin=window.LuviaTravelContext?.snapshot?.()?.location;if(!origin||!p.location||!window.LuviaPlaces?.route)return;const key=providerId(p);try{let route=state.routeCache.get(key);if(!route){route=(await window.LuviaPlaces.route(origin,p.location))?.data||null;if(route)state.routeCache.set(key,route)}if(route?.walk?.distanceMeters||route?.drive?.distanceMeters){const meters=route.walk?.distanceMeters||route.drive?.distanceMeters;p.route=route;p.gpsDistanceMeters=meters;p.distanceMeters=meters}}catch{}}))}
function intelligence(p,e=null){const base=window.LuviaPlaceIntelligence?.analyze?.('mobility',p,{trip:state.trip,destination:destination(),extension:ext(e)})||{};const profile=window.LuviaTransportIntelligence?.analyze?.(p,{trip:state.trip,extension:ext(e)})||{};return{...base,transport:profile,score:base.score||p.matchScore||75,distanceLabel:base.distanceLabel||fmtDistance(p.distanceMeters),bestTime:base.bestTime||null,bestTimeReason:base.bestTimeReason||null,reasons:[...(base.reasons||[]),...(profile.travelReasons||[])],warnings:base.warnings||[]}}
function resultCard(p,favoriteEntity=null){const added=Boolean(favoriteEntity);p=normalized(p);const intel=intelligence(p),rating=p.rating?`${Number(p.rating).toFixed(1).replace('.',',')} ★ · ${p.userRatingCount||0} Bewertungen`:'';p.description=[rating,p.description].filter(Boolean).join(' · ');return window.LuviaPlaceUI.card(p,{className:'rv2-search-card rv2-search-card-intelligent',openAttribute:`data-place-card-open="result:${esc(providerId(p))}"`,media:p._cardPhotoUri?`<div class="rv2-card-media"><img src="${esc(p._cardPhotoUri)}" alt="${esc(p.name)}" loading="eager" fetchpriority="high" decoding="sync"></div>`:`<div class="rv2-card-media is-placeholder"><span>🚉</span></div>`,intelligence:intel,actions:`<button type="button" class="rv2-detail-button primary" data-place-card-open="result:${esc(providerId(p))}">Warum passt das?</button>${window.LuviaPlaceCollections.favoriteButton({placeType:'mobility',providerPlaceId:providerId(p),tripPlaceId:favoriteEntity?link(favoriteEntity).id:'',isFavorite:added})}`})}
function savedCard(e){const p=normalized(place(e),link(e)),l=link(e),intel=intelligence(p,e);const rating=p.rating?`${Number(p.rating).toFixed(1).replace('.',',')} ★ · ${p.userRatingCount||0} Bewertungen`:'';p.description=[rating,p.description].filter(Boolean).join(' · ');return window.LuviaPlaceUI.card(p,{className:'rv2-search-card rv2-search-card-intelligent',openAttribute:`data-place-card-open="saved:${esc(l.id)}"`,media:p._cardPhotoUri?`<div class="rv2-card-media"><img src="${esc(p._cardPhotoUri)}" alt="${esc(p.name)}" loading="eager" fetchpriority="high"></div>`:`<div class="rv2-card-media is-placeholder"><span>🚉</span></div>`,intelligence:intel,actions:`<button type="button" class="rv2-detail-button primary" data-place-card-open="saved:${esc(l.id)}">Warum passt das?</button>${window.LuviaPlaceCollections.favoriteButton({placeType:'mobility',providerPlaceId:providerId(p),tripPlaceId:l.id,isFavorite:Boolean(l.is_favorite)})}`})}
async function hydrateFavoriteMedia(){const favorites=state.entities.filter(e=>link(e).is_favorite===true).filter(e=>providerId(place(e))&&!place(e)._cardPhotoUri).slice(0,6);if(!favorites.length)return;let changed=false;for(const entity of favorites){const p=place(entity),id=providerId(p);try{const prepared=await window.LuviaPlaceDetails?.prepare?.(id,{regionCode:'DE',photoLimit:1});const detail=prepared?.place||prepared?.response?.data?.place||{};Object.assign(p,detail,{providerPlaceId:id,primaryType:'mobility'});const photos=prepared?.photos?.length?prepared.photos:await photoUris((detail.photos||[]).slice(0,1),1);if(photos[0]?.uri){p._cardPhotoUri=photos[0].uri;changed=true}state.searchMap.set(id,p)}catch(_){}}if(changed&&state.root?.isConnected)render()}
function scheduledItems(){return (window.LuviaTripPlaceData?.dateEntries?.('mobility')||[]).map(e=>({id:e.id,tripPlaceId:e.tripPlaceId,dataKey:e.dataKey,title:e.title,time:`${new Date(e.startAt).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'})} · ${new Date(e.startAt).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'})} Uhr`,entry:e}))}
function timelineAction(l){return window.LuviaPlaceUIActions.actionButtons({favorite:Boolean(l?.is_favorite),planned:Boolean(ext({tripPlace:l||{}}).planned_at),favoriteAttr:l?.id?'data-fav':'data-import-detail',planAttr:'data-plan-mobility'})}
function openPlanning(p,l,e){return window.LuviaPlaceUIActions.openTimelineDialog({type:'mobility',tripId:tripId(),place:p,entity:e,tripPlace:l,importEntity:async()=>importOne(providerId(p),{silent:true,status:'planned',favorite:false}),onSaved:async()=>{await load()}})}
async function load(){try{await window.LuviaTripPlaceData?.hydrate?.(tripId());const r=await window.LuviaPlaceEntities.list({tripId:tripId(),type:'mobility'});state.entities=(r?.data?.entities||[]).filter(e=>link(e).status!=='archived');window.LuviaPlaceCollections?.remember?.('mobility',state.entities,tripId());await hydrate(state.entities.map(place));state.error=null}catch(e){state.error=e.message||String(e)}render();hydrateFavoriteMedia().catch(()=>{})}
async function search(query=state.query,options={}){state.visibleCount=6;state.query=String(query||'Mobilität Verkehr Bahnhöfe Parken und Laden').trim()||'Mobilität Verkehr Bahnhöfe Parken und Laden';state.options=options;state.loading=true;state.error=null;render();try{const planned=PLAN_BY_QUERY[state.query]||[];const plans=planned.length?planned:[{type:'',query:state.query}];const broad=plans.some(x=>['airport','international_airport','ferry_terminal','car_rental'].includes(x.type));const responses=await Promise.all(plans.slice(0,6).map(item=>window.LuviaPlaceEntities.searchPlaces({tripId:tripId(),type:'mobility',includedType:item.type||'',query:`${item.query} ${destination()}`,maxResultCount:8,strictDestination:!broad,minRating:options.minRating,sortBy:options.sortBy||'distance',openNow:options.openNow||false}).catch(error=>({error,data:{places:[]}}))));
 const merged=new Map();for(const response of responses)for(const raw of (response?.data?.places||[])){const id=providerId(raw);if(!id||raw.businessStatus==='CLOSED_PERMANENTLY')continue;const current=merged.get(id);if(!current||Number(raw.rating||0)>Number(current.rating||0))merged.set(id,raw)}
 state.results=[...merged.values()].sort((a,b)=>{if((options.sortBy||'distance')==='rating')return Number(b.rating||0)-Number(a.rating||0)||Number(b.userRatingCount||0)-Number(a.userRatingCount||0);return Number(a.distanceMeters??Infinity)-Number(b.distanceMeters??Infinity)||Number(b.rating||0)-Number(a.rating||0)}).slice(0,24);
 if(!state.results.length&&planned.length){const fallback=await window.LuviaPlaceEntities.searchPlaces({tripId:tripId(),type:'mobility',includedType:'',query:`${state.query} ${destination()}`,maxResultCount:16,strictDestination:false,sortBy:options.sortBy||'distance'});state.results=fallback?.data?.places||[]}
 await hydrate(state.results);state.searchMap=new Map(state.results.map(p=>[providerId(p),p]))}catch(e){state.error=e.message||String(e)}state.loading=false;render()}
async function importOne(id,{silent=false,status='idea',favorite=true}={}){try{const seed=state.searchMap.get(String(id))||state.results.find(x=>providerId(x)===String(id))||{};const profile=window.LuviaTransportIntelligence?.analyze?.(seed,{trip:state.trip})||{};const response=await window.LuviaPlaceEntities.importPlace(id,{tripId:tripId(),type:'mobility',tripPlace:{status,isFavorite:favorite},extension:{mobility_mode:profile.mobilityMode?.value||null,transport_role:profile.transportRole?.value||null,transfer_buffer:profile.transferBuffer?.value||null,access_hint:profile.accessHint?.value||null,operating_hint:profile.operatingHint?.value||null,parking_hint:profile.parkingHint?.value||null,charging_hint:profile.chargingHint?.value||null,ticket_hint:profile.ticketHint?.value||null,decision_sources:{mode:profile.mobilityMode?.source||null,role:profile.transportRole?.source||null,buffer:profile.transferBuffer?.source||null}}});await load();const entity=state.entities.find(e=>providerId(place(e))===String(id))||response?.data?.entity||response?.data?.tripPlaceEntity||null;if(!silent)window.LuviaUIKit?.toast?.('Mobilitätspunkt als Favorit gespeichert.',{type:'success'});return entity}catch(e){state.error=e.message||String(e);render();throw e}}
function transportGuidance(profile={}){const value=x=>x?.value||'Noch nicht eindeutig';return window.LuviaPlaceUI.insightGrid({className:'luv-transport-guidance',eyebrow:'Mobilitäts-Intelligence',title:'Verkehrsart, Nutzung und Reiseplanung',description:'Luvia ordnet den Mobilitätspunkt anhand verlässlicher Google-Place-Daten ein.',symbol:'🚉',items:[{label:'Verkehrsart',icon:'🚉',value:value(profile.mobilityMode),source:profile.mobilityMode?.source,confidence:profile.mobilityMode?.confidence,featured:true},{label:'Rolle in der Reise',icon:'🧭',value:value(profile.transportRole),source:profile.transportRole?.source,confidence:profile.transportRole?.confidence,featured:true},{label:'Zeitpuffer',icon:'⏱️',value:value(profile.transferBuffer),source:profile.transferBuffer?.source,confidence:profile.transferBuffer?.confidence,wide:true},{label:'Betrieb und Zeiten',icon:'🕒',value:value(profile.operatingHint),source:profile.operatingHint?.source,confidence:profile.operatingHint?.confidence},{label:'Barrierefreiheit',icon:'♿',value:value(profile.accessHint),source:profile.accessHint?.source,confidence:profile.accessHint?.confidence},{label:'Parken',icon:'🅿️',value:value(profile.parkingHint),source:profile.parkingHint?.source,confidence:profile.parkingHint?.confidence},{label:'Laden',icon:'⚡',value:value(profile.chargingHint),source:profile.chargingHint?.source,confidence:profile.chargingHint?.confidence},{label:'Ticket oder Nutzung',icon:'🎫',value:value(profile.ticketHint),source:profile.ticketHint?.source,confidence:profile.ticketHint?.confidence}],note:profile.decisionNote||'Live-Abfahrten, Belegung, Preise und Verspätungen müssen beim Betreiber geprüft werden.'})}
function guidanceFor(p,e=null){return transportGuidance(window.LuviaTransportIntelligence?.analyze?.(p,{trip:state.trip,extension:ext(e)})||{})}
async function detail(raw,l=null,e=null){let p=normalized(raw,l||{});const overlay=window.LuviaPlaceDetail.openLoading({typeLabel:'Transport & Mobilität'});const initialIntel=intelligence(p,e);window.LuviaPlaceDetail.update(overlay,{placeType:'mobility',place:p,photos:p._cardPhotoUri?[{uri:p._cardPhotoUri}]:[],intelligence:initialIntel,destination:destination(),typeLabel:'Transport & Mobilität',primaryActions:timelineAction(l),lifecycle:{title:'Mobilitäts-Lebenszyklus',status:l?.status||'discovered',order:['discovered','favorite','planned','visited','rated']},capabilityContent:guidanceFor(p,e),alternativesContent:'<p class="rv2-muted">Weitere Details werden geladen …</p>'});bindDetail(overlay,p,l,e);try{const prepared=await window.LuviaPlaceDetails.prepare(providerId(p),{regionCode:'DE',photoLimit:6,seedPlace:p});p=normalized({...p,...prepared.place},l||{});const photos=prepared.photos?.length?prepared.photos:await photoUris(p.photos);const intel=intelligence(p,e),alts=(state.results||[]).filter(a=>providerId(a)!==providerId(p)).slice(0,3);const alternatives=alts.length?`<div class="rv2-alternatives">${alts.map(a=>`<button type="button" class="luv-place-alternative" data-place-alternative="${esc(providerId(a))}"><span><strong>${esc(a.name||'Alternative')}</strong><small>Alternative aus der aktuellen Suche</small></span><b>${esc(intelligence(a).score)} %</b></button>`).join('')}</div>`:'<p class="rv2-muted">Noch keine Alternativen verfügbar.</p>';window.LuviaPlaceDetail.update(overlay,{placeType:'mobility',place:p,photos,intelligence:intel,destination:destination(),typeLabel:'Transport & Mobilität',primaryActions:timelineAction(l),lifecycle:{title:'Mobilitäts-Lebenszyklus',status:l?.status||'discovered',order:['discovered','favorite','planned','visited','rated']},capabilityContent:guidanceFor(p,e),alternativesContent:alternatives});bindDetail(overlay,p,l,e)}catch(error){console.warn('[Luvia Mobilität] Details konnten nicht vollständig geladen werden.',error)}}
function bindDetail(overlay,p,l,e){const root=overlay.node;root.querySelector('[data-import-detail]')?.addEventListener('click',async ev=>{ev.stopPropagation();const imported=await importOne(providerId(p),{silent:true});overlay.close();if(imported)detail(place(imported),link(imported),imported)});root.querySelector('[data-fav]')?.addEventListener('click',async ev=>{ev.stopPropagation();await window.LuviaPlaceCommands.toggleFavorite({tripId:tripId(),placeType:'mobility',tripPlaceId:l.id,entity:e,isFavorite:!l.is_favorite,status:l.status||'idea'});overlay.close();load()});root.querySelector('[data-plan-mobility]')?.addEventListener('click',ev=>{ev.preventDefault();ev.stopPropagation();openPlanning(p,l,e)});root.querySelectorAll('[data-place-alternative]').forEach(button=>button.addEventListener('click',()=>{const a=state.searchMap.get(button.dataset.placeAlternative);if(a)detail(a)}))}
function render(){const r=state.root;if(!r)return;const accent=state.trip?.accent||state.trip?.theme?.accent||getComputedStyle(document.documentElement).getPropertyValue('--lv-accent').trim()||'#ee6f83';r.className='luvia-restaurants-v2';for(const key of ['--trip-accent','--module-accent','--rv2-accent','--place-accent'])r.style.setProperty(key,accent);const scheduled=scheduledItems(),favorites=state.entities.filter(e=>link(e).is_favorite===true);const visible=state.results.slice(0,Math.max(6,state.visibleCount||6));const more=state.results.length>visible.length?`<button type="button" class="luv-place-load-more" data-place-more>Weitere ${Math.min(6,state.results.length-visible.length)} Orte anzeigen</button>`:'';const planned=window.LuviaPlaceExperience.plannedPanel({items:scheduled,eyebrow:'Geplant',emptyTitle:'Noch kein Mobilitätspunkt geplant',emptyText:'Fügt einen Mobilitätspunkt über „Zur Timeline“ hinzu – er erscheint hier und im Dashboard.',title:'Eure Mobilitätspunkte'});const results=state.loading?'<div class="rv2-search-loading"><span></span><span></span><span></span></div>':state.error?window.LuviaPlaceUIStates?.error?.(state.error)||`<div class="rv2-library-empty">${esc(state.error)}</div>`:visible.length?visible.map(x=>resultCard(x,state.entities.find(e=>link(e).is_favorite===true&&providerId(place(e))===providerId(x))||null)).join('')+more:'<div class="rv2-library-empty">Starte eine Suche oder wähle eine Kategorie.</div>';const discovery=window.LuviaPlaceExperience.discovery({destination:destination(),title:'Wie möchtet ihr unterwegs sein?',description:'Verkehrs- und Mobilitätspunkte direkt am Reiseziel – zentral in Luvia.',placeholder:'Bahnhof, Metro, Parkhaus, Ladestation oder Mietwagen',quickFilters:QUICK,activeFilter:state.filter,filters:{extra:''},status:state.error?state.error:(state.loading?'Luvia sucht passende Mobilitätspunkte …':`${state.results.length} passende Vorschläge`),results});const favoritesPanel=window.LuviaPlaceCollections.favoritePanel({placeType:'mobility',items:favorites,title:'Gespeicherte Mobilitätspunkte',empty:'Markiert Mobilitätspunkte mit einem Herz, um sie hier wiederzufinden.',renderCard:e=>savedCard(e),open:false});r.innerHTML=window.LuviaPlaceExperience.moduleShell({destination:destination(),title:'Transport & Mobilität',description:'Bahnhöfe, Nahverkehr, Parken, Laden und weitere Mobilitätspunkte zuverlässig finden.',planned,discovery,collection:favoritesPanel,collectionEyebrow:'Eure Sammlung',collectionTitle:'Nur öffnen, wenn ihr sie braucht',collectionCountLabel:`${favorites.length} Favoriten`});bind()}
function bind(){const r=state.root;r.onsubmit=e=>{e.preventDefault();const f=new FormData(e.currentTarget);search(f.get('query'),{minRating:f.get('minRating')?Number(f.get('minRating')):null,sortBy:f.get('sortBy'),openNow:f.get('openNow')==='on'})};r.onclick=async e=>{const more=e.target.closest('[data-place-more]');if(more){state.visibleCount=Math.min(state.results.length,state.visibleCount+6);render();return}const refresh=e.target.closest('[data-place-refresh]');if(refresh){search(state.query,state.options);return}const quick=e.target.closest('[data-place-query]');if(quick){state.filter=quick.dataset.placeQuery;search(quick.dataset.placeQuery,state.options);return}const open=e.target.closest('[data-place-card-open]');if(open&&!e.target.closest('[data-place-favorite-toggle]')){const [kind,id]=String(open.dataset.placeCardOpen||'').split(':');if(kind==='result'){const p=state.searchMap.get(id);if(p)detail(p)}else{const x=state.entities.find(y=>String(link(y).id)===id);if(x)detail(place(x),link(x),x)}return}const scheduled=e.target.closest('[data-place-schedule]');if(scheduled){const ev=scheduledItems().find(x=>String(x.id)===String(scheduled.dataset.placeSchedule));if(ev)openPlace({tripPlaceId:ev.tripPlaceId,placeId:ev.entry?.placeId});return}const edit=e.target.closest('[data-place-edit-schedule]');if(edit){const ev=scheduledItems().find(x=>String(x.id)===String(edit.dataset.placeEditSchedule));if(ev)window.LuviaTimelineCore?.editEntry?.(ev.entry,()=>render());return}const remove=e.target.closest('[data-place-remove-schedule]');if(remove){const ev=scheduledItems().find(x=>String(x.id)===String(remove.dataset.placeRemoveSchedule));if(ev)await window.LuviaTripPlaceData.updateDateFields(ev.tripPlaceId,{[ev.dataKey]:null},{tripId:tripId()});await window.LuviaTimelineCore?.hydrate?.(tripId());render();return}if(e.target.closest('[data-place-clear-schedule]')){for(const rec of window.LuviaTripPlaceData?.recordsForType?.('mobility')||[])await window.LuviaTripPlaceData.upsert({tripId:tripId(),tripPlaceId:rec.trip_place_id,placeId:rec.place_id,placeType:'mobility',fields:{planned_at:null}});await window.LuviaTimelineCore?.hydrate?.(tripId());render()}};r.onpointerover=e=>{const card=e.target.closest('[data-place-card-open^="result:"]');if(card){const id=String(card.dataset.placeCardOpen||'').split(':')[1];if(id)window.LuviaPlaceDetails?.prefetch?.([id],{regionCode:'DE'})}};r.onfocusin=r.onpointerover}
async function mount(instance,context={}){state.root=instance?.roots?.[0]||document.querySelector('#mobility-module');state.trip=context.trip||instance?.trip||window.LuviaTripStore?.snapshot?.().activeTrip;state.root.className='luvia-restaurants-v2';render();await load();if(!state.results.length)await search('Mobilität Verkehr Bahnhöfe Parken und Laden',{sortBy:'relevance'});return instance}
function unmount(){state.root=null;state.trip=null}
async function openPlace(payload={}){if(!state.trip)state.trip=activeTrip();const candidates=[payload.tripPlaceId,payload.placeId,payload.providerPlaceId].filter(Boolean).map(value=>String(value).replace(/^places\//,''));const matches=entity=>{const p=place(entity),l=link(entity);return candidates.includes(String(l.id||''))||candidates.includes(String(p.id||''))||candidates.includes(providerId(p))};let entity=state.entities.find(matches);if(!entity&&tripId()){try{const response=await window.LuviaPlaceEntities?.list?.({tripId:tripId(),type:'mobility'});const fresh=(response?.data?.entities||[]).filter(item=>link(item).status!=='archived');if(fresh.length){state.entities=fresh;window.LuviaPlaceCollections?.remember?.('mobility',fresh,tripId());entity=fresh.find(matches)}}catch(error){console.warn('[Luvia Mobilität] Mobilitätspunkt für externe Detailöffnung konnte nicht nachgeladen werden.',error)}}if(entity){detail(place(entity),link(entity),entity);return true}const seed=payload.seedPlace||null,provider=String(payload.providerPlaceId||'').replace(/^places\//,'');if(seed||provider){detail(normalized({...seed,id:seed?.id||payload.placeId||provider,providerPlaceId:provider||providerId(seed),name:seed?.name||payload.title||'Mobilitätspunkt'}));return true}return false}
window.addEventListener('luvia:open-place',e=>{if(e.detail?.type==='mobility')openPlace(e.detail)});window.addEventListener('luvia:trip-place-data-changed',()=>state.root&&render());window.addEventListener('luvia:place-collection-changed',e=>{if(state.root&&e.detail?.placeType==='mobility')load()});
window.LuviaPlaceDetail?.registerCapabilityRenderer?.('mobility',({place,context})=>guidanceFor(place,context?.entity||null));
window.LuviaMobility=Object.freeze({version:VERSION,load,search,openPlace,renderGuidance:guidanceFor});window.LuviaModules?.register({id:MODULE_ID,order:80,group:'Places',icon:'🚉',title:'Transport & Mobilität',description:'Bahnhöfe, Nahverkehr, Parken, Laden und weitere Mobilitätspunkte entdecken und planen.',selectors:['#mobility-module'],version:VERSION,mount,unmount});
})();
