(function(){
'use strict';
const VERSION='4.7.1';
const TYPE_META=Object.freeze({restaurant:['🍽️','Restaurant'],accommodation:['🛏️','Unterkunft'],attraction:['🏛️','Sehenswürdigkeit'],photo_spot:['📸','Fotospot'],activity:['✨','Aktivität'],shopping:['🛍️','Shopping'],nature:['🌿','Natur'],family:['👨‍👩‍👧','Familienort'],mobility:['🚗','Mobilität'],transit:['🚉','Verkehr'],custom:['📍','Eigener Ort']});
const LIFE_LABELS=Object.freeze({discovered:'Entdeckt',saved:'Favorit',favorite:'Favorit',planned:'Geplant',visited:'Besucht',rated:'Bewertet',memory:'Erinnerung',reserved:'Reserviert',idea:'Entdeckt',favorited:'Favorit'});
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const score=v=>Math.max(0,Math.min(100,Math.round(Number(v)||0)));
function typeMeta(place={}){return TYPE_META[place.primaryType]||TYPE_META.restaurant;}
function lifecycle(place={}){return place.lifecycle||place.lifecycleStatus||place.status||'discovered';}
function factValue(slot,place={},intel={}){switch(slot){case'rating':return place.rating?`⭐ ${Number(place.rating).toFixed(1).replace('.',',')}${place.userRatingCount?` · ${Number(place.userRatingCount).toLocaleString('de-DE')}`:''}`:'';case'distance':return intel.distanceLabel||place.distanceLabel?`📍 ${esc(intel.distanceLabel||place.distanceLabel)}`:'';case'bestTimeToVisit':return intel.bestTime?`✨ Beste Zeit ${esc(intel.bestTime)}${/:/.test(String(intel.bestTime))?' Uhr':''}`:'';case'priceLevel':{const raw=intel.priceLabel||place.priceLabel||place.priceLevel||'';const x=window.LuviaPlaceProviderFields?.formatPriceLevel?.(raw)||raw;return x?`💶 ${esc(x)}`:'';}case'openingState':{const x=intel.openLabel||place.openLabel||(place.openNow===true?'Jetzt geöffnet':place.openNow===false?'Aktuell geschlossen':'');return x?`${/geöffnet/i.test(x)?'🟢':'🕒'} ${esc(x)}`:''}default:return''}}
function badges(place={},intel={}){const type=place.primaryType||'restaurant',slots=window.LuviaPlaceUIContract?.forType?.(type)?.card?.factSlots||['rating','distance','bestTimeToVisit','priceLevel','openingState'];const items=slots.map(x=>factValue(x,place,intel)).filter(Boolean);return `<div class="luv-place-badges luv-place-fact-slots" data-place-facts="${esc(slots.join(','))}">${items.map(x=>`<span class="luv-place-badge">${x}</span>`).join('')}</div>`;}
function roleBadges(place={}){const roles=Array.isArray(place.roles)?place.roles:[];return roles.length?`<div class="luv-place-roles">${roles.map(r=>{const m=TYPE_META[r]||['•',r];return `<span>${m[0]} ${esc(m[1])}</span>`}).join('')}</div>`:'';}
function lifecyclePill(place={}){const value=lifecycle(place);return `<span class="luv-place-lifecycle" data-lifecycle="${esc(value)}">${esc(LIFE_LABELS[value]||value)}</span>`;}
function card(place={},options={}){const meta=typeMeta(place),intel=options.intelligence||{},title=place.name||place.displayName||'Unbenannter Ort',address=place.address||place.formattedAddress||place.shortAddress||'',description=place.description||place.editorialSummary||options.description||'',symbol=place.symbol||meta[0],id=place.id||place.placeId||'';return `<article class="luv-place-card ${options.className||''}" data-place-id="${esc(id)}" ${options.openAttribute||''} tabindex="0">${options.media||''}<div class="luv-place-card-head"><span class="luv-place-symbol">${esc(symbol)}</span><div><span class="luv-place-type">${esc(meta[1])}</span><h3>${esc(title)}</h3></div>${lifecyclePill(place)}</div>${address?`<p class="luv-place-address">📍 ${esc(address)}</p>`:''}${description?`<p class="luv-place-description">${esc(description)}</p>`:''}${roleBadges(place)}${badges(place,intel)}${options.extra||''}<div class="luv-place-actions">${options.actions||''}</div></article>`;}
function assessment(intel={}){const reasons=intel.reasons||[],warnings=intel.warnings||[];return `<section class="luv-place-assessment"><article><span>Warum passt das?</span><ul>${reasons.length?reasons.map(x=>`<li>${esc(x)}</li>`).join(''):'<li>Passt zum aktuellen Reisekontext.</li>'}</ul></article><article class="${warnings.length?'has-warning':'is-clear'}"><span>${warnings.length?'Was spricht dagegen?':'Keine wichtigen Einschränkungen'}</span>${warnings.length?`<ul>${warnings.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'<p>Im bekannten Reisekontext spricht nichts Wesentliches dagegen.</p>'}</article></section>`;}
function diagnostics(){return{version:VERSION,status:'ready',components:['card','factSlots','roles','lifecycle','assessment'],migratedModules:['restaurants','accommodations','attractions']};}
window.LuviaPlaceUI=Object.freeze({version:VERSION,typeMeta,badges,roleBadges,lifecyclePill,card,assessment,diagnostics});
})();
