(() => {
'use strict';
const VERSION='5.0.0';
let state={tripId:null,loading:false,entries:[],days:[],lastUpdatedAt:null,lastError:null};
let channels=[];const listeners=new Set();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const client=()=>window.LuviaSupabaseService?.getClient?.()||window.ParisSupabaseClient||window.ParisCloud?.client||null;
const activeTripId=()=>window.LuviaTripContext?.getActiveTrip?.()?.tripId||window.LuviaTripStore?.snapshot?.()?.activeTripId||null;
const iso=(d,t='00:00')=>new Date(`${d}T${String(t).slice(0,5)}:00`).toISOString();
const dayKey=v=>new Date(v).toLocaleDateString('sv-SE');
const typeIcon=t=>({restaurant:'🍽️',accommodation:'🏨',attraction:'🏛️',activity:'🎟️',photo_spot:'📸',parking:'🅿️',charging:'🔌',shopping:'🛍️',mobility:'🚉'}[t]||'📍');
function scheduleEntry(r){const start=iso(r.event_date,r.start_time),duration=Number(r.duration_minutes||60);return{id:`schedule:${r.id}`,sourceKey:r.source_key,tripId:r.trip_id,placeId:r.place_id,tripPlaceId:r.trip_place_id,providerPlaceId:r.provider_place_id,entityType:r.entity_type||'place',kind:/check-in/i.test(r.title)?'check_in':/check-out/i.test(r.title)?'check_out':'planned',title:r.title,startAt:start,endAt:new Date(new Date(start).getTime()+duration*60000).toISOString(),durationMinutes:duration,automatic:false,source:'schedule',metadata:r.metadata||{},icon:typeIcon(r.entity_type)}}
function eventEntry(r){return{id:`event:${r.id}`,sourceKey:r.id,tripId:r.trip_id,placeId:r.place_id,entityType:r.metadata?.entityType||String(r.event_type||'place').split('.')[0]||'place',kind:r.event_type,title:r.title,startAt:r.occurred_at,endAt:r.metadata?.endAt||null,durationMinutes:Number(r.metadata?.durationSeconds||0)/60||null,automatic:Boolean(r.is_automatic),source:r.source||'timeline',metadata:r.metadata||{},icon:typeIcon(r.metadata?.entityType)}}
function visitEntry(r){const duration=Number(r.duration_seconds||0);return{id:`visit:${r.id}`,sourceKey:r.id,tripId:r.trip_id,placeId:r.place_id,entityType:r.correction?.entityType||'place',kind:'visit',title:r.correction?.placeName||'Besuchter Ort',startAt:r.arrived_at||r.created_at,endAt:r.left_at||null,durationMinutes:duration?Math.max(1,Math.round(duration/60)):null,automatic:Boolean(r.is_automatic),source:'gps',metadata:{visitId:r.id,state:r.state,minimumDistanceMeters:r.minimum_distance_meters},icon:'📍'}}
function dedupe(list){const seen=new Map();for(const e of list){const key=e.source==='schedule'?`s:${e.sourceKey}`:e.source==='gps'?`v:${e.sourceKey}`:`e:${e.sourceKey}`;seen.set(key,e)}return [...seen.values()].sort((a,b)=>new Date(a.startAt)-new Date(b.startAt))}
function buildDays(entries){const map=new Map();for(const e of entries){const key=dayKey(e.startAt);if(!map.has(key))map.set(key,[]);map.get(key).push(e)}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,items])=>({date,items,hasAutomatic:items.some(x=>x.automatic),count:items.length}))}
function emit(){state.days=buildDays(state.entries);state.lastUpdatedAt=new Date().toISOString();const snap=snapshot();listeners.forEach(fn=>{try{fn(snap)}catch{}});window.dispatchEvent(new CustomEvent('luvia:timeline-changed',{detail:snap}));window.dispatchEvent(new CustomEvent('luvia:timeline-cloud-changed',{detail:snap}))}
async function hydrate(tripId=activeTripId()){state.tripId=tripId||null;if(!tripId){state.entries=[];emit();return snapshot()}const db=client();if(!db?.from)throw new Error('Keine Cloud-Verbindung für Timeline verfügbar.');state.loading=true;state.lastError=null;try{const [s,e,v]=await Promise.all([db.from('trip_schedule_events').select('*').eq('trip_id',tripId).order('event_date').order('start_time'),db.from('timeline_events').select('*').eq('trip_id',tripId).order('occurred_at'),db.from('place_visits').select('*').eq('trip_id',tripId).order('arrived_at')]);for(const r of [s,e,v])if(r.error)throw r.error;state.entries=dedupe([...(s.data||[]).map(scheduleEntry),...(e.data||[]).map(eventEntry),...(v.data||[]).filter(x=>x.arrived_at).map(visitEntry)]);emit();return snapshot()}catch(err){state.lastError=err.message;throw err}finally{state.loading=false}}
async function record(raw={}){const db=client(),tripId=raw.tripId||state.tripId||activeTripId();if(!db?.from||!tripId)throw new Error('Timeline-Cloud nicht verfügbar.');const row={trip_id:tripId,place_id:raw.placeId||null,participant_id:raw.participantId||null,event_type:raw.type||'place_event',title:raw.title||'Reiseereignis',description:raw.description||'',occurred_at:raw.occurredAt||new Date().toISOString(),source:raw.source||'manual',is_automatic:Boolean(raw.automatic),metadata:raw.metadata||{}};const {error}=await db.from('timeline_events').insert(row);if(error)throw error;return hydrate(tripId)}
function snapshot(){return clone(state)}
function entriesForDate(date){return state.entries.filter(e=>dayKey(e.startAt)===date)}
function dateRange(trip){const start=new Date(trip?.startDate||state.days[0]?.date||new Date()),end=new Date(trip?.endDate||state.days.at(-1)?.date||start),out=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))out.push(new Date(d));return out.slice(0,62)}
function renderCalendar(trip,esc=s=>String(s)){const range=dateRange(trip),marked=new Map(state.days.map(d=>[d.date,d]));return `<div class="lv-trip-calendar"><div class="lv-widget-title"><div><h2>Reise-Timeline</h2><small>Alle geplanten und automatisch erkannten Orte aus der Cloud.</small></div><span>${state.entries.length} Einträge</span></div><div class="lv-calendar-grid">${range.map(d=>{const key=d.toLocaleDateString('sv-SE'),day=marked.get(key);return `<button type="button" class="lv-calendar-day ${day?'has-events':''}" data-timeline-date="${key}"><span>${d.toLocaleDateString('de-DE',{weekday:'short'})}</span><strong>${d.getDate()}</strong><small>${d.toLocaleDateString('de-DE',{month:'short'})}</small>${day?`<em>${day.count}</em>`:''}</button>`}).join('')}</div><div class="lv-calendar-hint">Datum auswählen, um den Tagesablauf zu öffnen.</div></div>`}
function popup(date){const items=entriesForDate(date),fmt=v=>new Date(v).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'}),node=document.createElement('div');node.className='lv-timeline-modal';node.innerHTML=`<div class="lv-timeline-backdrop" data-close-timeline></div><section class="lv-timeline-sheet"><button data-close-timeline class="lv-timeline-close">×</button><span class="lv-kicker">${new Date(`${date}T12:00:00`).toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'})}</span><h2>Euer Tag</h2><div class="lv-day-timeline">${items.length?items.map((e,i)=>`<article class="lv-day-entry"><div class="lv-day-time">${fmt(e.startAt)}</div><div class="lv-day-line"><i></i></div><div class="lv-day-place"><span>${e.icon}</span><div><strong>${e.title}</strong><small>${e.durationMinutes?`${Math.round(e.durationMinutes)} Min. Aufenthalt`:e.automatic?'Automatisch per GPS erkannt':'Geplant'}</small></div></div>${i<items.length-1?`<div class="lv-day-transfer">↳ Weiter zum nächsten Ort</div>`:''}</article>`).join(''):'<p>Noch keine Einträge für diesen Tag.</p>'}</div></section>`;document.body.appendChild(node);node.querySelectorAll('[data-close-timeline]').forEach(x=>x.onclick=()=>node.remove());return node}
function bindCalendar(root=document){root.querySelectorAll('[data-timeline-date]').forEach(b=>b.onclick=()=>popup(b.dataset.timelineDate))}
function subscribeRealtime(tripId=state.tripId){channels.forEach(c=>{try{client()?.removeChannel(c)}catch{}});channels=[];const db=client();if(!db||!tripId)return false;for(const table of ['trip_schedule_events','timeline_events','place_visits'])channels.push(db.channel(`timeline-v5:${table}:${tripId}`).on('postgres_changes',{event:'*',schema:'public',table,filter:`trip_id=eq.${tripId}`},()=>hydrate(tripId).catch(()=>{})).subscribe());return true}
function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
async function init(){const id=activeTripId();await hydrate(id).catch(()=>{});subscribeRealtime(id);return diagnostics()}
function diagnostics(){return{version:VERSION,status:'ready',cloudAuthoritative:true,localPersistence:false,tripId:state.tripId,eventCount:state.entries.length,days:state.days.length,realtimeChannels:channels.length,lastError:state.lastError}}
window.addEventListener('luvia:trip-changed',e=>{const id=e.detail?.tripId||activeTripId();hydrate(id).then(()=>subscribeRealtime(id)).catch(()=>{})});window.addEventListener('luvia:place-plan-changed',()=>hydrate().catch(()=>{}));window.addEventListener('luvia:place-visit-changed',()=>hydrate().catch(()=>{}));
window.LuviaTimelineCore=Object.freeze({version:VERSION,init,hydrate,record,snapshot,entriesForDate,renderCalendar,bindCalendar,popup,subscribe,diagnostics});
})();
