(function(){
'use strict';
const VERSION='4.2.0.1';
let events=[];let realtime=null;let activeTripId=null;const metrics={created:0,loaded:0,synced:0,failed:0,lastError:null};
const now=()=>new Date().toISOString();
const id=()=>{try{return crypto.randomUUID();}catch{return`timeline-${Date.now()}-${Math.random().toString(36).slice(2)}`;}};
const client=()=>window.LuviaSupabaseService?.getClient?.()||window.ParisSupabaseClient||window.ParisCloud?.client||null;
function normalize(raw={}){return Object.freeze({id:raw.id||id(),tripId:raw.tripId||null,placeId:raw.placeId||null,participantId:raw.participantId||null,type:raw.type||'place_event',title:raw.title||'Reiseereignis',description:raw.description||'',occurredAt:raw.occurredAt||now(),source:raw.source||'manual',automatic:Boolean(raw.automatic),metadata:{...(raw.metadata||{})},createdAt:raw.createdAt||now()});}
function fromRow(row){return normalize({id:row.id,tripId:row.trip_id,placeId:row.place_id,participantId:row.participant_id,type:row.event_type,title:row.title,description:row.description,occurredAt:row.occurred_at,source:row.source,automatic:row.is_automatic,metadata:row.metadata,createdAt:row.created_at});}
function replaceAll(rows){events=(rows||[]).map(fromRow).sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt));metrics.loaded=events.length;emit();return events;}
function emit(){window.dispatchEvent(new CustomEvent('luvia:timeline-cloud-changed',{detail:{tripId:activeTripId,events:list({tripId:activeTripId})}}));}
async function hydrate(tripId=activeTripId){activeTripId=tripId||activeTripId;if(!activeTripId){events=[];emit();return[];}const db=client();if(!db?.from)throw new Error('Keine Cloud-Verbindung für Timeline verfügbar.');const {data,error}=await db.from('timeline_events').select('*').eq('trip_id',activeTripId).order('occurred_at',{ascending:true});if(error){metrics.failed++;metrics.lastError=error.message;throw error;}metrics.lastError=null;return replaceAll(data||[]);}
async function record(raw={}){const event=normalize(raw);if(!event.tripId)throw new Error('Timeline-Ereignis benötigt eine Trip-ID.');const db=client();if(!db?.from)throw new Error('Keine Cloud-Verbindung für Timeline verfügbar.');const row={id:event.id,trip_id:event.tripId,place_id:event.placeId,participant_id:event.participantId,event_type:event.type,title:event.title,description:event.description,occurred_at:event.occurredAt,source:event.source,is_automatic:event.automatic,metadata:event.metadata,created_at:event.createdAt};const {data,error}=await db.from('timeline_events').upsert(row,{onConflict:'id'}).select().single();if(error){metrics.failed++;metrics.lastError=error.message;throw error;}metrics.created++;metrics.synced++;metrics.lastError=null;const saved=fromRow(data);events=[...events.filter(x=>x.id!==saved.id),saved].sort((a,b)=>a.occurredAt.localeCompare(b.occurredAt));emit();await window.LuviaKernelEvents?.emit?.('timeline.event.created',saved,{service:'timeline'});return saved;}
function list(filters={}){return events.filter(e=>(!filters.tripId||e.tripId===filters.tripId)&&(!filters.placeId||e.placeId===filters.placeId)&&(!filters.type||e.type===filters.type)).sort((a,b)=>b.occurredAt.localeCompare(a.occurredAt));}
async function flush(){return hydrate(activeTripId);}
function subscribe(tripId){const db=client();if(!db||!tripId)return false;if(realtime){try{db.removeChannel(realtime);}catch{}}activeTripId=tripId;realtime=db.channel(`timeline-cloud:${tripId}`).on('postgres_changes',{event:'*',schema:'public',table:'timeline_events',filter:`trip_id=eq.${tripId}`},()=>hydrate(tripId).catch(error=>{metrics.lastError=error.message;})).subscribe();return true;}
async function init(){activeTripId=window.LuviaTripContext?.getActiveTrip?.()?.tripId||window.LuviaTripStore?.snapshot?.()?.activeTripId||null;if(activeTripId){await hydrate(activeTripId);subscribe(activeTripId);}return diagnostics();}
function diagnostics(){return{version:VERSION,status:'ready',cloudAuthoritative:true,localPersistence:false,eventCount:events.length,realtime:Boolean(realtime),metrics:{...metrics},recent:list().slice(0,20)};}
window.addEventListener('luvia:trip-changed',e=>{const id=e.detail?.tripId||window.LuviaTripContext?.getActiveTrip?.()?.tripId||null;if(id){hydrate(id).then(()=>subscribe(id)).catch(error=>{metrics.lastError=error.message;});}});
window.LuviaTimelineCore=Object.freeze({version:VERSION,init,hydrate,record,list,flush,subscribe,diagnostics});
})();
