(() => {
'use strict';
const VERSION='5.3.0';
let state={tripId:null,loading:false,hydrated:false,entries:[],days:[],lastUpdatedAt:null,lastError:null,members:{},places:{}};
let channels=[];const listeners=new Set();
const clone=v=>v==null?v:JSON.parse(JSON.stringify(v));
const client=()=>window.LuviaSupabaseService?.getClient?.()||window.ParisSupabaseClient||window.ParisCloud?.client||null;
const activeTripId=()=>window.LuviaTripContext?.getActiveTrip?.()?.tripId||window.LuviaTripStore?.snapshot?.()?.activeTripId||null;
const iso=(d,t='00:00')=>new Date(`${d}T${String(t||'00:00').slice(0,5)}:00`).toISOString();
const dayKey=v=>new Date(v).toLocaleDateString('sv-SE');
const typeIcon=t=>({restaurant:'🍽️',accommodation:'🏨',attraction:'🏛️',activity:'🎟️',photo_spot:'📸',parking:'🅿️',charging:'🔌',shopping:'🛍️',mobility:'🚉'}[t]||'📍');
const fmtTime=v=>new Date(v).toLocaleTimeString('de-DE',{hour:'2-digit',minute:'2-digit'});
const fmtDate=v=>new Date(v).toLocaleDateString('de-DE',{day:'2-digit',month:'2-digit',year:'numeric'});
function scheduleEntry(r){const start=iso(r.event_date,r.start_time),duration=Number(r.duration_minutes||0);return{id:`schedule:${r.id}`,rowId:r.id,sourceKey:r.source_key,tripId:r.trip_id,placeId:r.place_id,tripPlaceId:r.trip_place_id,providerPlaceId:r.provider_place_id,entityType:r.entity_type||'place',kind:/check-in/i.test(r.title)?'check_in':/check-out/i.test(r.title)?'check_out':'planned',title:r.title,startAt:start,endAt:r.end_time?iso(r.event_date,r.end_time):(duration?new Date(new Date(start).getTime()+duration*60000).toISOString():null),durationMinutes:duration||null,automatic:false,source:'schedule',metadata:r.metadata||{},icon:typeIcon(r.entity_type)}}
function dataEntry(e){return{id:e.id,rowId:null,sourceKey:e.id,tripId:e.tripId,placeId:e.placeId,tripPlaceId:e.tripPlaceId,providerPlaceId:e.record?.place?.provider_place_id||null,entityType:e.placeType,kind:e.kind,title:e.title,startAt:e.startAt,endAt:null,durationMinutes:null,automatic:false,source:'place-data',dataKey:e.dataKey,fields:e.fields||{},metadata:{placeName:e.record?.place?.name||''},icon:typeIcon(e.placeType)}}
function eventEntry(r){return{id:`event:${r.id}`,rowId:r.id,sourceKey:r.id,tripId:r.trip_id,placeId:r.place_id,tripPlaceId:r.trip_place_id||r.metadata?.tripPlaceId,entityType:r.metadata?.placeType||'place',kind:r.event_type,title:r.title,startAt:r.occurred_at,endAt:null,durationMinutes:null,automatic:Boolean(r.is_automatic),source:'event',metadata:r.metadata||{},icon:typeIcon(r.metadata?.placeType)}}
function visitEntry(r){const p=state.places[r.place_id]||{},name=state.members[r.participant_id]||'Mitreisender';return{id:`visit:${r.id}`,rowId:r.id,sourceKey:r.id,tripId:r.trip_id,placeId:r.place_id,tripPlaceId:r.trip_place_id,providerPlaceId:p.provider_place_id,entityType:p.primary_type||r.metadata?.placeType||'place',kind:'visited',title:p.name||r.metadata?.placeName||'Besuchter Ort',startAt:r.arrived_at,endAt:r.left_at,durationMinutes:Math.max(5,Math.round(Number(r.duration_seconds||0)/60)),automatic:true,source:'gps',participantId:r.participant_id,participantName:name,metadata:r.metadata||{},icon:typeIcon(p.primary_type)}}
function dedupe(list){const seen=new Map();for(const e of list){const key=e.source==='place-data'?`pd:${e.tripPlaceId}:${e.dataKey}`:e.source==='schedule'?`s:${e.sourceKey}`:e.source==='gps'?`v:${e.sourceKey}`:`e:${e.sourceKey}`;seen.set(key,e)}return [...seen.values()].sort((a,b)=>new Date(a.startAt)-new Date(b.startAt))}
function buildDays(entries){const map=new Map();for(const e of entries){const key=dayKey(e.startAt);if(!map.has(key))map.set(key,[]);map.get(key).push(e)}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([date,items])=>({date,items,hasAutomatic:items.some(x=>x.automatic),count:items.length}))}
function emit(){state.days=buildDays(state.entries);state.lastUpdatedAt=new Date().toISOString();const snap=snapshot();listeners.forEach(fn=>{try{fn(snap)}catch{}});window.dispatchEvent(new CustomEvent('luvia:timeline-changed',{detail:snap}));window.dispatchEvent(new CustomEvent('luvia:timeline-cloud-changed',{detail:snap}))}
async function hydrate(tripId=activeTripId()){
 state.tripId=tripId||null;state.loading=true;state.hydrated=false;state.lastError=null;
 if(!tripId){state.entries=[];state.loading=false;state.hydrated=true;emit();return snapshot()}
 const database=client();if(!database?.from){state.loading=false;state.lastError='Keine Cloud-Verbindung für Timeline verfügbar.';emit();throw new Error(state.lastError)}
 try{
  await window.LuviaTripPlaceData?.hydrate?.(tripId);
  const [scheduleRows,eventRows,visitRows,tripPlaces,members]=await Promise.all([
   database.from('trip_schedule_events').select('*').eq('trip_id',tripId).order('event_date').order('start_time'),
   database.from('timeline_events').select('*').eq('trip_id',tripId).order('occurred_at'),
   database.from('place_visits').select('*').eq('trip_id',tripId).order('arrived_at'),
   database.from('trip_places').select('id,place_id,module_key,status').eq('trip_id',tripId).neq('status','archived'),
   database.from('trip_members').select('*').eq('trip_id',tripId)
  ]);
  for(const result of [scheduleRows,eventRows,visitRows,tripPlaces,members])if(result.error)throw result.error;
  const linked=new Set((tripPlaces.data||[]).map(x=>x.place_id).filter(Boolean));
  const placeIds=[...new Set([...(scheduleRows.data||[]).map(x=>x.place_id),...(visitRows.data||[]).map(x=>x.place_id)].filter(Boolean))];state.places={};
  if(placeIds.length){const pr=await database.from('places').select('*').in('id',placeIds);if(pr.error)throw pr.error;for(const place of pr.data||[])state.places[place.id]=place}
  state.members={};for(const member of members.data||[]){const id=member.user_id||member.participant_id||member.id,name=member.display_name||member.member_name||member.name||member.email||'Mitreisender';state.members[id]=name;state.members[member.id]=name}
  const allowedEvents=new Set(['place_visited','manual_note','memory','trip_moment']);
  const validVisits=(visitRows.data||[]).filter(x=>linked.has(x.place_id)&&x.arrived_at&&Number(x.duration_seconds||0)>=300&&['visited','left'].includes(x.state));
  const placeData=window.LuviaTripPlaceData?.dateEntries?.()||[];
  const schedule=(scheduleRows.data||[]).filter(row=>String(row.entity_type)!=='accommodation');
  state.entries=dedupe([...placeData.map(dataEntry),...schedule.map(scheduleEntry),...(eventRows.data||[]).filter(x=>allowedEvents.has(x.event_type)).map(eventEntry),...validVisits.map(visitEntry)]);
  state.loading=false;state.hydrated=true;emit();return snapshot();
 }catch(error){state.loading=false;state.hydrated=false;state.lastError=error.message||String(error);emit();throw error}
}
async function record(raw={}){const db=client(),tripId=raw.tripId||state.tripId||activeTripId();if(!db?.from||!tripId)throw new Error('Timeline-Cloud nicht verfügbar.');const row={trip_id:tripId,place_id:raw.placeId||null,participant_id:raw.participantId||null,event_type:raw.type||'manual_note',title:raw.title||'Reiseereignis',description:raw.description||'',occurred_at:raw.occurredAt||new Date().toISOString(),source:raw.source||'manual',is_automatic:Boolean(raw.automatic),metadata:raw.metadata||{}};const {error}=await db.from('timeline_events').insert(row);if(error)throw error;return hydrate(tripId)}
async function removeEntry(identity,{tripId=state.tripId||activeTripId()}={}){
 const entry=typeof identity==='string'?state.entries.find(item=>String(item.id)===String(identity)):identity;
 if(!entry||!tripId)throw new Error('Timeline-Eintrag wurde nicht gefunden.');
 const database=client();if(!database?.from)throw new Error('Keine Cloud-Verbindung für Timeline verfügbar.');
 if(entry.source==='place-data'){
  if(!entry.tripPlaceId||!entry.dataKey)throw new Error('Der Place-Datensatz ist unvollständig.');
  await window.LuviaTripPlaceData.updateDateFields(entry.tripPlaceId,{[entry.dataKey]:null},{tripId});
 }else if(entry.source==='schedule'){
  let query=database.from('trip_schedule_events').delete().eq('trip_id',tripId);
  if(entry.rowId)query=query.eq('id',entry.rowId);else if(entry.sourceKey)query=query.eq('source_key',entry.sourceKey);else throw new Error('Der Cloud-Schlüssel des Planeintrags fehlt.');
  const {error}=await query;if(error)throw error;
 }else if(entry.source==='event'){
  const {error}=await database.from('timeline_events').delete().eq('trip_id',tripId).eq('id',entry.rowId);if(error)throw error;
 }else if(entry.source==='gps'){
  const {error}=await database.from('place_visits').delete().eq('trip_id',tripId).eq('id',entry.rowId);if(error)throw error;
 }
 await Promise.all([hydrate(tripId),window.LuviaScheduleIntelligence?.refresh?.({tripId,force:true,skipThrottle:true})]);
 window.dispatchEvent(new CustomEvent('luvia:place-plan-changed',{detail:{tripId,type:entry.entityType,tripPlaceId:entry.tripPlaceId,removed:true}}));
 window.dispatchEvent(new CustomEvent('luvia:in-window-data-changed',{detail:{tripId,placeType:entry.entityType,tripPlaceId:entry.tripPlaceId,removed:true}}));
 return true;
}
async function clearEntries({entityType,tripId=state.tripId||activeTripId()}={}){
 const entries=state.entries.filter(entry=>!entityType||entry.entityType===entityType).filter(entry=>['place-data','schedule'].includes(entry.source));
 for(const entry of entries)await removeEntry(entry,{tripId});
 return snapshot();
}
function snapshot(){return clone(state)}
function list(filter={}){return state.entries.filter(e=>(!filter.tripId||String(e.tripId)===String(filter.tripId))&&(!filter.entityType||e.entityType===filter.entityType))}
function entriesForDate(date){return state.entries.filter(e=>dayKey(e.startAt)===date)}
function dateRange(trip){const start=new Date(trip?.startDate||state.days[0]?.date||new Date()),end=new Date(trip?.endDate||state.days.at(-1)?.date||start),out=[];for(let d=new Date(start);d<=end;d.setDate(d.getDate()+1))out.push(new Date(d));return out.slice(0,62)}
function renderCalendar(trip,esc=s=>String(s)){const range=dateRange(trip),marked=new Map(state.days.map(d=>[d.date,d]));return `<div class="lv-trip-calendar"><div class="lv-widget-title"><div><h2>Reise-Timeline</h2><small>Alle geplanten und tatsächlich besuchten Orte aus der Cloud.</small></div><span>${state.entries.length} Einträge</span></div><div class="lv-calendar-grid">${range.map((d,index)=>{const key=d.toLocaleDateString('sv-SE'),day=marked.get(key);return `<button type="button" class="lv-calendar-day ${day?'has-events':''} ${index>=7?'is-calendar-hidden':''}" data-timeline-date="${key}"><span>${d.toLocaleDateString('de-DE',{weekday:'short'})}</span><strong>${d.getDate()}</strong><small>${d.toLocaleDateString('de-DE',{month:'short'})}</small>${day?`<em>${day.count}</em>`:''}</button>`}).join('')}</div>${range.length>7?`<button type="button" class="lv-calendar-more" data-timeline-more>Weitere Tage anzeigen</button>`:''}<div class="lv-calendar-hint">Datum auswählen, um den Tagesablauf zu öffnen.</div></div>`}
function stayText(e,allItems){if(e.kind==='check_in'){const out=state.entries.find(x=>x.kind==='check_out'&&x.tripPlaceId===e.tripPlaceId&&new Date(x.startAt)>=new Date(e.startAt));return out?`Aufenthalt bis ${fmtDate(out.startAt)}, ${fmtTime(out.startAt)} Uhr`:'Check-out noch offen'}if(e.kind==='check_out')return 'Ende des Aufenthalts';if(e.source==='gps')return `${e.durationMinutes||5} Min. Aufenthalt · GPS · ${e.participantName}`;return e.durationMinutes?`${Math.round(e.durationMinutes)} Min. geplant`:'Geplant'}
function openPlace(e){window.dispatchEvent(new CustomEvent('luvia:open-place-request',{detail:{type:e.entityType,placeId:e.placeId,tripPlaceId:e.tripPlaceId,title:String(e.title||'').replace(/^.*?·\s*/,''),returnView:'timeline',overlayOnly:true}}))}
const dateInput=(key,label,value)=>`<label>${label}<input type="datetime-local" data-field="${key}" value="${value?new Date(value).toLocaleString('sv-SE').replace(' ','T').slice(0,16):''}"></label>`;
function editPlaceDates(e,onDone){document.querySelectorAll('.lv-time-editor').forEach(x=>x.remove());const rec=window.LuviaTripPlaceData?.recordForTripPlace?.(e.tripPlaceId),fields=rec?.fields||e.fields||{};const defs=e.entityType==='accommodation'?[['check_in_at','Check-in'],['check_out_at','Check-out']]:e.entityType==='restaurant'?[['planned_at','Datum und Uhrzeit']]:[[e.dataKey||'planned_at','Datum und Uhrzeit']];const n=document.createElement('div');n.className='lv-timeline-modal lv-time-editor';n.innerHTML=`<div class="lv-timeline-backdrop" data-close-editor></div><section class="lv-timeline-sheet lv-time-editor-sheet"><button data-close-editor class="lv-timeline-close">×</button><span class="lv-kicker">Datum und Uhrzeit</span><h2>${e.icon||''} ${rec?.place?.name||String(e.title||'').replace(/^.*?·\s*/,'')}</h2><div class="lv-time-fields">${defs.map(([k,l])=>dateInput(k,l,fields[k])).join('')}</div><button class="lv-primary" data-save-time>Änderungen speichern</button></section>`;document.body.appendChild(n);n.querySelectorAll('[data-close-editor]').forEach(x=>x.onclick=()=>n.remove());n.querySelector('[data-save-time]').onclick=async()=>{const updates={};n.querySelectorAll('[data-field]').forEach(i=>updates[i.dataset.field]=i.value?new Date(i.value).toISOString():null);await window.LuviaTripPlaceData.updateDateFields(e.tripPlaceId,updates,{tripId:state.tripId});n.remove();await hydrate(state.tripId);window.dispatchEvent(new CustomEvent('luvia:place-plan-changed',{detail:{tripId:state.tripId,type:e.entityType,tripPlaceId:e.tripPlaceId}}));window.dispatchEvent(new CustomEvent('luvia:in-window-data-changed',{detail:{tripId:state.tripId,placeType:e.entityType,tripPlaceId:e.tripPlaceId}}));onDone?.()}}
function editLegacySchedule(e,onDone){document.querySelectorAll('.lv-time-editor').forEach(x=>x.remove());const n=document.createElement('div');n.className='lv-timeline-modal lv-time-editor';n.innerHTML=`<div class="lv-timeline-backdrop" data-close-editor></div><section class="lv-timeline-sheet lv-time-editor-sheet"><button data-close-editor class="lv-timeline-close">×</button><span class="lv-kicker">Datum und Uhrzeit</span><h2>${e.icon||''} ${e.title||'Datum und Uhrzeit'}</h2><label>Datum<input type="date" data-edit-date value="${dayKey(e.startAt)}"></label><label>Uhrzeit<input type="time" data-edit-time value="${fmtTime(e.startAt)}"></label><button class="lv-primary" data-save-time>Änderung speichern</button></section>`;document.body.appendChild(n);n.querySelectorAll('[data-close-editor]').forEach(x=>x.onclick=()=>n.remove());n.querySelector('[data-save-time]').onclick=async()=>{const d=n.querySelector('[data-edit-date]').value,t=n.querySelector('[data-edit-time]').value;if(!d||!t)return;const {error}=await client().from('trip_schedule_events').update({event_date:d,start_time:t,updated_at:new Date().toISOString()}).eq('id',e.rowId).eq('trip_id',state.tripId);if(error){alert(error.message);return}n.remove();await hydrate(state.tripId);window.dispatchEvent(new CustomEvent('luvia:place-plan-changed',{detail:{tripId:state.tripId,type:e.entityType,tripPlaceId:e.tripPlaceId}}));onDone?.()}}
function editEntry(e,onDone){return e.source==='place-data'?editPlaceDates(e,onDone):editLegacySchedule(e,onDone)}
function popup(date){const items=entriesForDate(date),node=document.createElement('div');node.className='lv-timeline-modal';node.innerHTML=`<div class="lv-timeline-backdrop" data-close-timeline></div><section class="lv-timeline-sheet"><button data-close-timeline class="lv-timeline-close">×</button><span class="lv-kicker">${new Date(`${date}T12:00:00`).toLocaleDateString('de-DE',{weekday:'long',day:'2-digit',month:'long'})}</span><h2>Euer Tag</h2><div class="lv-day-timeline">${items.length?items.map((e,i)=>`<article class="lv-day-entry"><div class="lv-day-time">${fmtTime(e.startAt)}</div><div class="lv-day-line"><i></i></div><button type="button" class="lv-day-place" data-open-entry="${e.id}"><span>${e.icon}</span><div><strong>${e.title}</strong><small>${stayText(e,items)}</small>${e.source==='gps'?`<em>GPS · ${e.participantName}</em>`:''}</div></button><div class="lv-day-entry-actions"><button type="button" data-open-entry="${e.id}">Place öffnen</button>${['schedule','place-data'].includes(e.source)?`<button type="button" data-edit-entry="${e.id}">Datum und Uhrzeit ändern</button>`:''}</div>${i<items.length-1?`<div class="lv-day-transfer">↳ Weiter zum nächsten Ort</div>`:''}</article>`).join(''):'<p>Noch keine Einträge für diesen Tag.</p>'}</div></section>`;document.body.appendChild(node);node.querySelectorAll('[data-close-timeline]').forEach(x=>x.onclick=()=>node.remove());node.querySelectorAll('[data-open-entry]').forEach(x=>x.onclick=ev=>{ev.preventDefault();ev.stopPropagation();const e=items.find(v=>v.id===x.dataset.openEntry);if(e)openPlace(e)});node.querySelectorAll('[data-edit-entry]').forEach(x=>x.onclick=ev=>{ev.preventDefault();ev.stopPropagation();const e=items.find(v=>v.id===x.dataset.editEntry);if(e)editEntry(e,()=>{node.remove();popup(dayKey(e.startAt))})});return node}
function bindCalendar(root=document){root.querySelectorAll('[data-timeline-date]').forEach(b=>b.onclick=()=>popup(b.dataset.timelineDate));root.querySelectorAll('[data-timeline-more]').forEach(button=>button.onclick=()=>{const calendar=button.closest('.lv-trip-calendar'),hidden=[...calendar.querySelectorAll('.lv-calendar-day.is-calendar-hidden')];hidden.slice(0,7).forEach(day=>day.classList.remove('is-calendar-hidden'));if(hidden.length<=7)button.remove()})}
function subscribeRealtime(tripId=state.tripId){channels.forEach(c=>{try{client()?.removeChannel(c)}catch{}});channels=[];const db=client();if(!db||!tripId)return false;for(const table of ['trip_schedule_events','timeline_events','place_visits','trip_place_data'])channels.push(db.channel(`timeline-v52:${table}:${tripId}`).on('postgres_changes',{event:'*',schema:'public',table,filter:`trip_id=eq.${tripId}`},()=>hydrate(tripId).catch(()=>{})).subscribe());return true}
function subscribe(fn){listeners.add(fn);return()=>listeners.delete(fn)}
async function init(){const id=activeTripId();await window.LuviaTripPlaceData?.init?.();await hydrate(id).catch(()=>{});subscribeRealtime(id);return diagnostics()}
function diagnostics(){return{version:VERSION,status:state.hydrated?'ready':'loading',cloudAuthoritative:true,localPersistence:false,tripId:state.tripId,hydrated:state.hydrated,loading:state.loading,eventCount:state.entries.length,days:state.days.length,realtimeChannels:channels.length,realtime:channels.length>0,metrics:{queued:0},lastError:state.lastError,placeDataSource:'trip_place_data',gpsRules:{linkedPlacesOnly:true,minStaySeconds:300,states:['visited','left']}}}
window.addEventListener('luvia:trip-changed',e=>{const id=e.detail?.tripId||activeTripId();hydrate(id).then(()=>subscribeRealtime(id)).catch(()=>{})});window.addEventListener('luvia:place-plan-changed',()=>hydrate().catch(()=>{}));window.addEventListener('luvia:place-visit-changed',()=>hydrate().catch(()=>{}));
window.LuviaTimelineCore=Object.freeze({version:VERSION,init,hydrate,record,removeEntry,clearEntries,snapshot,list,entriesForDate,renderCalendar,bindCalendar,popup,editEntry,subscribe,diagnostics});
})();