(()=>{
'use strict';
const VERSION='1.0.0';
let target=null,selectedTripId=null,selectedBookingId=null,bookings=[],threads=[],conversation=null,loading=false,error=null,filter='all',memorySeen={};
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ATTENTION=new Set(['needs_action','requires_action','review_required','alternative_proposed','blocked','failed']);
const STATUS_LABEL={draft:'Entwurf',ready:'Bereit',requested:'Angefragt',awaiting_reply:'Antwort ausstehend',confirmed:'Bestätigt',declined:'Abgelehnt',needs_action:'Aktion nötig',requires_action:'Aktion nötig',review_required:'Prüfung nötig',alternative_proposed:'Alternative vorgeschlagen',blocked:'Blockiert',cancelled:'Storniert',failed:'Fehler',completed:'Abgeschlossen'};
const TYPE_ICON={restaurant:'🍽',hotel:'▦',activity:'◇',event:'◇',transport:'↗',rental:'⌂',other:'✦'};
const clean=v=>String(v??'').trim();
const fmt=v=>{if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
const tripSnapshot=()=>window.LuviaTripStore?.snapshot?.()||{};
const tripList=()=>{const s=tripSnapshot();return Array.isArray(s.trips)?s.trips:Array.isArray(s.items)?s.items:[]};
const tripId=t=>t?.id||t?.tripId||null;const tripTitle=t=>t?.title||t?.name||t?.destination?.name||'Reise';
const activeTripId=()=>tripSnapshot().activeTripId||tripId(tripSnapshot().activeTrip)||window.LuviaControlCenterTravelIdentity?.snapshot?.()?.activeTrip?.id||null;
function seenKey(id){return `luvia.booking-inbox.seen.${id}`}
function getSeen(id){try{return localStorage.getItem(seenKey(id))||memorySeen[id]||null}catch{return memorySeen[id]||null}}
function markSeen(id,at){const value=at||new Date().toISOString();memorySeen[id]=value;try{localStorage.setItem(seenKey(id),value)}catch{}return value}
function isUnread(t){if(!t.lastInboundAt)return false;const seen=getSeen(t.id);return !seen||new Date(t.lastInboundAt)>new Date(seen)}
function intelligenceLabel(i){const intent=String(i?.intent||'').toLowerCase();return({confirmed:'Bestätigung erkannt',declined:'Absage erkannt',alternative_proposed:'Alternative erkannt',needs_action:'Rückfrage erkannt',informational:'Information erkannt',unknown:'Antwort prüfen'}[intent]||'Luvia Intelligence')}
function normalizeBooking(b){return {...b,id:b.id||b.booking_id,booking_type:b.booking_type||'other',status:clean(b.status||'draft').toLowerCase()}}
async function loadThreadSummary(b){const api=window.LuviaBookingIntegration||window.LuviaBooking;const c=await api.conversation(b.id);const msgs=c.messages||[];const inbound=msgs.filter(m=>m.direction==='inbound');const last=msgs[msgs.length-1]||null;const intel=(c.intelligence||[]).find(i=>i.review_required||i.requires_user_action)||(c.intelligence||[])[0]||null;const t={id:b.id,booking:b,messageCount:msgs.length,lastMessage:last,lastInboundAt:inbound[inbound.length-1]?.received_at||inbound[inbound.length-1]?.created_at||null,intelligence:intel,thread:c.thread||null};t.unread=isUnread(t);t.attention=ATTENTION.has(b.status)||Boolean(intel?.review_required||intel?.requires_user_action);return t}
async function load(){if(!target)return;loading=true;error=null;render();try{const api=window.LuviaBookingIntegration||window.LuviaBooking;if(!api?.listForTrip||!api?.conversation)throw new Error('Booking Message Capability ist nicht verfügbar.');await api.init?.();selectedTripId=selectedTripId||activeTripId();bookings=(selectedTripId?await api.listForTrip(selectedTripId):[]).map(normalizeBooking);threads=await Promise.all(bookings.map(loadThreadSummary));threads.sort((a,b)=>Number(b.attention)-Number(a.attention)||Number(b.unread)-Number(a.unread)||new Date(b.lastMessage?.created_at||b.booking.updated_at||0)-new Date(a.lastMessage?.created_at||a.booking.updated_at||0));if(selectedBookingId&&!threads.some(t=>String(t.id)===String(selectedBookingId)))selectedBookingId=null;if(!selectedBookingId&&threads.length)selectedBookingId=(threads.find(t=>t.attention)||threads.find(t=>t.unread)||threads[0]).id;if(selectedBookingId)await openConversation(selectedBookingId,false);}catch(e){error=e;threads=[];conversation=null;}finally{loading=false;render();}}
async function openConversation(id,rerender=true){selectedBookingId=id;const api=window.LuviaBookingIntegration||window.LuviaBooking;conversation=await api.conversation(id);const th=threads.find(t=>String(t.id)===String(id));if(th){markSeen(id,th.lastInboundAt||new Date().toISOString());th.unread=false}if(rerender)render();setTimeout(()=>target?.querySelector('.bi-messages')?.scrollTo?.({top:999999,behavior:'smooth'}),0)}
function filteredThreads(){return threads.filter(t=>filter==='all'||(filter==='unread'&&t.unread)||(filter==='attention'&&t.attention))}
function preview(t){const body=clean(t.lastMessage?.body_text);if(body)return body;const intel=t.intelligence;if(intel)return intelligenceLabel(intel);return t.messageCount?'Nachrichtenverlauf verfügbar':'Noch keine Nachricht'}
function threadCard(t){const b=t.booking;return `<button class="bi-thread" data-bi-thread="${esc(t.id)}" aria-current="${String(t.id)===String(selectedBookingId)}"><span class="bi-avatar">${TYPE_ICON[b.booking_type]||TYPE_ICON.other}</span><span class="bi-thread-main"><span class="bi-thread-top"><strong>${esc(b.title||'Buchung')}</strong><small>${esc(fmt(t.lastMessage?.created_at||b.updated_at))}</small></span><p>${esc(preview(t))}</p><span class="bi-thread-meta"><span class="bi-badge">${esc(STATUS_LABEL[b.status]||b.status)}</span>${t.attention?'<span class="bi-badge attn">Aktion nötig</span>':''}${t.messageCount?`<span class="bi-badge">${t.messageCount} Nachricht${t.messageCount===1?'':'en'}</span>`:''}</span></span>${t.unread?'<span class="bi-dot" title="Ungelesen"></span>':'<span></span>'}</button>`}
function message(m){const dir=m.direction||'system';const label=dir==='outbound'?'Du':dir==='inbound'?(conversation?.booking?.title||'Anbieter'):'Luvia';return `<article class="bi-msg ${esc(dir)}"><span class="bi-msg-label">${esc(label)}</span><div class="bi-bubble">${esc(m.body_text||m.subject||'Status aktualisiert')}</div><span class="bi-time">${esc(fmt(m.received_at||m.sent_at||m.created_at))}${m.delivery_status?` · ${esc(m.delivery_status)}`:''}</span></article>`}
function intelligenceCard(i){return `<aside class="bi-intel"><small>✦ Luvia Intelligence</small><strong>${esc(intelligenceLabel(i))}</strong><p>${esc(i.visible_reply||((i.review_required||i.requires_user_action)?'Diese Antwort braucht deine Entscheidung.':'Luvia hat diese Nachricht strukturiert eingeordnet.'))}</p>${i.extracted&&Object.keys(i.extracted).length?`<p><b>Erkannt:</b> ${esc(JSON.stringify(i.extracted))}</p>`:''}${(i.review_required||i.requires_user_action)?'<div class="bi-intel-actions"><button disabled>Bearbeiten ab v13.80</button></div>':''}</aside>`}
function conversationView(){if(!selectedBookingId||!conversation)return `<section class="bi-conversation"><div class="bi-empty"><strong>Unterhaltung auswählen</strong><p>Nachrichten von Restaurants, Hotels und später weiteren Anbietern erscheinen hier in einem einheitlichen Verlauf.</p></div></section>`;const b=conversation.booking||bookings.find(x=>String(x.id)===String(selectedBookingId))||{};const intelByMessage=new Map((conversation.intelligence||[]).map(i=>[String(i.message_id),i]));const content=[];(conversation.messages||[]).forEach(m=>{content.push(message(m));const i=intelByMessage.get(String(m.id));if(i)content.push(intelligenceCard(i))});return `<section class="bi-conversation"><header class="bi-conv-head"><div><small>${esc((b.booking_type||'Buchung').toUpperCase())} · ${esc(tripTitle(tripList().find(t=>String(tripId(t))===String(selectedTripId))||{}))}</small><h2>${esc(b.title||'Buchung')}</h2><p>${b.start_at?esc(fmt(b.start_at)):''}${b.party_size?` · ${esc(b.party_size)} Personen`:''}</p></div><span class="bi-status">${esc(STATUS_LABEL[b.status]||b.status||'Status')}</span></header><div class="bi-messages">${content.length?content.join(''):'<div class="bi-empty"><strong>Noch keine Nachrichten.</strong><p>Sobald über den Booking Core eine Nachricht gesendet oder empfangen wird, erscheint sie hier.</p></div>'}</div><form class="bi-composer" data-bi-composer><textarea placeholder="Nachricht schreiben …" aria-label="Nachricht schreiben"></textarea><button class="bi-send" type="submit">Senden</button><span class="bi-composer-note">Composer Foundation: Freie bidirektionale Antworten werden in v13.80 an den bestehenden Booking-Transport angebunden. Hier wird noch keine Nachricht vorgetäuscht oder lokal als gesendet gespeichert.</span></form></section>`}
function render(){if(!target)return;const trips=tripList();const list=filteredThreads();const unread=threads.filter(t=>t.unread).length,attn=threads.filter(t=>t.attention).length;target.innerHTML=`<section class="booking-inbox" aria-label="Booking Inbox"><header class="bi-hero"><div><span class="bi-kicker">Control Center · Booking Inbox</span><h1>Deine Gespräche mit Anbietern.</h1><p>Restaurant, Hotel oder später Aktivität: Luvia zeigt alle Booking-Nachrichten in einem einheitlichen, providerunabhängigen Verlauf.</p></div><button class="bi-back" type="button" data-view="control-center">← Control Center</button></header><section class="bi-toolbar"><label><span>Reise</span><select data-bi-trip>${trips.map(t=>`<option value="${esc(tripId(t))}" ${String(tripId(t))===String(selectedTripId)?'selected':''}>${esc(tripTitle(t))}</option>`).join('')}</select></label><div class="bi-chips"><button class="bi-chip ${filter==='all'?'is-active':''}" data-bi-filter="all">Alle · ${threads.length}</button><button class="bi-chip ${filter==='unread'?'is-active':''}" data-bi-filter="unread">Ungelesen · ${unread}</button><button class="bi-chip ${filter==='attention'?'is-active':''}" data-bi-filter="attention">Aktion nötig · ${attn}</button></div><button class="bi-refresh" data-bi-refresh>${loading?'Lädt …':'Aktualisieren'}</button></section>${error?`<div class="bi-state"><strong>Inbox konnte nicht geladen werden.</strong><p>${esc(error.message||error)}</p></div>`:`<div class="bi-layout"><section class="bi-list ${selectedBookingId?'is-thread-open':''}"><header class="bi-list-head"><small>Konversationen</small><h2>${list.length} Gespräch${list.length===1?'':'e'}</h2></header>${loading?'<div class="bi-state">Nachrichten werden geladen …</div>':list.length?list.map(threadCard).join(''):'<div class="bi-empty"><strong>Keine passenden Gespräche.</strong><p>Die Inbox zeigt nur echte Nachrichten aus dem bestehenden Booking Core.</p></div>'}</section>${conversationView()}</div>`}<footer class="bi-footer">Booking Inbox v13.79 · Message Truth: Booking Core · Actions & bidirektionale Antworten folgen v13.80</footer></section>`}
function click(e){const th=e.target.closest?.('[data-bi-thread]');if(th&&target?.contains(th)){openConversation(th.dataset.biThread).catch(err=>{error=err;render()});return}const f=e.target.closest?.('[data-bi-filter]');if(f&&target?.contains(f)){filter=f.dataset.biFilter;render();return}if(e.target.closest?.('[data-bi-refresh]'))load()}
function change(e){const s=e.target.closest?.('[data-bi-trip]');if(s&&target?.contains(s)){selectedTripId=s.value;selectedBookingId=null;conversation=null;load()}}
function submit(e){const form=e.target.closest?.('[data-bi-composer]');if(!form||!target?.contains(form))return;e.preventDefault();window.LuviaUIKit?.toast?.('Freie Antworten werden in v13.80 sicher an den bestehenden Booking-Transport angebunden.',{type:'info'});}
async function mount(el,options={}){if(!el)throw new Error('Booking Inbox target required');target=el;selectedTripId=options.tripId||activeTripId();selectedBookingId=options.bookingId||null;window.LuviaProductModuleRegistry?.mount?.('control-center',el,{surface:'booking-inbox'});target.addEventListener('click',click);target.addEventListener('change',change);target.addEventListener('submit',submit);await load();return diagnostics()}
function unmount(){if(target){target.removeEventListener('click',click);target.removeEventListener('change',change);target.removeEventListener('submit',submit);window.LuviaProductModuleRegistry?.unmount?.('control-center',target,{surface:'booking-inbox'})}target=null;selectedTripId=null;selectedBookingId=null;bookings=[];threads=[];conversation=null;loading=false;error=null}
function diagnostics(){return {version:VERSION,mounted:Boolean(target),selectedTripId,selectedBookingId,conversationCount:threads.length,unreadCount:threads.filter(t=>t.unread).length,actionRequiredCount:threads.filter(t=>t.attention).length,ownsMessageTruth:false,ownsBookingTruth:false,source:'booking-core',providerIndependent:true,composerTransport:'planned-v13.80',loading,error:error?.message||null}}
window.LuviaBookingInbox=Object.freeze({version:VERSION,mount,unmount,load,render,diagnostics});
})();
