(()=>{
'use strict';
const VERSION='1.2.0';
let target=null,selectedTripId=null,selectedBookingId=null,bookings=[],threads=[],conversation=null,loading=false,error=null,filter='all',memorySeen={},preferences=new Map(),actionBusy=false,composerStatus='';
const isMobile=()=>Boolean(window.matchMedia?.('(max-width: 780px)')?.matches);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ATTENTION=new Set(['needs_action','requires_action','review_required','alternative_proposed','blocked','failed']);
const STATUS_LABEL={draft:'Entwurf',ready:'Bereit',requested:'Angefragt',awaiting_reply:'Antwort ausstehend',confirmed:'Bestätigt',declined:'Abgelehnt',needs_action:'Aktion nötig',requires_action:'Aktion nötig',review_required:'Prüfung nötig',alternative_proposed:'Alternative vorgeschlagen',blocked:'Blockiert',cancelled:'Storniert',failed:'Fehler',completed:'Abgeschlossen'};
const TYPE_ICON={restaurant:'🍽',hotel:'▦',activity:'◇',event:'◇',transport:'↗',rental:'⌂',other:'✦'};
const clean=v=>String(v??'').trim();
const fmt=v=>{if(!v)return'';const d=new Date(v);if(Number.isNaN(d.getTime()))return String(v);return new Intl.DateTimeFormat('de-DE',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)};
const tripContract=()=>window.LuviaTripContractV1||window.LuviaTripContract||null;
const bookingContract=()=>window.LuviaBookingContractV1||(()=>{throw new Error('Booking Contract v1 fehlt.')})();
const tripList=()=>{const trips=tripContract()?.listTrips?.();return Array.isArray(trips)?trips:[]};
const tripId=t=>t?.id||t?.tripId||null;const tripTitle=t=>t?.title||t?.name||t?.destination?.name||'Reise';
const activeTripId=()=>tripId(tripContract()?.getActiveTrip?.())||null;
function seenKey(id){return `luvia.booking-inbox.seen.${id}`}
function getSeen(id){try{return localStorage.getItem(seenKey(id))||memorySeen[id]||null}catch{return memorySeen[id]||null}}
function markSeen(id,at){const value=at||new Date().toISOString();memorySeen[id]=value;try{localStorage.setItem(seenKey(id),value)}catch{}return value}
function isUnread(t){if(!t.lastInboundAt)return false;const seen=t.preference?.last_read_at||t.preference?.lastReadAt||getSeen(t.id);return !seen||new Date(t.lastInboundAt)>new Date(seen)}
function intelligenceLabel(i){const intent=String(i?.intent||'').toLowerCase();return({confirmed:'Bestätigung erkannt',declined:'Absage erkannt',alternative_proposed:'Alternative erkannt',needs_action:'Rückfrage erkannt',informational:'Information erkannt',unknown:'Antwort prüfen'}[intent]||'Luvia Intelligence')}
function normalizeBooking(b){return {...b,id:b.id||b.booking_id,booking_type:b.booking_type||'other',status:clean(b.status||'draft').toLowerCase()}}
function isOpenIntel(i){return Boolean(i&&(i.review_state==='open'||((i.review_state==null||i.review_state==='')&&(i.review_required||i.requires_user_action))))}
async function loadThreadSummary(b){const c=await bookingContract().reads.conversation(b.id);const msgs=c.messages||[];const inbound=msgs.filter(m=>m.direction==='inbound');const last=msgs[msgs.length-1]||null;const intel=(c.intelligence||[]).find(isOpenIntel)||(c.intelligence||[])[0]||null;const preference=preferences.get(String(b.id))||null;const t={id:b.id,booking:b,messageCount:msgs.length,lastMessage:last,lastInboundAt:inbound[inbound.length-1]?.received_at||inbound[inbound.length-1]?.created_at||null,intelligence:intel,thread:c.thread||null,preference,archived:Boolean(preference?.archived_at||preference?.archivedAt),deleted:Boolean(preference?.deleted_at||preference?.deletedAt)};t.unread=isUnread(t);t.attention=ATTENTION.has(b.status)||Boolean(isOpenIntel(intel));return t}
async function load(){if(!target)return;loading=true;error=null;render();try{const api=bookingContract();await api.init?.();selectedTripId=selectedTripId||activeTripId();bookings=(selectedTripId?await api.reads.listForTrip(selectedTripId):[]).map(normalizeBooking);preferences=new Map();if(api.reads.conversationPreferences&&bookings.length){const prefRows=await api.reads.conversationPreferences(bookings.map(b=>b.id));for(const p of prefRows||[])preferences.set(String(p.booking_id||p.bookingId),p)}threads=await Promise.all(bookings.map(loadThreadSummary));threads.sort((a,b)=>Number(b.attention)-Number(a.attention)||Number(b.unread)-Number(a.unread)||new Date(b.lastMessage?.created_at||b.booking.updated_at||0)-new Date(a.lastMessage?.created_at||a.booking.updated_at||0));if(selectedBookingId&&!threads.some(t=>String(t.id)===String(selectedBookingId)))selectedBookingId=null;if(!selectedBookingId&&threads.length&&!isMobile()){const visible=threads.filter(t=>!t.deleted&&!t.archived);selectedBookingId=(visible.find(t=>t.attention)||visible.find(t=>t.unread)||visible[0]||{}).id||null;}if(selectedBookingId)await openConversation(selectedBookingId,false);else conversation=null;}catch(e){error=e;threads=[];conversation=null;}finally{loading=false;render();}}
async function openConversation(id,rerender=true){selectedBookingId=id;const api=bookingContract();conversation=await api.reads.conversation(id);const th=threads.find(t=>String(t.id)===String(id));if(th){const at=th.lastInboundAt||new Date().toISOString();markSeen(id,at);th.unread=false;try{if(api.commands.setConversationPreference){const pref=await api.commands.setConversationPreference(id,'read',at);th.preference={...(th.preference||{}),last_read_at:pref?.lastReadAt||at};preferences.set(String(id),th.preference)}}catch(e){console.warn('[Booking Inbox] read state',e)}}if(rerender)render();setTimeout(()=>target?.querySelector('.bi-messages')?.scrollTo?.({top:999999,behavior:'smooth'}),0)}
function filteredThreads(){return threads.filter(t=>{if(t.deleted)return false;if(filter==='archive')return t.archived;if(t.archived)return false;return filter==='all'||(filter==='unread'&&t.unread)||(filter==='attention'&&t.attention)})}
function preview(t){const body=clean(t.lastMessage?.body_text);if(body)return body;const intel=t.intelligence;if(intel)return intelligenceLabel(intel);return t.messageCount?'Nachrichtenverlauf verfügbar':'Noch keine Nachricht'}
function threadCard(t){const b=t.booking;return `<button class="bi-thread ${t.archived?'is-archived':''}" data-bi-thread="${esc(t.id)}" aria-current="${String(t.id)===String(selectedBookingId)}"><span class="bi-avatar">${TYPE_ICON[b.booking_type]||TYPE_ICON.other}</span><span class="bi-thread-main"><span class="bi-thread-top"><strong>${esc(b.title||'Buchung')}</strong><small>${esc(fmt(t.lastMessage?.created_at||b.updated_at))}</small></span><p>${esc(preview(t))}</p><span class="bi-thread-meta"><span class="bi-badge">${esc(STATUS_LABEL[b.status]||b.status)}</span>${t.attention?'<span class="bi-badge attn">Aktion nötig</span>':''}${t.messageCount?`<span class="bi-badge">${t.messageCount} Nachricht${t.messageCount===1?'':'en'}</span>`:''}</span></span>${t.unread?'<span class="bi-dot" title="Ungelesen"></span>':'<span></span>'}</button>`}
function message(m){const dir=m.direction||'system';const label=dir==='outbound'?'Du':dir==='inbound'?(conversation?.booking?.title||'Anbieter'):'Luvia';return `<article class="bi-msg ${esc(dir)}"><span class="bi-msg-label">${esc(label)}</span><div class="bi-bubble">${esc(m.body_text||m.subject||'Status aktualisiert')}</div><span class="bi-time">${esc(fmt(m.received_at||m.sent_at||m.created_at))}${m.delivery_status?` · ${esc(m.delivery_status)}`:''}</span></article>`}
function intelActions(i){if(!isOpenIntel(i))return i.review_state==='resolved'?'<div class="bi-intel-resolved">✓ Von dir bearbeitet</div>':'';const intent=clean(i.intent).toLowerCase();if(intent==='alternative_proposed')return `<div class="bi-intel-actions"><button data-bi-intel-action="accept_alternative" data-intel-id="${esc(i.id)}" ${actionBusy?'disabled':''}>Alternative annehmen</button><button data-bi-intel-action="decline_alternative" data-intel-id="${esc(i.id)}" ${actionBusy?'disabled':''}>Ablehnen</button></div>`;if(intent==='needs_action'||i.requires_user_action)return `<div class="bi-intel-actions"><button data-bi-intel-focus="${esc(i.id)}" ${actionBusy?'disabled':''}>Antworten</button><button class="secondary" data-bi-intel-action="mark_reviewed" data-intel-id="${esc(i.id)}" ${actionBusy?'disabled':''}>Als geprüft markieren</button></div>`;return `<div class="bi-intel-actions"><button data-bi-intel-focus="${esc(i.id)}" ${actionBusy?'disabled':''}>Antworten</button><button class="secondary" data-bi-intel-action="mark_reviewed" data-intel-id="${esc(i.id)}" ${actionBusy?'disabled':''}>Als geprüft markieren</button></div>`}
function intelligenceCard(i){const ex=i.extracted||{};const recognized=ex.proposedTime?`Vorgeschlagene Zeit: ${esc(ex.proposedTime)} Uhr`:Object.keys(ex).length?esc(JSON.stringify(ex)):'';return `<aside class="bi-intel" data-intel-card="${esc(i.id)}"><small>✦ Luvia Intelligence</small><strong>${esc(intelligenceLabel(i))}</strong><p>${esc(i.visible_reply||((i.review_required||i.requires_user_action)?'Diese Antwort braucht deine Entscheidung.':'Luvia hat diese Nachricht strukturiert eingeordnet.'))}</p>${recognized?`<p><b>Erkannt:</b> ${recognized}</p>`:''}${intelActions(i)}</aside>`}
function conversationView(){if(!selectedBookingId||!conversation)return `<section class="bi-conversation"><div class="bi-empty"><strong>Unterhaltung auswählen</strong><p>Nachrichten von Restaurants, Hotels und später weiteren Anbietern erscheinen hier in einem einheitlichen Verlauf.</p></div></section>`;const b=conversation.booking||bookings.find(x=>String(x.id)===String(selectedBookingId))||{};const intelByMessage=new Map((conversation.intelligence||[]).map(i=>[String(i.message_id),i]));const content=[];(conversation.messages||[]).forEach(m=>{content.push(message(m));const i=intelByMessage.get(String(m.id));if(i)content.push(intelligenceCard(i))});return `<section class="bi-conversation"><header class="bi-conv-head"><button class="bi-mobile-inbox-back" type="button" data-bi-inbox-back aria-label="Zurück zur Inbox">← Inbox</button><div><small>${esc((b.booking_type||'Buchung').toUpperCase())} · ${esc(tripTitle(tripList().find(t=>String(tripId(t))===String(selectedTripId))||{}))}</small><h2>${esc(b.title||'Buchung')}</h2><p>${b.start_at?esc(fmt(b.start_at)):''}${b.party_size?` · ${esc(b.party_size)} Personen`:''}</p></div><div class="bi-conv-tools"><span class="bi-status">${esc(STATUS_LABEL[b.status]||b.status||'Status')}</span><button type="button" class="bi-more" data-bi-conv-menu aria-label="Conversation verwalten">•••</button><div class="bi-conv-menu"><button type="button" data-bi-pref="${threads.find(t=>String(t.id)===String(selectedBookingId))?.archived?'unarchive':'archive'}">${threads.find(t=>String(t.id)===String(selectedBookingId))?.archived?'Aus Archiv holen':'Archivieren'}</button><button type="button" class="is-danger" data-bi-pref="delete">Chat löschen</button></div></div></header><div class="bi-messages">${content.length?content.join(''):'<div class="bi-empty"><strong>Noch keine Nachrichten.</strong><p>Sobald über den Booking Core eine Nachricht gesendet oder empfangen wird, erscheint sie hier.</p></div>'}</div><form class="bi-composer" data-bi-composer><textarea placeholder="Nachricht schreiben …" aria-label="Nachricht schreiben" ${actionBusy?'disabled':''}></textarea><input type="hidden" data-bi-intel-context><button class="bi-send" type="submit" data-bi-send ${actionBusy?'disabled':''}>${actionBusy?'Wird gesendet …':'Senden'}</button><span class="bi-composer-note">Antworten werden über den bestehenden Booking-Thread versendet und erst nach bestätigtem Transport im Verlauf angezeigt.</span>${composerStatus?`<div class="bi-composer-status" role="status">${esc(composerStatus)}</div>`:''}</form></section>`}
function render(){if(!target)return;const trips=tripList();const list=filteredThreads();const activeThreads=threads.filter(t=>!t.deleted&&!t.archived);const unread=activeThreads.filter(t=>t.unread).length,attn=activeThreads.filter(t=>t.attention).length;target.innerHTML=`<section class="booking-inbox" aria-label="Booking Inbox"><header class="bi-hero"><div><span class="bi-kicker">Control Center · Booking Inbox</span><h1>Deine Gespräche mit Anbietern.</h1><p>Restaurant, Hotel oder später Aktivität: Luvia zeigt Nachrichten, Entscheidungen und Antworten in einem einheitlichen, providerunabhängigen Verlauf.</p></div><button class="bi-back" type="button" data-view="control-center">← Control Center</button></header><section class="bi-toolbar"><label><span>Reise</span><select data-bi-trip>${trips.map(t=>`<option value="${esc(tripId(t))}" ${String(tripId(t))===String(selectedTripId)?'selected':''}>${esc(tripTitle(t))}</option>`).join('')}</select></label><div class="bi-chips"><button class="bi-chip ${filter==='all'?'is-active':''}" data-bi-filter="all">Alle · ${activeThreads.length}</button><button class="bi-chip ${filter==='unread'?'is-active':''}" data-bi-filter="unread">Ungelesen · ${unread}</button><button class="bi-chip ${filter==='attention'?'is-active':''}" data-bi-filter="attention">Aktion nötig · ${attn}</button><button class="bi-chip ${filter==='archive'?'is-active':''}" data-bi-filter="archive">Archiv · ${threads.filter(t=>t.archived&&!t.deleted).length}</button></div><button class="bi-refresh" data-bi-refresh>${loading?'Lädt …':'Aktualisieren'}</button></section>${error?`<div class="bi-state"><strong>Inbox konnte nicht geladen werden.</strong><p>${esc(error.message||error)}</p></div>`:`<div class="bi-layout"><section class="bi-list ${selectedBookingId?'is-thread-open':''}"><header class="bi-list-head"><small>Konversationen</small><h2>${list.length} Gespräch${list.length===1?'':'e'}</h2></header>${loading?'<div class="bi-state">Nachrichten werden geladen …</div>':list.length?list.map(threadCard).join(''):'<div class="bi-empty"><strong>Keine passenden Gespräche.</strong><p>Die Inbox zeigt nur echte Nachrichten aus dem bestehenden Booking Core.</p></div>'}</section>${conversationView()}</div>`}<footer class="bi-footer">Booking Inbox v13.81 · Archive/Delete sind nur persönliche Sichtzustände · Message & Booking Truth bleiben im Booking Core</footer></section>`}
async function refreshConversation(){if(!selectedBookingId)return;await openConversation(selectedBookingId,false);bookings=(selectedTripId?await bookingContract().reads.listForTrip(selectedTripId):[]).map(normalizeBooking);threads=await Promise.all(bookings.map(loadThreadSummary));render();setTimeout(()=>target?.querySelector('.bi-messages')?.scrollTo?.({top:999999,behavior:'smooth'}),0)}
async function runAction(action,intelId,bodyText=''){if(actionBusy)return;const api=bookingContract().commands;const intel=(conversation?.intelligence||[]).find(i=>String(i.id)===String(intelId));if(!intel)throw new Error('Die Luvia-Entscheidung konnte nicht gefunden werden.');actionBusy=true;render();try{await api.performIntelligenceAction(selectedBookingId,{intelligence:intel,action,bodyText});window.LuviaUIKit?.toast?.(action==='accept_alternative'?'Alternative wurde beantwortet.':action==='decline_alternative'?'Alternative wurde abgelehnt und beantwortet.':action==='mark_reviewed'?'Als geprüft markiert.':'Antwort wurde versendet.',{type:'success'});await refreshConversation()}finally{actionBusy=false;render()}}
async function applyPreference(action){if(!selectedBookingId)return;const api=bookingContract().commands;if(!api?.setConversationPreference)throw new Error('Conversation Lifecycle ist nicht verfügbar.');if(action==='delete'&&!window.confirm('Chat wirklich aus deiner Inbox löschen? Die Booking- und Audit-Historie bleibt aus Sicherheitsgründen erhalten.'))return;actionBusy=true;render();try{await api.setConversationPreference(selectedBookingId,action);window.LuviaUIKit?.toast?.(action==='archive'?'Chat archiviert.':action==='unarchive'?'Chat aus Archiv geholt.':'Chat aus deiner Inbox entfernt.',{type:'success'});if(action==='delete'||action==='archive'){selectedBookingId=null;conversation=null}await load()}finally{actionBusy=false;render()}}
function click(e){const menu=e.target.closest?.('[data-bi-conv-menu]');if(menu&&target?.contains(menu)){menu.parentElement?.classList.toggle('is-open');return}const pref=e.target.closest?.('[data-bi-pref]');if(pref&&target?.contains(pref)){applyPreference(pref.dataset.biPref).catch(err=>{composerStatus=err.message||'Conversation konnte nicht geändert werden.';render()});return}const back=e.target.closest?.('[data-bi-inbox-back]');if(back&&target?.contains(back)){selectedBookingId=null;conversation=null;composerStatus='';render();return}const send=e.target.closest?.('[data-bi-send]');if(send&&target?.contains(send)){e.preventDefault();const form=send.closest('[data-bi-composer]');return sendFromForm(form)}const th=e.target.closest?.('[data-bi-thread]');if(th&&target?.contains(th)){openConversation(th.dataset.biThread).catch(err=>{error=err;render()});return}const f=e.target.closest?.('[data-bi-filter]');if(f&&target?.contains(f)){filter=f.dataset.biFilter;render();return}if(e.target.closest?.('[data-bi-refresh]')){load();return}const focus=e.target.closest?.('[data-bi-intel-focus]');if(focus){const form=target.querySelector('[data-bi-composer]');const input=form?.querySelector('[data-bi-intel-context]');if(input)input.value=focus.dataset.biIntelFocus||'';form?.querySelector('textarea')?.focus();composerStatus='Deine Antwort wird dieser Rückfrage zugeordnet.';render();return}const act=e.target.closest?.('[data-bi-intel-action]');if(act){runAction(act.dataset.biIntelAction,act.dataset.intelId).catch(err=>{actionBusy=false;composerStatus=err.message||'Aktion fehlgeschlagen.';window.LuviaUIKit?.toast?.(composerStatus,{type:'error'});render()});}}
function change(e){const s=e.target.closest?.('[data-bi-trip]');if(s&&target?.contains(s)){selectedTripId=s.value;selectedBookingId=null;conversation=null;load()}}
async function sendFromForm(form){if(!form||!target?.contains(form)||actionBusy)return;const text=clean(form.querySelector('textarea')?.value);if(!text){composerStatus='Bitte zuerst eine Nachricht eingeben.';window.LuviaUIKit?.toast?.(composerStatus,{type:'info'});render();return}const intelId=clean(form.querySelector('[data-bi-intel-context]')?.value);const api=bookingContract().commands;if(!api?.reply){composerStatus='Der Booking-Reply-Transport ist nicht verfügbar.';render();return}actionBusy=true;composerStatus='Antwort wird versendet …';render();try{if(intelId){const intel=(conversation?.intelligence||[]).find(i=>String(i.id)===String(intelId));if(!api.performIntelligenceAction)throw new Error('Booking Intelligence Actions sind nicht verfügbar.');await api.performIntelligenceAction(selectedBookingId,{intelligence:intel,action:'answer',bodyText:text})}else await api.reply(selectedBookingId,{bodyText:text});composerStatus='Antwort wurde erfolgreich versendet.';window.LuviaUIKit?.toast?.('Antwort wurde über den bestehenden Booking-Thread versendet.',{type:'success'});await refreshConversation()}catch(err){composerStatus=err?.message||'Antwort konnte nicht versendet werden.';window.LuviaUIKit?.toast?.(composerStatus,{type:'error'})}finally{actionBusy=false;render()}}
async function submit(e){const form=e.target.closest?.('[data-bi-composer]');if(!form||!target?.contains(form))return;e.preventDefault();return sendFromForm(form)}
async function mount(el,options={}){if(!el)throw new Error('Booking Inbox target required');target=el;selectedTripId=options.tripId||activeTripId();selectedBookingId=options.bookingId||null;window.LuviaProductModuleRegistry?.mount?.('control-center',el,{surface:'booking-inbox'});target.addEventListener('click',click);target.addEventListener('change',change);target.addEventListener('submit',submit);await load();return diagnostics()}
function unmount(){if(target){target.removeEventListener('click',click);target.removeEventListener('change',change);target.removeEventListener('submit',submit);window.LuviaProductModuleRegistry?.unmount?.('control-center',target,{surface:'booking-inbox'})}target=null;selectedTripId=null;selectedBookingId=null;bookings=[];threads=[];preferences=new Map();conversation=null;loading=false;error=null;actionBusy=false;composerStatus=''}
function diagnostics(){return {version:VERSION,mounted:Boolean(target),selectedTripId,selectedBookingId,conversationCount:threads.length,unreadCount:threads.filter(t=>t.unread).length,actionRequiredCount:threads.filter(t=>t.attention).length,ownsMessageTruth:false,ownsBookingTruth:false,source:'booking-core',providerIndependent:true,composerTransport:'booking-email-reply-v1',intelligenceActions:true,mobileInboxFirst:true,mobileBackNavigation:true,conversationArchiveDelete:true,hardDeletesMessageTruth:false,archivedCount:threads.filter(t=>t.archived&&!t.deleted).length,deletedCount:threads.filter(t=>t.deleted).length,actionBusy,composerStatus,loading,error:error?.message||null}}
window.LuviaBookingInbox=Object.freeze({version:VERSION,mount,unmount,load,render,diagnostics});
})();
