(() => {
  'use strict';
  const KEY='luvia.pendingJoin.v1';
  let client=null,channel=null,watchedTripId=null,members=[],listeners=new Set(),joining=false;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const normalizeCode=v=>String(v||'').trim().toUpperCase().replace(/[^A-Z0-9]/g,'').slice(0,12);
  const storage=()=>LuviaPlatformPorts?.require?.('StoragePort');
  const navigation=()=>{const value=LuviaOwnerFlowNavigationV1;if(!value?.current||!value?.openJoin||!value?.clearJoin)throw new Error('Owner Flow Navigation v1 fehlt.');return value};
  function codeFromUrl(){const params=navigation().current().query||{};return normalizeCode(params.join||params.invite||'')}
  function pending(){const urlCode=codeFromUrl();if(urlCode){storage()?.set?.(KEY,{code:urlCode,source:'link',createdAt:new Date().toISOString()});return {code:urlCode,source:'link'}}return storage()?.get?.(KEY,null)||null}
  function setPending(value){if(value?.code)storage()?.set?.(KEY,{...value,code:normalizeCode(value.code),createdAt:value.createdAt||new Date().toISOString()});else storage()?.remove?.(KEY)}
  function cleanUrl(options={}){return navigation().clearJoin(options)}
  async function preview(code){const c=client||window.LuviaSupabaseService?.getClient?.();if(!c)throw new Error('Cloud-Verbindung ist noch nicht bereit.');const r=await c.rpc('luvia_preview_trip_invite',{p_join_code:normalizeCode(code)});if(r.error)throw r.error;const data=Array.isArray(r.data)?r.data[0]:r.data;if(!data?.trip_id)throw new Error('Diese Einladung ist ungültig oder nicht mehr verfügbar.');return data}
  function styles(){if(document.getElementById('luviaJoinStyles'))return;const s=document.createElement('style');s.id='luviaJoinStyles';s.textContent=`
  .lj-shell{min-height:100dvh;display:grid;place-items:center;padding:22px;background:radial-gradient(circle at 15% 5%,color-mix(in srgb,var(--lv-accent,#ee6f83) 18%,transparent),transparent 40%),var(--lv-bg,#fff8f7)}.lj-card{width:min(660px,100%);padding:clamp(24px,5vw,44px);border:1px solid var(--lv-line,#e3e8eb);border-radius:32px;background:color-mix(in srgb,var(--lv-surface-elevated,#fff) 96%,transparent);box-shadow:0 30px 90px rgba(37,54,67,.16)}.lj-brand{display:flex;align-items:center;gap:12px;margin-bottom:28px}.lj-brand .lv-logo{width:46px;height:46px;margin:0}.lj-kicker{font-size:11px;font-weight:850;letter-spacing:.14em;text-transform:uppercase;color:var(--lv-accent,#ee6f83)}.lj-card h1{margin:8px 0 10px;font:500 clamp(34px,7vw,54px)/1.02 var(--lv-font-display,Manrope,system-ui);letter-spacing:-.035em}.lj-card p{color:var(--lv-muted,#748695);line-height:1.65}.lj-trip{display:flex;align-items:center;gap:16px;margin:24px 0;padding:18px;border-radius:22px;background:linear-gradient(135deg,color-mix(in srgb,var(--join-accent,#ee6f83) 11%,var(--lv-surface-elevated,#fff)),var(--lv-surface-soft,#f3f7f8));border:1px solid color-mix(in srgb,var(--join-accent,#ee6f83) 20%,var(--lv-line,#e3e8eb))}.lj-symbol{width:58px;height:58px;display:grid;place-items:center;border-radius:18px;background:var(--lv-surface-elevated,#fff);font-size:27px}.lj-trip strong,.lj-trip small{display:block}.lj-trip small{margin-top:5px;color:var(--lv-muted,#748695)}.lj-steps{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:22px 0}.lj-steps span{height:6px;border-radius:999px;background:var(--lv-line,#e3e8eb)}.lj-steps span.on{background:var(--join-accent,var(--lv-accent,#ee6f83))}.lj-field{display:grid;gap:7px;margin:18px 0}.lj-field label{font-size:12px;font-weight:800}.lj-field input{min-height:54px;border:1px solid var(--lv-line,#e3e8eb);border-radius:15px;padding:0 15px;background:var(--lv-input,#fff);color:var(--lv-text,#263f54);outline:none}.lj-field input:focus{border-color:var(--join-accent,var(--lv-accent));box-shadow:0 0 0 4px color-mix(in srgb,var(--join-accent,var(--lv-accent)) 13%,transparent)}.lj-actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:22px}.lj-btn{border:0;border-radius:14px;padding:13px 18px;background:var(--lv-surface-soft,#f3f7f8);color:var(--lv-text,#263f54);font-weight:800;cursor:pointer}.lj-btn.primary{background:var(--join-accent,var(--lv-accent,#ee6f83));color:#fff}.lj-btn:disabled{opacity:.55;cursor:wait}.lj-error{margin-top:14px;padding:13px;border-radius:14px;background:#fff0f1;color:#a94455}.lj-code-entry{display:flex;gap:9px}.lj-code-entry input{flex:1;min-width:0}@media(max-width:540px){.lj-shell{padding:0;align-items:end}.lj-card{border-radius:28px 28px 0 0;padding:26px 20px calc(26px + env(safe-area-inset-bottom))}.lj-actions{display:grid}.lj-actions>*{width:100%}.lj-code-entry{display:grid}}
  `;document.head.appendChild(s)}
  function authForm(root,invite){root.innerHTML=`<main class="lj-shell"><section class="lj-card" style="--join-accent:${esc(invite.accent||'#ee6f83')}"><div class="lj-brand"><span class="lv-logo"></span><div><b>Luvia</b><small style="display:block;color:var(--lv-muted)">Gemeinsam reisen</small></div></div><div class="lj-steps"><span class="on"></span><span></span><span></span></div><span class="lj-kicker">Du wurdest eingeladen</span><h1>Willkommen bei ${esc(invite.trip_name||'dieser Reise')}</h1><p>Melde dich an oder erstelle dein Profil. Danach trittst du genau dieser Reise bei.</p><div class="lj-trip"><span class="lj-symbol">${esc(invite.symbol||'❤️')}</span><div><strong>${esc(invite.trip_name||'Unsere Reise')}</strong><small>${esc(invite.destination_name||'Gemeinsames Reiseziel')} · ${Number(invite.member_count||0)} Teilnehmer</small></div></div><div data-join-auth></div><button class="lj-btn" data-cancel-join style="margin-top:14px">Einladung später öffnen</button></section></main>`;window.ParisAuthUI.renderAuthForm(root.querySelector('[data-join-auth]'),'login');root.querySelector('[data-cancel-join]').onclick=()=>{setPending(null);cleanUrl()}}
  function joinForm(root,invite,profile){root.innerHTML=`<main class="lj-shell"><section class="lj-card" style="--join-accent:${esc(invite.accent||'#ee6f83')}"><div class="lj-brand"><span class="lv-logo"></span><div><b>Luvia</b><small style="display:block;color:var(--lv-muted)">Einladung annehmen</small></div></div><div class="lj-steps"><span class="on"></span><span class="on"></span><span></span></div><span class="lj-kicker">Fast geschafft</span><h1>${esc(invite.trip_name||'Reise')} wartet auf dich</h1><div class="lj-trip"><span class="lj-symbol">${esc(invite.symbol||'❤️')}</span><div><strong>${esc(invite.trip_name||'Unsere Reise')}</strong><small>${esc(invite.destination_name||'Gemeinsames Reiseziel')}</small></div></div><div class="lj-field"><label>Dein Anzeigename in dieser Reise</label><input data-member-name maxlength="80" value="${esc(profile?.displayName||'')}"></div><div class="lj-actions"><button class="lj-btn" data-cancel-join>Abbrechen</button><button class="lj-btn primary" data-confirm-join>Reise beitreten</button></div><div data-join-message></div></section></main>`;
    root.querySelector('[data-cancel-join]').onclick=()=>{setPending(null);cleanUrl()};root.querySelector('[data-confirm-join]').onclick=async e=>{const b=e.currentTarget,name=root.querySelector('[data-member-name]').value.trim(),msg=root.querySelector('[data-join-message]');if(!name){msg.innerHTML='<div class="lj-error">Bitte gib einen Anzeigenamen ein.</div>';return}b.disabled=true;b.textContent='Beitritt läuft …';try{await join(pending().code,name);root.innerHTML=`<main class="lj-shell"><section class="lj-card" style="--join-accent:${esc(invite.accent||'#ee6f83')}"><div class="lj-steps"><span class="on"></span><span class="on"></span><span class="on"></span></div><span class="lj-kicker">Fertig</span><h1>Ihr reist jetzt gemeinsam</h1><p>Die Reise wurde deinem Luvia-Konto hinzugefügt und wird auf deinen Geräten synchronisiert.</p><div class="lj-actions"><button class="lj-btn primary" data-open-trip>Reise öffnen</button></div></section></main>`;root.querySelector('[data-open-trip]').onclick=()=>navigation().completeJoin()}catch(error){b.disabled=false;b.textContent='Reise beitreten';msg.innerHTML=`<div class="lj-error">${esc(error?.message||'Der Beitritt ist fehlgeschlagen.')}</div>`}}
  }
  async function renderIfPending(root,authState,profile){const p=pending();if(!p?.code)return false;styles();try{root.innerHTML='<main class="lj-shell"><section class="lj-card"><span class="lj-kicker">Einladung wird geprüft</span><h1>Einen Moment …</h1><p>Luvia lädt die Reisedaten sicher aus der Cloud.</p></section></main>';const invite=await preview(p.code);if(authState?.authenticated)joinForm(root,invite,profile);else authForm(root,invite);return true}catch(error){root.innerHTML=`<main class="lj-shell"><section class="lj-card"><span class="lj-kicker">Einladung nicht verfügbar</span><h1>Dieser Link funktioniert nicht</h1><div class="lj-error">${esc(error?.message||'Die Einladung konnte nicht geladen werden.')}</div><div class="lj-actions"><button class="lj-btn" data-cancel-join>Zurück zu Luvia</button></div></section></main>`;root.querySelector('[data-cancel-join]').onclick=()=>{setPending(null);cleanUrl()};return true}}
  const tripContract=()=>window.LuviaTripContractV1||window.LuviaTripContract||null;
  const tripRuntime=()=>tripContract()?.runtime||null;
  const tripCommands=()=>tripContract()?.commands||null;
  async function join(code,memberName){if(joining)return;joining=true;try{const c=client||window.LuviaSupabaseService?.getClient?.();if(!c)throw new Error('Cloud-Verbindung ist noch nicht bereit.');const r=await c.rpc('luvia_join_trip_by_code',{p_join_code:normalizeCode(code),p_display_name:String(memberName||'').trim()});if(r.error)throw r.error;setPending(null);cleanUrl({notify:false});await tripRuntime()?.loadRemote?.(c,{authoritative:true});const data=Array.isArray(r.data)?r.data[0]:r.data;if(data?.trip_id)tripCommands()?.selectActiveTrip?.(data.trip_id);return data}finally{joining=false}}
  function entryDialog(){styles();const ui=LuviaUI;if(!ui?.mount)throw new Error('Overlay Host v1 ist noch nicht bereit.');const content=document.createElement('section');content.className='lj-card';content.innerHTML=`<span class="lj-kicker">Einladungscode</span><h1>Reise beitreten</h1><p>Gib den Code ein, den du von einer mitreisenden Person erhalten hast.</p><div class="lj-code-entry"><input class="ltx-link" data-code maxlength="12" autocomplete="one-time-code" placeholder="z. B. LUVIA7K2"><button class="lj-btn primary" data-go>Weiter</button></div><div data-msg></div><div class="lj-actions"><button class="lj-btn" data-close>Abbrechen</button></div>`;const mounted=ui.mount({name:'trip.join-code',kind:'dialog',content,closeSelector:'[data-close]',initialFocus:'[data-code]'}),wrap=mounted.overlay,close=()=>mounted.close('owner');wrap.querySelector('[data-go]').onclick=async()=>{const code=normalizeCode(wrap.querySelector('[data-code]').value);if(code.length<5){wrap.querySelector('[data-msg]').innerHTML='<div class="lj-error">Bitte gib einen gültigen Einladungscode ein.</div>';return}setPending({code,source:'code'});close();navigation().openJoin(code)}}
  async function start(c){client=c||client;codeFromUrl();return pending()}
  function emit(){listeners.forEach(fn=>fn([...members]));window.dispatchEvent(new CustomEvent('luvia:members-changed',{detail:[...members]}))}
  async function loadMembers(tripId){const c=client||window.LuviaSupabaseService?.getClient?.();if(!c||!tripId)return[];const r=await c.rpc('luvia_list_trip_members',{p_trip_id:tripId});if(r.error)throw r.error;members=r.data||[];emit();return members}
  async function watchMembers(tripId){if(tripId&&watchedTripId===tripId)return;channel?.unsubscribe?.();channel=null;watchedTripId=tripId||null;if(!tripId)return;await loadMembers(tripId).catch(e=>console.warn('[LuviaMembers]',e));const c=client||window.LuviaSupabaseService?.getClient?.();if(!c?.channel)return;channel=c.channel(`luvia-members-${tripId}`).on('postgres_changes',{event:'*',schema:'public',table:'trip_members',filter:`trip_id=eq.${tripId}`},()=>loadMembers(tripId).catch(e=>console.warn('[LuviaMembers]',e))).subscribe()}
  window.LuviaJoinFlow=Object.freeze({version:'1.0.0',start,pending,setPending,renderIfPending,preview,join,openCodeEntry:entryDialog,watchMembers,loadMembers,snapshot:()=>[...members],subscribe(fn){listeners.add(fn);fn([...members]);return()=>listeners.delete(fn)}});
})();
