(function(){
'use strict';
const VERSION='0.3.0';let repository=null;
const C=()=>window.LuviaBookingContract;const E=()=>window.LuviaBookingEvents;const P=()=>window.LuviaBookingProviderRegistry;const M=()=>window.LuviaBookingCommunication;
const snake=b=>({trip_id:b.tripId,trip_place_id:b.tripPlaceId||null,place_id:b.placeId||null,requested_by:b.requestedBy||null,booking_type:b.type,status:b.status,channel:b.channel,provider:b.provider||null,provider_reference:b.providerReference||null,title:b.title,start_at:b.startAt,end_at:b.endAt,party_size:b.partySize,participant_ids:b.participantIds,currency:b.currency,amount:b.amount,confirmation_number:b.confirmationNumber,cancellation_deadline:b.cancellationDeadline,contact:b.contact,request:b.request,metadata:b.metadata});
function configure(options={}){if(options.repository)repository=options.repository;M()?.configure?.({repository,...options.communication});return api;}function repo(){if(!repository)throw new Error('BookingRepository ist noch nicht konfiguriert.');return repository;}
async function create(input){const check=C().validate(input);if(!check.valid)throw new Error(`Booking unvollständig: ${check.errors.join(', ')}`);const row=await repo().create(snake(check.booking));await E().emit(E().names.CREATED,{booking:row});return row;}
async function listForTrip(tripId){if(!tripId)throw new Error('tripId erforderlich.');return repo().listForTrip(tripId);}
async function transition(id,nextStatus,patch={}){const current=await repo().get(id);if(!current)throw new Error('Booking nicht gefunden.');C().assertTransition(current.status,nextStatus);const result=await repo().transition(id,nextStatus,patch);await E().emit(E().statusEvent(nextStatus),{bookingId:id,booking:result});return result;}
async function dispatch(id,context={}){const row=await repo().get(id);if(!row)throw new Error('Booking nicht gefunden.');const current=C().normalize(row);if(!['ready','needs_action'].includes(current.status))throw new Error(`Booking ist nicht versandbereit (${current.status}).`);const result=await M().send(current,context);if(result.deduplicated)return {booking:row,...result};const updated=await transition(id,result.status||'requested',{provider:result.provider||current.provider||null,provider_reference:result.providerReference||null,channel:result.channel||'email',metadata:{...(current.metadata||{}),communicationMode:context.mode||'test'}});return {booking:updated,...result};}
const service={name:'booking',version:VERSION,description:'Generischer Luvia Booking Core mit isolierter Communication Foundation.',dependencies:[],optionalDependencies:['places','planning'],async init(){return true;},async status(){return{state:'ready',configured:Boolean(repository),providers:P()?.list?.().length||0,communication:Boolean(M())};},async diagnostics(){return{version:VERSION,configured:Boolean(repository),providers:P()?.list?.()||[],types:C()?.TYPES||[],statuses:C()?.STATUSES||[],communicationVersion:M()?.version||null};},async test(){return{ok:Boolean(C()&&E()&&P()&&M()),message:'Booking + Communication Contracts verfügbar.'};}};
const api=Object.freeze({version:VERSION,service,configure,create,listForTrip,transition,dispatch});window.LuviaBookingCore=api;try{window.LuviaServiceRegistry?.register(service);}catch(error){if(!String(error?.message||'').includes('bereits registriert'))console.warn('[LuviaBookingCore]',error);}
})();
