(() => {
  'use strict';
  const LEGACY_BUCKET='paris-gallery';
  let channelStatus='CLOSED';
  const dateKey=iso=>{const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  async function context(){return window.ParisSync.requireReady()}
  const mediaContract=()=>window.LuviaMediaContractV1||window.LuviaMediaContract||null;
  const mediaReads=()=>{const reads=mediaContract()?.reads;if(!reads)throw new Error('Media Contract ist nicht geladen.');return reads};
  const mediaCommands=()=>{const commands=mediaContract()?.commands?.media;if(!commands)throw new Error('Media Contract Commands sind nicht geladen.');return commands};
  function canonicalPhoto(entity,blob,polaroid=false){const taken=entity.capturedAt||entity.createdAt,date=dateKey(taken);return{id:entity.id,blob,storagePath:null,storageBucket:null,originalName:entity.originalName||`media-${entity.id}`,size:entity.fileSize??blob?.size??0,lastModified:new Date(entity.createdAt||taken).getTime(),takenAt:taken,dateKey:date,group:['2026-07-31','2026-08-01','2026-08-02'].includes(date)?date:'other',favorite:Boolean(entity.favorite),polaroid:Boolean(polaroid),caption:entity.displayName||'',createdAt:entity.createdAt,placeId:entity.placeId||null,latitude:entity.latitude,longitude:entity.longitude,mediaEntity:true}}
  function legacyPhoto(row,blob){const taken=row.taken_at||row.created_at,date=dateKey(taken);return{id:row.id,blob,storagePath:row.storage_path,storageBucket:LEGACY_BUCKET,originalName:row.original_filename||row.storage_path?.split('/').pop(),size:row.file_size??blob?.size??0,lastModified:new Date(row.created_at).getTime(),takenAt:taken,dateKey:date,group:['2026-07-31','2026-08-01','2026-08-02'].includes(date)?date:'other',favorite:Boolean(row.is_favorite),polaroid:Boolean(row.is_polaroid),caption:row.description??row.caption??'',createdAt:row.created_at,legacySource:'gallery_photos'}}
  async function polaroidIds(){const rows=await mediaReads().listPolaroids();return new Set(Object.values(rows||{}).map(String))}
  async function downloadCanonical(entity,polaroid=false){const blob=await mediaReads().download(entity.id,'original');if(!blob)throw new Error('Mediendatei ist nicht verfügbar.');return canonicalPhoto(entity,blob,polaroid)}
  async function legacyRows(){const{client,tripId}=await context(),r=await client.from('gallery_photos').select('*').eq('trip_id',tripId).order('taken_at',{ascending:true});if(r.error){if(['42P01','PGRST205'].includes(r.error.code))return[];throw r.error}return r.data||[]}
  async function downloadLegacy(row){const{client}=await context(),r=await client.storage.from(LEGACY_BUCKET).download(row.storage_path);if(r.error)throw r.error;return legacyPhoto(row,r.data)}
  async function canonicalRows(){return mediaReads().listMedia({type:'image'})}
  const api={
    bucket:'luvia-media',legacyBucket:LEGACY_BUCKET,
    async listRows(){const [canonical,legacy,polaroids]=await Promise.all([canonicalRows(),legacyRows(),polaroidIds()]);const mapped=canonical.map(x=>({id:x.id,trip_id:x.tripId,participant_id:x.participantId,storage_path:null,storage_bucket:null,original_filename:x.originalName,mime_type:x.mimeType,file_size:x.fileSize,taken_at:x.capturedAt,created_at:x.createdAt,updated_at:x.updatedAt,is_favorite:Boolean(x.favorite),is_polaroid:polaroids.has(String(x.id)),caption:x.displayName||'',description:x.displayName||'',place_id:x.placeId,latitude:x.latitude,longitude:x.longitude,_source:'media'}));return[...mapped,...legacy.filter(x=>!canonical.some(m=>m.id===x.id)).map(x=>({...x,_source:'gallery_photos'}))]},
    async list(){const out=[],polaroids=await polaroidIds();for(const item of await canonicalRows()){try{out.push(await downloadCanonical(item,polaroids.has(String(item.id))))}catch(e){console.warn(`Media ${item.id} konnte nicht geladen werden:`,e.message)}}for(const row of await legacyRows()){if(out.some(x=>x.id===row.id))continue;try{out.push(await downloadLegacy(row))}catch(e){console.warn(`Legacy-Foto ${row.id} konnte nicht geladen werden:`,e.message)}}return out.sort((a,b)=>new Date(a.takenAt)-new Date(b.takenAt))},
    async get(id){const canonical=await mediaReads().getMedia(id);if(canonical){const polaroids=await polaroidIds();return downloadCanonical(canonical,polaroids.has(String(id)))}const{client,tripId}=await context(),r=await client.from('gallery_photos').select('*').eq('trip_id',tripId).eq('id',id).maybeSingle();if(r.error)throw r.error;return r.data?downloadLegacy(r.data):null},
    async upload(photo){if(!(photo.blob instanceof Blob))throw new Error('Das Foto enthält keine gültige Bilddatei.');const result=await mediaCommands().upload(photo.blob,{id:photo.id,originalName:photo.originalName,capturedAt:photo.takenAt,displayName:photo.caption,favorite:photo.favorite,source:'user_upload',metadata:{legacyGalleryCompatible:true,polaroid:Boolean(photo.polaroid),caption:photo.caption||''}});photo.id=result.entity.id;photo.storagePath=null;photo.storageBucket=null;photo.mediaEntity=true;photo.queued=Boolean(result.queued);return photo},
    async update(id,patch){const item=await mediaReads().getMedia(id);if(item){await mediaCommands().updateLegacyGallery(id,patch);return}const{client,tripId}=await context(),mapped={};if('favorite'in patch)mapped.is_favorite=Boolean(patch.favorite);if('polaroid'in patch)mapped.is_polaroid=Boolean(patch.polaroid);if('caption'in patch){mapped.caption=patch.caption||'';mapped.description=patch.caption||''}if(Object.keys(mapped).length){const r=await client.from('gallery_photos').update(mapped).eq('trip_id',tripId).eq('id',id);if(r.error)throw r.error}},
    async remove(photo){if(await mediaReads().getMedia(photo.id)){await mediaCommands().remove(photo.id);return}const{client,tripId}=await context();let path=photo.storagePath;if(!path){const q=await client.from('gallery_photos').select('storage_path').eq('trip_id',tripId).eq('id',photo.id).maybeSingle();if(q.error)throw q.error;path=q.data?.storage_path}if(path){const s=await client.storage.from(LEGACY_BUCKET).remove([path]);if(s.error)throw s.error}const r=await client.from('gallery_photos').delete().eq('trip_id',tripId).eq('id',photo.id);if(r.error)throw r.error},
    async clear(){for(const photo of await this.list())await this.remove(photo)},
    async subscribe(callback,statusCallback){channelStatus='CONNECTING';const stop=await mediaReads().subscribe(payload=>callback(payload));channelStatus='SUBSCRIBED';statusCallback?.('SUBSCRIBED');return async()=>{channelStatus='CLOSED';await stop()}},
    getRealtimeStatus(){return channelStatus}
  };
  window.ParisSync.register('gallery',api);
})();
