(() => {
  'use strict';
  const VERSION='4.28.0',BUILD='13.28.0',BUCKET='luvia-media',channels=new Map();
  const id=()=>crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(16).slice(2)}`;
  const ext=f=>(f?.name?.split('.').pop()||f?.type?.split('/').pop()||'jpg').replace(/[^a-z0-9]/gi,'').toLowerCase()||'jpg';
  const day=iso=>{const d=new Date(iso);return Number.isNaN(d.getTime())?null:`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
  async function context(){if(window.ParisSync?.requireReady)return window.ParisSync.requireReady();const client=window.LuviaSupabase?.getClient?.()||window.LuviaSupabase?.client?.()||window.ParisCloud?.client,tripId=window.LuviaTripContext?.getActiveTripId?.()||window.LuviaTripContext?.get?.()?.id,session=await client?.auth?.getSession?.(),userId=session?.data?.session?.user?.id;if(!client||!tripId||!userId)throw new Error('Media Core benötigt Anmeldung und aktive Reise.');return{client,tripId,userId}}
  function entity(r){return Object.freeze({id:r.id,tripId:r.trip_id,userId:r.user_id,participantId:r.participant_id||null,type:r.type,purpose:r.purpose,source:r.source,originalName:r.original_name,mimeType:r.mime_type,storageBucket:r.storage_bucket||BUCKET,storagePath:r.storage_path,previewPath:r.preview_path||null,thumbnailPath:r.thumbnail_path||null,status:r.status,capturedAt:r.captured_at||r.created_at,dayKey:r.day_key||day(r.captured_at||r.created_at),timezone:r.timezone||null,latitude:r.latitude==null?null:Number(r.latitude),longitude:r.longitude==null?null:Number(r.longitude),width:r.width||null,height:r.height||null,fileSize:r.file_size||null,contentHash:r.content_hash||null,placeId:r.place_id||null,metadata:r.metadata||{},createdAt:r.created_at,updatedAt:r.updated_at,legacySource:r.legacy_source||null,legacyId:r.legacy_id||null})}
  async function list(options={}){const{client,tripId}=await context();let q=client.from('media').select('*').eq('trip_id',tripId).neq('status','deleted');if(options.type)q=q.eq('type',options.type);if(options.dayKey)q=q.eq('day_key',options.dayKey);if(options.placeId)q=q.eq('place_id',options.placeId);const r=await q.order('captured_at',{ascending:true,nullsFirst:false}).order('created_at',{ascending:true});if(r.error)throw r.error;return(r.data||[]).map(entity)}
  async function get(mediaId){const{client,tripId}=await context(),r=await client.from('media').select('*').eq('trip_id',tripId).eq('id',mediaId).maybeSingle();if(r.error)throw r.error;return r.data?entity(r.data):null}
  async function signedUrl(item,expiresIn=3600){if(!item?.storagePath)return null;const{client}=await context(),r=await client.storage.from(item.storageBucket||BUCKET).createSignedUrl(item.storagePath,expiresIn);if(r.error)throw r.error;return r.data?.signedUrl||null}
  async function upload(file,options={}){if(!(file instanceof Blob))throw new TypeError('Media Core erwartet eine Datei oder einen Blob.');const{client,tripId,userId}=await context(),mediaId=options.id||id(),meta=await window.LuviaMediaMetadata.extract(file);if(meta.contentHash){const d=await client.from('media').select('*').eq('trip_id',tripId).eq('content_hash',meta.contentHash).neq('status','deleted').limit(1).maybeSingle();if(d.error&&d.error.code!=='PGRST116')throw d.error;if(d.data)return{entity:entity(d.data),duplicate:true}}const path=`${tripId}/${userId}/${mediaId}/original.${ext(file)}`,capturedAt=options.capturedAt||meta.capturedAt,row={id:mediaId,trip_id:tripId,user_id:userId,participant_id:options.participantId||null,module_key:options.moduleKey||'gallery',entity_type:options.entityType||null,entity_id:options.entityId||null,type:options.type||'image',purpose:options.purpose||'memory',source:'user_upload',original_name:file.name||options.originalName||null,mime_type:file.type||options.mimeType||'application/octet-stream',storage_bucket:BUCKET,storage_path:path,status:'pending',captured_at:capturedAt,day_key:day(capturedAt),timezone:options.timezone||meta.timezone,latitude:options.latitude??meta.latitude,longitude:options.longitude??meta.longitude,width:meta.width,height:meta.height,file_size:file.size||null,content_hash:meta.contentHash,place_id:options.placeId||null,metadata:{...(options.metadata||{}),captureEvidence:meta.evidence,favorite:Boolean(options.favorite),polaroid:Boolean(options.polaroid),caption:options.caption||''}};const created=await client.from('media').insert(row).select('*').single();if(created.error)throw created.error;const stored=await client.storage.from(BUCKET).upload(path,file,{upsert:false,contentType:row.mime_type,cacheControl:'31536000'});if(stored.error){await client.from('media').update({status:'failed',metadata:{...row.metadata,uploadError:stored.error.message}}).eq('id',mediaId).eq('trip_id',tripId);throw stored.error}const ready=await client.from('media').update({status:'ready'}).eq('id',mediaId).eq('trip_id',tripId).select('*').single();if(ready.error)throw ready.error;return{entity:entity(ready.data),duplicate:false}}
  async function update(mediaId,patch={}){const{client,tripId}=await context(),mapped={};if('capturedAt'in patch){mapped.captured_at=patch.capturedAt;mapped.day_key=day(patch.capturedAt)}if('placeId'in patch)mapped.place_id=patch.placeId||null;if('latitude'in patch)mapped.latitude=patch.latitude;if('longitude'in patch)mapped.longitude=patch.longitude;if('metadata'in patch)mapped.metadata=patch.metadata||{};if('status'in patch)mapped.status=patch.status;if(!Object.keys(mapped).length)return get(mediaId);const r=await client.from('media').update(mapped).eq('trip_id',tripId).eq('id',mediaId).select('*').single();if(r.error)throw r.error;return entity(r.data)}
  async function remove(mediaId){const{client,tripId}=await context(),item=await get(mediaId);if(!item)return false;if(item.storagePath){const s=await client.storage.from(item.storageBucket||BUCKET).remove([item.storagePath]);if(s.error)throw s.error}const r=await client.from('media').update({status:'deleted'}).eq('trip_id',tripId).eq('id',mediaId);if(r.error)throw r.error;return true}
  async function linkPlace(mediaId,placeId,options={}){const{client,tripId,userId}=await context(),r=await client.from('media_place_links').upsert({trip_id:tripId,media_id:mediaId,place_id:placeId,source:options.source||'manual',confidence:options.confidence??1,evidence:options.evidence||{},created_by:userId},{onConflict:'media_id,place_id'}).select('*').single();if(r.error)throw r.error;await update(mediaId,{placeId});return r.data}
  async function linkLiveMoment(mediaId,momentKey,options={}){const{client,tripId,userId}=await context(),r=await client.from('live_moment_media').upsert({trip_id:tripId,moment_key:momentKey,media_id:mediaId,position:options.position||0,created_by:userId},{onConflict:'trip_id,moment_key,media_id'}).select('*').single();if(r.error)throw r.error;return r.data}
  async function subscribe(callback){const{client,tripId}=await context();if(channels.has(tripId))await client.removeChannel(channels.get(tripId));const c=client.channel(`luvia-media-${tripId}-${Math.random().toString(36).slice(2)}`).on('postgres_changes',{event:'*',schema:'public',table:'media',filter:`trip_id=eq.${tripId}`},callback).subscribe();channels.set(tripId,c);return async()=>{if(channels.get(tripId)===c)channels.delete(tripId);await client.removeChannel(c)}}
  const diagnostics=()=>({service:'media-core',version:VERSION,build:BUILD,status:'active',ok:true,checkedAt:new Date().toISOString(),durationMs:0,dependencies:{metadata:Boolean(window.LuviaMediaMetadata)},checks:{canonicalMediaEntity:true,privateBucketContract:true,deduplication:true,exifFoundation:true,placeLinks:true,liveMomentLinks:true},failedChecks:[],warnings:[]});
  window.LuviaMediaCore=Object.freeze({version:VERSION,build:BUILD,bucket:BUCKET,list,get,upload,update,remove,signedUrl,subscribe,linkPlace,linkLiveMoment,diagnostics,rowToEntity:entity});
})();
