(() => {
'use strict';
const VERSION='4.29.0',BUILD='13.29.0',channels=new Map();
async function ctx(){const media=window.LuviaMediaCore;if(!media)throw new Error('Media Core ist nicht geladen.');return{...(await media.getContext()),media}}
async function list(){const{client,tripId}=await ctx();const a=await client.from('memory_albums').select('*').eq('trip_id',tripId).order('created_at',{ascending:false});if(a.error){if(['42P01','PGRST205'].includes(a.error.code))return[];throw a.error}const ids=(a.data||[]).map(x=>x.id);let links=[];if(ids.length){const q=await client.from('memory_album_items').select('*').in('album_id',ids).order('position');if(q.error)throw q.error;links=q.data||[]}return(a.data||[]).map(row=>({...row,mediaIds:links.filter(x=>x.album_id===row.id).map(x=>x.media_id)}))}
async function getByCluster(clusterId){return(await list()).find(x=>String(x.source_cluster_id)===String(clusterId))||null}
async function saveDraft(input){const{client,tripId,userId}=await ctx(),mediaIds=[...new Set((input.mediaIds||[]).map(String))];if(!mediaIds.length)throw new Error('Die Erinnerung braucht mindestens ein Foto.');const payload={trip_id:tripId,source_cluster_id:input.clusterId||null,title:String(input.title||'Unsere Erinnerung').trim(),description:String(input.description||'').trim(),mood:input.mood||null,cover_media_id:input.coverMediaId||mediaIds[0],status:input.status||'published',metadata:{...(input.metadata||{}),wizardVersion:1},updated_by:userId};let row=input.id?null:await getByCluster(input.clusterId);if(input.id)row={id:input.id};let result;if(row?.id){result=await client.from('memory_albums').update(payload).eq('trip_id',tripId).eq('id',row.id).select('*').single()}else result=await client.from('memory_albums').insert({...payload,created_by:userId}).select('*').single();if(result.error)throw result.error;const id=result.data.id;const del=await client.from('memory_album_items').delete().eq('album_id',id);if(del.error)throw del.error;const ins=mediaIds.map((media_id,position)=>({album_id:id,media_id,position,created_by:userId}));if(ins.length){const r=await client.from('memory_album_items').insert(ins);if(r.error)throw r.error}if(input.clusterId){const c=await client.from('media_clusters').update({is_automatic:false,updated_by:userId}).eq('trip_id',tripId).eq('id',input.clusterId);if(c.error)throw c.error}window.dispatchEvent(new CustomEvent('luvia:memory-album-updated',{detail:{albumId:id,clusterId:input.clusterId}}));return{...result.data,mediaIds}}
async function remove(id){const{client,tripId}=await ctx();const r=await client.from('memory_albums').delete().eq('trip_id',tripId).eq('id',id);if(r.error)throw r.error;window.dispatchEvent(new CustomEvent('luvia:memory-album-updated',{detail:{albumId:id,deleted:true}}));return true}
async function subscribe(callback){const{client,tripId}=await ctx();if(channels.has(tripId))await channels.get(tripId)();const channel=client.channel(`luvia-memory-albums-${tripId}-${Math.random().toString(36).slice(2)}`).on('postgres_changes',{event:'*',schema:'public',table:'memory_albums',filter:`trip_id=eq.${tripId}`},callback).on('postgres_changes',{event:'*',schema:'public',table:'memory_album_items'},callback).subscribe();const stop=async()=>{await client.removeChannel(channel);channels.delete(tripId)};channels.set(tripId,stop);return stop}
const diagnostics=()=>({service:'memory-albums',version:VERSION,build:BUILD,status:'active',ok:Boolean(window.LuviaMediaCore),checkedAt:new Date().toISOString(),checks:{persistentAlbums:true,clusterPromotion:true,manualCuration:true,coverSelection:true,realtime:true,canonicalMedia:true},warnings:[]});
window.LuviaMemoryAlbums=Object.freeze({version:VERSION,build:BUILD,list,getByCluster,saveDraft,remove,subscribe,diagnostics});
})();
