(() => {
'use strict';
const VERSION='4.29.2',BUILD='13.29.2',channels=new Map();
let localWriteDepth=0;
async function ctx(){const media=window.LuviaMediaCore;if(!media)throw new Error('Media Core ist nicht geladen.');return{...(await media.getContext()),media}}
const missing=e=>['42P01','PGRST205'].includes(e?.code);
async function list(){const{client,tripId}=await ctx();const a=await client.from('memory_albums').select('*').eq('trip_id',tripId).order('updated_at',{ascending:false});if(a.error){if(missing(a.error))return[];throw a.error}const ids=(a.data||[]).map(x=>x.id);let links=[],favorites=[];if(ids.length){const [q,f]=await Promise.all([client.from('memory_album_items').select('album_id,media_id,position').in('album_id',ids).order('position'),client.from('memory_album_favorites').select('album_id,user_id,media_id,created_at').in('album_id',ids)]);if(q.error&&!missing(q.error))throw q.error;if(f.error&&!missing(f.error))throw f.error;links=q.data||[];favorites=f.data||[]}return(a.data||[]).map(row=>({...row,mediaIds:links.filter(x=>x.album_id===row.id).map(x=>x.media_id),favorites:favorites.filter(x=>x.album_id===row.id)}))}
async function getByCluster(clusterId){const{client,tripId}=await ctx();const a=await client.from('memory_albums').select('*').eq('trip_id',tripId).eq('source_cluster_id',clusterId).maybeSingle();if(a.error){if(missing(a.error))return null;throw a.error}if(!a.data)return null;const q=await client.from('memory_album_items').select('media_id,position').eq('album_id',a.data.id).order('position');if(q.error&&!missing(q.error))throw q.error;return{...a.data,mediaIds:(q.data||[]).map(x=>x.media_id)}}
async function listMembers(){const{client,tripId}=await ctx();const r=await client.rpc('luvia_list_trip_members',{p_trip_id:tripId});if(r.error)return[];return(r.data||[]).map(x=>({id:x.user_id||x.userId||x.id,displayName:x.display_name||x.displayName||x.name||'Teilnehmer',avatarUrl:x.avatar_url||x.avatarUrl||null,role:x.role||'member'})).filter(x=>x.id)}
async function setFavorite(albumId,mediaId){const{client,userId}=await ctx();if(!albumId||!mediaId)return null;const r=await client.from('memory_album_favorites').upsert({album_id:albumId,user_id:userId,media_id:mediaId,updated_at:new Date().toISOString()},{onConflict:'album_id,user_id'}).select('*').single();if(r.error&&!missing(r.error))throw r.error;return r.data||null}
async function saveDraft(input){const{client,tripId,userId}=await ctx(),mediaIds=[...new Set((input.mediaIds||[]).map(String))];if(!mediaIds.length)throw new Error('Die Erinnerung braucht mindestens ein Foto.');localWriteDepth++;try{const payload={trip_id:tripId,source_cluster_id:input.clusterId||null,title:String(input.title||'Unsere Erinnerung').trim(),description:String(input.description||'').trim(),mood:input.mood||null,cover_media_id:input.coverMediaId||mediaIds[0],status:input.status||'published',metadata:{...(input.metadata||{}),wizardVersion:2},updated_by:userId,updated_at:new Date().toISOString()};let row=input.id?{id:input.id}:await getByCluster(input.clusterId),result;if(row?.id)result=await client.from('memory_albums').update(payload).eq('trip_id',tripId).eq('id',row.id).select('*').single();else result=await client.from('memory_albums').insert({...payload,created_by:userId}).select('*').single();if(result.error)throw result.error;const id=result.data.id;const del=await client.from('memory_album_items').delete().eq('album_id',id);if(del.error)throw del.error;const ins=mediaIds.map((media_id,position)=>({album_id:id,media_id,position,created_by:userId}));if(ins.length){const r=await client.from('memory_album_items').insert(ins);if(r.error)throw r.error}if(input.favoriteMediaId)await setFavorite(id,input.favoriteMediaId);if(input.clusterId){const c=await client.from('media_clusters').update({is_automatic:false,updated_by:userId}).eq('trip_id',tripId).eq('id',input.clusterId);if(c.error)throw c.error}await client.from('memory_albums').update({updated_at:new Date().toISOString(),updated_by:userId}).eq('id',id);window.dispatchEvent(new CustomEvent('luvia:memory-album-updated',{detail:{albumId:id,clusterId:input.clusterId,local:true}}));return{...result.data,mediaIds}}finally{localWriteDepth=Math.max(0,localWriteDepth-1)}}
async function remove(id){const{client,tripId}=await ctx();const r=await client.from('memory_albums').delete().eq('trip_id',tripId).eq('id',id);if(r.error)throw r.error;window.dispatchEvent(new CustomEvent('luvia:memory-album-updated',{detail:{albumId:id,deleted:true,local:true}}));return true}
async function subscribe(callback){const{client,tripId}=await ctx();if(channels.has(tripId))await channels.get(tripId)();const channel=client.channel(`luvia-memory-albums-${tripId}-${Math.random().toString(36).slice(2)}`).on('postgres_changes',{event:'*',schema:'public',table:'memory_albums',filter:`trip_id=eq.${tripId}`},payload=>{if(!localWriteDepth)callback(payload)}).subscribe();const stop=async()=>{await client.removeChannel(channel);channels.delete(tripId)};channels.set(tripId,stop);return stop}
const diagnostics=()=>({service:'memory-albums',version:VERSION,build:BUILD,status:'active',ok:Boolean(window.LuviaMediaCore),checkedAt:new Date().toISOString(),checks:{persistentAlbums:true,clusterPromotion:true,manualCuration:true,coverSelection:true,participantFavorites:true,lightweightRealtime:true,canonicalMedia:true},metrics:{localWriteDepth},warnings:[]});
window.LuviaMemoryAlbums=Object.freeze({version:VERSION,build:BUILD,list,getByCluster,listMembers,setFavorite,saveDraft,remove,subscribe,isWriting:()=>localWriteDepth>0,diagnostics});
})();
