(() => {
'use strict';
const VERSION='4.35.0',BUILD='13.35.0',channels=new Map();
let writeDepth=0;
const missing=e=>['42P01','PGRST205'].includes(e?.code);
async function ctx(){const runtime=globalThis.LuviaMemoryRuntimeContextV1;if(!runtime?.get)throw new Error('Memory Runtime Context v1 ist nicht geladen.');return runtime.get()}
async function mediaByIds(ids=[]){const unique=[...new Set(ids.map(String).filter(Boolean))];if(!unique.length)return[];const contract=globalThis.LuviaMediaContractV1||globalThis.LuviaMediaContract;if(!contract?.reads?.listMedia)throw new Error('Media Contract v1 ist nicht geladen.');const rows=await contract.reads.listMedia();const map=new Map((rows||[]).map(row=>[String(row.id),row]));return unique.map(id=>map.get(id)).filter(Boolean)}
async function contributionsFor(albumIds=[]){if(!albumIds.length)return[];const{client}=await ctx();const r=await client.from('memory_album_contributions').select('*').in('album_id',albumIds).order('updated_at',{ascending:true});if(r.error){if(missing(r.error))return[];throw r.error}return r.data||[]}
async function list(){const{client,tripId}=await ctx();const a=await client.from('memory_albums').select('*').eq('trip_id',tripId).order('updated_at',{ascending:false});if(a.error){if(missing(a.error))return[];throw a.error}const ids=(a.data||[]).map(x=>x.id);let links=[],favorites=[],contributions=[];if(ids.length){const [q,f,c]=await Promise.all([client.from('memory_album_items').select('album_id,media_id,position').in('album_id',ids).order('position'),client.from('memory_album_favorites').select('album_id,user_id,media_id').in('album_id',ids),contributionsFor(ids)]);if(q.error&&!missing(q.error))throw q.error;if(f.error&&!missing(f.error))throw f.error;links=q.data||[];favorites=f.data||[];contributions=c||[]}return(a.data||[]).map(row=>({...row,mediaIds:links.filter(x=>x.album_id===row.id).map(x=>x.media_id),favorites:favorites.filter(x=>x.album_id===row.id),contributions:contributions.filter(x=>x.album_id===row.id)}))}
async function listClusters(){const clustering=window.LuviaMediaClustering;if(!clustering?.listPersisted)return[];const rows=await clustering.listPersisted();return(rows||[]).filter(x=>x.state!=='dismissed'&&Array.isArray(x.mediaIds)&&x.mediaIds.length)}
async function getByCluster(clusterId){const{client,tripId}=await ctx();const a=await client.from('memory_albums').select('*').eq('trip_id',tripId).eq('source_cluster_id',clusterId).maybeSingle();if(a.error){if(missing(a.error))return null;throw a.error}if(!a.data)return null;const [q,c,f]=await Promise.all([client.from('memory_album_items').select('media_id,position').eq('album_id',a.data.id).order('position'),contributionsFor([a.data.id]),client.from('memory_album_favorites').select('*').eq('album_id',a.data.id)]);if(q.error&&!missing(q.error))throw q.error;if(f.error&&!missing(f.error))throw f.error;return{...a.data,mediaIds:(q.data||[]).map(x=>x.media_id),contributions:c||[],favorites:f.data||[]}}
async function listMembers(){const{client,tripId}=await ctx();const r=await client.rpc('luvia_list_trip_members',{p_trip_id:tripId});if(r.error)return[];return(r.data||[]).map(x=>({id:x.user_id||x.userId||x.id,displayName:x.display_name||x.displayName||x.name||'Teilnehmer',avatarUrl:x.avatar_url||x.avatarUrl||null})).filter(x=>x.id)}
async function setFavorite(albumId,mediaId){const{client,userId}=await ctx();const r=await client.from('memory_album_favorites').upsert({album_id:albumId,user_id:userId,media_id:mediaId,updated_at:new Date().toISOString()},{onConflict:'album_id,user_id'}).select('*').single();if(r.error&&!missing(r.error))throw r.error;return r.data||null}
async function saveContribution(albumId,input={}){const{client,userId}=await ctx();const payload={album_id:albumId,user_id:userId,prompt_key:String(input.promptKey||'perspective'),prompt_text:String(input.promptText||''),answer_text:String(input.answerText||''),reaction:String(input.reaction||''),media_id:input.mediaId||null,metadata:input.metadata||{},updated_at:new Date().toISOString()};const r=await client.from('memory_album_contributions').upsert(payload,{onConflict:'album_id,user_id,prompt_key'}).select('*').single();if(r.error){if(missing(r.error))throw new Error('Bitte zuerst die Migration für gemeinsame Memory-Beiträge ausführen.');throw r.error}window.dispatchEvent(new CustomEvent('luvia:memory-contribution-updated',{detail:{albumId,local:true}}));return r.data}
async function save(input){const{client,tripId,userId}=await ctx(),mediaIds=[...new Set((input.mediaIds||[]).map(String))];if(!mediaIds.length)throw new Error('Die Erinnerung braucht mindestens ein Foto.');writeDepth++;try{const payload={trip_id:tripId,source_cluster_id:input.clusterId||null,title:String(input.title||'Unsere Erinnerung').trim(),description:String(input.description||'').trim(),mood:input.mood||null,cover_media_id:input.coverMediaId||mediaIds[0],status:input.status||'draft',metadata:{...(input.metadata||{}),module:'memory-moment-v1'},updated_by:userId,updated_at:new Date().toISOString()};let existing=input.id?{id:input.id}:input.clusterId?await getByCluster(input.clusterId):null,result;if(existing?.id)result=await client.from('memory_albums').update(payload).eq('trip_id',tripId).eq('id',existing.id).select('*').single();else result=await client.from('memory_albums').insert({...payload,created_by:userId}).select('*').single();if(result.error)throw result.error;const id=result.data.id;const del=await client.from('memory_album_items').delete().eq('album_id',id);if(del.error)throw del.error;const rows=mediaIds.map((media_id,position)=>({album_id:id,media_id,position,created_by:userId}));if(rows.length){const ins=await client.from('memory_album_items').insert(rows);if(ins.error)throw ins.error}if(input.favoriteMediaId)await setFavorite(id,input.favoriteMediaId);window.dispatchEvent(new CustomEvent('luvia:memory-album-updated',{detail:{albumId:id,clusterId:input.clusterId,local:true}}));return{...result.data,mediaIds}}finally{writeDepth=Math.max(0,writeDepth-1)}}
async function remove(id){const{client,tripId}=await ctx();const r=await client.from('memory_albums').delete().eq('trip_id',tripId).eq('id',id);if(r.error)throw r.error;window.dispatchEvent(new CustomEvent('luvia:memory-album-updated',{detail:{albumId:id,deleted:true,local:true}}));return true}
async function subscribe(callback){const{client,tripId}=await ctx();if(channels.has(tripId))await channels.get(tripId)();const c=client.channel(`luvia-memory-albums-${tripId}-${Math.random().toString(36).slice(2)}`).on('postgres_changes',{event:'*',schema:'public',table:'memory_albums',filter:`trip_id=eq.${tripId}`},payload=>{if(!writeDepth)callback(payload)}).on('postgres_changes',{event:'*',schema:'public',table:'memory_album_contributions'},payload=>{if(!writeDepth)callback(payload)}).subscribe();const stop=async()=>{await client.removeChannel(c);channels.delete(tripId)};channels.set(tripId,stop);return stop}
window.LuviaMemoryAlbums=Object.freeze({version:VERSION,build:BUILD,list,listClusters,mediaByIds,getByCluster,listMembers,setFavorite,saveContribution,save,remove,subscribe,isWriting:()=>writeDepth>0,diagnostics:()=>({version:VERSION,build:BUILD,isolated:true,galleryTouched:false,writeDepth})});
})();
