-- Luvia 13.30.1 / Core 4.30.1 - full-trip collaborative Memory Journeys
begin;
create table if not exists public.memory_journeys (
 id uuid primary key default gen_random_uuid(), trip_id uuid not null, title text not null default 'Unsere Reisegeschichte', subtitle text not null default '', description text not null default '', cover_media_id uuid references public.media(id) on delete set null, status text not null default 'draft', metadata jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), updated_by uuid references auth.users(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index if not exists memory_journeys_trip_idx on public.memory_journeys(trip_id,updated_at desc);
create table if not exists public.memory_journey_chapters (
 id uuid primary key default gen_random_uuid(), journey_id uuid not null references public.memory_journeys(id) on delete cascade, position integer not null default 0, title text not null, day_key text, summary text not null default '', mood text, cover_media_id uuid references public.media(id) on delete set null, metadata jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(journey_id,position)
);
create table if not exists public.memory_journey_items (
 id uuid primary key default gen_random_uuid(), journey_id uuid not null references public.memory_journeys(id) on delete cascade, chapter_position integer not null default 0, position integer not null default 0, item_type text not null default 'media', media_id uuid references public.media(id) on delete cascade, cluster_id uuid, memory_album_id uuid references public.memory_albums(id) on delete set null, timeline_event_id uuid, day_key text, metadata jsonb not null default '{}'::jsonb, created_by uuid references auth.users(id), created_at timestamptz not null default now(), unique(journey_id,chapter_position,position)
);
create table if not exists public.memory_journey_contributions (
 id uuid primary key default gen_random_uuid(), journey_id uuid not null references public.memory_journeys(id) on delete cascade, user_id uuid not null references auth.users(id) on delete cascade, prompt_key text not null default 'journey-perspective', prompt_text text not null default '', answer_text text not null default '', reaction text not null default '', metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(journey_id,user_id,prompt_key)
);
create index if not exists memory_journey_items_journey_idx on public.memory_journey_items(journey_id,chapter_position,position);
create index if not exists memory_journey_contributions_journey_idx on public.memory_journey_contributions(journey_id,updated_at);
alter table public.memory_journeys enable row level security;alter table public.memory_journey_chapters enable row level security;alter table public.memory_journey_items enable row level security;alter table public.memory_journey_contributions enable row level security;
drop policy if exists memory_journeys_member_all on public.memory_journeys;create policy memory_journeys_member_all on public.memory_journeys for all to authenticated using(public.luvia_is_trip_member(trip_id,auth.uid())) with check(public.luvia_is_trip_member(trip_id,auth.uid()));
drop policy if exists memory_journey_chapters_member_all on public.memory_journey_chapters;create policy memory_journey_chapters_member_all on public.memory_journey_chapters for all to authenticated using(exists(select 1 from public.memory_journeys j where j.id=journey_id and public.luvia_is_trip_member(j.trip_id,auth.uid()))) with check(exists(select 1 from public.memory_journeys j where j.id=journey_id and public.luvia_is_trip_member(j.trip_id,auth.uid())));
drop policy if exists memory_journey_items_member_all on public.memory_journey_items;create policy memory_journey_items_member_all on public.memory_journey_items for all to authenticated using(exists(select 1 from public.memory_journeys j where j.id=journey_id and public.luvia_is_trip_member(j.trip_id,auth.uid()))) with check(exists(select 1 from public.memory_journeys j where j.id=journey_id and public.luvia_is_trip_member(j.trip_id,auth.uid())));
drop policy if exists memory_journey_contributions_member_all on public.memory_journey_contributions;create policy memory_journey_contributions_member_all on public.memory_journey_contributions for all to authenticated using(exists(select 1 from public.memory_journeys j where j.id=journey_id and public.luvia_is_trip_member(j.trip_id,auth.uid()))) with check(user_id=auth.uid() and exists(select 1 from public.memory_journeys j where j.id=journey_id and public.luvia_is_trip_member(j.trip_id,auth.uid())));
grant select,insert,update,delete on public.memory_journeys,public.memory_journey_chapters,public.memory_journey_items,public.memory_journey_contributions to authenticated;
do $$ begin if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='memory_journeys') then alter publication supabase_realtime add table public.memory_journeys; end if; if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='memory_journey_contributions') then alter publication supabase_realtime add table public.memory_journey_contributions; end if; end $$;
commit;
