-- Core 4.2.0 / Build 13.2.0 - Universal Place Data Completion
begin;
create or replace function public.luvia_import_place_entity(p_trip_id uuid,p_place jsonb,p_trip_place jsonb default '{}'::jsonb,p_extension jsonb default '{}'::jsonb)
returns jsonb language plpgsql security definer set search_path=public as $$
declare v_user uuid:=auth.uid();v_place uuid;v_tp uuid;v_created_place boolean:=false;v_created_tp boolean:=false;v_provider text:=coalesce(nullif(p_place->>'provider',''),'google-places');v_provider_id text:=nullif(p_place->>'provider_place_id','');v_type text:=coalesce(nullif(p_place->>'primary_type',''),'custom');
begin
 if v_user is null then raise exception 'AUTH_REQUIRED'; end if;if not public.luvia_is_trip_member(p_trip_id) then raise exception 'NOT_AUTHORIZED';end if;
 if v_provider_id is null or nullif(p_place->>'name','') is null then raise exception 'PLACE_IMPORT_INVALID';end if;
 select id into v_place from public.places where (provider=v_provider and provider_place_id=v_provider_id) or (source=coalesce(nullif(p_place->>'source',''),'google_places') and source_id=coalesce(nullif(p_place->>'source_id',''),v_provider_id)) limit 1;
 if v_place is null then
  insert into public.places(provider,provider_place_id,name,address,latitude,longitude,maps_url,website,phone,rating,rating_count,price_level,categories,attributes,opening_hours,raw_provider_data,source_updated_at,primary_type,roles,capabilities,source,source_id,metadata,created_at,updated_at)
  values(v_provider,v_provider_id,p_place->>'name',nullif(p_place->>'address',''),nullif(p_place->>'latitude','')::double precision,nullif(p_place->>'longitude','')::double precision,nullif(p_place->>'maps_url',''),nullif(p_place->>'website',''),nullif(p_place->>'phone',''),nullif(p_place->>'rating','')::numeric,nullif(p_place->>'rating_count','')::integer,nullif(p_place->>'price_level','')::integer,coalesce(array(select jsonb_array_elements_text(coalesce(p_place->'categories','[]'))),'{}'),coalesce(p_place->'attributes','{}'),coalesce(p_place->'opening_hours','[]'),coalesce(p_place->'raw_provider_data','{}'),now(),v_type,coalesce(array(select jsonb_array_elements_text(coalesce(p_place->'roles','[]'))),'{}'),coalesce(array(select jsonb_array_elements_text(coalesce(p_place->'capabilities','[]'))),'{}'),coalesce(nullif(p_place->>'source',''),'google_places'),coalesce(nullif(p_place->>'source_id',''),v_provider_id),coalesce(p_place->'metadata','{}'),now(),now()) returning id into v_place;v_created_place:=true;
 else update public.places set name=coalesce(nullif(p_place->>'name',''),name),address=coalesce(nullif(p_place->>'address',''),address),latitude=coalesce(nullif(p_place->>'latitude','')::double precision,latitude),longitude=coalesce(nullif(p_place->>'longitude','')::double precision,longitude),primary_type=v_type,roles=coalesce(array(select jsonb_array_elements_text(coalesce(p_place->'roles','[]'))),roles),metadata=metadata||coalesce(p_place->'metadata','{}'),updated_at=now() where id=v_place;end if;
 select id into v_tp from public.trip_places where trip_id=p_trip_id and place_id=v_place limit 1;
 if v_tp is null then insert into public.trip_places(trip_id,place_id,module_key,status,position,is_favorite,user_notes,custom_name,custom_description,custom_symbol,planned_date,planned_time,created_by,sync_status,created_at,updated_at)
 values(p_trip_id,v_place,'places',coalesce(nullif(p_trip_place->>'status',''),'idea'),coalesce(nullif(p_trip_place->>'position','')::int,0),coalesce((p_trip_place->>'isFavorite')::boolean,false),nullif(p_trip_place->>'userNotes',''),nullif(p_trip_place->>'customName',''),nullif(p_trip_place->>'customDescription',''),nullif(p_trip_place->>'customSymbol',''),nullif(p_trip_place->>'plannedDate','')::date,nullif(p_trip_place->>'plannedTime','')::time,v_user,'synced',now(),now()) returning id into v_tp;v_created_tp:=true;end if;
 if v_type='restaurant' then insert into public.restaurants(trip_place_id,reservation_status,reservation_date,reservation_time,reservation_name,reservation_url,reservation_notes,metadata,created_at,updated_at) values(v_tp,coalesce(nullif(p_extension->>'reservationStatus',''),'idea'),nullif(p_extension->>'reservationDate','')::date,nullif(p_extension->>'reservationTime','')::time,nullif(p_extension->>'reservationName',''),nullif(p_extension->>'reservationUrl',''),nullif(p_extension->>'reservationNotes',''),coalesce(p_extension->'metadata','{}'),now(),now()) on conflict(trip_place_id) do update set updated_at=now(); end if;
 return (select jsonb_build_object('place',to_jsonb(p),'tripPlace',to_jsonb(tp),'extension',case when v_type='restaurant' then (select to_jsonb(r) from public.restaurants r where r.trip_place_id=v_tp) else p_extension end,'created',jsonb_build_object('place',v_created_place,'tripPlace',v_created_tp),'alreadyAdded',not v_created_tp) from public.places p join public.trip_places tp on tp.id=v_tp where p.id=v_place);
end$$;
create or replace function public.luvia_list_place_entities(p_trip_id uuid,p_primary_type text default null,p_role text default null,p_status text default null) returns jsonb language sql stable security definer set search_path=public as $$select case when auth.uid() is null or not public.luvia_is_trip_member(p_trip_id) then '[]'::jsonb else coalesce(jsonb_agg(jsonb_build_object('place',to_jsonb(p),'tripPlace',to_jsonb(tp),'extension',case when p.primary_type='restaurant' then (select to_jsonb(r) from public.restaurants r where r.trip_place_id=tp.id) else null end) order by tp.position,tp.created_at),'[]'::jsonb) end from public.trip_places tp join public.places p on p.id=tp.place_id where tp.trip_id=p_trip_id and tp.status<>'archived' and (p_primary_type is null or p.primary_type=p_primary_type) and (p_role is null or p_role=any(p.roles)) and (p_status is null or tp.status=p_status)$$;
create or replace function public.luvia_update_place_lifecycle(p_trip_id uuid,p_trip_place_id uuid,p_status text,p_patch jsonb default '{}'::jsonb) returns jsonb language plpgsql security definer set search_path=public as $$begin if not public.luvia_is_trip_member(p_trip_id) then raise exception 'NOT_AUTHORIZED';end if;update public.trip_places set status=p_status,is_favorite=coalesce((p_patch->>'isFavorite')::boolean,is_favorite),planned_date=case when p_patch?'plannedDate' then nullif(p_patch->>'plannedDate','')::date else planned_date end,planned_time=case when p_patch?'plannedTime' then nullif(p_patch->>'plannedTime','')::time else planned_time end,user_notes=coalesce(p_patch->>'userNotes',user_notes),updated_at=now() where id=p_trip_place_id and trip_id=p_trip_id;return(select jsonb_build_object('place',to_jsonb(p),'tripPlace',to_jsonb(tp)) from public.trip_places tp join public.places p on p.id=tp.place_id where tp.id=p_trip_place_id);end$$;
create or replace function public.luvia_remove_place_from_trip(p_trip_id uuid,p_trip_place_id uuid) returns boolean language plpgsql security definer set search_path=public as $$begin if not public.luvia_is_trip_member(p_trip_id) then raise exception 'NOT_AUTHORIZED';end if;update public.trip_places set status='archived',updated_at=now() where id=p_trip_place_id and trip_id=p_trip_id;return found;end$$;
grant execute on function public.luvia_import_place_entity(uuid,jsonb,jsonb,jsonb) to authenticated;grant execute on function public.luvia_list_place_entities(uuid,text,text,text) to authenticated;grant execute on function public.luvia_update_place_lifecycle(uuid,uuid,text,jsonb) to authenticated;grant execute on function public.luvia_remove_place_from_trip(uuid,uuid) to authenticated;
commit;
